/**
 * Grammar Exercises Data
 *
 * Each question links to a grammar pattern via `grammarId`.
 * Types: fill-blank | sentence-builder | error-correction | pattern-match | translation | listening
 */

const grammarPatterns = [
  {
    id: "B1-NP2", lesson: 1,
    title: "Câu chữ 是 — Câu Vị Ngữ Danh Từ",
    structure: "CN + 是/不是 + DT",
    explanation: "Khi vị ngữ là danh từ, 是 bắt buộc phải có — không thể lược bỏ. Phủ định dùng 不是. Câu hỏi: thêm 吗 ở cuối (xem B1-NP3).<br><br><b>Công thức:</b><br>(1) CN + 是 + DT<br>(2) CN + 不是 + DT",
    examples: [
      { zh: "她是老师。", vi: "Cô ấy là giáo viên." },
      { zh: "我不是学生。", vi: "Tôi không phải là học sinh." },
      { zh: "你是留学生吗？", vi: "Bạn có phải là lưu học sinh không?" },
    ],
    notes: [
      "是 KHÔNG dùng trước tính từ: 她是高兴 ✗ → 她很高兴 ✓",
      "Phủ định: 不是 (một khối), không phải 不是是",
    ],
  },
  {
    id: "B1-NP3", lesson: 1,
    title: "Câu hỏi 吗",
    structure: "Câu khẳng định + 吗？",
    explanation: "Thêm 吗 vào cuối câu khẳng định để tạo câu hỏi có/không. Trật tự từ không thay đổi — không cần đảo ngữ. Có 3 loại tùy vị ngữ: danh từ, động từ, hoặc tính từ.<br><br><b>Công thức:</b><br>(1) CN + 是 + DT + 吗？<br>(2) CN + ĐT + TN + 吗？<br>(3) CN + TT + 吗？",
    examples: [
      { zh: "你是老师吗？", vi: "Bạn có phải là giáo viên không? (vị ngữ DT)" },
      { zh: "他叫大卫吗？", vi: "Anh ấy có tên là David không? (vị ngữ ĐT)" },
      { zh: "他好吗？", vi: "Anh ấy khỏe không? (vị ngữ TT)" },
    ],
    notes: [
      "KHÔNG dùng 吗 cùng với 谁, 什么, 哪 — câu đã là câu hỏi rồi",
      "3 loại vị ngữ đều dùng 吗 được — chỉ cần thêm vào cuối câu, trật tự giữ nguyên",
      "吗 ≠ câu hỏi đuôi tiếng Anh (isn't it?). Chỉ hỏi có/không.",
    ],
  },
  {
    id: "B1-NP4", lesson: 1,
    title: "叫 — Tên gọi",
    structure: "CN + 叫 + tên",
    explanation: "叫 nghĩa là 'được gọi là / tên là'. Dùng để giới thiệu tên hoặc hỏi tên người khác.",
    examples: [
      { zh: "我叫大卫。", vi: "Tôi tên là David." },
      { zh: "你叫什么名字？", vi: "Bạn tên là gì?" },
      { zh: "她叫什么？", vi: "Cô ấy tên là gì?" },
    ],
    notes: [
      "叫 = tên đầy đủ / tên gọi. Khác với 姓 chỉ nói về họ.",
      "名字 (míngzi) = tên, họ tên",
    ],
  },
  {
    id: "B1-NP5", lesson: 1,
    title: "很 trước tính từ",
    structure: "CN + 很 + TT",
    explanation: "Tính từ làm vị ngữ bắt buộc phải có phó từ đứng trước (thường là 很). Nếu bỏ 很, câu nghe KHÔNG hoàn chỉnh và người Trung sẽ hiểu thành câu so sánh ngầm — ví dụ 她高兴 nghe như 'cô ấy vui HƠN ai đó', không phải 'cô ấy vui'.",
    examples: [
      { zh: "我很高兴。", vi: "Tôi rất vui." },
      { zh: "她很好。", vi: "Cô ấy rất tốt/khỏe." },
      { zh: "认识你很高兴。", vi: "Rất vui được quen biết bạn." },
    ],
    notes: [
      "很 ở đây không nhất thiết mang nghĩa 'rất' — chỉ là từ đệm cú pháp bắt buộc",
      "她高兴 (không có 很) → nghe không tự nhiên, mang nghĩa so sánh: 'cô ấy vui HƠN người khác'",
      "Sai phổ biến: 她是高兴 ✗ — 是 không đứng trước tính từ",
    ],
  },
  {
    id: "B2-NP1", lesson: 2,
    title: "Hậu tố 们 — Số nhiều",
    structure: "Đại từ / DT người + 们",
    explanation: "们 thêm vào sau đại từ hoặc danh từ chỉ người để tạo số nhiều. Chỉ dùng với người, không dùng với vật.",
    examples: [
      { zh: "我们是学生。", vi: "Chúng tôi là học sinh." },
      { zh: "你们好！", vi: "Các bạn/Mọi người chào!" },
      { zh: "同学们很高兴。", vi: "Các bạn cùng học rất vui." },
    ],
    notes: [
      "KHÔNG dùng 们 sau từ chỉ quốc tịch: 美国人们 ✗ → 美国人 ✓ (đã mang nghĩa tập thể)",
      "们 chỉ dùng với NGƯỜI, không dùng với đồ vật hay động vật",
    ],
  },
  {
    id: "B2-NP2", lesson: 2,
    title: "Trợ từ 的 — Sở hữu",
    structure: "ĐN + 的 + DT",
    explanation: "的 đứng sau định ngữ để biểu thị sở hữu hoặc bổ nghĩa cho danh từ. Đặt TRƯỚC danh từ — ngược với tiếng Việt đặt sau.",
    examples: [
      { zh: "这是我的书。", vi: "Đây là sách của tôi." },
      { zh: "那是谁的词典？", vi: "Đó là từ điển của ai?" },
      { zh: "她是我的同学。", vi: "Cô ấy là bạn cùng học của tôi." },
    ],
    notes: [
      "Vị trí: [người sở hữu] + 的 + [vật] — định ngữ đứng TRƯỚC danh từ",
      "Có thể bỏ 的 khi quan hệ gần gũi: 我朋友 ≈ 我的朋友",
    ],
  },
  {
    id: "B2-NP3", lesson: 2,
    title: "Phó từ 也 — Cũng",
    structure: "CN + 也 + VN",
    explanation: "也 (cũng) phải đặt TRƯỚC động từ/tính từ (giống tiếng Việt: 'Tôi cũng là học sinh'). Không đặt 也 ở cuối câu như 'too' trong tiếng Anh.",
    examples: [
      { zh: "我也是学生。", vi: "Tôi cũng là học sinh." },
      { zh: "她也很高兴。", vi: "Cô ấy cũng rất vui." },
      { zh: "我也认识他。", vi: "Tôi cũng quen biết anh ấy." },
    ],
    notes: [
      "Lỗi phổ biến (bị tiếng Anh ảnh hưởng): 我是学生也 ✗ (giống 'I am a student too')",
      "Đúng: 我也是学生 ✓ — 也 đứng sau CN, trước ĐT/TT (giống tiếng Việt: 'Tôi cũng là học sinh')",
    ],
  },
  {
    id: "B2-NP4", lesson: 2,
    title: "Trợ từ 呢 — Còn… thì sao?",
    structure: "[chủ đề] + 呢？",
    explanation: "呢 cuối câu rút ngắn = hỏi lại về chủ đề đã nhắc. Dùng khi muốn hỏi 'còn X thì sao?' mà không cần lặp lại toàn bộ câu.",
    examples: [
      { zh: "我是越南人，你呢？", vi: "Tôi là người Việt Nam, còn bạn thì sao?" },
      { zh: "A：我很好。B：你呢？", vi: "A: Tôi khỏe. B: Còn bạn?" },
      { zh: "他是老师，她呢？", vi: "Anh ấy là giáo viên, còn cô ấy?" },
    ],
    notes: [
      "Khác 吗: 吗 hỏi hoàn toàn mới; 呢 hỏi lại trong ngữ cảnh đã có",
      "呢 rút ngắn câu — không cần lặp lại động từ hay vị ngữ",
    ],
  },
  {
    id: "B2-NP5", lesson: 2,
    title: "姓 — Họ",
    structure: "CN + 姓 + họ",
    explanation: "姓 dùng để nói về họ (surname). Khác với 叫 (tên đầy đủ). Hỏi họ: 你姓什么？",
    examples: [
      { zh: "我姓王。", vi: "Tôi họ Vương." },
      { zh: "你姓什么？", vi: "Bạn họ gì?" },
      { zh: "她姓李，叫李军。", vi: "Cô ấy họ Lý, tên là Lý Quân." },
    ],
    notes: [
      "姓 là động từ trong cấu trúc này, không phải danh từ",
      "Họ người Trung thường chỉ một chữ: 王, 李…",
    ],
  },
  {
    id: "B2-NP6", lesson: 2,
    title: "哪国人 — Quốc tịch",
    structure: "CN + 是 + [quốc gia] + 人",
    explanation: "Tên quốc gia + 人 = người nước đó. Hỏi quốc tịch: 你是哪国人？ (Bạn là người nước nào?)",
    examples: [
      { zh: "我是越南人。", vi: "Tôi là người Việt Nam." },
      { zh: "他是中国人。", vi: "Anh ấy là người Trung Quốc." },
      { zh: "你是哪国人？", vi: "Bạn là người nước nào?" },
    ],
    notes: [
      "哪国人 = người nước nào? (câu hỏi quốc tịch)",
      "Không dùng 们 sau [quốc gia]人: 越南人们 ✗",
    ],
  },
  {
    id: "B2-NP7", lesson: 2,
    title: "Câu S + V + O cơ bản",
    structure: "CN + ĐT + TN",
    explanation: "Cấu trúc câu cơ bản: Chủ ngữ + Động từ + Tân ngữ. Tân ngữ đứng SAU động từ, giống tiếng Việt.",
    examples: [
      { zh: "你认识他吗？", vi: "Bạn có quen biết anh ấy không?" },
      { zh: "我介绍一下儿。", vi: "Tôi giới thiệu một chút." },
      { zh: "她学汉语。", vi: "Cô ấy học tiếng Trung." },
    ],
    notes: [
      "Trật tự SVO cơ bản giống tiếng Việt — tân ngữ đứng sau động từ",
      "Thêm 吗 vào cuối để biến thành câu hỏi, không cần đảo ngữ",
    ],
  },
  {
    id: "B2-NP8", lesson: 2,
    title: "我来 + ĐT — Lời đề nghị lịch sự",
    structure: "我来 + ĐT",
    explanation: "我来 + ĐT = 'để tôi làm / tôi sẽ làm'. Thể hiện sự chủ động, lịch sự. Thường dùng trong lớp học hoặc khi giúp đỡ người khác.",
    examples: [
      { zh: "我来介绍一下。", vi: "Để tôi giới thiệu một chút." },
      { zh: "我来说。", vi: "Để tôi nói." },
      { zh: "我来看。", vi: "Để tôi xem." },
    ],
    notes: [
      "来 trong cụm này mang nghĩa 'để tôi…' — không phải nghĩa gốc 'đến'",
      "Thường kết hợp với 一下: 我来介绍一下 = để tôi giới thiệu một chút (nghe lịch sự hơn)",
    ],
  },
  {
    id: "B3-NP1", lesson: 3,
    title: "这/那 — Chỉ định từ",
    structure: "这/那 + 是 + DT",
    explanation: "这 (zhè) = này/đây, 那 (nà) = đó/kia. Dùng để chỉ định hoặc giới thiệu đối tượng.",
    examples: [
      { zh: "这是我的书。", vi: "Đây là sách của tôi." },
      { zh: "那是谁？", vi: "Kia là ai?" },
      { zh: "这是我的同屋。", vi: "Đây là bạn cùng phòng của tôi." },
    ],
    notes: [
      "这/那 trực tiếp làm chủ ngữ. Khi đứng trước DT cần thêm lượng từ: 这本书, 那个人",
      "这里/这儿 = nơi này; 那里/那儿 = nơi kia",
    ],
  },
  {
    id: "B3-NP2", lesson: 3,
    title: "的 với từ nghi vấn",
    structure: "谁的/什么 + DT",
    explanation: "Đại từ nghi vấn (谁, 什么, 哪) đứng ngay tại vị trí của đáp án — không cần đảo ngữ. 谁的 = của ai.",
    examples: [
      { zh: "这是谁的书？", vi: "Đây là sách của ai?" },
      { zh: "那是什么杂志？", vi: "Đó là tạp chí gì?" },
      { zh: "哪本是你的？", vi: "Cuốn nào là của bạn?" },
    ],
    notes: [
      "Vị trí đại từ nghi vấn = vị trí của đáp án trong câu trả lời",
      "KHÔNG thêm 吗 vào câu đã có 谁/什么/哪",
    ],
  },
  {
    id: "B3-NP3", lesson: 3,
    title: "吗 vs 谁/什么/哪 — Hai loại câu hỏi",
    structure: "吗 ↔ 谁/什么/哪 (không dùng cùng nhau)",
    explanation: "Hai loại câu hỏi khác nhau hoàn toàn: (1) Hỏi có/không → dùng 吗. (2) Hỏi thông tin cụ thể → dùng 谁/什么/哪, KHÔNG dùng 吗.",
    examples: [
      { zh: "那是词典吗？✓", vi: "Đó có phải từ điển không?" },
      { zh: "那是什么词典？✓", vi: "Đó là từ điển gì?" },
      { zh: "那是什么词典吗？✗", vi: "(Sai — không dùng 吗 cùng 什么)" },
    ],
    notes: [
      "Quy tắc: câu đã có 谁/什么/哪 → KHÔNG thêm 吗",
      "Lỗi thường gặp: 这是谁的书吗？✗ → 这是谁的书？✓",
      "Câu hỏi với 谁/什么/哪 không cần đảo ngữ — giữ nguyên trật tự câu",
    ],
  },
  {
    id: "B3-NP4", lesson: 3,
    title: "就是 — Tức là / Chính là",
    structure: "X，就是 Y",
    explanation: "就是 = 'tức là / chính là' — dùng để giải thích, định nghĩa hoặc nhấn mạnh. Mạnh hơn 是 thông thường.",
    examples: [
      { zh: "《汉日词典》，就是汉语日语词典。", vi: "Từ điển Hán-Nhật, tức là từ điển Trung-Nhật." },
      { zh: "这，就是我说的那本书。", vi: "Đây chính là cuốn sách tôi đã nói." },
      { zh: "他就是李军。", vi: "Anh ấy chính là Lý Quân." },
    ],
    notes: [
      "就是 nhấn mạnh hơn 是: 他是李军 (trung tính) vs 他就是李军 (chính là anh ấy)",
      "Thường dùng để giải thích thuật ngữ hoặc xác nhận danh tính",
    ],
  },
  {
    id: "CB-NP1", lesson: 3,
    title: "Lượng từ 本",
    structure: "Số / Đại từ chỉ định + 本 + DT",
    explanation: "本 là lượng từ dùng cho sách, vở, tạp chí. Lượng từ bắt buộc phải có giữa số từ/chỉ định từ và danh từ — không thể bỏ qua như tiếng Việt.",
    examples: [
      { zh: "一本书", vi: "một cuốn sách" },
      { zh: "这本词典是我的。", vi: "Cuốn từ điển này là của tôi." },
      { zh: "那本杂志叫什么名字？", vi: "Tờ tạp chí kia tên là gì?" },
    ],
    notes: [
      "本 chỉ dùng cho vật dạng cuốn/quyển. Lượng từ chung: 个 (người/vật chung)",
      "Không thể nói 一书 ✗ hay 这书 ✗ — lượng từ là bắt buộc",
    ],
  },
  {
    id: "CB-NP2", lesson: 3,
    title: "会 — Biết làm (qua học)",
    structure: "CN + 会/不会 + ĐT",
    explanation: "会 biểu thị khả năng có được qua học tập, luyện tập ('biết làm'). Phủ định: 不会.",
    examples: [
      { zh: "我会说汉语。", vi: "Tôi biết nói tiếng Trung." },
      { zh: "大卫不会说越南语。", vi: "David không biết nói tiếng Việt." },
      { zh: "你会说什么语言？", vi: "Bạn biết nói ngôn ngữ gì?" },
    ],
    notes: [
      "会 nhấn mạnh khả năng đạt được qua học tập / luyện tập (skill)",
      "Phủ định: 不会 + ĐT — 不会 là một khối, không tách",
    ],
  },
  {
    id: "CB-NP3", lesson: 3,
    title: "喜欢 — Thích",
    structure: "CN + 喜欢 + ĐT/DT",
    explanation: "喜欢 = thích. Theo sau có thể là động từ (thích làm gì) hoặc danh từ (thích cái gì). Không cần thêm gì giữa 喜欢 và động từ.",
    examples: [
      { zh: "我喜欢听音乐。", vi: "Tôi thích nghe nhạc." },
      { zh: "她喜欢汉语。", vi: "Cô ấy thích tiếng Trung." },
      { zh: "你喜欢看什么杂志？", vi: "Bạn thích đọc tạp chí gì?" },
    ],
    notes: [
      "喜欢 + ĐT trực tiếp — không cần thêm từ nối nào (khác tiếng Anh 'like doing')",
      "Phủ định: 不喜欢 + ĐT/DT",
    ],
  },
  {
    id: "B4-NP1", lesson: 4,
    title: "在 vs 是 — Biểu thị vị trí",
    structure: "CN + 在 + địa điểm<br>địa điểm + 是 + CN",
    explanation: "Hai cấu trúc diễn tả vị trí, không hoán đổi được: (1) '<b>X ở đâu</b>' dùng 在 — CN là vật, vị ngữ là địa điểm. (2) '<b>Ở đâu là X</b>' dùng 是 — CN là địa điểm, vị ngữ là tên nơi/vật.",
    examples: [
      { zh: "图书馆在左边。", vi: "Thư viện ở bên trái." },
      { zh: "左边是图书馆。", vi: "Bên trái là thư viện." },
      { zh: "宿舍在哪儿？", vi: "Ký túc xá ở đâu?" },
    ],
    notes: [
      "是 = 'là' (định nghĩa/phân loại); 在 = 'ở' (vị trí)",
      "Lỗi phổ biến: 图书馆是那儿 ✗ → 图书馆在那儿 ✓",
    ],
  },
  {
    id: "B4-NP2", lesson: 4,
    title: "Phương vị từ + 边",
    structure: "左/右/上/下/北 + 边",
    explanation: "Phương vị từ đầy đủ = gốc chỉ hướng + 边: 左边, 右边, 上边, 下边, 北边. Khi gắn với DT: <b>N + 的 + phương vị từ</b> = 'bên ... của N' (ngược trật tự tiếng Việt).",
    examples: [
      { zh: "图书馆在学校的左边。", vi: "Thư viện ở bên trái trường học." },
      { zh: "宿舍在图书馆的右边。", vi: "Ký túc xá ở bên phải thư viện." },
      { zh: "书在课本的上边。", vi: "Sách ở bên trên sách giáo khoa." },
    ],
    notes: [
      "Không nói chỉ '左/右/上/下' thiếu '边'",
      "Trật tự ngược tiếng Việt: 图书馆的右边 = 'bên phải của thư viện' (tiếng Việt: 'bên phải thư viện' — định ngữ đi sau)",
    ],
  },
  {
    id: "B4-NP3", lesson: 4,
    title: "哪儿 / 哪里 — Ở đâu?",
    structure: "CN + 在 + 哪儿 / 哪里？",
    explanation: "哪儿 = 哪里 — đại từ nghi vấn chỉ địa điểm 'ở đâu?'. Đặt sau 在 để hỏi vị trí. Hai từ hoàn toàn thay thế được cho nhau (哪儿 phổ biến ở phương Bắc, 哪里 phổ biến ở phương Nam/Đài Loan).",
    examples: [
      { zh: "图书馆在哪儿？", vi: "Thư viện ở đâu?" },
      { zh: "你的书在哪里？", vi: "Sách của bạn ở đâu?" },
      { zh: "宿舍在哪儿？", vi: "Ký túc xá ở đâu?" },
    ],
    notes: [
      "哪儿 và 哪里 thay thế được 100% — chọn theo thói quen",
      "Trật tự giữ nguyên: CN + 在 + 哪儿 (không đảo ngữ)",
    ],
  },
  {
    id: "B4-NP4", lesson: 4,
    title: "请问 — Xin hỏi",
    structure: "请问 + [câu hỏi]",
    explanation: "请问 = 'Xin hỏi' — mở đầu câu hỏi lịch sự khi hỏi người lạ. Đặt ở đầu câu, theo sau là câu hỏi bình thường (không thay đổi trật tự từ).",
    examples: [
      { zh: "请问，图书馆在哪儿？", vi: "Xin hỏi, thư viện ở đâu?" },
      { zh: "请问，你叫什么名字？", vi: "Xin hỏi, bạn tên là gì?" },
      { zh: "请问，这是您的书吗？", vi: "Xin hỏi, đây có phải sách của ngài không?" },
    ],
    notes: [
      "Thường có dấu phẩy sau 请问",
      "Khác 问 (hỏi, động từ bình thường): 请问 là kính ngữ mở đầu câu hỏi",
    ],
  },
  {
    id: "B4-NP5", lesson: 4,
    title: "对不起 / 没关系 — Xin lỗi & đáp lại",
    structure: "A: 对不起 → B: 没关系",
    explanation: "Cặp câu xin lỗi/đáp lại cố định: 对不起 = 'xin lỗi'; 没关系 = 'không sao' (nghĩa đen: không có quan hệ gì). Khi ai đó nói 对不起, đáp chuẩn là 没关系.",
    examples: [
      { zh: "A：对不起！ B：没关系。", vi: "A: Xin lỗi! B: Không sao." },
      { zh: "对不起，我不知道。", vi: "Xin lỗi, tôi không biết." },
      { zh: "没关系，我来介绍。", vi: "Không sao, để tôi giới thiệu." },
    ],
    notes: [
      "没关系 là cụm cố định — không dùng riêng 关系 để đáp",
      "Dùng 对不起 khi lỗi rõ ràng; đáp 没关系 để nói 'không phải lỗi gì'",
    ],
  },
  {
    id: "B4-NP6", lesson: 4,
    title: "A 的 B — đảo trật tự đảo nghĩa",
    structure: "N + 的 + phương vị từ (vị trí)<br>phương vị từ + 的 + N (sự vật)",
    explanation: "Quy tắc chung <b>A 的 B</b>: B là thành phần chính, A bổ nghĩa cho B. Đảo trật tự thì đảo nghĩa hoàn toàn:<br><br>(1) <b>N + 的 + phương vị từ</b> → phương vị từ là chính, nói về <b>vị trí</b> ('phía nào của N').<br>(2) <b>phương vị từ + 的 + N</b> → N là chính, chỉ <b>sự vật</b> nằm ở phía đó ('cái N ở phía đó').",
    examples: [
      { zh: "楼的右边是学校。", vi: "Phía bên phải của tòa nhà là trường học. (vị trí)" },
      { zh: "右边的楼是图书馆。", vi: "Tòa nhà bên phải là thư viện. (sự vật)" },
      { zh: "上边的宿舍是我的。", vi: "Ký túc xá phía trên là của tôi. (sự vật)" },
    ],
    notes: [
      "A 的 B → B là chính, A bổ nghĩa cho B",
      "楼的右边 = vị trí (nói về phía bên phải) ↔ 右边的楼 = sự vật (nói về tòa nhà)",
    ],
  },
  {
    id: "CB-NP4", lesson: 4,
    title: "Lượng từ 个",
    structure: "Số / Đại từ chỉ định + 个 + DT",
    explanation: "个 là lượng từ chung cho người và nhiều vật. Dùng khi không có lượng từ chuyên biệt. 这/那 + 个 + DT = 'cái/người này/đó'. Khác 这 + 是 + DT (câu định nghĩa).",
    examples: [
      { zh: "这个人是大卫。", vi: "Người này là David." },
      { zh: "那个学校很大。", vi: "Trường đó rất lớn." },
      { zh: "一个老师", vi: "một giáo viên" },
    ],
    notes: [
      "本 là lượng từ cho sách/vở; 个 là lượng từ chung cho người và nhiều vật khác",
      "这 + 是 + DT (định nghĩa) ≠ 这 + 个 + DT (chỉ định cụ thể)",
    ],
  },
  {
    id: "CB-NP5", lesson: 4,
    title: "知道 vs 会 — Biết thông tin / Biết kỹ năng",
    structure: "知道 + fact<br>会 + kỹ năng",
    explanation: "Hai 'biết' khác nhau: 知道 = biết thông tin/sự kiện ('biết rằng…'); 会 = biết làm kỹ năng ('biết cách…', qua học tập).",
    examples: [
      { zh: "我知道他叫大卫。", vi: "Tôi biết anh ấy tên là David. (thông tin)" },
      { zh: "我会说汉语。", vi: "Tôi biết nói tiếng Trung. (kỹ năng)" },
      { zh: "你知道图书馆在哪儿吗？", vi: "Bạn có biết thư viện ở đâu không?" },
    ],
    notes: [
      "Lỗi phổ biến: 我知道说汉语 ✗ → 我会说汉语 ✓ (nói là kỹ năng)",
      "知道 thường đi với mệnh đề (biết rằng…); 会 đi với động từ (biết làm gì)",
    ],
  },
  {
    id: "CB-NP6", lesson: 4,
    title: "Cụm ĐT làm định ngữ — Mệnh đề quan hệ 🔴",
    structure: "[Cụm ĐT] + 的 + DT",
    explanation: "Cụm động từ (có thể có CN, 在, TN) làm định ngữ cho DT — tương đương mệnh đề quan hệ ('người mà...', 'cuốn sách mà...'). Tiếng Trung đặt mệnh đề TRƯỚC DT, ngược trật tự tiếng Việt:<br><br>(1) <b>[在 + V] + 的 + DT</b> = DT (đang) làm gì: 在看书的学生 = học sinh đang đọc sách.<br>(2) <b>[CN + 在 + V] + 的 + DT</b> = DT (mà) CN đang làm: 大卫在听的音乐 = nhạc David đang nghe.<br>(3) <b>[CN + V] + 的 + DT</b> = DT (mà) CN làm: 你看的书 = cuốn sách bạn đọc.",
    examples: [
      { zh: "在看书的学生是大卫。", vi: "Học sinh (đang) đọc sách là David." },
      { zh: "大卫在听的音乐是中国音乐。", vi: "Nhạc (mà) David đang nghe là nhạc Trung Quốc." },
      { zh: "你看的书是我的。", vi: "Cuốn sách (mà) bạn đọc là của tôi." },
    ],
    notes: [
      "Trật tự ngược tiếng Việt: [mệnh đề] + 的 + DT (Việt đặt mệnh đề SAU: 'sách mà bạn đọc')",
      "Chèn 在 trước ĐT để diễn tả ý 'đang...': 在听音乐的老师 = giáo viên đang nghe nhạc",
      "Có thể thêm định ngữ trước DT chính: 在听音乐的中国老师 = giáo viên Trung Quốc đang nghe nhạc",
      "Ngữ pháp nâng cao 🔴 — cần luyện đọc hiểu nhiều",
    ],
  },
  {
    id: "B5-NP1", lesson: 5,
    title: "小 / 中 / 大 + DT — Tính từ kích cỡ làm định ngữ",
    structure: "小 / 中 / 大 + DT",
    explanation: "Tính từ chỉ kích cỡ (小/中/大) đặt TRỰC TIẾP trước danh từ — KHÔNG cần 的. Khác với khi tính từ làm vị ngữ ('教室很大' — phòng học rất lớn) thì cần 很.",
    examples: [
      { zh: "这是大教室。", vi: "Đây là phòng học lớn." },
      { zh: "我们的宿舍是小宿舍。", vi: "Ký túc xá của chúng tôi là ký túc xá nhỏ." },
      { zh: "大图书馆在哪儿？", vi: "Thư viện lớn ở đâu?" },
    ],
    notes: [
      "Định ngữ kích cỡ trực tiếp: 大教室 ✓ — không cần 的",
      "Vị ngữ kích cỡ: 教室很大 ✓ — phải có 很 (xem B1-NP5)",
      "Một số kết hợp lexicalized: 大学 (đại học), 小学 (tiểu học) — không phải 'trường lớn/nhỏ' theo nghĩa đen",
    ],
  },
  {
    id: "B5-NP2", lesson: 5,
    title: "有 / 没有 — Sở hữu / Tồn tại",
    structure: "CN + 有 + DT<br>CN + 没有 + DT",
    explanation: "有 = 'có' (sở hữu hoặc tồn tại). Phủ định ĐẶC BIỆT: dùng <b>没有</b>, KHÔNG dùng 不有 ✗. 有 là động từ duy nhất trong tiếng Trung phủ định bằng 没.",
    examples: [
      { zh: "我有书。", vi: "Tôi có sách." },
      { zh: "他没有工作。", vi: "Anh ấy không có việc làm." },
      { zh: "学校有图书馆。", vi: "Trường học có thư viện. (tồn tại)" },
    ],
    notes: [
      "Phủ định: 没有 (không phải 不有 ✗) — 有 là ngoại lệ duy nhất",
      "有 vừa nghĩa 'sở hữu' (我有...) vừa 'tồn tại' (... 有 ...)",
      "Văn nói có thể rút gọn 没有 → 没",
    ],
  },
  {
    id: "B5-NP3", lesson: 5,
    title: "...的时候 — Khi / Lúc làm gì",
    structure: "[Cụm ĐT] + 的时候",
    explanation: "Đặt [cụm động từ] trước <b>的时候</b> = 'khi/lúc làm gì'. Toàn bộ cụm này là trạng ngữ chỉ thời gian, có thể đứng đầu câu hoặc giữa CN và VN. Ngược trật tự tiếng Việt: 'khi tôi học' → '<b>我学</b>的时候' (mệnh đề ở TRƯỚC '的时候', không phải sau 'khi').",
    examples: [
      { zh: "我看书的时候，他来了。", vi: "Khi tôi đọc sách, anh ấy đến." },
      { zh: "你来的时候，我在教室。", vi: "Khi bạn đến, tôi đang ở lớp học." },
      { zh: "我听音乐的时候很高兴。", vi: "Khi tôi nghe nhạc tôi rất vui." },
    ],
    notes: [
      "的时候 LUÔN đặt ở CUỐI cụm động từ — không tách: '的' bên trong, '时候' ngay sau",
      "Trạng ngữ thời gian thường ở đầu câu, theo sau là dấu phẩy",
      "Mệnh đề con [cụm ĐT] có thể có CN (我学的时候) hoặc không (看书的时候)",
    ],
  },
  {
    id: "B5-NP4", lesson: 5,
    title: "什么时候 — Khi nào? / Lúc nào?",
    structure: "CN + 什么时候 + VN？",
    explanation: "什么时候 = 'lúc nào / khi nào' — đại từ nghi vấn hỏi về thời gian. Đặt sau CN và trước VN. Vì đã là câu hỏi (có 什么) nên KHÔNG thêm 吗.",
    examples: [
      { zh: "你什么时候有空儿？", vi: "Bạn lúc nào rảnh?" },
      { zh: "你什么时候去？", vi: "Bạn khi nào đi?" },
      { zh: "什么时候你来教室？", vi: "Khi nào bạn đến lớp học? (đặt ở đầu câu)" },
    ],
    notes: [
      "什么时候 là đại từ nghi vấn → KHÔNG thêm 吗 ở cuối câu",
      "Vị trí phổ biến: CN + 什么时候 + VN; cũng có thể đặt 什么时候 ở đầu câu",
      "Trả lời thường dùng [VP] + 的时候 (xem B5-NP3) hoặc thời gian cụ thể",
    ],
  },
  {
    id: "B5-NP5", lesson: 5,
    title: "来 / 去 — Đến / Đi",
    structure: "CN + 来 / 去 + địa điểm",
    explanation: "来 và 去 là cặp động từ chỉ hướng:<br>• <b>来</b> = 'đến' — chuyển động <b>về phía người nói</b>.<br>• <b>去</b> = 'đi' — chuyển động <b>rời khỏi người nói</b>.<br>Đặt địa điểm TRỰC TIẾP sau 来/去 — không cần thêm giới từ.",
    examples: [
      { zh: "我去图书馆。", vi: "Tôi đi thư viện." },
      { zh: "大卫来中国。", vi: "David đến Trung Quốc." },
      { zh: "你去哪儿？", vi: "Bạn đi đâu?" },
    ],
    notes: [
      "Sau 来/去 đặt địa điểm trực tiếp: 去图书馆 ✓, không nói 去在图书馆 ✗",
      "来 ↔ 去 chọn theo vị trí người nói: ở nhà bảo người khác '来' (đến đây); rời nhà bảo '去' (đi đó)",
      "Hỏi điểm đến: 来/去 + 哪儿？",
    ],
  },
  {
    id: "B6-NP1", lesson: 6,
    title: "Cách đọc giờ phút",
    structure: "N + 点 (+ M + 分)",
    explanation: "Cách đọc giờ phút trong tiếng Trung:<br>(1) <b>Giờ tròn</b>: Số giờ + 点 → 三点 (3 giờ).<br>(2) <b>Giờ + phút</b>: Số giờ + 点 + Số phút + 分 → 三点二十分 (3 giờ 20 phút).<br>(3) <b>Phút < 10</b>: chèn 零 trước số phút → 三点零五分 (3 giờ 05 phút).<br>(4) <b>30 phút</b>: dùng 半 → 三点半 (3 giờ rưỡi).<br>(5) <b>15 / 45 phút</b>: dùng 刻 → 三点一刻 (3 giờ 15), 三点三刻 (3 giờ 45).<br>(6) <b>Kém</b>: 差 + phút + 分 + giờ + 点 → 差五分三点 (3 giờ kém 5).",
    examples: [
      { zh: "我三点去图书馆。", vi: "Tôi đi thư viện lúc 3 giờ." },
      { zh: "他七点半来教室。", vi: "Anh ấy đến lớp học lúc 7 giờ rưỡi." },
      { zh: "我差五分八点来。", vi: "Tôi đến lúc 8 giờ kém 5 phút." },
    ],
    notes: [
      "Phút có 1 chữ số (1–9): bắt buộc thêm 零 trước số phút (三点零五分, không nói 三点五分 ✗)",
      "刻 = 15 phút: 一刻 = 15, 三刻 = 45 (KHÔNG có 二刻 dùng 半 thay)",
      "Hỏi giờ: dùng 什么时候 (xem B5-NP4) — cấu trúc hỏi giờ chuyên biệt sẽ học ở bài sau",
    ],
  },
  {
    id: "B6-NP2", lesson: 6,
    title: "两 vs 二 — Khi nào dùng 'hai' nào",
    structure: "两 + lượng từ<br>二 (số đếm thuần / số nhiều chữ số)",
    explanation: "Cả 二 và 两 đều nghĩa là 'hai' nhưng dùng trong ngữ cảnh khác nhau:<br>• <b>二</b>: số đếm trừu tượng (1, 2, 3...), số thứ tự, các chữ số trong số nhiều chữ số (12, 22, 200...).<br>• <b>两</b>: dùng TRƯỚC lượng từ khi nói '<b>hai cái gì đó</b>'.<br>Quy tắc: trước lượng từ → 两; còn lại → 二.",
    examples: [
      { zh: "两本书", vi: "hai cuốn sách (本 là lượng từ → dùng 两)" },
      { zh: "两个学生", vi: "hai học sinh (个 là lượng từ → dùng 两)" },
      { zh: "两点", vi: "2 giờ (点 hoạt động như lượng từ → 两点, KHÔNG 二点)" },
    ],
    notes: [
      "Số đếm thuần / số thứ tự / số nhiều chữ số: dùng 二 — 十二 (12), 二十 (20), 二百 (200)",
      "Trước lượng từ (本, 个, 点...): dùng 两 — sai khi viết 二本书 ✗ → 两本书 ✓",
      "Trước 百 (trăm): cả 二百 và 两百 đều dùng được; văn nói thường nghiêng về 两百",
    ],
  },
  {
    id: "B6-NP3", lesson: 6,
    title: "太...了 / 不太... — Quá... / Không... lắm",
    structure: "太 + TT + 了 (quá ...)<br>不太 + TT (không ... lắm)",
    explanation: "Hai cấu trúc dùng 太 để biểu thị mức độ:<br>(1) <b>太 + TT + 了</b>: nhấn mạnh 'quá...' — thường mang sắc thái phàn nàn hoặc khen mạnh. 了 là BẮT BUỘC.<br>(2) <b>不太 + TT</b>: phủ định nhẹ 'không... lắm'. KHÔNG có 了 đi kèm.",
    examples: [
      { zh: "太好了！", vi: "Quá tốt! / Tuyệt!" },
      { zh: "老师太高兴了。", vi: "Giáo viên quá vui." },
      { zh: "这本书不太好。", vi: "Cuốn sách này không tốt lắm." },
    ],
    notes: [
      "太 + TT phải có 了 ở cuối: 太好 ✗ → 太好了 ✓",
      "不太 + TT KHÔNG cần 了: 不太好了 ✗ → 不太好 ✓",
      "Khẩu ngữ: '太好了！' thường dùng thay 'tuyệt vời!' hoặc đáp lời tích cực",
    ],
  },
  {
    id: "B6-NP4", lesson: 6,
    title: "差 — Kém / Tệ (đánh giá khả năng)",
    structure: "CN + 很 + 差 / 不太 + 差",
    explanation: "差 với nghĩa 'kém, tệ' là tính từ — dùng giống các tính từ khác, cần phó từ (thường là 很) đứng trước khi làm vị ngữ. Diễn tả trình độ/khả năng kém hoặc chất lượng tồi.<br><br>Lưu ý: 差 còn có nghĩa khác là 'thiếu/kém' trong cách nói giờ (xem B6-NP1): 差五分八点 = '8 giờ kém 5'.",
    examples: [
      { zh: "我的汉语很差。", vi: "Tiếng Hán của tôi rất kém." },
      { zh: "他的工作不太差。", vi: "Công việc của anh ấy không tệ lắm." },
      { zh: "我的日语很差。", vi: "Tiếng Nhật của tôi rất kém." },
    ],
    notes: [
      "差 là tính từ: làm vị ngữ phải có phó từ (很 / 不太 / 太...了): 我差 ✗ → 我很差 ✓",
      "差 mạnh hơn 不好: 不好 = 'không tốt'; 差 = 'kém, tệ' (chất lượng/khả năng yếu)",
      "Hai nghĩa của 差: (a) tính từ 'kém' (我的汉语差) — bài này; (b) động từ 'thiếu' khi nói giờ (差五分) — xem B6-NP1",
    ],
  },
  {
    id: "B6-NP5", lesson: 6,
    title: "早上 / 上午 / 中午 / 下午 / 晚上 — Các buổi trong ngày",
    structure: "[Buổi] + (giờ cụ thể) + V",
    explanation: "Tiếng Trung chia ngày thành 5 buổi, dùng làm trạng ngữ thời gian:<br>• <b>早上</b> (zǎoshang) — sáng sớm (~5h–8h)<br>• <b>上午</b> (shàngwǔ) — buổi sáng (8h–12h, nghĩa đen: 'trên 午/ngọ')<br>• <b>中午</b> (zhōngwǔ) — giữa trưa (~11h–13h, 'chính ngọ')<br>• <b>下午</b> (xiàwǔ) — buổi chiều (12h–18h, 'dưới ngọ')<br>• <b>晚上</b> (wǎnshang) — buổi tối (18h–24h)<br>Đặt buổi TRƯỚC giờ cụ thể: 上午八点 = '8 giờ sáng', 晚上九点 = '9 giờ tối'.",
    examples: [
      { zh: "我早上六点上课。", vi: "Tôi vào lớp lúc 6 giờ sáng." },
      { zh: "他下午三点来教室。", vi: "Anh ấy đến lớp học lúc 3 giờ chiều." },
      { zh: "我们晚上八点见。", vi: "Chúng ta gặp nhau lúc 8 giờ tối." },
    ],
    notes: [
      "Trật tự: [Buổi] + [Giờ] — KHÔNG đảo ngược: 早上八点 ✓, 八点早上 ✗",
      "早上 và 上午 hơi chồng nhau (~7–8h): 早上 nhấn 'sáng sớm/khi mới dậy'; 上午 chỉ 'cả buổi sáng đến trưa'",
      "Mẹo nhớ: 午 (ngọ) = giữa trưa → 上午 'trên ngọ' (trước trưa), 下午 'dưới ngọ' (sau trưa)",
    ],
  },
];

const grammarQuestions = [
  // ── Fill-in-the-Blank ──
  { id: "fb-001", grammarId: "B1-NP2", type: "fill-blank", lesson: 1,
    prompt: "她___老师。", options: ["是", "很", "吗", "的"], answer: "是",
    explanation: "Vị ngữ là danh từ (老师) → bắt buộc có 是 ở giữa.",
    hanVietHint: "是 → THỊ | 老师 → LÃO SƯ" },
  { id: "fb-002", grammarId: "B1-NP3", type: "fill-blank", lesson: 1,
    prompt: "你是学生___？", options: ["吗", "呢", "的", "也"], answer: "吗",
    explanation: "吗 đặt cuối câu khẳng định để biến thành câu hỏi có/không. Trật tự từ không đổi!",
    hanVietHint: "学生 → HỌC SINH" },
  { id: "fb-003", grammarId: "B1-NP5", type: "fill-blank", lesson: 1,
    prompt: "我___高兴。", options: ["很", "是", "也", "不是"], answer: "很",
    explanation: "Tính từ làm vị ngữ phải có phó từ đứng trước (thường là 很).",
    hanVietHint: "高兴 → CAO HỨNG (vui, hứng khởi)" },
  { id: "fb-004", grammarId: "B2-NP1", type: "fill-blank", lesson: 2,
    prompt: "你___是留学生吗？", options: ["们", "的", "也", "呢"], answer: "们",
    explanation: "们 thêm vào sau đại từ để tạo số nhiều: 你们 = các bạn.",
    hanVietHint: "留学生 → LƯU HỌC SINH" },
  { id: "fb-005", grammarId: "B2-NP2", type: "fill-blank", lesson: 2,
    prompt: "这是我___书。", options: ["的", "们", "也", "吗"], answer: "的",
    explanation: "的 đứng sau ĐN để biểu thị sở hữu. 我的书 = sách của tôi.",
    hanVietHint: null },
  { id: "fb-006", grammarId: "B2-NP3", type: "fill-blank", lesson: 2,
    prompt: "我___是中国人。", options: ["也", "很", "吗", "们"], answer: "也",
    explanation: "也 (cũng) phải đặt trước động từ/tính từ (giống tiếng Việt 'cũng'). Không đặt ở cuối câu kiểu tiếng Anh 'too'.",
    hanVietHint: "也 → DÃ (cũng vậy)" },
  { id: "fb-007", grammarId: "B2-NP4", type: "fill-blank", lesson: 2,
    prompt: "我是越南人，你___？", options: ["呢", "吗", "的", "也"], answer: "呢",
    explanation: "呢 cuối câu = 'còn bạn thì sao?' — hỏi lại về chủ đề đã nhắc.",
    hanVietHint: null },
  { id: "fb-008", grammarId: "CB-NP2", type: "fill-blank", lesson: 3,
    prompt: "你___说汉语吗？", options: ["会", "是", "很", "也"], answer: "会",
    explanation: "会 biểu thị khả năng học được: 'biết làm'. 会说 = biết nói.",
    hanVietHint: "会 → HỘI | 汉语 → HÁN NGỮ" },
  { id: "fb-009", grammarId: "CB-NP3", type: "fill-blank", lesson: 3,
    prompt: "我___听音乐。", options: ["喜欢", "会", "是", "很"], answer: "喜欢",
    explanation: "喜欢 + ĐT = thích làm gì. Theo sau có thể là ĐT hoặc DT.",
    hanVietHint: "喜欢 → HỶ HOAN | 音乐 → ÂM NHẠC" },
  { id: "fb-010", grammarId: "B3-NP4", type: "fill-blank", lesson: 3,
    prompt: "《汉日词典》，___汉语、日语词典。", options: ["就是", "是", "也是", "不是"], answer: "就是",
    explanation: "就是 = 'tức là / chính là' — dùng để giải thích hoặc nhấn mạnh định nghĩa.",
    hanVietHint: "就是 → TỰU THỊ | 词典 → TỪ ĐIỂN" },
  { id: "fb-011", grammarId: "B4-NP1", type: "fill-blank", lesson: 4,
    prompt: "图书馆___左边。", options: ["在", "是", "的", "吗"], answer: "在",
    explanation: "Chủ ngữ (图书馆) + 在 + địa điểm (左边): hỏi/trả lời 'ở đâu'. Ngược lại: 左边是图书馆 (địa điểm + 是 + tên nơi chốn).",
    hanVietHint: "图书馆 → ĐỒ THƯ QUÁN (thư viện) | 在 → TẠI (ở)" },
  { id: "fb-012", grammarId: "B4-NP1", type: "fill-blank", lesson: 4,
    prompt: "左边___图书馆。", options: ["是", "在", "的", "吗"], answer: "是",
    explanation: "Địa điểm (左边) + 是 + tên nơi chốn (图书馆): câu kiểu 'bên trái là thư viện'. Chú ý hướng ngược lại so với 在.",
    hanVietHint: "左边 → TẢ BIÊN (bên trái)" },
  { id: "fb-013", grammarId: "B4-NP2", type: "fill-blank", lesson: 4,
    prompt: "宿舍在图书馆的___。", options: ["左边", "左", "边", "北边"], answer: "左边",
    explanation: "Phương vị từ đầy đủ = gốc phương hướng + 边. 左 (trái) + 边 = 左边 (bên trái). Không nói chỉ '左' mà thiếu '边'.",
    hanVietHint: "宿舍 → TÚC XÁ (ký túc xá) | 左边 → TẢ BIÊN (bên trái)" },
  { id: "fb-014", grammarId: "B4-NP3", type: "fill-blank", lesson: 4,
    prompt: "请问，图书馆在___？", options: ["哪儿", "哪", "哪国", "哪里边"], answer: "哪儿",
    explanation: "哪儿 (= 哪里) là đại từ nghi vấn chỉ địa điểm 'ở đâu?'. Đặt sau 在 để hỏi vị trí.",
    hanVietHint: "哪儿 = 哪里 → NÃ LÝ (ở đâu?)" },
  { id: "fb-015", grammarId: "B4-NP4", type: "fill-blank", lesson: 4,
    prompt: "___，宿舍在哪儿？", options: ["请问", "对不起", "谢谢", "你好"], answer: "请问",
    explanation: "请问 = 'Xin hỏi' — dùng để mở đầu câu hỏi lịch sự khi hỏi người lạ. Đặt ở đầu câu, theo sau là câu hỏi bình thường.",
    hanVietHint: "请问 → THỈNH VẤN (xin hỏi) | 宿舍 → TÚC XÁ (ký túc xá)" },
  { id: "fb-016", grammarId: "B4-NP5", type: "fill-blank", lesson: 4,
    prompt: "A: 对不起！ B: ___。", options: ["没关系", "谢谢", "不客气", "你好"], answer: "没关系",
    explanation: "没关系 = 'Không sao' — câu đáp lại cố định khi nghe 对不起. Nghĩa đen: 'không có quan hệ [gì cả]'.",
    hanVietHint: "没关系 → MỘT QUAN HỆ | 关系 → QUAN HỆ ✨ (giống hệt tiếng Việt!)" },
  { id: "fb-017", grammarId: "CB-NP4", type: "fill-blank", lesson: 4,
    prompt: "这___人是谁？", options: ["个", "本", "们", "的"], answer: "个",
    explanation: "个 là lượng từ chung cho người. 这 + 个 + DT = 'cái/người này'. Khác 这 + 是 + DT (câu định nghĩa).",
    hanVietHint: "个 → CÁ (trong 'cá nhân' 个人)" },
  { id: "fb-018", grammarId: "CB-NP5", type: "fill-blank", lesson: 4,
    prompt: "我___他叫什么名字。", options: ["知道", "会", "是", "认识"], answer: "知道",
    explanation: "知道 = biết thông tin/sự kiện. Biết tên ai → dùng 知道 (biết rằng tên là gì). Khác 会 = biết làm kỹ năng gì.",
    hanVietHint: "知道 → TRI ĐẠO | 名字 → DANH TỰ (tên)" },
  { id: "fb-019", grammarId: "CB-NP5", type: "fill-blank", lesson: 4,
    prompt: "你___说日语吗？", options: ["会", "知道", "是", "很"], answer: "会",
    explanation: "会 = biết làm kỹ năng (qua học hỏi, luyện tập). Nói tiếng Nhật là kỹ năng → dùng 会. Không thể nói '知道说日语'.",
    hanVietHint: "会 → HỘI (lĩnh hội, biết qua rèn luyện) | 日语 → NHẬT NGỮ" },

  // ── Sentence Builder ──
  { id: "sb-001", grammarId: "B1-NP2", type: "sentence-builder", lesson: 1,
    fragments: ["她", "是", "老师"], answer: ["她", "是", "老师"],
    explanation: "CN + 是 + DT: Chủ ngữ + là + danh từ vị ngữ.",
    hanVietHint: "老师 → LÃO SƯ" },
  { id: "sb-002", grammarId: "B1-NP2", type: "sentence-builder", lesson: 1,
    fragments: ["留学生", "你", "不是"], answer: ["你", "不是", "留学生"],
    explanation: "Phủ định: CN + 不是 + DT. 不是 là một khối.",
    hanVietHint: "留学生 → LƯU HỌC SINH" },
  { id: "sb-003", grammarId: "B1-NP5", type: "sentence-builder", lesson: 1,
    fragments: ["高兴", "我", "很"], answer: ["我", "很", "高兴"],
    explanation: "CN + 很 + TT: tính từ làm VN phải có 很 đứng trước.",
    hanVietHint: "高兴 → CAO HỨNG" },
  { id: "sb-004", grammarId: "B2-NP3", type: "sentence-builder", lesson: 2,
    fragments: ["中国人", "我", "是", "也"], answer: ["我", "也", "是", "中国人"],
    explanation: "也 phải đặt sau CN và TRƯỚC 是/ĐT/TT — không được đặt cuối câu.",
    hanVietHint: "中国 → TRUNG QUỐC" },
  { id: "sb-005", grammarId: "B2-NP7", type: "sentence-builder", lesson: 2,
    fragments: ["他", "你", "吗", "认识"], answer: ["你", "认识", "他", "吗"],
    explanation: "S + V + O + 吗: câu hỏi cơ bản. Thêm 吗 vào cuối, trật tự từ không đổi.",
    hanVietHint: "认识 → NHẬN THỨC" },
  { id: "sb-006", grammarId: "CB-NP2", type: "sentence-builder", lesson: 3,
    fragments: ["越南语", "大卫", "说", "不会"], answer: ["大卫", "不会", "说", "越南语"],
    explanation: "CN + 不会 + ĐT: phủ định khả năng. 不会 là một khối.",
    hanVietHint: "越南 → VIỆT NAM | 说 → THUYẾT" },
  { id: "sb-007", grammarId: "CB-NP1", type: "sentence-builder", lesson: 3,
    fragments: ["书", "这", "本", "是", "我的"], answer: ["这", "本", "书", "是", "我的"],
    explanation: "这/那 + 本 + DT: 本 là lượng từ cho sách, đứng giữa chỉ định từ và danh từ.",
    hanVietHint: "本 → BẢN (cuốn/quyển)" },
  { id: "sb-008", grammarId: "B4-NP1", type: "sentence-builder", lesson: 4,
    fragments: ["图书馆", "在", "左边"], answer: ["图书馆", "在", "左边"],
    explanation: "CN + 在 + địa điểm: 图书馆 (CN) + 在 + 左边 (địa điểm). Trật tự giống tiếng Việt: 'Thư viện ở bên trái'.",
    hanVietHint: "图书馆 → ĐỒ THƯ QUÁN | 左边 → TẢ BIÊN" },
  { id: "sb-009", grammarId: "B4-NP2", type: "sentence-builder", lesson: 4,
    fragments: ["朋友", "在", "我的", "左边"], answer: ["朋友", "在", "我的", "左边"],
    explanation: "CN + 在 + N的 + phương vị từ: 'Bạn ở bên trái tôi'. Chú ý N的 + phương vị từ = 'bên trái của N' (trật tự ngược tiếng Việt: 'bên trái tôi' vs '我的左边').",
    hanVietHint: "朋友 → BẰNG HỮU ✨ | 左边 → TẢ BIÊN (bên trái)" },
  { id: "sb-010", grammarId: "B4-NP3", type: "sentence-builder", lesson: 4,
    fragments: ["请问", "图书馆", "在", "哪儿"], answer: ["请问", "图书馆", "在", "哪儿"],
    explanation: "请问 đầu câu + câu hỏi bình thường. 图书馆在哪儿？ = thư viện ở đâu? Không đảo trật tự từ.",
    hanVietHint: "请问 → THỈNH VẤN | 哪儿 = 哪里" },
  { id: "sb-011", grammarId: "CB-NP4", type: "sentence-builder", lesson: 4,
    fragments: ["那", "个", "人", "是", "大卫"], answer: ["那", "个", "人", "是", "大卫"],
    explanation: "那 + 个 + DT + 是 + tên: 'Người đó là David'. 那个人 = người đó (那 + lượng từ 个 + DT).",
    hanVietHint: "个 → CÁ (cá nhân)" },

  // ── Error Correction ──
  { id: "ec-001", grammarId: "B1-NP2", type: "error-correction", lesson: 1,
    tokens: ["她", "是", "很", "高兴", "。"], errorIndex: 1,
    correction: ["她", "很", "高兴", "。"],
    explanation: "是 KHÔNG dùng trước tính từ! Tiếng Trung nói '她很高兴', KHÔNG phải '她是很高兴'.",
    hanVietHint: "高兴 → CAO HỨNG" },
  { id: "ec-002", grammarId: "B2-NP1", type: "error-correction", lesson: 2,
    tokens: ["美国人们", "来", "。"], errorIndex: 0,
    correction: ["美国人", "来", "。"],
    explanation: "们 KHÔNG dùng sau từ chỉ quốc tịch. Chỉ dùng 们 với đại từ (我们) hoặc DT chỉ người cụ thể (老师们).",
    hanVietHint: null },
  { id: "ec-003", grammarId: "B2-NP3", type: "error-correction", lesson: 2,
    tokens: ["我", "是", "中国人", "也", "。"], errorIndex: 3,
    correction: ["我", "也", "是", "中国人", "。"],
    explanation: "也 phải đứng TRƯỚC động từ/tính từ, không phải cuối câu.",
    hanVietHint: "也 → DÃ" },
  { id: "ec-004", grammarId: "B3-NP3", type: "error-correction", lesson: 3,
    tokens: ["那", "是", "谁", "的", "书", "吗", "？"], errorIndex: 5,
    correction: ["那", "是", "谁", "的", "书", "？"],
    explanation: "吗 KHÔNG dùng cùng với đại từ nghi vấn (谁, 什么, 哪). Khi đã có 谁/什么/哪, câu đã là câu hỏi.",
    hanVietHint: "谁 → THÙY (ai)" },
  { id: "ec-005", grammarId: "B1-NP5", type: "error-correction", lesson: 1,
    tokens: ["她", "高兴", "。"], errorIndex: 1,
    correction: ["她", "很", "高兴", "。"],
    explanation: "Tính từ làm VN phải có phó từ đứng trước (thường dùng 很). Nói '她很高兴' mới tự nhiên.",
    hanVietHint: "高兴 → CAO HỨNG" },
  { id: "ec-006", grammarId: "B4-NP1", type: "error-correction", lesson: 4,
    tokens: ["图书馆", "是", "那儿", "。"], errorIndex: 1,
    correction: ["图书馆", "在", "那儿", "。"],
    explanation: "Khi chủ ngữ là một địa điểm/vật và ta nói nó 'ở đâu' → dùng 在 chứ không phải 是. 是 dùng khi địa điểm làm CHỦ NGỮ: '那儿是图书馆'.",
    hanVietHint: "在 → TẠI (ở) | 是 → THỊ (là)" },
  { id: "ec-007", grammarId: "CB-NP5", type: "error-correction", lesson: 4,
    tokens: ["我", "知道", "说", "汉语", "。"], errorIndex: 1,
    correction: ["我", "会", "说", "汉语", "。"],
    explanation: "Nói tiếng Trung là một KỸ NĂNG học được → dùng 会, không phải 知道. 知道 = biết thông tin. 会 = biết làm. '我知道说汉语' không đúng ngữ pháp.",
    hanVietHint: "会 → HỘI | 汉语 → HÁN NGỮ" },

  // ── Pattern Matching ──
  { id: "pm-001", grammarId: null, type: "pattern-match", lesson: 1,
    pairs: [
      { left: "CN + 是 + DT",     right: "Cô ấy là giáo viên." },
      { left: "CN + 不是 + DT",   right: "Bạn không phải là học sinh." },
      { left: "CN + 很 + TT",     right: "Tôi rất vui." },
      { left: "CN + VN + 吗？",   right: "Bạn có phải là lưu học sinh không?" }
    ],
    explanation: "是 chỉ dùng với DT. 很 chỉ dùng với TT. 吗 thêm vào cuối câu để hỏi." },
  { id: "pm-002", grammarId: null, type: "pattern-match", lesson: 2,
    pairs: [
      { left: "ĐN + 的 + DT",         right: "sách của tôi / 我的书" },
      { left: "CN + 也 + VN",          right: "Tôi cũng là người Trung Quốc." },
      { left: "[chủ đề] + 呢？",       right: "Còn bạn thì sao?" },
      { left: "CN + 不 + ĐT + TN",    right: "Tôi không quen anh ấy." }
    ],
    explanation: null },
  { id: "pm-003", grammarId: null, type: "pattern-match", lesson: 3,
    pairs: [
      { left: "谁的 + DT",      right: "Đây là sách của ai?" },
      { left: "什么 + DT",      right: "Đây là tạp chí gì?" },
      { left: "哪 + 本 + DT",   right: "Cuốn sách nào là của bạn?" },
      { left: "X，就是 Y",      right: "Từ điển Hán-Nhật, tức là từ điển TQ-NB." }
    ],
    explanation: "谁的/什么/哪 là đại từ nghi vấn — câu hỏi KHÔNG dùng 吗 thêm vào." },
  { id: "pm-004", grammarId: null, type: "pattern-match", lesson: 3,
    pairs: [
      { left: "你会说什么语言？",      right: "会 + ĐT (biết làm)" },
      { left: "我喜欢听音乐。",        right: "喜欢 + ĐT (thích làm)" },
      { left: "这本书是我的。",        right: "Số/ĐT chỉ định + 本 + DT" },
      { left: "你认识他吗？",          right: "S + V + O + 吗 (câu hỏi cơ bản)" }
    ],
    explanation: null },
  { id: "pm-005", grammarId: null, type: "pattern-match", lesson: 4,
    pairs: [
      { left: "CN + 在 + DT",          right: "Thư viện ở bên trái." },
      { left: "DT + 是 + CN",          right: "Bên trái là thư viện." },
      { left: "CN + 在哪儿？",         right: "Ký túc xá ở đâu?" },
      { left: "请问 + [câu hỏi]",      right: "Xin hỏi, thư viện ở đâu?" }
    ],
    explanation: "在 hỏi/trả lời 'ở đâu'. 是 hỏi/trả lời 'là gì'. Hai cấu trúc KHÔNG hoán đổi cho nhau." },
  { id: "pm-006", grammarId: null, type: "pattern-match", lesson: 4,
    pairs: [
      { left: "左边",    right: "bên trái" },
      { left: "右边",    right: "bên phải" },
      { left: "上边",    right: "phía trên" },
      { left: "下边",    right: "phía dưới" },
      { left: "北边",    right: "phía bắc" }
    ],
    explanation: "Phương vị từ: gốc chỉ hướng + 边." },
  { id: "pm-007", grammarId: null, type: "pattern-match", lesson: 4,
    pairs: [
      { left: "我知道他是学生。",       right: "知道 — biết thông tin/sự kiện" },
      { left: "我会说汉语。",           right: "会 — biết kỹ năng (qua học)" },
      { left: "对不起！没关系。",       right: "对不起/没关系 — xin lỗi & đáp lại" },
      { left: "那个人是谁？",           right: "个 — lượng từ chung cho người" }
    ],
    explanation: null },

  // ── Translation ──
  { id: "tr-001", grammarId: "B1-NP2", type: "translation", lesson: 1,
    direction: "vi-to-zh", sourceText: "Cô ấy là giáo viên.", targetText: "她是老师。",
    acceptedVariants: ["她是老师"],
    hanVietHint: "老师 → LÃO SƯ | 她 = cô ấy",
    explanation: "CN + 是 + DT. 是 bắt buộc — không được bỏ qua!" },
  { id: "tr-002", grammarId: "B1-NP3", type: "translation", lesson: 1,
    direction: "vi-to-zh", sourceText: "Bạn có phải là lưu học sinh không?", targetText: "你是留学生吗？",
    acceptedVariants: ["你是留学生吗"],
    hanVietHint: "留学生 → LƯU HỌC SINH ✨",
    explanation: "Thêm 吗 vào cuối câu khẳng định, trật tự từ giữ nguyên." },
  { id: "tr-003", grammarId: "B2-NP6", type: "translation", lesson: 2,
    direction: "vi-to-zh", sourceText: "Tôi là người Việt Nam.", targetText: "我是越南人。",
    acceptedVariants: ["我是越南人"],
    hanVietHint: "越南 → VIỆT NAM ✨ | 人 → NHÂN",
    explanation: "Tên quốc gia + 人 = người nước đó." },
  { id: "tr-004", grammarId: "B2-NP3", type: "translation", lesson: 2,
    direction: "vi-to-zh", sourceText: "Tôi cũng rất vui.", targetText: "我也很高兴。",
    acceptedVariants: ["我也很高兴"],
    hanVietHint: "高兴 → CAO HỨNG ✨ | 也 → DÃ",
    explanation: "也 đứng trước 很, 很 đứng trước tính từ. Trật tự: CN + 也 + 很 + TT." },
  { id: "tr-005", grammarId: "B3-NP1", type: "translation", lesson: 3,
    direction: "vi-to-zh", sourceText: "Đó là từ điển của bạn tôi.", targetText: "那是我朋友的词典。",
    acceptedVariants: ["那是我朋友的词典", "那是我的朋友的词典"],
    hanVietHint: "词典 → TỪ ĐIỂN ✨ | 朋友 → BẰNG HỮU ✨",
    explanation: "那 + 是 + [ĐN]的 + DT. 我朋友的 = của bạn tôi." },
  { id: "tr-006", grammarId: "CB-NP2", type: "translation", lesson: 3,
    direction: "vi-to-zh", sourceText: "Bạn biết nói ngôn ngữ gì?", targetText: "你会说什么语言？",
    acceptedVariants: ["你会说什么语言"],
    hanVietHint: "语言 → NGỮ NGÔN ✨ | 说 → THUYẾT",
    explanation: "会说 = biết nói. 什么语言 = ngôn ngữ gì — đại từ nghi vấn giữ nguyên vị trí." },
  { id: "tr-007", grammarId: "B2-NP2", type: "translation", lesson: 2,
    direction: "zh-to-vi", sourceText: "那是你的词典吗？", targetText: "Đó có phải từ điển của bạn không?",
    acceptedVariants: null,
    hanVietHint: "词典 → TỪ ĐIỂN ✨",
    explanation: "那 = đó/kia. 你的词典 = từ điển của bạn. 吗 = câu hỏi có/không." },
  { id: "tr-008", grammarId: "B4-NP1", type: "translation", lesson: 4,
    direction: "vi-to-zh", sourceText: "Xin hỏi, thư viện ở đâu?", targetText: "请问，图书馆在哪儿？",
    acceptedVariants: ["请问，图书馆在哪里？", "请问图书馆在哪儿？", "请问图书馆在哪里？"],
    hanVietHint: "请问 → THỈNH VẤN ✨ | 图书馆 → ĐỒ THƯ QUÁN | 哪儿 = 哪里",
    explanation: "请问 đầu câu → câu hỏi bình thường. 在哪儿？= 在哪里？ (ở đâu?)." },
  { id: "tr-009", grammarId: "B4-NP1", type: "translation", lesson: 4,
    direction: "vi-to-zh", sourceText: "Bên trái là ký túc xá.", targetText: "左边是宿舍。",
    acceptedVariants: ["左边是宿舍"],
    hanVietHint: "宿舍 → TÚC XÁ ✨ (ký túc xá) | 左边 → TẢ BIÊN",
    explanation: "Địa điểm làm chủ ngữ → dùng 是: 左边 (địa điểm) + 是 + 宿舍 (tên nơi)." },
  { id: "tr-010", grammarId: "B4-NP2", type: "translation", lesson: 4,
    direction: "vi-to-zh", sourceText: "Trường học ở bên phải thư viện.", targetText: "学校在图书馆的右边。",
    acceptedVariants: ["学校在图书馆右边。", "学校在图书馆的右边"],
    hanVietHint: "右边 → HỮU BIÊN (bên phải)",
    explanation: "N + 的 + phương vị từ: 图书馆的右边 = 'bên phải của thư viện'. Trật tự N + 的 trước phương vị từ." },
  { id: "tr-011", grammarId: "CB-NP6", type: "translation", lesson: 4,
    direction: "vi-to-zh", sourceText: "Người tôi thích là cô ấy.", targetText: "我喜欢的人是她。",
    acceptedVariants: ["我喜欢的人是她"],
    hanVietHint: "喜欢 → HỶ HOAN ✨ | [CN+ĐT] + 的 + DT = mệnh đề quan hệ",
    explanation: "Cụm ĐT làm định ngữ: [我喜欢] + 的 + 人. Tiếng Trung đặt mệnh đề quan hệ TRƯỚC danh từ — ngược với tiếng Việt ('người *mà tôi thích*' → đặt sau)." },
];
