/**
 * Grammar Exercises Data
 *
 * Each question links to a grammar pattern via `grammarId`.
 * Types: fill-blank | sentence-builder | error-correction | pattern-match | translation | listening
 */

const grammarPatterns = [
  {
    id: "B1-NP2", lesson: 1, difficulty: "beginner-1",
    title: "Câu chữ 是 — Câu Vị Ngữ Danh Từ",
    structure: "CN + 是/不是 + DT",
    explanation: "Khi vị ngữ là danh từ, 是 bắt buộc phải có — không được bỏ như tiếng Anh ('She teacher' ✗). Phủ định dùng 不是.",
    examples: [
      { zh: "她是老师。", vi: "Cô ấy là giáo viên." },
      { zh: "我不是学生。", vi: "Tôi không phải là học sinh." },
      { zh: "你是留学生吗？", vi: "Bạn có phải là lưu học sinh không?" },
    ],
    notes: [
      "Textbook định nghĩa 2 công thức chuẩn: (1) S + 是 + N, (2) S + 不是 + N. Câu hỏi: xem B1-NP3.",
      "是 KHÔNG dùng trước tính từ: 她是漂亮 ✗ → 她很漂亮 ✓",
      "Phủ định: 不是 (một khối), không phải 不是是",
    ],
  },
  {
    id: "B1-NP3", lesson: 1, difficulty: "beginner-1",
    title: "Câu hỏi 吗",
    structure: "Câu khẳng định + 吗？",
    explanation: "Thêm 吗 vào cuối câu khẳng định để tạo câu hỏi có/không. Trật tự từ không thay đổi — không cần đảo ngữ như tiếng Anh. Có 3 loại tùy vị ngữ: (1) vị ngữ DT — S+是+N+吗, (2) vị ngữ ĐT — S+V+O+吗, (3) vị ngữ TT — S+Adj+吗.",
    examples: [
      { zh: "你是老师吗？", vi: "Bạn có phải là giáo viên không? (vị ngữ DT)" },
      { zh: "他叫大卫吗？", vi: "Anh ấy có tên là David không? (vị ngữ ĐT)" },
      { zh: "他好吗？", vi: "Anh ấy khỏe không? (vị ngữ TT)" },
    ],
    notes: [
      "KHÔNG dùng 吗 cùng với 谁, 什么, 哪 — câu đã là câu hỏi rồi",
      "3 loại vị ngữ đều dùng 吗 được — chỉ cần thêm vào cuối câu, trật tự giữ nguyên",
      "吗 ≠ câu hỏi đuôi tiếng Anh (isn't it?). Chỉ hỏi có/không.",
    ],
  },
  {
    id: "B1-NP4", lesson: 1, difficulty: "beginner-1",
    title: "叫 — Tên gọi",
    structure: "CN + 叫 + tên",
    explanation: "叫 nghĩa là 'được gọi là / tên là'. Dùng để giới thiệu tên hoặc hỏi tên người khác.",
    examples: [
      { zh: "我叫大卫。", vi: "Tôi tên là David." },
      { zh: "你叫什么名字？", vi: "Bạn tên là gì?" },
      { zh: "她叫什么？", vi: "Cô ấy tên là gì?" },
    ],
    notes: [
      "叫 = tên đầy đủ / tên gọi. Khác với 姓 chỉ nói về họ.",
      "名字 (míngzi) = tên, họ tên",
    ],
  },
  {
    id: "B1-NP5", lesson: 1, difficulty: "beginner-1",
    title: "很 trước tính từ",
    structure: "CN + 很 + TT",
    explanation: "Tính từ làm vị ngữ bắt buộc phải có phó từ đứng trước (thường là 很). Nếu thiếu, câu mang nghĩa so sánh ngầm — nghe rất tự nhiên.",
    examples: [
      { zh: "我很高兴。", vi: "Tôi rất vui." },
      { zh: "她很漂亮。", vi: "Cô ấy rất đẹp." },
      { zh: "认识你很高兴。", vi: "Rất vui được quen biết bạn." },
    ],
    notes: [
      "很 ở đây không nhất thiết mang nghĩa 'rất' — chỉ là từ đệm cú pháp bắt buộc",
      "她高兴 nghe như so sánh: 'cô ấy vui hơn (ai đó)' ✗",
      "Sai phổ biến: 她是高兴 ✗ — 是 không đứng trước tính từ",
    ],
  },
  {
    id: "B2-NP1", lesson: 2, difficulty: "beginner-1",
    title: "Hậu tố 们 — Số nhiều",
    structure: "Đại từ / DT người + 们",
    explanation: "们 thêm vào sau đại từ hoặc danh từ chỉ người để tạo số nhiều. Chỉ dùng với người, không dùng với vật.",
    examples: [
      { zh: "我们是学生。", vi: "Chúng tôi là học sinh." },
      { zh: "你们好！", vi: "Các bạn/Mọi người chào!" },
      { zh: "老师们都很忙。", vi: "Các giáo viên đều rất bận." },
    ],
    notes: [
      "KHÔNG dùng 们 sau từ chỉ quốc tịch: 美国人们 ✗ → 美国人 ✓ (đã mang nghĩa tập thể)",
      "们 chỉ dùng với NGƯỜI, không dùng với đồ vật hay động vật",
    ],
  },
  {
    id: "B2-NP2", lesson: 2, difficulty: "beginner-1",
    title: "Trợ từ 的 — Sở hữu",
    structure: "ĐN + 的 + DT",
    explanation: "的 đứng sau định ngữ để biểu thị sở hữu hoặc bổ nghĩa cho danh từ. Đặt TRƯỚC danh từ — ngược với tiếng Việt đặt sau.",
    examples: [
      { zh: "这是我的书。", vi: "Đây là sách của tôi." },
      { zh: "那是谁的词典？", vi: "Đó là từ điển của ai?" },
      { zh: "她是我的同学。", vi: "Cô ấy là bạn cùng học của tôi." },
    ],
    notes: [
      "Vị trí: [người sở hữu] + 的 + [vật] — định ngữ đứng TRƯỚC danh từ",
      "Có thể bỏ 的 khi quan hệ gần gũi: 我妈妈 (không cần 我的妈妈)",
    ],
  },
  {
    id: "B2-NP3", lesson: 2, difficulty: "beginner-2",
    title: "Phó từ 也 — Cũng",
    structure: "CN + 也 + VN",
    explanation: "也 (cũng) phải đặt TRƯỚC động từ/tính từ, không được đặt cuối câu như tiếng Việt.",
    examples: [
      { zh: "我也是学生。", vi: "Tôi cũng là học sinh." },
      { zh: "她也很高兴。", vi: "Cô ấy cũng rất vui." },
      { zh: "我也认识他。", vi: "Tôi cũng quen biết anh ấy." },
    ],
    notes: [
      "Lỗi phổ biến của người Việt: 我是学生也 ✗ (đặt cuối kiểu tiếng Việt)",
      "Đúng: 我也是学生 ✓ — 也 đứng sau CN, trước ĐT/TT",
    ],
  },
  {
    id: "B2-NP4", lesson: 2, difficulty: "beginner-2",
    title: "Trợ từ 呢 — Còn… thì sao?",
    structure: "[chủ đề] + 呢？",
    explanation: "呢 cuối câu rút ngắn = hỏi lại về chủ đề đã nhắc. Dùng khi muốn hỏi 'còn X thì sao?' mà không cần lặp lại toàn bộ câu.",
    examples: [
      { zh: "我是越南人，你呢？", vi: "Tôi là người Việt Nam, còn bạn thì sao?" },
      { zh: "A：我很好。B：你呢？", vi: "A: Tôi khỏe. B: Còn bạn?" },
      { zh: "他是老师，她呢？", vi: "Anh ấy là giáo viên, còn cô ấy?" },
    ],
    notes: [
      "Khác 吗: 吗 hỏi hoàn toàn mới; 呢 hỏi lại trong ngữ cảnh đã có",
      "呢 rút ngắn câu — không cần lặp lại động từ hay vị ngữ",
    ],
  },
  {
    id: "B2-NP5", lesson: 2, difficulty: "beginner-1",
    title: "姓 — Họ",
    structure: "CN + 姓 + họ",
    explanation: "姓 dùng để nói về họ (surname). Khác với 叫 (tên đầy đủ). Hỏi họ: 你姓什么？",
    examples: [
      { zh: "我姓王。", vi: "Tôi họ Vương." },
      { zh: "你姓什么？", vi: "Bạn họ gì?" },
      { zh: "她姓李，叫李军。", vi: "Cô ấy họ Lý, tên là Lý Quân." },
    ],
    notes: [
      "姓 là động từ trong cấu trúc này, không phải danh từ",
      "Họ người Trung thường chỉ một chữ: 王, 李, 张…",
    ],
  },
  {
    id: "B2-NP6", lesson: 2, difficulty: "beginner-1",
    title: "哪国人 — Quốc tịch",
    structure: "CN + 是 + [quốc gia] + 人",
    explanation: "Tên quốc gia + 人 = người nước đó. Hỏi quốc tịch: 你是哪国人？ (Bạn là người nước nào?)",
    examples: [
      { zh: "我是越南人。", vi: "Tôi là người Việt Nam." },
      { zh: "他是中国人。", vi: "Anh ấy là người Trung Quốc." },
      { zh: "你是哪国人？", vi: "Bạn là người nước nào?" },
    ],
    notes: [
      "哪国人 = người nước nào? (câu hỏi quốc tịch)",
      "Không dùng 们 sau [quốc gia]人: 越南人们 ✗",
    ],
  },
  {
    id: "B2-NP7", lesson: 2, difficulty: "beginner-1",
    title: "Câu S + V + O cơ bản",
    structure: "CN + ĐT + TN",
    explanation: "Cấu trúc câu cơ bản: Chủ ngữ + Động từ + Tân ngữ. Tân ngữ đứng SAU động từ, giống tiếng Việt.",
    examples: [
      { zh: "你认识他吗？", vi: "Bạn có quen biết anh ấy không?" },
      { zh: "我介绍一下儿。", vi: "Tôi giới thiệu một chút." },
      { zh: "她学汉语。", vi: "Cô ấy học tiếng Trung." },
    ],
    notes: [
      "Trật tự SVO cơ bản giống tiếng Việt — tân ngữ đứng sau động từ",
      "Thêm 吗 vào cuối để biến thành câu hỏi, không cần đảo ngữ",
    ],
  },
  {
    id: "B2-NP8", lesson: 2, difficulty: "beginner-1",
    title: "我来 + ĐT — Lời đề nghị lịch sự",
    structure: "我来 + ĐT",
    explanation: "我来 + ĐT = 'để tôi làm / tôi sẽ làm'. Thể hiện sự chủ động, lịch sự. Thường dùng trong lớp học hoặc khi giúp đỡ người khác.",
    examples: [
      { zh: "我来介绍一下。", vi: "Để tôi giới thiệu một chút." },
      { zh: "我来做。", vi: "Để tôi làm." },
      { zh: "我来回答。", vi: "Để tôi trả lời." },
    ],
    notes: [
      "来 trong cụm này mang nghĩa 'để tôi…' — không phải nghĩa gốc 'đến'",
      "Thường kết hợp với 一下: 我来介绍一下 = để tôi giới thiệu một chút (nghe lịch sự hơn)",
    ],
  },
  {
    id: "B3-NP1", lesson: 3, difficulty: "beginner-1",
    title: "这/那 — Chỉ định từ",
    structure: "这/那 + 是 + DT",
    explanation: "这 (zhè) = này/đây, 那 (nà) = đó/kia. Dùng để chỉ định hoặc giới thiệu đối tượng.",
    examples: [
      { zh: "这是我的书。", vi: "Đây là sách của tôi." },
      { zh: "那是谁？", vi: "Kia là ai?" },
      { zh: "这是我的同屋。", vi: "Đây là bạn cùng phòng của tôi." },
    ],
    notes: [
      "这/那 trực tiếp làm chủ ngữ. Khi đứng trước DT cần thêm lượng từ: 这本书, 那个人",
      "这里/这儿 = nơi này; 那里/那儿 = nơi kia",
    ],
  },
  {
    id: "B3-NP2", lesson: 3, difficulty: "beginner-2",
    title: "的 với từ nghi vấn",
    structure: "谁的/什么 + DT",
    explanation: "Đại từ nghi vấn (谁, 什么, 哪) đứng ngay tại vị trí của đáp án — không cần đảo ngữ. 谁的 = của ai.",
    examples: [
      { zh: "这是谁的书？", vi: "Đây là sách của ai?" },
      { zh: "那是什么杂志？", vi: "Đó là tạp chí gì?" },
      { zh: "哪本是你的？", vi: "Cuốn nào là của bạn?" },
    ],
    notes: [
      "Vị trí đại từ nghi vấn = vị trí của đáp án trong câu trả lời",
      "KHÔNG thêm 吗 vào câu đã có 谁/什么/哪",
    ],
  },
  {
    id: "B3-NP3", lesson: 3, difficulty: "beginner-2",
    title: "吗 vs 谁/什么/哪 — Hai loại câu hỏi",
    structure: "吗 ↔ 谁/什么/哪 (không dùng cùng nhau)",
    explanation: "Hai loại câu hỏi khác nhau hoàn toàn: (1) Hỏi có/không → dùng 吗. (2) Hỏi thông tin cụ thể → dùng 谁/什么/哪, KHÔNG dùng 吗.",
    examples: [
      { zh: "那是词典吗？✓", vi: "Đó có phải từ điển không?" },
      { zh: "那是什么词典？✓", vi: "Đó là từ điển gì?" },
      { zh: "那是什么词典吗？✗", vi: "(Sai — không dùng 吗 cùng 什么)" },
    ],
    notes: [
      "Quy tắc: câu đã có 谁/什么/哪 → KHÔNG thêm 吗",
      "Lỗi thường gặp: 这是谁的书吗？✗ → 这是谁的书？✓",
      "Câu hỏi với 谁/什么/哪 không cần đảo ngữ — giữ nguyên trật tự câu",
    ],
  },
  {
    id: "B3-NP4", lesson: 3, difficulty: "beginner-2",
    title: "就是 — Tức là / Chính là",
    structure: "X，就是 Y",
    explanation: "就是 = 'tức là / chính là' — dùng để giải thích, định nghĩa hoặc nhấn mạnh. Mạnh hơn 是 thông thường.",
    examples: [
      { zh: "《汉日词典》，就是汉语日语词典。", vi: "Từ điển Hán-Nhật, tức là từ điển Trung-Nhật." },
      { zh: "这，就是我说的那本书。", vi: "Đây chính là cuốn sách tôi đã nói." },
      { zh: "他就是李军。", vi: "Anh ấy chính là Lý Quân." },
    ],
    notes: [
      "就是 nhấn mạnh hơn 是: 他是李军 (trung tính) vs 他就是李军 (chính là anh ấy)",
      "Thường dùng để giải thích thuật ngữ hoặc xác nhận danh tính",
    ],
  },
  {
    id: "CB-NP1", lesson: 3, difficulty: "beginner-2",
    title: "Lượng từ 本",
    structure: "Số / ĐT chỉ định + 本 + DT",
    explanation: "本 là lượng từ dùng cho sách, vở, tạp chí. Lượng từ bắt buộc phải có giữa số từ/chỉ định từ và danh từ — không thể bỏ qua như tiếng Việt.",
    examples: [
      { zh: "一本书", vi: "một cuốn sách" },
      { zh: "这本词典是我的。", vi: "Cuốn từ điển này là của tôi." },
      { zh: "那本杂志叫什么名字？", vi: "Tờ tạp chí kia tên là gì?" },
    ],
    notes: [
      "本 chỉ dùng cho vật dạng cuốn/quyển. Các lượng từ khác: 个 (người/vật chung), 张 (tờ giấy)",
      "Không thể nói 一书 ✗ hay 这书 ✗ — lượng từ là bắt buộc",
    ],
  },
  {
    id: "CB-NP2", lesson: 3, difficulty: "beginner-2",
    title: "会 — Biết làm (qua học)",
    structure: "CN + 会/不会 + ĐT",
    explanation: "会 biểu thị khả năng có được qua học tập, luyện tập ('biết làm'). Phủ định: 不会.",
    examples: [
      { zh: "我会说汉语。", vi: "Tôi biết nói tiếng Trung." },
      { zh: "大卫不会说越南语。", vi: "David không biết nói tiếng Việt." },
      { zh: "你会说什么语言？", vi: "Bạn biết nói ngôn ngữ gì?" },
    ],
    notes: [
      "会 ≠ 能: 会 = khả năng do học; 能 = khả năng do điều kiện cho phép",
      "会说话 = biết nói (đã học xong); 能说话 = có thể nói (điều kiện OK)",
    ],
  },
  {
    id: "CB-NP3", lesson: 3, difficulty: "beginner-2",
    title: "喜欢 — Thích",
    structure: "CN + 喜欢 + ĐT/DT",
    explanation: "喜欢 = thích. Theo sau có thể là động từ (thích làm gì) hoặc danh từ (thích cái gì). Không cần thêm gì giữa 喜欢 và động từ.",
    examples: [
      { zh: "我喜欢听音乐。", vi: "Tôi thích nghe nhạc." },
      { zh: "她喜欢汉语。", vi: "Cô ấy thích tiếng Trung." },
      { zh: "你喜欢看什么杂志？", vi: "Bạn thích đọc tạp chí gì?" },
    ],
    notes: [
      "喜欢 + ĐT trực tiếp — không cần thêm 做 hay từ nối nào",
      "Phủ định: 不喜欢 + ĐT/DT",
    ],
  },
];

const grammarQuestions = [
  // ── Fill-in-the-Blank ──
  { id: "fb-001", grammarId: "B1-NP2", type: "fill-blank", lesson: 1, difficulty: "beginner-1",
    prompt: "她___老师。", options: ["是", "很", "吗", "的"], answer: "是",
    explanation: "Vị ngữ là danh từ (老师) → bắt buộc có 是 ở giữa.",
    hanVietHint: "是 → THỊ | 老师 → LÃO SƯ" },
  { id: "fb-002", grammarId: "B1-NP3", type: "fill-blank", lesson: 1, difficulty: "beginner-1",
    prompt: "你是学生___？", options: ["吗", "呢", "的", "也"], answer: "吗",
    explanation: "吗 đặt cuối câu khẳng định để biến thành câu hỏi có/không. Trật tự từ không đổi!",
    hanVietHint: "学生 → HỌC SINH" },
  { id: "fb-003", grammarId: "B1-NP5", type: "fill-blank", lesson: 1, difficulty: "beginner-1",
    prompt: "我___高兴。", options: ["很", "是", "也", "不是"], answer: "很",
    explanation: "Tính từ làm vị ngữ phải có phó từ đứng trước (thường là 很).",
    hanVietHint: "高兴 → CAO HỨNG (vui, hứng khởi)" },
  { id: "fb-004", grammarId: "B2-NP1", type: "fill-blank", lesson: 2, difficulty: "beginner-1",
    prompt: "你___是留学生吗？", options: ["们", "的", "也", "呢"], answer: "们",
    explanation: "们 thêm vào sau đại từ để tạo số nhiều: 你们 = các bạn.",
    hanVietHint: "留学生 → LƯU HỌC SINH" },
  { id: "fb-005", grammarId: "B2-NP2", type: "fill-blank", lesson: 2, difficulty: "beginner-1",
    prompt: "这是我___书。", options: ["的", "们", "也", "吗"], answer: "的",
    explanation: "的 đứng sau ĐN để biểu thị sở hữu. 我的书 = sách của tôi.",
    hanVietHint: null },
  { id: "fb-006", grammarId: "B2-NP3", type: "fill-blank", lesson: 2, difficulty: "beginner-2",
    prompt: "我___是中国人。", options: ["也", "很", "吗", "们"], answer: "也",
    explanation: "也 (cũng) phải đặt trước động từ/tính từ, KHÔNG đặt cuối câu như tiếng Việt.",
    hanVietHint: "也 → DÃ (cũng vậy)" },
  { id: "fb-007", grammarId: "B2-NP4", type: "fill-blank", lesson: 2, difficulty: "beginner-2",
    prompt: "我是越南人，你___？", options: ["呢", "吗", "的", "也"], answer: "呢",
    explanation: "呢 cuối câu = 'còn bạn thì sao?' — hỏi lại về chủ đề đã nhắc.",
    hanVietHint: null },
  { id: "fb-008", grammarId: "CB-NP2", type: "fill-blank", lesson: 3, difficulty: "beginner-2",
    prompt: "你___说汉语吗？", options: ["会", "是", "很", "也"], answer: "会",
    explanation: "会 biểu thị khả năng học được: 'biết làm'. 会说 = biết nói.",
    hanVietHint: "会 → HỘI | 汉语 → HÁN NGỮ" },
  { id: "fb-009", grammarId: "CB-NP3", type: "fill-blank", lesson: 3, difficulty: "beginner-2",
    prompt: "我___听音乐。", options: ["喜欢", "会", "是", "很"], answer: "喜欢",
    explanation: "喜欢 + ĐT = thích làm gì. Theo sau có thể là ĐT hoặc DT.",
    hanVietHint: "喜欢 → HỶ HOAN | 音乐 → ÂM NHẠC" },
  { id: "fb-010", grammarId: "B3-NP4", type: "fill-blank", lesson: 3, difficulty: "beginner-2",
    prompt: "《汉日词典》，___汉语、日语词典。", options: ["就是", "是", "也是", "不是"], answer: "就是",
    explanation: "就是 = 'tức là / chính là' — dùng để giải thích hoặc nhấn mạnh định nghĩa.",
    hanVietHint: "就是 → TỰU THỊ | 词典 → TỪ ĐIỂN" },

  // ── Sentence Builder ──
  { id: "sb-001", grammarId: "B1-NP2", type: "sentence-builder", lesson: 1, difficulty: "beginner-1",
    fragments: ["她", "是", "老师"], answer: ["她", "是", "老师"],
    explanation: "CN + 是 + DT: Chủ ngữ + là + danh từ vị ngữ.",
    hanVietHint: "老师 → LÃO SƯ" },
  { id: "sb-002", grammarId: "B1-NP2", type: "sentence-builder", lesson: 1, difficulty: "beginner-1",
    fragments: ["留学生", "你", "不是"], answer: ["你", "不是", "留学生"],
    explanation: "Phủ định: CN + 不是 + DT. 不是 là một khối.",
    hanVietHint: "留学生 → LƯU HỌC SINH" },
  { id: "sb-003", grammarId: "B1-NP5", type: "sentence-builder", lesson: 1, difficulty: "beginner-1",
    fragments: ["高兴", "我", "很"], answer: ["我", "很", "高兴"],
    explanation: "CN + 很 + TT: tính từ làm VN phải có 很 đứng trước.",
    hanVietHint: "高兴 → CAO HỨNG" },
  { id: "sb-004", grammarId: "B2-NP3", type: "sentence-builder", lesson: 2, difficulty: "beginner-2",
    fragments: ["中国人", "我", "是", "也"], answer: ["我", "也", "是", "中国人"],
    explanation: "也 phải đặt sau CN và TRƯỚC 是/ĐT/TT — không được đặt cuối câu.",
    hanVietHint: "中国 → TRUNG QUỐC" },
  { id: "sb-005", grammarId: "B2-NP7", type: "sentence-builder", lesson: 2, difficulty: "beginner-1",
    fragments: ["他", "你", "吗", "认识"], answer: ["你", "认识", "他", "吗"],
    explanation: "S + V + O + 吗: câu hỏi cơ bản. Thêm 吗 vào cuối, trật tự từ không đổi.",
    hanVietHint: "认识 → NHẬN THỨC" },
  { id: "sb-006", grammarId: "CB-NP2", type: "sentence-builder", lesson: 3, difficulty: "beginner-2",
    fragments: ["越南语", "大卫", "说", "不会"], answer: ["大卫", "不会", "说", "越南语"],
    explanation: "CN + 不会 + ĐT: phủ định khả năng. 不会 là một khối.",
    hanVietHint: "越南 → VIỆT NAM | 说 → THUYẾT" },
  { id: "sb-007", grammarId: "CB-NP1", type: "sentence-builder", lesson: 3, difficulty: "beginner-2",
    fragments: ["书", "这", "本", "是", "我的"], answer: ["这", "本", "书", "是", "我的"],
    explanation: "这/那 + 本 + DT: 本 là lượng từ cho sách, đứng giữa chỉ định từ và danh từ.",
    hanVietHint: "本 → BẢN (cuốn/quyển)" },

  // ── Error Correction ──
  { id: "ec-001", grammarId: "B1-NP2", type: "error-correction", lesson: 1, difficulty: "beginner-1",
    tokens: ["她", "是", "很", "漂亮", "。"], errorIndex: 1,
    correction: ["她", "很", "漂亮", "。"],
    explanation: "是 KHÔNG dùng trước tính từ! Tiếng Trung nói '她很漂亮', KHÔNG phải '她是很漂亮'.",
    hanVietHint: null },
  { id: "ec-002", grammarId: "B2-NP1", type: "error-correction", lesson: 2, difficulty: "beginner-2",
    tokens: ["美国人们", "来了", "。"], errorIndex: 0,
    correction: ["美国人", "来了", "。"],
    explanation: "们 KHÔNG dùng sau từ chỉ quốc tịch. Chỉ dùng 们 với đại từ (我们) hoặc DT chỉ người cụ thể (老师们).",
    hanVietHint: null },
  { id: "ec-003", grammarId: "B2-NP3", type: "error-correction", lesson: 2, difficulty: "beginner-2",
    tokens: ["我", "是", "中国人", "也", "。"], errorIndex: 3,
    correction: ["我", "也", "是", "中国人", "。"],
    explanation: "也 phải đứng TRƯỚC động từ/tính từ, không phải cuối câu.",
    hanVietHint: "也 → DÃ" },
  { id: "ec-004", grammarId: "B3-NP3", type: "error-correction", lesson: 3, difficulty: "beginner-2",
    tokens: ["那", "是", "谁", "的", "书", "吗", "？"], errorIndex: 5,
    correction: ["那", "是", "谁", "的", "书", "？"],
    explanation: "吗 KHÔNG dùng cùng với đại từ nghi vấn (谁, 什么, 哪). Khi đã có 谁/什么/哪, câu đã là câu hỏi.",
    hanVietHint: "谁 → THÙY (ai)" },
  { id: "ec-005", grammarId: "B1-NP5", type: "error-correction", lesson: 1, difficulty: "beginner-1",
    tokens: ["她", "高兴", "。"], errorIndex: 1,
    correction: ["她", "很", "高兴", "。"],
    explanation: "Tính từ làm VN phải có phó từ đứng trước (thường dùng 很). Nói '她很高兴' mới tự nhiên.",
    hanVietHint: "高兴 → CAO HỨNG" },

  // ── Pattern Matching ──
  { id: "pm-001", grammarId: null, type: "pattern-match", lesson: 1, difficulty: "beginner-1",
    pairs: [
      { left: "CN + 是 + DT",     right: "Cô ấy là giáo viên." },
      { left: "CN + 不是 + DT",   right: "Bạn không phải là học sinh." },
      { left: "CN + 很 + TT",     right: "Tôi rất vui." },
      { left: "CN + VN + 吗？",   right: "Bạn có phải là lưu học sinh không?" }
    ],
    explanation: "是 chỉ dùng với DT. 很 chỉ dùng với TT. 吗 thêm vào cuối câu để hỏi." },
  { id: "pm-002", grammarId: null, type: "pattern-match", lesson: 2, difficulty: "beginner-2",
    pairs: [
      { left: "ĐN + 的 + DT",         right: "sách của tôi / 我的书" },
      { left: "CN + 也 + VN",          right: "Tôi cũng là người Trung Quốc." },
      { left: "[chủ đề] + 呢？",       right: "Còn bạn thì sao?" },
      { left: "CN + 不 + ĐT + TN",    right: "Tôi không quen anh ấy." }
    ],
    explanation: null },
  { id: "pm-003", grammarId: null, type: "pattern-match", lesson: 3, difficulty: "beginner-2",
    pairs: [
      { left: "谁的 + DT",      right: "Đây là sách của ai?" },
      { left: "什么 + DT",      right: "Đây là tạp chí gì?" },
      { left: "哪 + 本 + DT",   right: "Cuốn sách nào là của bạn?" },
      { left: "X，就是 Y",      right: "Từ điển Hán-Nhật, tức là từ điển TQ-NB." }
    ],
    explanation: "谁的/什么/哪 là đại từ nghi vấn — câu hỏi KHÔNG dùng 吗 thêm vào." },
  { id: "pm-004", grammarId: null, type: "pattern-match", lesson: 3, difficulty: "beginner-2",
    pairs: [
      { left: "你会说什么语言？",      right: "会 + ĐT (biết làm)" },
      { left: "我喜欢听音乐。",        right: "喜欢 + ĐT (thích làm)" },
      { left: "这本书是我的。",        right: "Số/ĐT chỉ định + 本 + DT" },
      { left: "你认识他吗？",          right: "S + V + O + 吗 (câu hỏi cơ bản)" }
    ],
    explanation: null },

  // ── Translation ──
  { id: "tr-001", grammarId: "B1-NP2", type: "translation", lesson: 1, difficulty: "beginner-1",
    direction: "vi-to-zh", sourceText: "Cô ấy là giáo viên.", targetText: "她是老师。",
    acceptedVariants: ["她是老师"],
    hanVietHint: "老师 → LÃO SƯ | 她 = cô ấy",
    explanation: "CN + 是 + DT. 是 bắt buộc — không được bỏ qua!" },
  { id: "tr-002", grammarId: "B1-NP3", type: "translation", lesson: 1, difficulty: "beginner-1",
    direction: "vi-to-zh", sourceText: "Bạn có phải là lưu học sinh không?", targetText: "你是留学生吗？",
    acceptedVariants: ["你是留学生吗"],
    hanVietHint: "留学生 → LƯU HỌC SINH ✨",
    explanation: "Thêm 吗 vào cuối câu khẳng định, trật tự từ giữ nguyên." },
  { id: "tr-003", grammarId: "B2-NP6", type: "translation", lesson: 2, difficulty: "beginner-1",
    direction: "vi-to-zh", sourceText: "Tôi là người Việt Nam.", targetText: "我是越南人。",
    acceptedVariants: ["我是越南人"],
    hanVietHint: "越南 → VIỆT NAM ✨ | 人 → NHÂN",
    explanation: "Tên quốc gia + 人 = người nước đó." },
  { id: "tr-004", grammarId: "B2-NP3", type: "translation", lesson: 2, difficulty: "beginner-2",
    direction: "vi-to-zh", sourceText: "Tôi cũng rất vui.", targetText: "我也很高兴。",
    acceptedVariants: ["我也很高兴"],
    hanVietHint: "高兴 → CAO HỨNG ✨ | 也 → DÃ",
    explanation: "也 đứng trước 很, 很 đứng trước tính từ. Trật tự: CN + 也 + 很 + TT." },
  { id: "tr-005", grammarId: "B3-NP1", type: "translation", lesson: 3, difficulty: "beginner-1",
    direction: "vi-to-zh", sourceText: "Đó là từ điển của bạn tôi.", targetText: "那是我朋友的词典。",
    acceptedVariants: ["那是我朋友的词典", "那是我的朋友的词典"],
    hanVietHint: "词典 → TỪ ĐIỂN ✨ | 朋友 → BẰNG HỮU ✨",
    explanation: "那 + 是 + [ĐN]的 + DT. 我朋友的 = của bạn tôi." },
  { id: "tr-006", grammarId: "CB-NP2", type: "translation", lesson: 3, difficulty: "beginner-2",
    direction: "vi-to-zh", sourceText: "Bạn biết nói ngôn ngữ gì?", targetText: "你会说什么语言？",
    acceptedVariants: ["你会说什么语言"],
    hanVietHint: "语言 → NGỮ NGÔN ✨ | 说 → THUYẾT",
    explanation: "会说 = biết nói. 什么语言 = ngôn ngữ gì — đại từ nghi vấn giữ nguyên vị trí." },
  { id: "tr-007", grammarId: "B2-NP2", type: "translation", lesson: 2, difficulty: "beginner-1",
    direction: "zh-to-vi", sourceText: "那是你的词典吗？", targetText: "Đó có phải từ điển của bạn không?",
    acceptedVariants: null,
    hanVietHint: "词典 → TỪ ĐIỂN ✨",
    explanation: "那 = đó/kia. 你的词典 = từ điển của bạn. 吗 = câu hỏi có/không." },
];
