/**
 * Grammar Exercises Data
 *
 * Each question links to a grammar pattern via `grammarId`.
 * Types: fill-blank | sentence-builder | error-correction | pattern-match | translation | listening
 */

const grammarPatterns = [
  {
    id: "B1-NP2", lesson: 1,
    title: "Câu chữ 是 — Câu Vị Ngữ Danh Từ",
    structure: "CN + 是/不是 + DT",
    explanation: "Khi vị ngữ là danh từ, 是 bắt buộc phải có — không thể lược bỏ. Phủ định dùng 不是. Câu hỏi: thêm 吗 ở cuối (xem B1-NP3).<br><br><b>Công thức:</b><br>(1) CN + 是 + DT<br>(2) CN + 不是 + DT",
    examples: [
      { zh: "她是老师。", vi: "Cô ấy là giáo viên." },
      { zh: "我不是学生。", vi: "Tôi không phải là học sinh." },
      { zh: "你是留学生吗？", vi: "Bạn có phải là lưu học sinh không?" },
    ],
    notes: [
      "是 KHÔNG dùng trước tính từ: 她是高兴 ✗ → 她很高兴 ✓",
      "Phủ định: 不是 (một khối), không phải 不是是",
    ],
  },
  {
    id: "B1-NP3", lesson: 1,
    title: "Câu hỏi 吗",
    structure: "Câu khẳng định + 吗？",
    explanation: "Thêm 吗 vào cuối câu khẳng định để tạo câu hỏi có/không. Trật tự từ không thay đổi — không cần đảo ngữ. Có 3 loại tùy vị ngữ: danh từ, động từ, hoặc tính từ.<br><br><b>Công thức:</b><br>(1) CN + 是 + DT + 吗？<br>(2) CN + ĐT + TN + 吗？<br>(3) CN + TT + 吗？",
    examples: [
      { zh: "你是老师吗？", vi: "Bạn có phải là giáo viên không? (vị ngữ DT)" },
      { zh: "他叫大卫吗？", vi: "Anh ấy có tên là David không? (vị ngữ ĐT)" },
      { zh: "他好吗？", vi: "Anh ấy khỏe không? (vị ngữ TT)" },
    ],
    notes: [
      "KHÔNG dùng 吗 cùng với 谁, 什么, 哪 — câu đã là câu hỏi rồi",
      "3 loại vị ngữ đều dùng 吗 được — chỉ cần thêm vào cuối câu, trật tự giữ nguyên",
      "吗 ≠ câu hỏi đuôi tiếng Anh (isn't it?). Chỉ hỏi có/không.",
    ],
  },
  {
    id: "B1-NP4", lesson: 1,
    title: "叫 — Tên gọi",
    structure: "CN + 叫 + tên",
    explanation: "叫 nghĩa là 'được gọi là / tên là'. Dùng để giới thiệu tên hoặc hỏi tên người khác.",
    examples: [
      { zh: "我叫大卫。", vi: "Tôi tên là David." },
      { zh: "你叫什么名字？", vi: "Bạn tên là gì?" },
      { zh: "她叫什么？", vi: "Cô ấy tên là gì?" },
    ],
    notes: [
      "叫 = tên đầy đủ / tên gọi. Khác với 姓 chỉ nói về họ.",
      "名字 (míngzi) = tên, họ tên",
    ],
  },
  {
    id: "B1-NP5", lesson: 1,
    title: "很 trước tính từ",
    structure: "CN + 很 + TT",
    explanation: "Tính từ làm vị ngữ bắt buộc phải có phó từ đứng trước (thường là 很). Nếu bỏ 很, câu nghe KHÔNG hoàn chỉnh và người Trung sẽ hiểu thành câu so sánh ngầm — ví dụ 她高兴 nghe như 'cô ấy vui HƠN ai đó', không phải 'cô ấy vui'.",
    examples: [
      { zh: "我很高兴。", vi: "Tôi rất vui." },
      { zh: "她很好。", vi: "Cô ấy rất tốt/khỏe." },
      { zh: "认识你很高兴。", vi: "Rất vui được quen biết bạn." },
    ],
    notes: [
      "很 ở đây không nhất thiết mang nghĩa 'rất' — chỉ là từ đệm cú pháp bắt buộc",
      "她高兴 (không có 很) → nghe không tự nhiên, mang nghĩa so sánh: 'cô ấy vui HƠN người khác'",
      "Sai phổ biến: 她是高兴 ✗ — 是 không đứng trước tính từ",
    ],
  },
  {
    id: "B2-NP1", lesson: 2,
    title: "Hậu tố 们 — Số nhiều",
    structure: "Đại từ / DT người + 们",
    explanation: "们 thêm vào sau đại từ hoặc danh từ chỉ người để tạo số nhiều. Chỉ dùng với người, không dùng với vật.",
    examples: [
      { zh: "我们是学生。", vi: "Chúng tôi là học sinh." },
      { zh: "你们好！", vi: "Các bạn/Mọi người chào!" },
      { zh: "同学们很高兴。", vi: "Các bạn cùng học rất vui." },
    ],
    notes: [
      "KHÔNG dùng 们 sau từ chỉ quốc tịch: 美国人们 ✗ → 美国人 ✓ (đã mang nghĩa tập thể)",
      "们 chỉ dùng với NGƯỜI, không dùng với đồ vật hay động vật",
    ],
  },
  {
    id: "B2-NP2", lesson: 2,
    title: "Trợ từ 的 — Sở hữu",
    structure: "ĐN + 的 + DT",
    explanation: "的 đứng sau định ngữ để biểu thị sở hữu hoặc bổ nghĩa cho danh từ. Đặt TRƯỚC danh từ — ngược với tiếng Việt đặt sau.",
    examples: [
      { zh: "这是我的书。", vi: "Đây là sách của tôi." },
      { zh: "那是谁的词典？", vi: "Đó là từ điển của ai?" },
      { zh: "她是我的同学。", vi: "Cô ấy là bạn cùng học của tôi." },
    ],
    notes: [
      "Vị trí: [người sở hữu] + 的 + [vật] — định ngữ đứng TRƯỚC danh từ",
      "Có thể bỏ 的 khi quan hệ gần gũi: 我朋友 ≈ 我的朋友",
    ],
  },
  {
    id: "B2-NP3", lesson: 2,
    title: "Phó từ 也 — Cũng",
    structure: "CN + 也 + VN",
    explanation: "也 (cũng) phải đặt TRƯỚC động từ/tính từ (giống tiếng Việt: 'Tôi cũng là học sinh'). Không đặt 也 ở cuối câu như 'too' trong tiếng Anh.",
    examples: [
      { zh: "我也是学生。", vi: "Tôi cũng là học sinh." },
      { zh: "她也很高兴。", vi: "Cô ấy cũng rất vui." },
      { zh: "我也认识他。", vi: "Tôi cũng quen biết anh ấy." },
    ],
    notes: [
      "Lỗi phổ biến (bị tiếng Anh ảnh hưởng): 我是学生也 ✗ (giống 'I am a student too')",
      "Đúng: 我也是学生 ✓ — 也 đứng sau CN, trước ĐT/TT (giống tiếng Việt: 'Tôi cũng là học sinh')",
    ],
  },
  {
    id: "B2-NP4", lesson: 2,
    title: "Trợ từ 呢 — Còn… thì sao?",
    structure: "[chủ đề] + 呢？",
    explanation: "呢 cuối câu rút ngắn = hỏi lại về chủ đề đã nhắc. Dùng khi muốn hỏi 'còn X thì sao?' mà không cần lặp lại toàn bộ câu.",
    examples: [
      { zh: "我是越南人，你呢？", vi: "Tôi là người Việt Nam, còn bạn thì sao?" },
      { zh: "A：我很好。B：你呢？", vi: "A: Tôi khỏe. B: Còn bạn?" },
      { zh: "他是老师，她呢？", vi: "Anh ấy là giáo viên, còn cô ấy?" },
    ],
    notes: [
      "Khác 吗: 吗 hỏi hoàn toàn mới; 呢 hỏi lại trong ngữ cảnh đã có",
      "呢 rút ngắn câu — không cần lặp lại động từ hay vị ngữ",
    ],
  },
  {
    id: "B2-NP5", lesson: 2,
    title: "姓 — Họ",
    structure: "CN + 姓 + họ",
    explanation: "姓 dùng để nói về họ (surname). Khác với 叫 (tên đầy đủ). Hỏi họ: 你姓什么？",
    examples: [
      { zh: "我姓王。", vi: "Tôi họ Vương." },
      { zh: "你姓什么？", vi: "Bạn họ gì?" },
      { zh: "她姓李，叫李军。", vi: "Cô ấy họ Lý, tên là Lý Quân." },
    ],
    notes: [
      "姓 là động từ trong cấu trúc này, không phải danh từ",
      "Họ người Trung thường chỉ một chữ: 王, 李…",
    ],
  },
  {
    id: "B2-NP6", lesson: 2,
    title: "哪国人 — Quốc tịch",
    structure: "CN + 是 + [quốc gia] + 人",
    explanation: "Tên quốc gia + 人 = người nước đó. Hỏi quốc tịch: 你是哪国人？ (Bạn là người nước nào?)",
    examples: [
      { zh: "我是越南人。", vi: "Tôi là người Việt Nam." },
      { zh: "他是中国人。", vi: "Anh ấy là người Trung Quốc." },
      { zh: "你是哪国人？", vi: "Bạn là người nước nào?" },
    ],
    notes: [
      "哪国人 = người nước nào? (câu hỏi quốc tịch)",
      "Không dùng 们 sau [quốc gia]人: 越南人们 ✗",
    ],
  },
  {
    id: "B2-NP7", lesson: 2,
    title: "Câu S + V + O cơ bản",
    structure: "CN + ĐT + TN",
    explanation: "Cấu trúc câu cơ bản: Chủ ngữ + Động từ + Tân ngữ. Tân ngữ đứng SAU động từ, giống tiếng Việt.",
    examples: [
      { zh: "你认识他吗？", vi: "Bạn có quen biết anh ấy không?" },
      { zh: "我介绍一下儿。", vi: "Tôi giới thiệu một chút." },
      { zh: "她学汉语。", vi: "Cô ấy học tiếng Trung." },
    ],
    notes: [
      "Trật tự SVO cơ bản giống tiếng Việt — tân ngữ đứng sau động từ",
      "Thêm 吗 vào cuối để biến thành câu hỏi, không cần đảo ngữ",
    ],
  },
  {
    id: "B2-NP8", lesson: 2,
    title: "我来 + ĐT — Lời đề nghị lịch sự",
    structure: "我来 + ĐT",
    explanation: "我来 + ĐT = 'để tôi làm / tôi sẽ làm'. Thể hiện sự chủ động, lịch sự. Thường dùng trong lớp học hoặc khi giúp đỡ người khác.",
    examples: [
      { zh: "我来介绍一下。", vi: "Để tôi giới thiệu một chút." },
      { zh: "我来说。", vi: "Để tôi nói." },
      { zh: "我来看。", vi: "Để tôi xem." },
    ],
    notes: [
      "来 trong cụm này mang nghĩa 'để tôi…' — không phải nghĩa gốc 'đến'",
      "Thường kết hợp với 一下: 我来介绍一下 = để tôi giới thiệu một chút (nghe lịch sự hơn)",
    ],
  },
  {
    id: "B3-NP1", lesson: 3,
    title: "这/那 — Chỉ định từ",
    structure: "这/那 + 是 + DT",
    explanation: "这 (zhè) = này/đây, 那 (nà) = đó/kia. Dùng để chỉ định hoặc giới thiệu đối tượng.",
    examples: [
      { zh: "这是我的书。", vi: "Đây là sách của tôi." },
      { zh: "那是谁？", vi: "Kia là ai?" },
      { zh: "这是我的同屋。", vi: "Đây là bạn cùng phòng của tôi." },
    ],
    notes: [
      "这/那 trực tiếp làm chủ ngữ. Khi đứng trước DT cần thêm lượng từ: 这本书, 那个人",
      "这里/这儿 = nơi này; 那里/那儿 = nơi kia",
    ],
  },
  {
    id: "B3-NP2", lesson: 3,
    title: "的 với từ nghi vấn",
    structure: "谁的/什么 + DT",
    explanation: "Đại từ nghi vấn (谁, 什么, 哪) đứng ngay tại vị trí của đáp án — không cần đảo ngữ. 谁的 = của ai.",
    examples: [
      { zh: "这是谁的书？", vi: "Đây là sách của ai?" },
      { zh: "那是什么杂志？", vi: "Đó là tạp chí gì?" },
      { zh: "哪本是你的？", vi: "Cuốn nào là của bạn?" },
    ],
    notes: [
      "Vị trí đại từ nghi vấn = vị trí của đáp án trong câu trả lời",
      "KHÔNG thêm 吗 vào câu đã có 谁/什么/哪",
    ],
  },
  {
    id: "B3-NP3", lesson: 3,
    title: "吗 vs 谁/什么/哪 — Hai loại câu hỏi",
    structure: "吗 ↔ 谁/什么/哪 (không dùng cùng nhau)",
    explanation: "Hai loại câu hỏi khác nhau hoàn toàn: (1) Hỏi có/không → dùng 吗. (2) Hỏi thông tin cụ thể → dùng 谁/什么/哪, KHÔNG dùng 吗.",
    examples: [
      { zh: "那是词典吗？✓", vi: "Đó có phải từ điển không?" },
      { zh: "那是什么词典？✓", vi: "Đó là từ điển gì?" },
      { zh: "那是什么词典吗？✗", vi: "(Sai — không dùng 吗 cùng 什么)" },
    ],
    notes: [
      "Quy tắc: câu đã có 谁/什么/哪 → KHÔNG thêm 吗",
      "Lỗi thường gặp: 这是谁的书吗？✗ → 这是谁的书？✓",
      "Câu hỏi với 谁/什么/哪 không cần đảo ngữ — giữ nguyên trật tự câu",
    ],
  },
  {
    id: "B3-NP4", lesson: 3,
    title: "就是 — Tức là / Chính là",
    structure: "X，就是 Y",
    explanation: "就是 = 'tức là / chính là' — dùng để giải thích, định nghĩa hoặc nhấn mạnh. Mạnh hơn 是 thông thường.",
    examples: [
      { zh: "《汉日词典》，就是汉语日语词典。", vi: "Từ điển Hán-Nhật, tức là từ điển Trung-Nhật." },
      { zh: "这，就是我说的那本书。", vi: "Đây chính là cuốn sách tôi đã nói." },
      { zh: "他就是李军。", vi: "Anh ấy chính là Lý Quân." },
    ],
    notes: [
      "就是 nhấn mạnh hơn 是: 他是李军 (trung tính) vs 他就是李军 (chính là anh ấy)",
      "Thường dùng để giải thích thuật ngữ hoặc xác nhận danh tính",
    ],
  },
  {
    id: "CB-NP1", lesson: 3,
    title: "Lượng từ 本",
    structure: "Số / Đại từ chỉ định + 本 + DT",
    explanation: "本 là lượng từ dùng cho sách, vở, tạp chí. Lượng từ bắt buộc phải có giữa số từ/chỉ định từ và danh từ — không thể bỏ qua như tiếng Việt.",
    examples: [
      { zh: "一本书", vi: "một cuốn sách" },
      { zh: "这本词典是我的。", vi: "Cuốn từ điển này là của tôi." },
      { zh: "那本杂志叫什么名字？", vi: "Tờ tạp chí kia tên là gì?" },
    ],
    notes: [
      "本 chỉ dùng cho vật dạng cuốn/quyển. Lượng từ chung: 个 (người/vật chung)",
      "Không thể nói 一书 ✗ hay 这书 ✗ — lượng từ là bắt buộc",
    ],
  },
  {
    id: "CB-NP2", lesson: 3,
    title: "会 — Biết làm (qua học)",
    structure: "CN + 会/不会 + ĐT",
    explanation: "会 biểu thị khả năng có được qua học tập, luyện tập ('biết làm'). Phủ định: 不会.",
    examples: [
      { zh: "我会说汉语。", vi: "Tôi biết nói tiếng Trung." },
      { zh: "大卫不会说越南语。", vi: "David không biết nói tiếng Việt." },
      { zh: "你会说什么语言？", vi: "Bạn biết nói ngôn ngữ gì?" },
    ],
    notes: [
      "会 nhấn mạnh khả năng đạt được qua học tập / luyện tập (skill)",
      "Phủ định: 不会 + ĐT — 不会 là một khối, không tách",
    ],
  },
  {
    id: "CB-NP3", lesson: 3,
    title: "喜欢 — Thích",
    structure: "CN + 喜欢 + ĐT/DT",
    explanation: "喜欢 = thích. Theo sau có thể là động từ (thích làm gì) hoặc danh từ (thích cái gì). Không cần thêm gì giữa 喜欢 và động từ.",
    examples: [
      { zh: "我喜欢听音乐。", vi: "Tôi thích nghe nhạc." },
      { zh: "她喜欢汉语。", vi: "Cô ấy thích tiếng Trung." },
      { zh: "你喜欢看什么杂志？", vi: "Bạn thích đọc tạp chí gì?" },
    ],
    notes: [
      "喜欢 + ĐT trực tiếp — không cần thêm từ nối nào (khác tiếng Anh 'like doing')",
      "Phủ định: 不喜欢 + ĐT/DT",
    ],
  },
  {
    id: "B4-NP1", lesson: 4,
    title: "在 vs 是 — Biểu thị vị trí",
    structure: "CN + 在 + địa điểm<br>địa điểm + 是 + CN",
    explanation: "Hai cấu trúc diễn tả vị trí, không hoán đổi được: (1) '<b>X ở đâu</b>' dùng 在 — CN là vật, vị ngữ là địa điểm. (2) '<b>Ở đâu là X</b>' dùng 是 — CN là địa điểm, vị ngữ là tên nơi/vật.",
    examples: [
      { zh: "图书馆在左边。", vi: "Thư viện ở bên trái." },
      { zh: "左边是图书馆。", vi: "Bên trái là thư viện." },
      { zh: "宿舍在哪儿？", vi: "Ký túc xá ở đâu?" },
    ],
    notes: [
      "是 = 'là' (định nghĩa/phân loại); 在 = 'ở' (vị trí)",
      "Lỗi phổ biến: 图书馆是那儿 ✗ → 图书馆在那儿 ✓",
    ],
  },
  {
    id: "B4-NP2", lesson: 4,
    title: "Phương vị từ + 边",
    structure: "左/右/上/下/北 + 边",
    explanation: "Phương vị từ đầy đủ = gốc chỉ hướng + 边: 左边, 右边, 上边, 下边, 北边. Khi gắn với DT: <b>N + 的 + phương vị từ</b> = 'bên ... của N' (ngược trật tự tiếng Việt).",
    examples: [
      { zh: "图书馆在学校的左边。", vi: "Thư viện ở bên trái trường học." },
      { zh: "宿舍在图书馆的右边。", vi: "Ký túc xá ở bên phải thư viện." },
      { zh: "书在课本的上边。", vi: "Sách ở bên trên sách giáo khoa." },
    ],
    notes: [
      "Không nói chỉ '左/右/上/下' thiếu '边'",
      "Trật tự ngược tiếng Việt: 图书馆的右边 = 'bên phải của thư viện' (tiếng Việt: 'bên phải thư viện' — định ngữ đi sau)",
    ],
  },
  {
    id: "B4-NP3", lesson: 4,
    title: "哪儿 / 哪里 — Ở đâu?",
    structure: "CN + 在 + 哪儿 / 哪里？",
    explanation: "哪儿 = 哪里 — đại từ nghi vấn chỉ địa điểm 'ở đâu?'. Đặt sau 在 để hỏi vị trí. Hai từ hoàn toàn thay thế được cho nhau (哪儿 phổ biến ở phương Bắc, 哪里 phổ biến ở phương Nam/Đài Loan).",
    examples: [
      { zh: "图书馆在哪儿？", vi: "Thư viện ở đâu?" },
      { zh: "你的书在哪里？", vi: "Sách của bạn ở đâu?" },
      { zh: "宿舍在哪儿？", vi: "Ký túc xá ở đâu?" },
    ],
    notes: [
      "哪儿 và 哪里 thay thế được 100% — chọn theo thói quen",
      "Trật tự giữ nguyên: CN + 在 + 哪儿 (không đảo ngữ)",
    ],
  },
  {
    id: "B4-NP4", lesson: 4,
    title: "请问 — Xin hỏi",
    structure: "请问 + [câu hỏi]",
    explanation: "请问 = 'Xin hỏi' — mở đầu câu hỏi lịch sự khi hỏi người lạ. Đặt ở đầu câu, theo sau là câu hỏi bình thường (không thay đổi trật tự từ).",
    examples: [
      { zh: "请问，图书馆在哪儿？", vi: "Xin hỏi, thư viện ở đâu?" },
      { zh: "请问，你叫什么名字？", vi: "Xin hỏi, bạn tên là gì?" },
      { zh: "请问，这是您的书吗？", vi: "Xin hỏi, đây có phải sách của ngài không?" },
    ],
    notes: [
      "Thường có dấu phẩy sau 请问",
      "Khác 问 (hỏi, động từ bình thường): 请问 là kính ngữ mở đầu câu hỏi",
    ],
  },
  {
    id: "B4-NP5", lesson: 4,
    title: "对不起 / 没关系 — Xin lỗi & đáp lại",
    structure: "A: 对不起 → B: 没关系",
    explanation: "Cặp câu xin lỗi/đáp lại cố định: 对不起 = 'xin lỗi'; 没关系 = 'không sao' (nghĩa đen: không có quan hệ gì). Khi ai đó nói 对不起, đáp chuẩn là 没关系.",
    examples: [
      { zh: "A：对不起！ B：没关系。", vi: "A: Xin lỗi! B: Không sao." },
      { zh: "对不起，我不知道。", vi: "Xin lỗi, tôi không biết." },
      { zh: "没关系，我来介绍。", vi: "Không sao, để tôi giới thiệu." },
    ],
    notes: [
      "没关系 là cụm cố định — không dùng riêng 关系 để đáp",
      "Dùng 对不起 khi lỗi rõ ràng; đáp 没关系 để nói 'không phải lỗi gì'",
    ],
  },
  {
    id: "B4-NP6", lesson: 4,
    title: "A 的 B — đảo trật tự đảo nghĩa",
    structure: "N + 的 + phương vị từ (vị trí)<br>phương vị từ + 的 + N (sự vật)",
    explanation: "Quy tắc chung <b>A 的 B</b>: B là thành phần chính, A bổ nghĩa cho B. Đảo trật tự thì đảo nghĩa hoàn toàn:<br><br>(1) <b>N + 的 + phương vị từ</b> → phương vị từ là chính, nói về <b>vị trí</b> ('phía nào của N').<br>(2) <b>phương vị từ + 的 + N</b> → N là chính, chỉ <b>sự vật</b> nằm ở phía đó ('cái N ở phía đó').",
    examples: [
      { zh: "楼的右边是学校。", vi: "Phía bên phải của tòa nhà là trường học. (vị trí)" },
      { zh: "右边的楼是图书馆。", vi: "Tòa nhà bên phải là thư viện. (sự vật)" },
      { zh: "上边的宿舍是我的。", vi: "Ký túc xá phía trên là của tôi. (sự vật)" },
    ],
    notes: [
      "A 的 B → B là chính, A bổ nghĩa cho B",
      "楼的右边 = vị trí (nói về phía bên phải) ↔ 右边的楼 = sự vật (nói về tòa nhà)",
    ],
  },
  {
    id: "CB-NP4", lesson: 4,
    title: "Lượng từ 个",
    structure: "Số / Đại từ chỉ định + 个 + DT",
    explanation: "个 là lượng từ chung cho người và nhiều vật. Dùng khi không có lượng từ chuyên biệt. 这/那 + 个 + DT = 'cái/người này/đó'. Khác 这 + 是 + DT (câu định nghĩa).",
    examples: [
      { zh: "这个人是大卫。", vi: "Người này là David." },
      { zh: "那个学校很大。", vi: "Trường đó rất lớn." },
      { zh: "一个老师", vi: "một giáo viên" },
    ],
    notes: [
      "本 là lượng từ cho sách/vở; 个 là lượng từ chung cho người và nhiều vật khác",
      "这 + 是 + DT (định nghĩa) ≠ 这 + 个 + DT (chỉ định cụ thể)",
    ],
  },
  {
    id: "CB-NP5", lesson: 4,
    title: "知道 vs 会 — Biết thông tin / Biết kỹ năng",
    structure: "知道 + fact<br>会 + kỹ năng",
    explanation: "Hai 'biết' khác nhau: 知道 = biết thông tin/sự kiện ('biết rằng…'); 会 = biết làm kỹ năng ('biết cách…', qua học tập).",
    examples: [
      { zh: "我知道他叫大卫。", vi: "Tôi biết anh ấy tên là David. (thông tin)" },
      { zh: "我会说汉语。", vi: "Tôi biết nói tiếng Trung. (kỹ năng)" },
      { zh: "你知道图书馆在哪儿吗？", vi: "Bạn có biết thư viện ở đâu không?" },
    ],
    notes: [
      "Lỗi phổ biến: 我知道说汉语 ✗ → 我会说汉语 ✓ (nói là kỹ năng)",
      "知道 thường đi với mệnh đề (biết rằng…); 会 đi với động từ (biết làm gì)",
    ],
  },
  {
    id: "CB-NP6", lesson: 4,
    title: "Cụm ĐT làm định ngữ — Mệnh đề quan hệ 🔴",
    structure: "[Cụm ĐT] + 的 + DT",
    explanation: "Cụm động từ (có thể có CN, 在, TN) làm định ngữ cho DT — tương đương mệnh đề quan hệ ('người mà...', 'cuốn sách mà...'). Tiếng Trung đặt mệnh đề TRƯỚC DT, ngược trật tự tiếng Việt:<br><br>(1) <b>[在 + V] + 的 + DT</b> = DT (đang) làm gì: 在看书的学生 = học sinh đang đọc sách.<br>(2) <b>[CN + 在 + V] + 的 + DT</b> = DT (mà) CN đang làm: 大卫在听的音乐 = nhạc David đang nghe.<br>(3) <b>[CN + V] + 的 + DT</b> = DT (mà) CN làm: 你看的书 = cuốn sách bạn đọc.",
    examples: [
      { zh: "在看书的学生是大卫。", vi: "Học sinh (đang) đọc sách là David." },
      { zh: "大卫在听的音乐是中国音乐。", vi: "Nhạc (mà) David đang nghe là nhạc Trung Quốc." },
      { zh: "你看的书是我的。", vi: "Cuốn sách (mà) bạn đọc là của tôi." },
    ],
    notes: [
      "Trật tự ngược tiếng Việt: [mệnh đề] + 的 + DT (Việt đặt mệnh đề SAU: 'sách mà bạn đọc')",
      "Chèn 在 trước ĐT để diễn tả ý 'đang...': 在听音乐的老师 = giáo viên đang nghe nhạc",
      "Có thể thêm định ngữ trước DT chính: 在听音乐的中国老师 = giáo viên Trung Quốc đang nghe nhạc",
      "Ngữ pháp nâng cao 🔴 — cần luyện đọc hiểu nhiều",
    ],
  },
  {
    id: "B5-NP1", lesson: 5,
    title: "小 / 中 / 大 + DT — Tính từ kích cỡ làm định ngữ",
    structure: "小 / 中 / 大 + DT",
    explanation: "Tính từ chỉ kích cỡ (小/中/大) đặt TRỰC TIẾP trước danh từ — KHÔNG cần 的. Khác với khi tính từ làm vị ngữ ('教室很大' — phòng học rất lớn) thì cần 很.",
    examples: [
      { zh: "这是大教室。", vi: "Đây là phòng học lớn." },
      { zh: "我们的宿舍是小宿舍。", vi: "Ký túc xá của chúng tôi là ký túc xá nhỏ." },
      { zh: "大图书馆在哪儿？", vi: "Thư viện lớn ở đâu?" },
    ],
    notes: [
      "Định ngữ kích cỡ trực tiếp: 大教室 ✓ — không cần 的",
      "Vị ngữ kích cỡ: 教室很大 ✓ — phải có 很 (xem B1-NP5)",
      "Một số kết hợp lexicalized: 大学 (đại học), 小学 (tiểu học) — không phải 'trường lớn/nhỏ' theo nghĩa đen",
    ],
  },
  {
    id: "B5-NP2", lesson: 5,
    title: "有 / 没有 — Sở hữu / Tồn tại",
    structure: "CN + 有 + DT<br>CN + 没有 + DT",
    explanation: "有 = 'có' (sở hữu hoặc tồn tại). Phủ định ĐẶC BIỆT: dùng <b>没有</b>, KHÔNG dùng 不有 ✗. 有 là động từ duy nhất trong tiếng Trung phủ định bằng 没.",
    examples: [
      { zh: "我有书。", vi: "Tôi có sách." },
      { zh: "他没有工作。", vi: "Anh ấy không có việc làm." },
      { zh: "学校有图书馆。", vi: "Trường học có thư viện. (tồn tại)" },
    ],
    notes: [
      "Phủ định: 没有 (không phải 不有 ✗) — 有 là ngoại lệ duy nhất",
      "有 vừa nghĩa 'sở hữu' (我有...) vừa 'tồn tại' (... 有 ...)",
      "Văn nói có thể rút gọn 没有 → 没",
    ],
  },
  {
    id: "B5-NP3", lesson: 5,
    title: "...的时候 — Khi / Lúc làm gì",
    structure: "[Cụm ĐT] + 的时候",
    explanation: "Đặt [cụm động từ] trước <b>的时候</b> = 'khi/lúc làm gì'. Toàn bộ cụm này là trạng ngữ chỉ thời gian, có thể đứng đầu câu hoặc giữa CN và VN. Ngược trật tự tiếng Việt: 'khi tôi học' → '<b>我学</b>的时候' (mệnh đề ở TRƯỚC '的时候', không phải sau 'khi').",
    examples: [
      { zh: "我看书的时候，他来了。", vi: "Khi tôi đọc sách, anh ấy đến." },
      { zh: "你来的时候，我在教室。", vi: "Khi bạn đến, tôi đang ở lớp học." },
      { zh: "我听音乐的时候很高兴。", vi: "Khi tôi nghe nhạc tôi rất vui." },
    ],
    notes: [
      "的时候 LUÔN đặt ở CUỐI cụm động từ — không tách: '的' bên trong, '时候' ngay sau",
      "Trạng ngữ thời gian thường ở đầu câu, theo sau là dấu phẩy",
      "Mệnh đề con [cụm ĐT] có thể có CN (我学的时候) hoặc không (看书的时候)",
    ],
  },
  {
    id: "B5-NP4", lesson: 5,
    title: "什么时候 — Khi nào? / Lúc nào?",
    structure: "CN + 什么时候 + VN？",
    explanation: "什么时候 = 'lúc nào / khi nào' — đại từ nghi vấn hỏi về thời gian. Đặt sau CN và trước VN. Vì đã là câu hỏi (có 什么) nên KHÔNG thêm 吗.",
    examples: [
      { zh: "你什么时候有空儿？", vi: "Bạn lúc nào rảnh?" },
      { zh: "你什么时候去？", vi: "Bạn khi nào đi?" },
      { zh: "什么时候你来教室？", vi: "Khi nào bạn đến lớp học? (đặt ở đầu câu)" },
    ],
    notes: [
      "什么时候 là đại từ nghi vấn → KHÔNG thêm 吗 ở cuối câu",
      "Vị trí phổ biến: CN + 什么时候 + VN; cũng có thể đặt 什么时候 ở đầu câu",
      "Trả lời thường dùng [VP] + 的时候 (xem B5-NP3) hoặc thời gian cụ thể",
    ],
  },
  {
    id: "B5-NP5", lesson: 5,
    title: "来 / 去 — Đến / Đi",
    structure: "CN + 来 / 去 + địa điểm",
    explanation: "来 và 去 là cặp động từ chỉ hướng:<br>• <b>来</b> = 'đến' — chuyển động <b>về phía người nói</b>.<br>• <b>去</b> = 'đi' — chuyển động <b>rời khỏi người nói</b>.<br>Đặt địa điểm TRỰC TIẾP sau 来/去 — không cần thêm giới từ.",
    examples: [
      { zh: "我去图书馆。", vi: "Tôi đi thư viện." },
      { zh: "大卫来中国。", vi: "David đến Trung Quốc." },
      { zh: "你去哪儿？", vi: "Bạn đi đâu?" },
    ],
    notes: [
      "Sau 来/去 đặt địa điểm trực tiếp: 去图书馆 ✓, không nói 去在图书馆 ✗",
      "来 ↔ 去 chọn theo vị trí người nói: ở nhà bảo người khác '来' (đến đây); rời nhà bảo '去' (đi đó)",
      "Hỏi điểm đến: 来/去 + 哪儿？",
    ],
  },
  {
    id: "B6-NP1", lesson: 6,
    title: "Cách đọc giờ phút",
    structure: "N + 点 (+ M + 分)",
    explanation: "Cách đọc giờ phút trong tiếng Trung:<br>(1) <b>Giờ tròn</b>: Số giờ + 点 → 三点 (3 giờ).<br>(2) <b>Giờ + phút</b>: Số giờ + 点 + Số phút + 分 → 三点二十分 (3 giờ 20 phút).<br>(3) <b>Phút < 10</b>: chèn 零 trước số phút → 三点零五分 (3 giờ 05 phút).<br>(4) <b>30 phút</b>: dùng 半 → 三点半 (3 giờ rưỡi).<br>(5) <b>15 / 45 phút</b>: dùng 刻 → 三点一刻 (3 giờ 15), 三点三刻 (3 giờ 45).<br>(6) <b>Kém</b>: 差 + phút + 分 + giờ + 点 → 差五分三点 (3 giờ kém 5).",
    examples: [
      { zh: "我三点去图书馆。", vi: "Tôi đi thư viện lúc 3 giờ." },
      { zh: "他七点半来教室。", vi: "Anh ấy đến lớp học lúc 7 giờ rưỡi." },
      { zh: "我差五分八点来。", vi: "Tôi đến lúc 8 giờ kém 5 phút." },
    ],
    notes: [
      "Phút có 1 chữ số (1–9): bắt buộc thêm 零 trước số phút (三点零五分, không nói 三点五分 ✗)",
      "刻 = 15 phút: 一刻 = 15, 三刻 = 45 (KHÔNG có 二刻 dùng 半 thay)",
      "Hỏi giờ: dùng 什么时候 (xem B5-NP4) — cấu trúc hỏi giờ chuyên biệt sẽ học ở bài sau",
    ],
  },
  {
    id: "B6-NP2", lesson: 6,
    title: "两 vs 二 — Khi nào dùng 'hai' nào",
    structure: "两 + lượng từ<br>二 (số đếm thuần / số nhiều chữ số)",
    explanation: "Cả 二 và 两 đều nghĩa là 'hai' nhưng dùng trong ngữ cảnh khác nhau:<br>• <b>二</b>: số đếm trừu tượng (1, 2, 3...), số thứ tự, các chữ số trong số nhiều chữ số (12, 22, 200...).<br>• <b>两</b>: dùng TRƯỚC lượng từ khi nói '<b>hai cái gì đó</b>'.<br>Quy tắc: trước lượng từ → 两; còn lại → 二.",
    examples: [
      { zh: "两本书", vi: "hai cuốn sách (本 là lượng từ → dùng 两)" },
      { zh: "两个学生", vi: "hai học sinh (个 là lượng từ → dùng 两)" },
      { zh: "两点", vi: "2 giờ (点 hoạt động như lượng từ → 两点, KHÔNG 二点)" },
    ],
    notes: [
      "Số đếm thuần / số thứ tự / số nhiều chữ số: dùng 二 — 十二 (12), 二十 (20), 二百 (200)",
      "Trước lượng từ (本, 个, 点...): dùng 两 — sai khi viết 二本书 ✗ → 两本书 ✓",
      "Trước 百 (trăm): cả 二百 và 两百 đều dùng được; văn nói thường nghiêng về 两百",
    ],
  },
  {
    id: "B6-NP3", lesson: 6,
    title: "太...了 / 不太... — Quá... / Không... lắm",
    structure: "太 + TT + 了 (quá ...)<br>不太 + TT (không ... lắm)",
    explanation: "Hai cấu trúc dùng 太 để biểu thị mức độ:<br>(1) <b>太 + TT + 了</b>: nhấn mạnh 'quá...' — thường mang sắc thái phàn nàn hoặc khen mạnh. 了 là BẮT BUỘC.<br>(2) <b>不太 + TT</b>: phủ định nhẹ 'không... lắm'. KHÔNG có 了 đi kèm.",
    examples: [
      { zh: "太好了！", vi: "Quá tốt! / Tuyệt!" },
      { zh: "老师太高兴了。", vi: "Giáo viên quá vui." },
      { zh: "这本书不太好。", vi: "Cuốn sách này không tốt lắm." },
    ],
    notes: [
      "太 + TT phải có 了 ở cuối: 太好 ✗ → 太好了 ✓",
      "不太 + TT KHÔNG cần 了: 不太好了 ✗ → 不太好 ✓",
      "Khẩu ngữ: '太好了！' thường dùng thay 'tuyệt vời!' hoặc đáp lời tích cực",
    ],
  },
  {
    id: "B6-NP4", lesson: 6,
    title: "差 — Kém / Tệ (đánh giá khả năng)",
    structure: "CN + 很 + 差 / 不太 + 差",
    explanation: "差 với nghĩa 'kém, tệ' là tính từ — dùng giống các tính từ khác, cần phó từ (thường là 很) đứng trước khi làm vị ngữ. Diễn tả trình độ/khả năng kém hoặc chất lượng tồi.<br><br>Lưu ý: 差 còn có nghĩa khác là 'thiếu/kém' trong cách nói giờ (xem B6-NP1): 差五分八点 = '8 giờ kém 5'.",
    examples: [
      { zh: "我的汉语很差。", vi: "Tiếng Hán của tôi rất kém." },
      { zh: "他的工作不太差。", vi: "Công việc của anh ấy không tệ lắm." },
      { zh: "我的日语很差。", vi: "Tiếng Nhật của tôi rất kém." },
    ],
    notes: [
      "差 là tính từ: làm vị ngữ phải có phó từ (很 / 不太 / 太...了): 我差 ✗ → 我很差 ✓",
      "差 mạnh hơn 不好: 不好 = 'không tốt'; 差 = 'kém, tệ' (chất lượng/khả năng yếu)",
      "Hai nghĩa của 差: (a) tính từ 'kém' (我的汉语差) — bài này; (b) động từ 'thiếu' khi nói giờ (差五分) — xem B6-NP1",
    ],
  },
  {
    id: "B6-NP5", lesson: 6,
    title: "早上 / 上午 / 中午 / 下午 / 晚上 — Các buổi trong ngày",
    structure: "[Buổi] + (giờ cụ thể) + V",
    explanation: "Tiếng Trung chia ngày thành 5 buổi, dùng làm trạng ngữ thời gian:<br>• <b>早上</b> (zǎoshang) — sáng sớm (~5h–8h)<br>• <b>上午</b> (shàngwǔ) — buổi sáng (8h–12h, nghĩa đen: 'trên 午/ngọ')<br>• <b>中午</b> (zhōngwǔ) — giữa trưa (~11h–13h, 'chính ngọ')<br>• <b>下午</b> (xiàwǔ) — buổi chiều (12h–18h, 'dưới ngọ')<br>• <b>晚上</b> (wǎnshang) — buổi tối (18h–24h)<br>Đặt buổi TRƯỚC giờ cụ thể: 上午八点 = '8 giờ sáng', 晚上九点 = '9 giờ tối'.",
    examples: [
      { zh: "我早上六点上课。", vi: "Tôi vào lớp lúc 6 giờ sáng." },
      { zh: "他下午三点来教室。", vi: "Anh ấy đến lớp học lúc 3 giờ chiều." },
      { zh: "我们晚上八点见。", vi: "Chúng ta gặp nhau lúc 8 giờ tối." },
    ],
    notes: [
      "Trật tự: [Buổi] + [Giờ] — KHÔNG đảo ngược: 早上八点 ✓, 八点早上 ✗",
      "早上 và 上午 hơi chồng nhau (~7–8h): 早上 nhấn 'sáng sớm/khi mới dậy'; 上午 chỉ 'cả buổi sáng đến trưa'",
      "Mẹo nhớ: 午 (ngọ) = giữa trưa → 上午 'trên ngọ' (trước trưa), 下午 'dưới ngọ' (sau trưa)",
    ],
  },
  {
    id: "B6-NP6", lesson: 6,
    title: "Vị trí từ chỉ thời gian + 几点 — Mấy giờ?",
    structure: "Time + CN + V<br>CN + Time + V<br>CN + 几点 + V?",
    explanation: "Trạng ngữ thời gian (giờ, buổi, từ chỉ thời điểm) có hai vị trí hợp lệ:<br>(1) <b>Time + CN + V</b>: thời gian đặt đầu câu — nhấn mạnh thời điểm.<br>(2) <b>CN + Time + V</b>: thời gian giữa CN và VN — phổ biến hơn trong khẩu ngữ.<br>KHÔNG bao giờ đặt thời gian SAU động từ (giống tiếng Anh '*go to school 8 o'clock').<br><br>Hỏi giờ: dùng <b>几点</b> ở vị trí của thời gian: <i>你几点来？</i> = 'Bạn mấy giờ đến?'. Vì 几 là đại từ nghi vấn nên KHÔNG thêm 吗.",
    examples: [
      { zh: "我八点去图书馆。", vi: "Tôi 8 giờ đi thư viện. (CN + Time + V)" },
      { zh: "八点我去图书馆。", vi: "8 giờ tôi đi thư viện. (Time + CN + V — nhấn mạnh)" },
      { zh: "你几点上课？", vi: "Bạn mấy giờ vào lớp?" },
    ],
    notes: [
      "Cả 2 vị trí 'Time + CN + V' và 'CN + Time + V' đều đúng — KHÔNG đặt sau động từ",
      "几点 thay thế trực tiếp vị trí của giờ — giữ trật tự câu, không đảo",
      "几点 là đại từ nghi vấn → KHÔNG thêm 吗 ở cuối",
    ],
  },
  {
    id: "B6-NP7", lesson: 6,
    title: "早饭 / 午饭 / 晚饭 — Bữa ăn",
    structure: "吃 + 早饭 / 午饭 / 晚饭",
    explanation: "Tên bữa ăn ghép từ buổi + 饭 (cơm):<br>• <b>早饭</b> (zǎofàn) — bữa sáng (lit. 'cơm sáng')<br>• <b>午饭</b> (wǔfàn) — bữa trưa (lit. 'cơm trưa')<br>• <b>晚饭</b> (wǎnfàn) — bữa tối (lit. 'cơm tối')<br>Động từ chuyên dùng: <b>吃 + [bữa]</b> = ăn bữa đó. 吃饭 (chung chung) = 'ăn cơm/dùng bữa'.",
    examples: [
      { zh: "我早上七点吃早饭。", vi: "Tôi ăn sáng lúc 7 giờ sáng." },
      { zh: "他中午十二点吃午饭。", vi: "Anh ấy ăn trưa lúc 12 giờ trưa." },
      { zh: "我们晚上六点半吃晚饭。", vi: "Chúng tôi ăn tối lúc 6 giờ rưỡi tối." },
    ],
    notes: [
      "Cấu trúc cố định: buổi (早/午/晚) + 饭 → tên bữa ăn",
      "吃 + bữa ăn là cụm verb-object: '吃早饭' không tách giữa 吃 và 早饭",
      "Khi nói chung 'ăn cơm/dùng bữa', dùng 吃饭 (không cần xác định bữa nào)",
    ],
  },
  {
    id: "B6-NP8", lesson: 6,
    title: "睡觉 — Tách rời chèn 早 / 午 / 晚",
    structure: "睡 + 早 / 午 / 晚 + 觉",
    explanation: "睡觉 (shuìjiào) là <b>động từ tách rời</b> (li-he-ci) — gồm phần động từ 睡 ('ngủ') và phần danh từ 觉 ('giấc'). Khi muốn nói 'ngủ buổi nào', ta CHÈN buổi (早 / 午 / 晚) vào GIỮA hai phần — KHÔNG đặt buổi trước hoặc sau cụm 睡觉 nguyên khối.<br><br><b>Ba dạng phổ biến:</b><br>• <b>睡早觉</b> (shuì zǎo jiào) — ngủ sáng / dậy muộn<br>• <b>睡午觉</b> (shuì wǔ jiào) — ngủ trưa (rất phổ biến)<br>• <b>睡晚觉</b> (shuì wǎn jiào) — ngủ buổi tối / ngủ muộn",
    examples: [
      { zh: "我每天中午睡午觉。", vi: "Tôi mỗi ngày ngủ trưa lúc giữa trưa." },
      { zh: "他喜欢睡晚觉。", vi: "Anh ấy thích ngủ muộn." },
      { zh: "你几点睡觉？", vi: "Bạn mấy giờ đi ngủ? (dùng 睡觉 nguyên khối — không nêu buổi cụ thể)" },
    ],
    notes: [
      "Động từ tách rời: chèn 早/午/晚 vào GIỮA → 睡午觉 ✓ ; 午睡觉 ✗ ; 睡觉午 ✗",
      "Nói 'đi ngủ' chung chung (không nêu buổi): dùng nguyên khối 睡觉 — 我去睡觉 = 'tôi đi ngủ'",
      "睡午觉 (cụm verb-object cố định) ≠ 中午睡觉 (中午 làm trạng ngữ thời gian, sau đó là 睡觉)",
    ],
  },
  {
    id: "B6-NP9", lesson: 6,
    title: "上课 — Tách rời chèn N (môn học)",
    structure: "上 + N(môn học) + 课",
    explanation: "上课 (shàngkè) là <b>động từ tách rời</b> — gồm phần động từ 上 ('lên/vào') và phần danh từ 课 ('lớp học / tiết học'). Khi muốn nói 'học môn nào', ta CHÈN tên môn (汉语 / 日语 / 英语 / 数学 ...) vào GIỮA 上 và 课.<br><br><b>Hai dạng:</b><br>• <b>上课</b> — đi học / vào lớp (chung chung, không nêu môn)<br>• <b>上 + [môn] + 课</b> — học (lớp) môn đó<br>Ví dụ: 上汉语课 = học (lớp) tiếng Hán; 上日语课 = học (lớp) tiếng Nhật; 上英语课 = học (lớp) tiếng Anh.",
    examples: [
      { zh: "我每天上汉语课。", vi: "Tôi mỗi ngày học tiếng Hán." },
      { zh: "他八点上日语课。", vi: "Anh ấy 8 giờ học tiếng Nhật." },
      { zh: "你几点上课？", vi: "Bạn mấy giờ vào lớp? (dùng nguyên khối — không nêu môn)" },
    ],
    notes: [
      "Động từ tách rời: tên môn chèn vào GIỮA → 上汉语课 ✓ ; 上课汉语 ✗ ; 汉语上课 ✗",
      "Đi học chung chung dùng nguyên khối 上课 — 我去上课 = 'tôi đi học / vào lớp'",
      "Cùng họ tách rời ở Bài 6: 睡觉 (B6-NP8 — chèn buổi), 吃饭 (B6-NP7 — đổi thành 吃X饭). 下课 ít khi tách.",
    ],
  },
  {
    id: "B6-NP10", lesson: 6,
    title: "Time + 见 — Lời chào hẹn gặp",
    structure: "[Time] + 见",
    explanation: "Cấu trúc <b>[từ chỉ thời gian] + 见</b> là lời tạm biệt phổ biến, hàm ý 'gặp lại bạn vào [thời gian đó]'. Tiếng Việt tương đương: 'Hẹn gặp [lúc nào]' hoặc 'Chiều/tối/lát nữa gặp nhé'.<br><br><b>Các dạng phổ biến:</b><br>• <b>下午见</b> — chiều gặp / hẹn chiều<br>• <b>晚上见</b> — tối gặp / hẹn tối<br>• <b>一会儿见</b> — lát nữa gặp<br>• <b>一下儿见</b> — chốc nữa gặp (khẩu ngữ, đồng nghĩa với 一会儿见)<br>• <b>明天见</b> — mai gặp<br><br><b>Đặc biệt — 再见:</b> 再 ('lại, lần nữa') + 见 = 'gặp lại'. Đây là lời chia tay <i>chung chung</i>, không nêu thời gian cụ thể — tương đương 'tạm biệt' tiếng Việt.",
    examples: [
      { zh: "下午见！", vi: "Chiều gặp nhé!" },
      { zh: "一会儿见。", vi: "Lát nữa gặp." },
      { zh: "好的，再见！", vi: "Được rồi, tạm biệt! (gặp lại)" },
    ],
    notes: [
      "Trật tự cố định: thời gian ĐẶT TRƯỚC 见 — 见下午 ✗ → 下午见 ✓",
      "Dùng độc lập như câu hoàn chỉnh, không cần CN: '一会儿见！' = 'Lát nữa gặp!'",
      "再见 là dạng khái quát của cấu trúc này: 再 ('lại / lần sau') + 见 — khi không hẹn thời gian cụ thể",
      "一会儿见 vs 一下儿见: cùng nghĩa 'lát nữa gặp', khẩu ngữ. 一会儿 phổ biến hơn trong văn viết.",
    ],
  },
  {
    id: "B7-NP1", lesson: 7,
    title: "跟 / 和 + người + 说 — Nói với ai",
    structure: "跟 / 和 + [người] + 说 + [nội dung]",
    explanation: "Cấu trúc <b>'跟 / 和 + người + 说 + nội dung'</b> = 'nói với ai điều gì'. Cả 跟 (gēn) và 和 (hé) đều là giới từ 'với' trong mẫu này — có thể thay nhau:<br>• <b>跟</b> mang sắc thái khẩu ngữ hơn (rất phổ biến trong tiếng Trung phổ thông).<br>• <b>和</b> trung tính, phù hợp cả văn nói lẫn văn viết.<br>Người (đối tượng nghe) đặt giữa giới từ và 说. Nội dung muốn nói đặt sau 说.",
    examples: [
      { zh: "我跟他说明天没课。", vi: "Tôi nói với anh ấy rằng ngày mai không có tiết." },
      { zh: "她和我说了这件事。", vi: "Cô ấy nói với tôi về chuyện này." },
      { zh: "你跟老师说一下儿。", vi: "Bạn nói với thầy/cô một chút đi." },
    ],
    notes: [
      "跟 và 和 thay nhau được trong mẫu này — 跟 nghiêng về khẩu ngữ, 和 trung tính",
      "Trật tự cố định: 跟/和 + [người] + 说 — không đặt người sau 说 ('我说他' KHÔNG phải 'nói với anh ấy', mà là 'tôi nói anh ấy' = phê bình)",
      "Khác với 给 + người + 打电话 (gọi điện cho ai) — 跟/和 dùng cho hành động NÓI; 给 dùng cho hành động HƯỚNG TỚI",
    ],
  },
  {
    id: "B7-NP12", lesson: 7,
    title: "和 / 跟 + người + V — Cùng làm gì với ai",
    structure: "CN + 和 / 跟 + [người] + V (+ TN)<br>Tùy chọn: + 一起 (yīqǐ) trước V để nhấn 'cùng nhau'",
    explanation: "Cấu trúc <b>'CN + 和/跟 + [người] + V'</b> = 'làm gì cùng/với ai'. Đây là mở rộng từ B7-NP1 (跟/和 + 说 — nói với ai) sang TẤT CẢ các động từ chỉ hoạt động chung.<br><br><b>Vị trí cố định:</b> cụm <b>和/跟 + người</b> đặt SAU chủ ngữ và TRƯỚC động từ — KHÔNG đặt sau động từ.<br><br><b>Chọn 和 hay 跟:</b><br>• <b>跟</b> — khẩu ngữ, thân mật hơn (gēn — CĂN)<br>• <b>和</b> — trung tính, hợp cả văn nói và viết (hé — HÒA)<br>Hai từ có thể thay nhau trong mẫu này.<br><br><b>Tùy chọn 一起</b> (yīqǐ = 'cùng nhau'): thêm trước động từ để NHẤN MẠNH cùng làm:<br>• 我和朋友去图书馆 = Tôi đi thư viện với bạn.<br>• 我和朋友<b>一起</b>去图书馆 = Tôi đi thư viện <i>cùng</i> bạn. (nhấn mạnh hơn)<br><br><b>So sánh với B7-NP1:</b> B7-NP1 chuyên cho động từ 说 (nói chuyện, có nội dung sau). B7-NP12 cho mọi hoạt động chung (去, 吃, 看, 学习, 玩 …).",
    examples: [
      { zh: "我和朋友去图书馆。", vi: "Tôi đi thư viện với bạn." },
      { zh: "他跟我吃饭。", vi: "Anh ấy ăn cơm với tôi." },
      { zh: "她和老师学习汉语。", vi: "Cô ấy học tiếng Hán với cô giáo." },
      { zh: "我跟他一起看电影。", vi: "Tôi xem phim cùng anh ấy. (有 一起 nhấn mạnh)" },
    ],
    notes: [
      "Trật tự cố định: CN + 和/跟 + người + V — KHÔNG đặt sau động từ ('我去和朋友图书馆' ✗ / '我去图书馆和朋友' ✗)",
      "和 ≈ 跟 trong mẫu này: 跟 khẩu ngữ hơn, 和 trung tính. Cả hai thay nhau được",
      "Thiếu 和/跟 sẽ đổi nghĩa: '我朋友去图书馆' = 'BẠN CỦA TÔI đi thư viện' (không phải 'tôi và bạn cùng đi')",
      "B7-NP12 (V chung) ≠ B7-NP1 (chuyên cho 说): khi V = 说, dùng B7-NP1 để có thêm 'nội dung nói' sau",
      "一起 (yīqǐ — 'cùng nhau') là từ NHẤN MẠNH tùy chọn, KHÔNG bắt buộc — đặt giữa người và động từ",
    ],
  },
  {
    id: "B7-NP2", lesson: 7,
    title: "昨/今/明 + 早/晚 — Rút gọn cụm thời gian",
    structure: "昨/今/明 + 早/晚 (bỏ 天 và 上)",
    explanation: "Khẩu ngữ tiếng Trung thường <b>rút gọn</b> các cụm thời gian 'ngày + buổi' bằng cách bỏ 天 (ngày) và 上 (buổi):<br><br><b>Bảng đối chiếu:</b><br>• 昨天早上 → <b>昨早</b> — sáng hôm qua<br>• 昨天晚上 → <b>昨晚</b> — tối hôm qua<br>• 今天早上 → <b>今早</b> — sáng nay<br>• 今天晚上 → <b>今晚</b> — tối nay<br>• 明天早上 → <b>明早</b> — sáng mai<br>• 明天晚上 → <b>明晚</b> — tối mai<br><br>Dạng rút gọn nghe TỰ NHIÊN HƠN trong khẩu ngữ. Dạng đầy đủ vẫn đúng và hay dùng trong văn viết.",
    examples: [
      { zh: "今早我去图书馆。", vi: "Sáng nay tôi đi thư viện." },
      { zh: "昨晚我们看了一部电影。", vi: "Tối hôm qua chúng tôi xem một bộ phim." },
      { zh: "明早八点见！", vi: "Sáng mai 8 giờ gặp!" },
    ],
    notes: [
      "Chỉ áp dụng với 早 (sáng) và 晚 (tối) — KHÔNG có 昨午/今午/明午 (giữ nguyên 中午)",
      "Rút gọn = khẩu ngữ. Văn viết trang trọng vẫn dùng đầy đủ: 昨天早上, 今天晚上...",
      "Phân biệt: 早 ở đây là 'sáng' (= 早上), khác với 早 'sớm' trong 早点儿来 ('đến sớm chút')",
    ],
  },
  {
    id: "B7-NP3", lesson: 7,
    title: "辆 / 骑 / 开 — Đếm và dùng xe",
    structure: "一 + 辆 + xe<br>骑 + xe (2 bánh)<br>开 + xe (có động cơ)",
    explanation: "Ba từ then chốt khi nói về xe cộ:<br><br><b>1. 辆 (liàng)</b> — lượng từ CHUNG cho mọi loại xe:<br>• 一<b>辆</b>自行车 = một chiếc xe đạp<br>• 一<b>辆</b>摩托车 = một chiếc xe máy<br>• 一<b>辆</b>汽车 = một chiếc ô tô<br><br><b>2. 骑 (qí)</b> — 'cưỡi/đi', dùng cho xe <b>2 bánh</b> hoặc động vật:<br>• <b>骑</b>自行车 = đi xe đạp<br>• <b>骑</b>摩托车 = đi xe máy (nhấn mạnh tư thế cưỡi)<br>• <b>骑</b>马 = cưỡi ngựa<br><br><b>3. 开 (kāi)</b> — 'lái', dùng cho xe có <b>động cơ</b>:<br>• <b>开</b>汽车 = lái ô tô<br>• <b>开</b>摩托车 = lái xe máy (nhấn mạnh điều khiển)<br>• <b>开</b>飞机 = lái máy bay",
    examples: [
      { zh: "我有一辆自行车。", vi: "Tôi có một chiếc xe đạp." },
      { zh: "他骑自行车去学校。", vi: "Anh ấy đi xe đạp đến trường." },
      { zh: "我哥哥开汽车。", vi: "Anh trai tôi lái ô tô." },
    ],
    notes: [
      "辆 dùng cho mọi loại xe — không dùng 个/本: 一辆自行车 ✓, 一个自行车 ✗",
      "骑 chỉ dùng cho xe 2 bánh hoặc động vật cưỡi: 骑汽车 ✗ → 开汽车 ✓",
      "Xe máy có thể dùng cả 骑 và 开: 骑摩托车 (nhấn cưỡi/tư thế), 开摩托车 (nhấn điều khiển/lái)",
    ],
  },
  {
    id: "B7-NP4", lesson: 7,
    title: "上 / 下 / 里 / 外 / 前 / 后 — Phương vị từ (cùng cấu trúc)",
    structure: "N + 上 / 下 / 里 / 外 / 前 / 后<br>N + (的) + ...边 (dạng đầy đủ)",
    explanation: "Sáu <b>phương vị từ đơn</b> dùng cùng một cấu trúc — đặt TRỰC TIẾP sau danh từ địa điểm để chỉ vị trí:<br><br>• <b>上</b> (THƯỢNG) — trên: 桌子<b>上</b> = trên bàn<br>• <b>下</b> (HẠ) — dưới: 床<b>下</b> = dưới giường<br>• <b>里</b> (LÝ) — trong: 教室<b>里</b> = trong lớp<br>• <b>外</b> (NGOẠI) — ngoài: 学校<b>外</b> = ngoài trường<br>• <b>前</b> (TIỀN) — trước: 楼<b>前</b> = trước tòa nhà<br>• <b>后</b> (HẬU) — sau: 楼<b>后</b> = sau tòa nhà<br><br><b>Quy tắc chung:</b><br>(1) Dạng ngắn <i>N + phương vị từ</i> — KHÔNG có 的<br>(2) Dạng đầy đủ <i>N + (的) + ...边</i> (上边/下边/里边/外边/前边/后边) — có thể có 的 (xem B4-NP2)<br><br>Mẫu thường gặp: <b>CN + 在 + N + phương vị từ</b> = 'CN ở [vị trí] N'.",
    examples: [
      { zh: "钥匙在书包里。", vi: "Chìa khóa ở trong cặp." },
      { zh: "桌子上有一本书。", vi: "Trên bàn có một cuốn sách." },
      { zh: "他在教室外等我。", vi: "Anh ấy đợi tôi ở ngoài lớp học." },
      { zh: "车棚在楼后。", vi: "Chỗ để xe ở sau tòa nhà." },
    ],
    notes: [
      "Dạng ngắn (上/下/里/外/前/后) đặt TRỰC TIẾP sau N — không chèn 的: 桌子上 ✓ ; 桌子的上 ✗",
      "Dạng đầy đủ (上边/里边/前边...) mới có thể đi với 的: 桌子(的)上边 ✓",
      "Cặp đối lập đối xứng: 上 ↔ 下 (trên/dưới), 里 ↔ 外 (trong/ngoài), 前 ↔ 后 (trước/sau)",
      "Hán Việt giúp nhớ: THƯỢNG / HẠ / LÝ / NGOẠI / TIỀN / HẬU — đều thân thuộc với tiếng Việt",
    ],
  },
  {
    id: "B7-NP5", lesson: 7,
    title: "S + 在 + N + 上/下/里/外/前/后 — Ở vị trí cụ thể",
    structure: "CN + 在 + N + 上 / 下 / 里 / 外 / 前 / 后",
    explanation: "Kết hợp giữa <b>动词 在</b> (B4-NP1) và <b>phương vị từ đơn</b> (B7-NP4) để diễn tả 'CN ở [vị trí cụ thể] của N'.<br><br><b>Cấu trúc:</b> CN + 在 + N + [phương vị từ]<br>(không có động từ chính khác — đây là câu MÔ TẢ vị trí, không phải hành động)<br><br><b>Ví dụ mẫu:</b><br>• 我在教室<b>里</b>。 = Tôi ở trong lớp.<br>• 钥匙在书包<b>里</b>。 = Chìa khóa ở trong cặp.<br>• 自行车在车棚<b>外</b>。 = Xe đạp ở ngoài chỗ để xe.<br>• 商店在学校<b>前</b>。 = Cửa hàng ở trước trường.",
    examples: [
      { zh: "钥匙在书包里。", vi: "Chìa khóa ở trong cặp." },
      { zh: "我在教室外。", vi: "Tôi ở ngoài lớp học." },
      { zh: "车棚在楼后。", vi: "Chỗ để xe ở sau tòa nhà." },
    ],
    notes: [
      "Phương vị từ đặt TRỰC TIẾP sau N — không chèn 的 (giống B7-NP4): 书包里 ✓, 书包的里 ✗",
      "Câu này KHÔNG có động từ khác sau phương vị từ — nếu thêm động từ thì chuyển sang B7-NP6",
      "Hỏi vị trí: CN + 在 + 哪儿/哪里? — ví dụ '钥匙在哪儿？' (xem B4-NP3)",
    ],
  },
  {
    id: "B7-NP6", lesson: 7,
    title: "S + 在 + nơi chốn + V — Trạng ngữ địa điểm đặt TRƯỚC động từ",
    structure: "CN + 在 + [nơi chốn] + V (+ TN)",
    explanation: "Khi nói 'làm gì ở đâu', tiếng Trung BẮT BUỘC đặt cụm chỉ địa điểm <b>在 + [nơi]</b> ĐỨNG TRƯỚC động từ. Đây là điểm khác biệt lớn với tiếng Việt/tiếng Anh — không thể đặt sau động từ.<br><br><b>Quy tắc 'ở đâu trước, làm gì sau':</b><br>• <b>我在教室学习。</b> = Tôi học (ở trong) lớp. (在教室 + 学习)<br>• <b>他在家吃饭。</b> = Anh ấy ăn cơm ở nhà. (在家 + 吃饭)<br>• <b>我们在电影院看电影。</b> = Chúng tôi xem phim ở rạp chiếu phim.<br><br>Cụm 在 + [nơi] có thể kết hợp với phương vị từ (B7-NP4): <b>她在书包里找钥匙。</b> = Cô ấy tìm chìa khóa trong cặp.",
    examples: [
      { zh: "我在教室学习。", vi: "Tôi học ở (trong) lớp học." },
      { zh: "他在家吃饭。", vi: "Anh ấy ăn cơm ở nhà." },
      { zh: "我们在电影院看电影。", vi: "Chúng tôi xem phim ở rạp chiếu phim." },
      { zh: "她在图书馆看书。", vi: "Cô ấy đọc sách ở thư viện." },
    ],
    notes: [
      "Trật tự CỐ ĐỊNH: 在 + nơi đặt TRƯỚC V → 我在教室学习 ✓ ; KHÔNG đặt sau V → 我学习在教室 ✗",
      "Khác biệt với tiếng Việt: 'tôi học ở lớp' (động từ trước) ≠ 我在教室学习 (địa điểm trước)",
      "So sánh với B7-NP5: nếu CHỈ nói vị trí (không có động từ khác) → 我在教室 = 'tôi ở trong lớp'; thêm động từ → 'tôi làm gì đó ở lớp'",
      "Có thể kết hợp phương vị từ: 在 + N + 上/下/里/外/前/后 + V — ví dụ 在书包里找钥匙",
    ],
  },
  {
    id: "B7-NP7", lesson: 7,
    title: "Adj + (的) + N — Tính từ làm định ngữ",
    structure: "Adj 1 âm tiết + N (KHÔNG 的)<br>Adj 2 âm tiết + 的 + N (BẮT BUỘC 的)<br>Adv + Adj 1 âm tiết + 的 + N (BẮT BUỘC 的)",
    explanation: "Khi tính từ đứng TRƯỚC danh từ để bổ nghĩa, có hay không có 的 phụ thuộc vào ĐỘ DÀI của cụm tính từ:<br><br>(1) <b>Tính từ 1 âm tiết</b>: KHÔNG cần 的, ghép trực tiếp với danh từ.<br>• 好 + 电影 → <b>好电影</b> = phim hay<br>• 大 + 房间 → <b>大房间</b> = phòng to<br>• 小 + 孩子 → <b>小孩子</b> = đứa nhỏ<br><br>(2) <b>Tính từ 2 âm tiết</b>: BẮT BUỘC có 的 ở giữa.<br>• 有名 + <b>的</b> + 人 → <b>有名的人</b> = người nổi tiếng<br>• 高兴 + <b>的</b> + 老师 → <b>高兴的老师</b> = giáo viên vui vẻ<br>• 有用 + <b>的</b> + 书 → <b>有用的书</b> = cuốn sách có ích<br><br>(3) <b>Phó từ + tính từ 1 âm tiết</b>: BẮT BUỘC có 的. Khi thêm phó từ (很 / 太 / 真 / 非常 ...) trước tính từ ngắn, cụm trở nên 'dài' nên cần 的.<br>• 很好 + <b>的</b> + 电影 → <b>很好的电影</b> = phim rất hay<br>• 很大 + <b>的</b> + 房间 → <b>很大的房间</b> = phòng rất to<br>• 真好 + <b>的</b> + 人 → <b>真好的人</b> = người thật tốt<br><br>So sánh với câu vị ngữ (B1-NP5): khi tính từ làm VỊ NGỮ (sau danh từ + 很) thì khác — '这本书很好' = 'cuốn sách này tốt'. Mẫu này chỉ áp dụng khi tính từ đứng TRƯỚC danh từ.",
    examples: [
      { zh: "他是有名的人。", vi: "Anh ấy là người nổi tiếng. (2 âm tiết → có 的)" },
      { zh: "这是好电影。", vi: "Đây là phim hay. (1 âm tiết → không 的)" },
      { zh: "这是很好的电影。", vi: "Đây là phim rất hay. (adv 很 + 1 âm tiết → có 的)" },
      { zh: "他有一个很大的房间。", vi: "Anh ấy có một phòng rất to. (adv 很 + 1 âm tiết 大 → có 的)" },
    ],
    notes: [
      "2 âm tiết BẮT BUỘC 的: 有名的人 ✓ ; 有名人 ✗",
      "1 âm tiết THƯỜNG KHÔNG 的: 好电影 ✓ ; 好的电影 cũng được nhưng nghe trang trọng hơn",
      "Adv + 1 âm tiết BẮT BUỘC 的: 很好的电影 ✓ ; 很好电影 ✗ — thêm phó từ làm cụm 'dài' nên cần cầu nối 的",
      "Phó từ phổ biến: 很 (rất), 太 (quá), 真 (thật), 非常 (hết sức) — tất cả đều buộc 的 khi đứng trước Adj 1 âm tiết",
      "Khác với câu VN tính từ (B1-NP5): '这本书很好' (vị ngữ — sau danh từ + 很) ≠ '很好的书' (định ngữ — trước danh từ)",
      "Mẹo nhớ: 'từ dài cần cầu nối 的'; 1 âm tiết đủ ngắn để bám trực tiếp, thêm phó từ → trở nên dài",
    ],
  },
  {
    id: "B7-NP8", lesson: 7,
    title: "可是 — Liên từ 'nhưng / tuy nhiên'",
    structure: "[Mệnh đề 1] , 可是 [Mệnh đề 2]",
    explanation: "<b>可是</b> (kěshi) là liên từ chỉ sự đối lập, đặt ĐẦU mệnh đề thứ hai để nối hai ý trái ngược. Nghĩa tiếng Việt: 'nhưng, tuy nhiên'.<br><br><b>Đặc điểm:</b><br>• Đứng ở ĐẦU mệnh đề 2, sau dấu phẩy<br>• Khẩu ngữ phổ biến; <b>但是</b> (dànshì) trang trọng / văn viết hơn — hai từ tương đương về nghĩa<br>• Hai mệnh đề thường có sắc thái: ý 1 dương → ý 2 âm (hoặc ngược lại)<br><br><b>Mẫu thường gặp:</b> <i>'Muốn/thích làm gì, 可是 + không thể / không có'</i>",
    examples: [
      { zh: "我想去图书馆，可是没有时间。", vi: "Tôi muốn đi thư viện, nhưng không có thời gian." },
      { zh: "我会说汉语，可是不会说日语。", vi: "Tôi biết nói tiếng Hán, nhưng không biết nói tiếng Nhật." },
      { zh: "他是有名的人，可是不太高兴。", vi: "Anh ấy là người nổi tiếng, nhưng không vui lắm." },
    ],
    notes: [
      "可是 ĐẶT ĐẦU mệnh đề 2 — không đặt giữa hoặc cuối: '我想去，可是没有时间' ✓ ; '我想去没有时间可是' ✗",
      "Tương đương 但是 (dànshì): 可是 khẩu ngữ hơn, 但是 trang trọng hơn — nghĩa giống nhau",
      "Khác với 也 (cũng — bổ sung) và 还 (vẫn — tiếp diễn): 可是 báo hiệu sự đối lập",
    ],
  },
  {
    id: "B7-NP9", lesson: 7,
    title: "当然 — Phó từ 'tất nhiên / dĩ nhiên'",
    structure: "当然! (độc lập làm câu trả lời)<br>CN + 当然 + V (+ TN)",
    explanation: "<b>当然</b> (dāngrán) = 'tất nhiên / dĩ nhiên / đương nhiên' — Hán Việt trùng hệt tiếng Việt. Hai cách dùng:<br><br>(1) <b>Độc lập làm câu trả lời</b> — khẳng định mạnh:<br>• A: 你会说汉语吗? B: <b>当然</b>! = 'Bạn biết nói tiếng Hán không? — Tất nhiên!'<br>• A: 可以吗? B: <b>当然可以</b>! = 'Được không? — Tất nhiên được!'<br><br>(2) <b>Đứng trước động từ làm phó từ</b>:<br>• 我<b>当然</b>知道。 = Tất nhiên tôi biết.<br>• 他<b>当然</b>是有名的人。 = Tất nhiên anh ấy là người nổi tiếng.<br><br>Vị trí trong câu: SAU chủ ngữ, TRƯỚC động từ (giống các phó từ 也 / 很 / 不).",
    examples: [
      { zh: "我当然知道。", vi: "Tất nhiên tôi biết." },
      { zh: "你想去吗？当然想去！", vi: "Bạn muốn đi không? Tất nhiên muốn đi!" },
      { zh: "他当然会说汉语。", vi: "Tất nhiên anh ấy biết nói tiếng Hán." },
    ],
    notes: [
      "Hán Việt TRÙNG tiếng Việt: 当然 → ĐƯƠNG NHIÊN = 'đương nhiên / tất nhiên'",
      "Vị trí phó từ: CN + 当然 + V → 我当然知道 ✓ ; 当然我知道 nghe khẳng định mạnh hơn cũng dùng được",
      "Câu trả lời độc lập: 当然! / 当然 + V (当然会, 当然可以, 当然知道) — không cần CN",
    ],
  },
  {
    id: "B7-NP10", lesson: 7,
    title: "吧 — Trợ từ gợi ý / xác nhận (so sánh với 吗)",
    structure: "Câu đề nghị: [Câu] + 吧<br>Câu hỏi xác nhận: [Câu khẳng định] + 吧?<br>Trả lời đồng ý: 好吧 / 行吧",
    explanation: "<b>吧</b> (ba) là trợ từ cuối câu có 3 cách dùng:<br><br>(1) <b>Đề nghị / mệnh lệnh nhẹ</b> — 'đi nhé / nào / chứ':<br>• 我们去图书馆<b>吧</b>。 = Mình đi thư viện nhé.<br>• 你来<b>吧</b>。 = Bạn đến đi.<br>(Làm câu mệnh lệnh mềm hơn, bớt gay gắt.)<br><br>(2) <b>Hỏi xác nhận</b> — 'đúng không? / phải không?':<br>• 你是学生<b>吧</b>? = Bạn là học sinh, đúng không?<br>• 你会说汉语<b>吧</b>? = Bạn biết nói tiếng Hán phải không?<br>(Người nói đã <i>đoán</i> đáp án, chỉ cần xác nhận.)<br><br>(3) <b>Đồng ý / chấp nhận</b> — 'OK đi / được thôi':<br>• 好<b>吧</b>。 = Được thôi.<br>• 行<b>吧</b>，我去。 = Được, tôi đi.<br><br><b>So sánh 吧 vs 吗 (xem B1-NP3):</b><br>• <b>吗</b> — hỏi THUẦN TÚY, không có giả định: '你是学生<b>吗</b>?' = 'Bạn có phải học sinh không?' (chưa biết)<br>• <b>吧</b> — hỏi có giả định, mong xác nhận: '你是学生<b>吧</b>?' = 'Bạn là học sinh đúng không?' (nghĩ là vậy)<br><br>Cùng câu khẳng định nhưng <b>吗</b> = không biết · <b>吧</b> = đoán biết — đó là khác biệt cốt lõi.",
    examples: [
      { zh: "我们去图书馆吧。", vi: "Mình đi thư viện nhé. (đề nghị)" },
      { zh: "你是学生吧？", vi: "Bạn là học sinh đúng không? (xác nhận — đã đoán)" },
      { zh: "你是学生吗？", vi: "Bạn có phải học sinh không? (hỏi thuần — chưa biết) — so sánh!" },
      { zh: "好吧，我去。", vi: "Được thôi, tôi đi." },
    ],
    notes: [
      "KHÔNG dùng 吗 và 吧 cùng lúc: 你是学生吗吧? ✗",
      "Mệnh lệnh: 走! (Đi!) gay gắt — 走吧 (Đi đi/nhé) lịch sự, nhẹ nhàng hơn",
      "Cốt lõi 吗 vs 吧: 吗 = không có giả định ('Are you...?'); 吧 = có giả định ('You are..., right?')",
      "Trả lời '好吧' nhiều khi mang sắc thái đồng ý MIỄN CƯỠNG — không phải vui vẻ tuyệt đối",
    ],
  },
  {
    id: "B7-NP11", lesson: 7,
    title: "上班 / 下班 — Đi làm / tan làm (song song với 上课/下课)",
    structure: "上 + 班 / 下 + 班<br>(động từ tách rời — cùng kiểu 上课 / 下课)",
    explanation: "<b>上班</b> (shàngbān) và <b>下班</b> (xiàbān) là cặp động từ tách rời chỉ chu kỳ làm việc — <b>song song hoàn toàn với 上课 / 下课</b> đã học ở Bài 6.<br><br>• <b>上班</b> = đi làm / bắt đầu ca (lit. 'lên ca')<br>• <b>下班</b> = tan làm / hết ca (lit. 'xuống ca')<br><br><b>Bảng đối chiếu trường học vs công sở:</b><br>• 上课 ↔ 上班 (vào lớp ↔ vào ca)<br>• 下课 ↔ 下班 (tan học ↔ tan làm)<br><br><b>Mẫu thường gặp với giờ:</b> <i>Time + 上班 / 下班</i><br>• 我八点上班。 = Tôi 8 giờ đi làm.<br>• 我下午五点下班。 = Tôi 5 giờ chiều tan làm.<br><br><b>Lưu ý — đây là động từ tách rời</b> giống 上课: 上 + 班 là một cụm verb-object. KHÔNG chèn tên môn / công ty vào giữa — chỉ dùng nguyên khối 上班 / 下班.",
    examples: [
      { zh: "我每天八点上班。", vi: "Tôi mỗi ngày 8 giờ đi làm." },
      { zh: "他五点下班。", vi: "Anh ấy 5 giờ tan làm." },
      { zh: "你几点上班？", vi: "Bạn mấy giờ đi làm?" },
    ],
    notes: [
      "Cấu trúc song song với 上课/下课 (Bài 6): nhớ một cặp là biết cặp kia",
      "Hỏi giờ: dùng 几点 — 你几点上班？= 'Bạn mấy giờ đi làm?'",
      "KHÔNG chèn tên công ty/môn vào giữa: 上班 luôn nguyên khối (khác với 上课 có thể tách → 上汉语课, xem B6-NP9)",
      "Hán Việt rõ nghĩa: THƯỢNG BAN ↔ HẠ BAN (cùng cặp THƯỢNG / HẠ với THƯỢNG KHÓA / HẠ KHÓA)",
    ],
  },
];

const grammarQuestions = [
  // ── Fill-in-the-Blank ──
  { id: "fb-001", grammarId: "B1-NP2", type: "fill-blank", lesson: 1,
    prompt: "她___老师。", options: ["是", "很", "吗", "的"], answer: "是",
    explanation: "Vị ngữ là danh từ (老师) → bắt buộc có 是 ở giữa.",
    hanVietHint: "是 → THỊ | 老师 → LÃO SƯ" },
  { id: "fb-002", grammarId: "B1-NP3", type: "fill-blank", lesson: 1,
    prompt: "你是学生___？", options: ["吗", "呢", "的", "也"], answer: "吗",
    explanation: "吗 đặt cuối câu khẳng định để biến thành câu hỏi có/không. Trật tự từ không đổi!",
    hanVietHint: "学生 → HỌC SINH" },
  { id: "fb-003", grammarId: "B1-NP5", type: "fill-blank", lesson: 1,
    prompt: "我___高兴。", options: ["很", "是", "也", "不是"], answer: "很",
    explanation: "Tính từ làm vị ngữ phải có phó từ đứng trước (thường là 很).",
    hanVietHint: "高兴 → CAO HỨNG (vui, hứng khởi)" },
  { id: "fb-004", grammarId: "B2-NP1", type: "fill-blank", lesson: 2,
    prompt: "你___是留学生吗？", options: ["们", "的", "也", "呢"], answer: "们",
    explanation: "们 thêm vào sau đại từ để tạo số nhiều: 你们 = các bạn.",
    hanVietHint: "留学生 → LƯU HỌC SINH" },
  { id: "fb-005", grammarId: "B2-NP2", type: "fill-blank", lesson: 2,
    prompt: "这是我___书。", options: ["的", "们", "也", "吗"], answer: "的",
    explanation: "的 đứng sau ĐN để biểu thị sở hữu. 我的书 = sách của tôi.",
    hanVietHint: null },
  { id: "fb-006", grammarId: "B2-NP3", type: "fill-blank", lesson: 2,
    prompt: "我___是中国人。", options: ["也", "很", "吗", "们"], answer: "也",
    explanation: "也 (cũng) phải đặt trước động từ/tính từ (giống tiếng Việt 'cũng'). Không đặt ở cuối câu kiểu tiếng Anh 'too'.",
    hanVietHint: "也 → DÃ (cũng vậy)" },
  { id: "fb-007", grammarId: "B2-NP4", type: "fill-blank", lesson: 2,
    prompt: "我是越南人，你___？", options: ["呢", "吗", "的", "也"], answer: "呢",
    explanation: "呢 cuối câu = 'còn bạn thì sao?' — hỏi lại về chủ đề đã nhắc.",
    hanVietHint: null },
  { id: "fb-008", grammarId: "CB-NP2", type: "fill-blank", lesson: 3,
    prompt: "你___说汉语吗？", options: ["会", "是", "很", "也"], answer: "会",
    explanation: "会 biểu thị khả năng học được: 'biết làm'. 会说 = biết nói.",
    hanVietHint: "会 → HỘI | 汉语 → HÁN NGỮ" },
  { id: "fb-009", grammarId: "CB-NP3", type: "fill-blank", lesson: 3,
    prompt: "我___听音乐。", options: ["喜欢", "会", "是", "很"], answer: "喜欢",
    explanation: "喜欢 + ĐT = thích làm gì. Theo sau có thể là ĐT hoặc DT.",
    hanVietHint: "喜欢 → HỶ HOAN | 音乐 → ÂM NHẠC" },
  { id: "fb-010", grammarId: "B3-NP4", type: "fill-blank", lesson: 3,
    prompt: "《汉日词典》，___汉语、日语词典。", options: ["就是", "是", "也是", "不是"], answer: "就是",
    explanation: "就是 = 'tức là / chính là' — dùng để giải thích hoặc nhấn mạnh định nghĩa.",
    hanVietHint: "就是 → TỰU THỊ | 词典 → TỪ ĐIỂN" },
  { id: "fb-011", grammarId: "B4-NP1", type: "fill-blank", lesson: 4,
    prompt: "图书馆___左边。", options: ["在", "是", "的", "吗"], answer: "在",
    explanation: "Chủ ngữ (图书馆) + 在 + địa điểm (左边): hỏi/trả lời 'ở đâu'. Ngược lại: 左边是图书馆 (địa điểm + 是 + tên nơi chốn).",
    hanVietHint: "图书馆 → ĐỒ THƯ QUÁN (thư viện) | 在 → TẠI (ở)" },
  { id: "fb-012", grammarId: "B4-NP1", type: "fill-blank", lesson: 4,
    prompt: "左边___图书馆。", options: ["是", "在", "的", "吗"], answer: "是",
    explanation: "Địa điểm (左边) + 是 + tên nơi chốn (图书馆): câu kiểu 'bên trái là thư viện'. Chú ý hướng ngược lại so với 在.",
    hanVietHint: "左边 → TẢ BIÊN (bên trái)" },
  { id: "fb-013", grammarId: "B4-NP2", type: "fill-blank", lesson: 4,
    prompt: "宿舍在图书馆的___。", options: ["左边", "左", "边", "北边"], answer: "左边",
    explanation: "Phương vị từ đầy đủ = gốc phương hướng + 边. 左 (trái) + 边 = 左边 (bên trái). Không nói chỉ '左' mà thiếu '边'.",
    hanVietHint: "宿舍 → TÚC XÁ (ký túc xá) | 左边 → TẢ BIÊN (bên trái)" },
  { id: "fb-014", grammarId: "B4-NP3", type: "fill-blank", lesson: 4,
    prompt: "请问，图书馆在___？", options: ["哪儿", "哪", "哪国", "哪里边"], answer: "哪儿",
    explanation: "哪儿 (= 哪里) là đại từ nghi vấn chỉ địa điểm 'ở đâu?'. Đặt sau 在 để hỏi vị trí.",
    hanVietHint: "哪儿 = 哪里 → NÃ LÝ (ở đâu?)" },
  { id: "fb-015", grammarId: "B4-NP4", type: "fill-blank", lesson: 4,
    prompt: "___，宿舍在哪儿？", options: ["请问", "对不起", "谢谢", "你好"], answer: "请问",
    explanation: "请问 = 'Xin hỏi' — dùng để mở đầu câu hỏi lịch sự khi hỏi người lạ. Đặt ở đầu câu, theo sau là câu hỏi bình thường.",
    hanVietHint: "请问 → THỈNH VẤN (xin hỏi) | 宿舍 → TÚC XÁ (ký túc xá)" },
  { id: "fb-016", grammarId: "B4-NP5", type: "fill-blank", lesson: 4,
    prompt: "A: 对不起！ B: ___。", options: ["没关系", "谢谢", "不客气", "你好"], answer: "没关系",
    explanation: "没关系 = 'Không sao' — câu đáp lại cố định khi nghe 对不起. Nghĩa đen: 'không có quan hệ [gì cả]'.",
    hanVietHint: "没关系 → MỘT QUAN HỆ | 关系 → QUAN HỆ ✨ (giống hệt tiếng Việt!)" },
  { id: "fb-017", grammarId: "CB-NP4", type: "fill-blank", lesson: 4,
    prompt: "这___人是谁？", options: ["个", "本", "们", "的"], answer: "个",
    explanation: "个 là lượng từ chung cho người. 这 + 个 + DT = 'cái/người này'. Khác 这 + 是 + DT (câu định nghĩa).",
    hanVietHint: "个 → CÁ (trong 'cá nhân' 个人)" },
  { id: "fb-018", grammarId: "CB-NP5", type: "fill-blank", lesson: 4,
    prompt: "我___他叫什么名字。", options: ["知道", "会", "是", "认识"], answer: "知道",
    explanation: "知道 = biết thông tin/sự kiện. Biết tên ai → dùng 知道 (biết rằng tên là gì). Khác 会 = biết làm kỹ năng gì.",
    hanVietHint: "知道 → TRI ĐẠO | 名字 → DANH TỰ (tên)" },
  { id: "fb-019", grammarId: "CB-NP5", type: "fill-blank", lesson: 4,
    prompt: "你___说日语吗？", options: ["会", "知道", "是", "很"], answer: "会",
    explanation: "会 = biết làm kỹ năng (qua học hỏi, luyện tập). Nói tiếng Nhật là kỹ năng → dùng 会. Không thể nói '知道说日语'.",
    hanVietHint: "会 → HỘI (lĩnh hội, biết qua rèn luyện) | 日语 → NHẬT NGỮ" },
  { id: "fb-020", grammarId: "B6-NP8", type: "fill-blank", lesson: 6,
    prompt: "我中午常常___。", options: ["睡午觉", "午睡觉", "睡觉午", "午觉睡"], answer: "睡午觉",
    explanation: "睡觉 là động từ tách rời: chèn buổi (午) vào GIỮA 睡 và 觉 → 睡午觉. Không đặt 午 trước hoặc sau nguyên khối.",
    hanVietHint: "睡觉 → THỤY GIÁC | 午 → NGỌ (giữa trưa)" },
  { id: "fb-021", grammarId: "B6-NP8", type: "fill-blank", lesson: 6,
    prompt: "他喜欢睡___觉，每天起得很晚。", options: ["晚", "早", "中", "好"], answer: "晚",
    explanation: "睡晚觉 = ngủ tối/ngủ muộn → dậy muộn. Buổi (晚) chèn vào giữa 睡 và 觉.",
    hanVietHint: "晚 → VÃN (muộn/tối)" },
  { id: "fb-022", grammarId: "B6-NP9", type: "fill-blank", lesson: 6,
    prompt: "我每天___。", options: ["上汉语课", "上课汉语", "汉语上课", "课汉语上"], answer: "上汉语课",
    explanation: "上课 là động từ tách rời: tên môn (汉语) chèn vào GIỮA 上 và 课 → 上 + 汉语 + 课.",
    hanVietHint: "上课 → THƯỢNG KHÓA | 汉语 → HÁN NGỮ" },
  { id: "fb-023", grammarId: "B6-NP9", type: "fill-blank", lesson: 6,
    prompt: "你几点___？", options: ["上课", "上的课", "课上", "课的上"], answer: "上课",
    explanation: "Khi không nêu môn cụ thể, dùng nguyên khối 上课 = 'đi học / vào lớp'. Không tách 上 và 课.",
    hanVietHint: "上课 → THƯỢNG KHÓA (lên lớp)" },
  { id: "fb-024", grammarId: "B6-NP10", type: "fill-blank", lesson: 6,
    prompt: "我们晚上六点吃饭，___！", options: ["晚上见", "见晚上", "晚上吗", "再晚上"], answer: "晚上见",
    explanation: "Cấu trúc 'Time + 见': thời gian đặt TRƯỚC 见. 晚上见 = 'tối gặp / hẹn tối'.",
    hanVietHint: "晚上 → VÃN THƯỢNG (buổi tối) | 见 → KIẾN" },
  { id: "fb-025", grammarId: "B6-NP10", type: "fill-blank", lesson: 6,
    prompt: "好的，那___！(không hẹn thời gian cụ thể)", options: ["再见", "见再", "再吗", "见现在"], answer: "再见",
    explanation: "再见 = 'tạm biệt / gặp lại' — lời chia tay chung khi không nêu thời gian cụ thể. 再 (lại) + 见 (gặp).",
    hanVietHint: "再 → TÁI (lại) | 见 → KIẾN | 再见 → TÁI KIẾN" },
  { id: "fb-026", grammarId: "B7-NP1", type: "fill-blank", lesson: 7,
    prompt: "我___他说明天没课。", options: ["跟", "的", "吗", "了"], answer: "跟",
    explanation: "Cấu trúc 'tôi nói với anh ấy': 我 + 跟/和 + 他 + 说. 跟 (hoặc 和) là giới từ 'với' đặt trước người nghe.",
    hanVietHint: "跟 → CĂN (giới từ 'với') | 说 → THUYẾT (nói)" },
  { id: "fb-027", grammarId: "B7-NP2", type: "fill-blank", lesson: 7,
    prompt: "___我去图书馆。(sáng nay)", options: ["今早", "早今", "今天的早", "早今天"], answer: "今早",
    explanation: "Dạng rút gọn của 今天早上 = 今早 (bỏ 天 và 上). Trật tự ngày + buổi.",
    hanVietHint: "今天 → KIM THIÊN | 早上 → TẢO THƯỢNG (sáng) | 今早 = sáng nay" },
  { id: "fb-028", grammarId: "B7-NP3", type: "fill-blank", lesson: 7,
    prompt: "我有一___自行车。", options: ["辆", "本", "个", "只"], answer: "辆",
    explanation: "辆 là lượng từ chung cho xe cộ (xe đạp, xe máy, ô tô). Không dùng 个/本/只 cho xe.",
    hanVietHint: "辆 → LƯỢNG (lượng từ cho xe) | 自行车 → TỰ HÀNH XA" },
  { id: "fb-029", grammarId: "B7-NP3", type: "fill-blank", lesson: 7,
    prompt: "他___自行车去学校。", options: ["骑", "开", "坐", "走"], answer: "骑",
    explanation: "骑 dùng cho xe 2 bánh (xe đạp, xe máy). 开 dành cho xe có động cơ — không dùng cho xe đạp.",
    hanVietHint: "骑 → KỴ (cưỡi, đi xe 2 bánh) | 自行车 → xe đạp" },
  { id: "fb-030", grammarId: "B7-NP3", type: "fill-blank", lesson: 7,
    prompt: "我哥哥___汽车。", options: ["开", "骑", "走", "坐"], answer: "开",
    explanation: "汽车 (ô tô) là xe có động cơ → dùng 开 'lái'. 骑 chỉ dùng cho xe 2 bánh hoặc động vật.",
    hanVietHint: "开 → KHAI (lái xe có động cơ) | 汽车 → KHÍ XA (ô tô)" },
  { id: "fb-031", grammarId: "B7-NP4", type: "fill-blank", lesson: 7,
    prompt: "钥匙在书包___。", options: ["里", "外", "上", "下"], answer: "里",
    explanation: "里 = trong. 'Chìa khóa ở trong cặp' → 书包里. Phương vị từ đặt TRỰC TIẾP sau danh từ, không cần 的.",
    hanVietHint: "里 → LÝ (trong) | 书包 → THƯ BAO (cặp sách)" },
  { id: "fb-032", grammarId: "B7-NP4", type: "fill-blank", lesson: 7,
    prompt: "他在教室___等我。", options: ["外", "里", "上", "下"], answer: "外",
    explanation: "外 = ngoài. 'Đợi tôi ở ngoài lớp học' → 教室外. Cặp đối lập 里 ↔ 外.",
    hanVietHint: "外 → NGOẠI (ngoài) | 教室 → GIÁO THẤT (lớp học)" },
  { id: "fb-033", grammarId: "B7-NP4", type: "fill-blank", lesson: 7,
    prompt: "车棚___有很多自行车。", options: ["里", "外", "上", "下"], answer: "里",
    explanation: "里 = trong. 'Trong chỗ để xe có nhiều xe đạp' → 车棚里. Có thể đứng đầu câu làm trạng ngữ thời gian/địa điểm.",
    hanVietHint: "车棚 → XA BỒNG (chỗ để xe) | 里 → LÝ (trong)" },
  { id: "fb-034", grammarId: "B7-NP4", type: "fill-blank", lesson: 7,
    prompt: "桌子___有一本书。", options: ["上", "下", "里", "外"], answer: "上",
    explanation: "上 = trên. 'Trên bàn có một cuốn sách' → 桌子上. Phương vị từ đặt trực tiếp sau danh từ.",
    hanVietHint: "桌子 → bàn | 上 → THƯỢNG (trên)" },
  { id: "fb-035", grammarId: "B7-NP4", type: "fill-blank", lesson: 7,
    prompt: "车棚在楼___。", options: ["后", "前", "上", "下"], answer: "后",
    explanation: "后 = sau. 'Chỗ để xe ở sau tòa nhà' → 楼后. Cặp đối lập 前 ↔ 后.",
    hanVietHint: "楼 → LÂU (lầu/tòa nhà) | 后 → HẬU (sau)" },
  { id: "fb-036", grammarId: "B7-NP4", type: "fill-blank", lesson: 7,
    prompt: "学校___有一家商店。", options: ["前", "后", "里", "外"], answer: "前",
    explanation: "前 = trước. 'Trước trường có một cửa hàng' → 学校前.",
    hanVietHint: "学校 → HỌC HIỆU (trường) | 前 → TIỀN (trước)" },
  { id: "fb-037", grammarId: "B7-NP5", type: "fill-blank", lesson: 7,
    prompt: "钥匙___书包里。", options: ["在", "是", "有", "的"], answer: "在",
    explanation: "CN + 在 + N + phương vị từ. 'Chìa khóa ở trong cặp' — vị trí mô tả dùng 在, không dùng 是.",
    hanVietHint: "在 → TẠI (ở/đang) | 里 → LÝ (trong)" },
  { id: "fb-038", grammarId: "B7-NP5", type: "fill-blank", lesson: 7,
    prompt: "他在教室___。(không có động từ khác)", options: ["里", "学习", "了", "吗"], answer: "里",
    explanation: "Câu mô tả vị trí: CN + 在 + N + phương vị từ → 他在教室里 = 'anh ấy ở trong lớp'. Không cần động từ khác.",
    hanVietHint: "在 → TẠI | 里 → LÝ (trong)" },
  { id: "fb-039", grammarId: "B7-NP6", type: "fill-blank", lesson: 7,
    prompt: "我___教室学习。", options: ["在", "是", "去", "也"], answer: "在",
    explanation: "在 + nơi chốn + V: cụm địa điểm 'ở đâu' (在教室) đặt TRƯỚC động từ (学习). 'Tôi học ở trong lớp'.",
    hanVietHint: "在 → TẠI (ở) | 学习 → HỌC TẬP" },
  { id: "fb-040", grammarId: "B7-NP6", type: "fill-blank", lesson: 7,
    prompt: "我们___电影院看电影。", options: ["在", "是", "去", "和"], answer: "在",
    explanation: "在 + 电影院 (rạp chiếu phim) đặt trước động từ 看. 'Chúng tôi xem phim ở rạp chiếu phim'.",
    hanVietHint: "在 → TẠI | 电影院 → ĐIỆN ẢNH VIỆN (rạp phim)" },
  { id: "fb-041", grammarId: "B7-NP7", type: "fill-blank", lesson: 7,
    prompt: "他是有名___人。", options: ["的", "很", "也", "了"], answer: "的",
    explanation: "有名 là tính từ 2 âm tiết → BẮT BUỘC có 的 trước danh từ. 有名的人 = 'người nổi tiếng'.",
    hanVietHint: "有名 → HỮU DANH (nổi tiếng) | 的 → trợ từ nối định ngữ" },
  { id: "fb-042", grammarId: "B7-NP7", type: "fill-blank", lesson: 7,
    prompt: "这是一___电影。(cần một lượng từ)", options: ["部", "的", "本", "辆"], answer: "部",
    explanation: "Tính từ 1 âm tiết KHÔNG cần 的: 好电影 ✓. Câu này hỏi LƯỢNG TỪ cho 电影 = 部. Lượng từ 部 dùng cho phim, sách dài...",
    hanVietHint: "部 → BỘ (lượng từ cho phim/bộ phim)" },
  { id: "fb-043", grammarId: "B7-NP7", type: "fill-blank", lesson: 7,
    prompt: "这是好___。(1 âm tiết, không 的)", options: ["电影", "的电影", "电影的", "了电影"], answer: "电影",
    explanation: "好 là tính từ 1 âm tiết → KHÔNG cần 的: 好电影 ✓. 'Đây là phim hay'.",
    hanVietHint: "好 → HẢO (hay/tốt) | 电影 → ĐIỆN ẢNH" },
  { id: "fb-044", grammarId: "B7-NP7", type: "fill-blank", lesson: 7,
    prompt: "这是很好___电影。", options: ["的", "了", "也", "吗"], answer: "的",
    explanation: "Phó từ 很 + tính từ 1 âm tiết (好) → cụm 'rất hay' trở nên dài, BẮT BUỘC có 的: 很好的电影 = 'phim rất hay'.",
    hanVietHint: "很 → tăng cường mức độ | 好 → HẢO | 的 → bắt buộc khi có phó từ trước Adj 1 âm tiết" },
  { id: "fb-045", grammarId: "B7-NP7", type: "fill-blank", lesson: 7,
    prompt: "他有一个___房间。(rất to)", options: ["很大的", "很大", "大的", "大"], answer: "很大的",
    explanation: "'Phòng rất to' = 很 + 大 + 的 + 房间. Có phó từ 很 trước tính từ 1 âm tiết 大 → cần 的.",
    hanVietHint: "很 → rất | 大 → ĐẠI (to/lớn) | 房间 → PHÒNG GIAN" },
  { id: "fb-046", grammarId: "B7-NP8", type: "fill-blank", lesson: 7,
    prompt: "我想去图书馆，___没有时间。", options: ["可是", "当然", "也", "在"], answer: "可是",
    explanation: "可是 = 'nhưng' — đặt đầu mệnh đề 2 để báo hiệu ý đối lập (muốn đi nhưng không có thời gian).",
    hanVietHint: "可是 → KHẢ THỊ (nhưng/tuy nhiên) — liên từ đối lập" },
  { id: "fb-047", grammarId: "B7-NP8", type: "fill-blank", lesson: 7,
    prompt: "我会说汉语，___不会说日语。", options: ["可是", "也", "当然", "在"], answer: "可是",
    explanation: "Ý 1 (biết tiếng Hán) đối lập ý 2 (không biết tiếng Nhật) → dùng 可是 để nối.",
    hanVietHint: "可是 → nhưng | 不会 → không biết (làm gì)" },
  { id: "fb-048", grammarId: "B7-NP9", type: "fill-blank", lesson: 7,
    prompt: "你会说汉语吗？___！", options: ["当然", "可是", "也", "不"], answer: "当然",
    explanation: "当然! = 'Tất nhiên!' — câu trả lời khẳng định mạnh, đứng độc lập.",
    hanVietHint: "当然 → ĐƯƠNG NHIÊN (tất nhiên — HV trùng tiếng Việt)" },
  { id: "fb-049", grammarId: "B7-NP9", type: "fill-blank", lesson: 7,
    prompt: "我___知道这件事。", options: ["当然", "可是", "在", "和"], answer: "当然",
    explanation: "当然 đứng SAU CN, TRƯỚC động từ làm phó từ: 我 + 当然 + 知道 = 'tất nhiên tôi biết'.",
    hanVietHint: "当然 → ĐƯƠNG NHIÊN | 知道 → TRI ĐẠO (biết)" },
  { id: "fb-050", grammarId: "B7-NP10", type: "fill-blank", lesson: 7,
    prompt: "我们去图书馆___！(rủ đi)", options: ["吧", "吗", "也", "不"], answer: "吧",
    explanation: "吧 dùng để đề nghị / rủ rê — 'đi nhé / chứ'. 吗 chỉ để hỏi có/không, không dùng làm lời rủ.",
    hanVietHint: "吧 → BA — trợ từ gợi ý/đề nghị | 吗 → MA — trợ từ hỏi có/không" },
  { id: "fb-051", grammarId: "B7-NP10", type: "fill-blank", lesson: 7,
    prompt: "你是老师___？ (mình đoán đúng không?)", options: ["吧", "吗", "了", "也"], answer: "吧",
    explanation: "吧 ở cuối câu hỏi mang nghĩa 'phải không / đúng không' — người nói đã đoán biết, chỉ xin xác nhận.",
    hanVietHint: "吧 — hỏi xác nhận | so sánh: 你是老师吗? = hỏi thuần (chưa biết)" },
  { id: "fb-052", grammarId: "B7-NP10", type: "fill-blank", lesson: 7,
    prompt: "你是中国人___？ (mình thật sự không biết)", options: ["吗", "吧", "也", "在"], answer: "吗",
    explanation: "Khi người nói THẬT SỰ chưa biết câu trả lời → dùng 吗 (hỏi thuần). Nếu đã đoán biết và xin xác nhận thì dùng 吧.",
    hanVietHint: "吗 — hỏi thuần có/không (không có giả định) | 吧 — hỏi xác nhận (có giả định)" },
  { id: "fb-053", grammarId: "B7-NP11", type: "fill-blank", lesson: 7,
    prompt: "我每天八点___。(đi làm)", options: ["上班", "下班", "上课", "下课"], answer: "上班",
    explanation: "上班 = 'đi làm / vào ca'. 上课 = 'vào lớp' (đi học). Trong ngữ cảnh đi làm hằng ngày → 上班.",
    hanVietHint: "上班 → THƯỢNG BAN (đi làm) | 上课 → THƯỢNG KHÓA (vào lớp)" },
  { id: "fb-054", grammarId: "B7-NP11", type: "fill-blank", lesson: 7,
    prompt: "他下午五点___。(tan làm)", options: ["下班", "上班", "下课", "上课"], answer: "下班",
    explanation: "下班 = 'tan làm / xuống ca'. Cặp đối lập với 上班 (đi làm).",
    hanVietHint: "下班 → HẠ BAN (tan làm) — song song với 下课 (tan học)" },
  { id: "fb-055", grammarId: "B7-NP12", type: "fill-blank", lesson: 7,
    prompt: "我___朋友去图书馆。(cùng với)", options: ["和", "在", "也", "了"], answer: "和",
    explanation: "和 + người + V = 'cùng [người] làm gì'. '我 + 和 + 朋友 + 去 + 图书馆' = 'Tôi đi thư viện với bạn'. Có thể thay 和 bằng 跟 (khẩu ngữ hơn).",
    hanVietHint: "和 → HÒA ('với/và') | 跟 → CĂN — cả hai dùng được" },
  { id: "fb-056", grammarId: "B7-NP12", type: "fill-blank", lesson: 7,
    prompt: "她___我学习汉语。", options: ["跟", "在", "可是", "吧"], answer: "跟",
    explanation: "跟 (hoặc 和) + người + V: 'Cô ấy học tiếng Hán với tôi' → 她 + 跟 + 我 + 学习 + 汉语.",
    hanVietHint: "跟 → CĂN (giới từ 'với') | 学习 → HỌC TẬP" },

  // ── Sentence Builder ──
  { id: "sb-001", grammarId: "B1-NP2", type: "sentence-builder", lesson: 1,
    fragments: ["她", "是", "老师"], answer: ["她", "是", "老师"],
    explanation: "CN + 是 + DT: Chủ ngữ + là + danh từ vị ngữ.",
    hanVietHint: "老师 → LÃO SƯ" },
  { id: "sb-002", grammarId: "B1-NP2", type: "sentence-builder", lesson: 1,
    fragments: ["留学生", "你", "不是"], answer: ["你", "不是", "留学生"],
    explanation: "Phủ định: CN + 不是 + DT. 不是 là một khối.",
    hanVietHint: "留学生 → LƯU HỌC SINH" },
  { id: "sb-003", grammarId: "B1-NP5", type: "sentence-builder", lesson: 1,
    fragments: ["高兴", "我", "很"], answer: ["我", "很", "高兴"],
    explanation: "CN + 很 + TT: tính từ làm VN phải có 很 đứng trước.",
    hanVietHint: "高兴 → CAO HỨNG" },
  { id: "sb-004", grammarId: "B2-NP3", type: "sentence-builder", lesson: 2,
    fragments: ["中国人", "我", "是", "也"], answer: ["我", "也", "是", "中国人"],
    explanation: "也 phải đặt sau CN và TRƯỚC 是/ĐT/TT — không được đặt cuối câu.",
    hanVietHint: "中国 → TRUNG QUỐC" },
  { id: "sb-005", grammarId: "B2-NP7", type: "sentence-builder", lesson: 2,
    fragments: ["他", "你", "吗", "认识"], answer: ["你", "认识", "他", "吗"],
    explanation: "S + V + O + 吗: câu hỏi cơ bản. Thêm 吗 vào cuối, trật tự từ không đổi.",
    hanVietHint: "认识 → NHẬN THỨC" },
  { id: "sb-006", grammarId: "CB-NP2", type: "sentence-builder", lesson: 3,
    fragments: ["越南语", "大卫", "说", "不会"], answer: ["大卫", "不会", "说", "越南语"],
    explanation: "CN + 不会 + ĐT: phủ định khả năng. 不会 là một khối.",
    hanVietHint: "越南 → VIỆT NAM | 说 → THUYẾT" },
  { id: "sb-007", grammarId: "CB-NP1", type: "sentence-builder", lesson: 3,
    fragments: ["书", "这", "本", "是", "我的"], answer: ["这", "本", "书", "是", "我的"],
    explanation: "这/那 + 本 + DT: 本 là lượng từ cho sách, đứng giữa chỉ định từ và danh từ.",
    hanVietHint: "本 → BẢN (cuốn/quyển)" },
  { id: "sb-008", grammarId: "B4-NP1", type: "sentence-builder", lesson: 4,
    fragments: ["图书馆", "在", "左边"], answer: ["图书馆", "在", "左边"],
    explanation: "CN + 在 + địa điểm: 图书馆 (CN) + 在 + 左边 (địa điểm). Trật tự giống tiếng Việt: 'Thư viện ở bên trái'.",
    hanVietHint: "图书馆 → ĐỒ THƯ QUÁN | 左边 → TẢ BIÊN" },
  { id: "sb-009", grammarId: "B4-NP2", type: "sentence-builder", lesson: 4,
    fragments: ["朋友", "在", "我的", "左边"], answer: ["朋友", "在", "我的", "左边"],
    explanation: "CN + 在 + N的 + phương vị từ: 'Bạn ở bên trái tôi'. Chú ý N的 + phương vị từ = 'bên trái của N' (trật tự ngược tiếng Việt: 'bên trái tôi' vs '我的左边').",
    hanVietHint: "朋友 → BẰNG HỮU ✨ | 左边 → TẢ BIÊN (bên trái)" },
  { id: "sb-010", grammarId: "B4-NP3", type: "sentence-builder", lesson: 4,
    fragments: ["请问", "图书馆", "在", "哪儿"], answer: ["请问", "图书馆", "在", "哪儿"],
    explanation: "请问 đầu câu + câu hỏi bình thường. 图书馆在哪儿？ = thư viện ở đâu? Không đảo trật tự từ.",
    hanVietHint: "请问 → THỈNH VẤN | 哪儿 = 哪里" },
  { id: "sb-011", grammarId: "CB-NP4", type: "sentence-builder", lesson: 4,
    fragments: ["那", "个", "人", "是", "大卫"], answer: ["那", "个", "人", "是", "大卫"],
    explanation: "那 + 个 + DT + 是 + tên: 'Người đó là David'. 那个人 = người đó (那 + lượng từ 个 + DT).",
    hanVietHint: "个 → CÁ (cá nhân)" },
  { id: "sb-012", grammarId: "B6-NP8", type: "sentence-builder", lesson: 6,
    fragments: ["他", "睡", "觉", "晚"], answer: ["他", "睡", "晚", "觉"],
    explanation: "睡觉 là động từ tách rời: 睡 + 晚 + 觉. Buổi (晚) phải chèn vào GIỮA 睡 và 觉, không đặt sau 觉.",
    hanVietHint: "晚 → VÃN (muộn/tối) | 睡觉 → THỤY GIÁC" },
  { id: "sb-013", grammarId: "B6-NP8", type: "sentence-builder", lesson: 6,
    fragments: ["我", "睡", "午", "中午", "觉"], answer: ["我", "中午", "睡", "午", "觉"],
    explanation: "中午 (trạng ngữ thời gian) đứng trước cụm động từ. 睡午觉 giữ thứ tự 睡 + 午 + 觉 — buổi 午 chèn giữa.",
    hanVietHint: "中午 → TRUNG NGỌ (giữa trưa)" },
  { id: "sb-014", grammarId: "B6-NP9", type: "sentence-builder", lesson: 6,
    fragments: ["上", "课", "他", "日语"], answer: ["他", "上", "日语", "课"],
    explanation: "上课 tách rời: 上 + 日语 + 课. Tên môn (日语) chèn vào GIỮA 上 và 课 — không đặt sau 课.",
    hanVietHint: "日语 → NHẬT NGỮ | 上课 → THƯỢNG KHÓA" },
  { id: "sb-015", grammarId: "B6-NP10", type: "sentence-builder", lesson: 6,
    fragments: ["见", "一会儿"], answer: ["一会儿", "见"],
    explanation: "Time + 见: 一会儿 (lát nữa) đặt TRƯỚC 见 → 一会儿见 = 'lát nữa gặp'.",
    hanVietHint: "一会儿 → NHẤT HỘI (một lát) | 见 → KIẾN" },
  { id: "sb-016", grammarId: "B7-NP1", type: "sentence-builder", lesson: 7,
    fragments: ["他", "说", "跟", "我", "明天没课"], answer: ["他", "跟", "我", "说", "明天没课"],
    explanation: "跟/和 + người + 说 + nội dung: '他 + 跟 + 我 + 说 + 明天没课' = 'Anh ấy nói với tôi rằng mai không có tiết'.",
    hanVietHint: "跟 → CĂN | 说 → THUYẾT | 课 → KHÓA" },
  { id: "sb-017", grammarId: "B7-NP2", type: "sentence-builder", lesson: 7,
    fragments: ["来", "明早", "他"], answer: ["他", "明早", "来"],
    explanation: "Trạng ngữ thời gian (明早 = sáng mai, dạng rút gọn của 明天早上) đặt sau CN, trước động từ.",
    hanVietHint: "明早 = 明天早上 (sáng mai) | 来 → LAI (đến)" },
  { id: "sb-018", grammarId: "B7-NP3", type: "sentence-builder", lesson: 7,
    fragments: ["一", "我", "辆", "自行车", "有"], answer: ["我", "有", "一", "辆", "自行车"],
    explanation: "CN + 有 + số + 辆 + xe: 'Tôi có một chiếc xe đạp'. 辆 là lượng từ chèn giữa số và danh từ xe.",
    hanVietHint: "辆 → LƯỢNG | 自行车 → TỰ HÀNH XA (xe đạp)" },
  { id: "sb-019", grammarId: "B7-NP4", type: "sentence-builder", lesson: 7,
    fragments: ["里", "在", "钥匙", "书包"], answer: ["钥匙", "在", "书包", "里"],
    explanation: "CN + 在 + N + 里: 'Chìa khóa ở trong cặp'. 里 đặt trực tiếp sau danh từ địa điểm — không có 的.",
    hanVietHint: "里 → LÝ (trong) | 书包 → THƯ BAO | 钥匙 → THƯỢC THI (chìa khóa)" },
  { id: "sb-020", grammarId: "B7-NP5", type: "sentence-builder", lesson: 7,
    fragments: ["在", "车棚", "外", "自行车"], answer: ["自行车", "在", "车棚", "外"],
    explanation: "CN + 在 + N + phương vị từ: '自行车 + 在 + 车棚 + 外' = 'xe đạp ở ngoài chỗ để xe'.",
    hanVietHint: "在 → TẠI | 外 → NGOẠI (ngoài) | 自行车 → TỰ HÀNH XA" },
  { id: "sb-021", grammarId: "B7-NP6", type: "sentence-builder", lesson: 7,
    fragments: ["看书", "图书馆", "她", "在"], answer: ["她", "在", "图书馆", "看书"],
    explanation: "S + 在 + nơi chốn + V: '她 + 在 + 图书馆 + 看书' = 'Cô ấy đọc sách ở thư viện'. 'Ở đâu' (在图书馆) đặt TRƯỚC động từ (看书).",
    hanVietHint: "在 → TẠI (ở) | 图书馆 → ĐỒ THƯ QUÁN | 看书 → KHÁN THƯ (đọc sách)" },
  { id: "sb-022", grammarId: "B7-NP7", type: "sentence-builder", lesson: 7,
    fragments: ["有名", "他", "人", "的", "是"], answer: ["他", "是", "有名", "的", "人"],
    explanation: "Tính từ 2 âm tiết (有名) + 的 + N (人) làm định ngữ. 'Anh ấy LÀ NGƯỜI nổi tiếng'.",
    hanVietHint: "有名 → HỮU DANH (nổi tiếng) | 的 → trợ từ định ngữ" },
  { id: "sb-023", grammarId: "B7-NP8", type: "sentence-builder", lesson: 7,
    fragments: ["可是", "没有时间", "我", "想去图书馆"], answer: ["我", "想去图书馆", "可是", "没有时间"],
    explanation: "[Mệnh đề 1] + , + 可是 + [Mệnh đề 2]: '我想去图书馆，可是没有时间' = 'Tôi muốn đi thư viện, nhưng không có thời gian'.",
    hanVietHint: "可是 → KHẢ THỊ (nhưng) — đặt đầu mệnh đề 2" },
  { id: "sb-024", grammarId: "B7-NP9", type: "sentence-builder", lesson: 7,
    fragments: ["知道", "我", "当然"], answer: ["我", "当然", "知道"],
    explanation: "当然 làm phó từ đứng SAU chủ ngữ, TRƯỚC động từ: '我 + 当然 + 知道' = 'tất nhiên tôi biết'.",
    hanVietHint: "当然 → ĐƯƠNG NHIÊN | 知道 → TRI ĐẠO" },
  { id: "sb-025", grammarId: "B7-NP10", type: "sentence-builder", lesson: 7,
    fragments: ["吧", "我们", "图书馆", "去"], answer: ["我们", "去", "图书馆", "吧"],
    explanation: "Đề nghị / rủ rê: [Câu] + 吧 cuối câu. '我们去图书馆吧' = 'Mình đi thư viện nhé'.",
    hanVietHint: "吧 → trợ từ gợi ý — đặt cuối câu" },
  { id: "sb-026", grammarId: "B7-NP11", type: "sentence-builder", lesson: 7,
    fragments: ["上班", "八点", "我", "每天"], answer: ["我", "每天", "八点", "上班"],
    explanation: "CN + Time + V: 我 + 每天 + 八点 + 上班 = 'Tôi mỗi ngày 8 giờ đi làm'. Giờ đứng trước động từ tách rời.",
    hanVietHint: "上班 → THƯỢNG BAN | 每天 → MỖI THIÊN (mỗi ngày)" },
  { id: "sb-027", grammarId: "B7-NP12", type: "sentence-builder", lesson: 7,
    fragments: ["和", "我", "看电影", "朋友"], answer: ["我", "和", "朋友", "看电影"],
    explanation: "CN + 和 + người + V: '我 + 和 + 朋友 + 看电影' = 'Tôi xem phim với bạn'. Cụm 和+người đặt giữa CN và động từ.",
    hanVietHint: "和 → HÒA (với/và) | 看电影 → KHÁN ĐIỆN ẢNH (xem phim)" },

  // ── Error Correction ──
  { id: "ec-001", grammarId: "B1-NP2", type: "error-correction", lesson: 1,
    tokens: ["她", "是", "很", "高兴", "。"], errorIndex: 1,
    correction: ["她", "很", "高兴", "。"],
    explanation: "是 KHÔNG dùng trước tính từ! Tiếng Trung nói '她很高兴', KHÔNG phải '她是很高兴'.",
    hanVietHint: "高兴 → CAO HỨNG" },
  { id: "ec-002", grammarId: "B2-NP1", type: "error-correction", lesson: 2,
    tokens: ["美国人们", "来", "。"], errorIndex: 0,
    correction: ["美国人", "来", "。"],
    explanation: "们 KHÔNG dùng sau từ chỉ quốc tịch. Chỉ dùng 们 với đại từ (我们) hoặc DT chỉ người cụ thể (老师们).",
    hanVietHint: null },
  { id: "ec-003", grammarId: "B2-NP3", type: "error-correction", lesson: 2,
    tokens: ["我", "是", "中国人", "也", "。"], errorIndex: 3,
    correction: ["我", "也", "是", "中国人", "。"],
    explanation: "也 phải đứng TRƯỚC động từ/tính từ, không phải cuối câu.",
    hanVietHint: "也 → DÃ" },
  { id: "ec-004", grammarId: "B3-NP3", type: "error-correction", lesson: 3,
    tokens: ["那", "是", "谁", "的", "书", "吗", "？"], errorIndex: 5,
    correction: ["那", "是", "谁", "的", "书", "？"],
    explanation: "吗 KHÔNG dùng cùng với đại từ nghi vấn (谁, 什么, 哪). Khi đã có 谁/什么/哪, câu đã là câu hỏi.",
    hanVietHint: "谁 → THÙY (ai)" },
  { id: "ec-005", grammarId: "B1-NP5", type: "error-correction", lesson: 1,
    tokens: ["她", "高兴", "。"], errorIndex: 1,
    correction: ["她", "很", "高兴", "。"],
    explanation: "Tính từ làm VN phải có phó từ đứng trước (thường dùng 很). Nói '她很高兴' mới tự nhiên.",
    hanVietHint: "高兴 → CAO HỨNG" },
  { id: "ec-006", grammarId: "B4-NP1", type: "error-correction", lesson: 4,
    tokens: ["图书馆", "是", "那儿", "。"], errorIndex: 1,
    correction: ["图书馆", "在", "那儿", "。"],
    explanation: "Khi chủ ngữ là một địa điểm/vật và ta nói nó 'ở đâu' → dùng 在 chứ không phải 是. 是 dùng khi địa điểm làm CHỦ NGỮ: '那儿是图书馆'.",
    hanVietHint: "在 → TẠI (ở) | 是 → THỊ (là)" },
  { id: "ec-007", grammarId: "CB-NP5", type: "error-correction", lesson: 4,
    tokens: ["我", "知道", "说", "汉语", "。"], errorIndex: 1,
    correction: ["我", "会", "说", "汉语", "。"],
    explanation: "Nói tiếng Trung là một KỸ NĂNG học được → dùng 会, không phải 知道. 知道 = biết thông tin. 会 = biết làm. '我知道说汉语' không đúng ngữ pháp.",
    hanVietHint: "会 → HỘI | 汉语 → HÁN NGỮ" },
  { id: "ec-008", grammarId: "B6-NP8", type: "error-correction", lesson: 6,
    tokens: ["他", "睡觉", "晚", "。"], errorIndex: 2,
    correction: ["他", "睡", "晚", "觉", "。"],
    explanation: "睡觉 là động từ tách rời. Buổi (晚) phải CHÈN vào giữa 睡 và 觉 — không đặt sau cụm 睡觉 nguyên khối. Đúng: 睡晚觉.",
    hanVietHint: "睡觉 → THỤY GIÁC (động từ tách rời)" },
  { id: "ec-009", grammarId: "B6-NP9", type: "error-correction", lesson: 6,
    tokens: ["我", "上课", "汉语", "。"], errorIndex: 2,
    correction: ["我", "上", "汉语", "课", "。"],
    explanation: "上课 là động từ tách rời. Tên môn (汉语) phải CHÈN vào giữa 上 và 课 — không đặt sau cụm 上课 nguyên khối. Đúng: 上汉语课.",
    hanVietHint: "上课 → THƯỢNG KHÓA (động từ tách rời) | 汉语 → HÁN NGỮ" },
  { id: "ec-010", grammarId: "B6-NP10", type: "error-correction", lesson: 6,
    tokens: ["见", "下午", "！"], errorIndex: 0,
    correction: ["下午", "见", "！"],
    explanation: "Sai trật tự — thời gian phải đặt TRƯỚC 见 trong cấu trúc 'Time + 见'. Đúng: 下午见 = 'chiều gặp'.",
    hanVietHint: "下午 → HẠ NGỌ (chiều) | 见 → KIẾN" },
  { id: "ec-011", grammarId: "B7-NP3", type: "error-correction", lesson: 7,
    tokens: ["我", "开", "自行车", "。"], errorIndex: 1,
    correction: ["我", "骑", "自行车", "。"],
    explanation: "自行车 (xe đạp) là xe 2 bánh → phải dùng 骑 'cưỡi/đi'. 开 chỉ dùng cho xe có động cơ (摩托车, 汽车, 飞机).",
    hanVietHint: "骑 → KỴ (cưỡi) | 开 → KHAI (lái — dành cho xe có động cơ)" },
  { id: "ec-012", grammarId: "B7-NP1", type: "error-correction", lesson: 7,
    tokens: ["我", "说", "他", "明天没课", "。"], errorIndex: 1,
    correction: ["我", "跟", "他", "说", "明天没课", "。"],
    explanation: "Cấu trúc nói với ai phải có giới từ 跟/和 trước người: 我 + 跟 + 他 + 说. Thiếu 跟/和 thì câu mang nghĩa 'tôi nói anh ấy' (= phê bình anh ấy), không phải 'nói với anh ấy'.",
    hanVietHint: "跟 → CĂN (giới từ 'với') | 说 → THUYẾT" },
  { id: "ec-013", grammarId: "B7-NP6", type: "error-correction", lesson: 7,
    tokens: ["我", "学习", "在", "教室", "。"], errorIndex: 2,
    correction: ["我", "在", "教室", "学习", "。"],
    explanation: "Sai trật tự kiểu tiếng Anh/Việt — trong tiếng Trung, cụm 在 + nơi chốn PHẢI đứng TRƯỚC động từ. Đúng: 我在教室学习 ('tôi ở-trong-lớp học').",
    hanVietHint: "在 → TẠI (ở) — quy tắc 'ở đâu trước, làm gì sau'" },
  { id: "ec-014", grammarId: "B7-NP7", type: "error-correction", lesson: 7,
    tokens: ["他", "是", "有名", "人", "。"], errorIndex: 2,
    correction: ["他", "是", "有名", "的", "人", "。"],
    explanation: "Tính từ 2 âm tiết (有名) BẮT BUỘC có 的 trước danh từ. Thiếu 的 thì câu sai cấu trúc — '有名人' không có nghĩa 'người nổi tiếng', phải là '有名的人'.",
    hanVietHint: "有名 → HỮU DANH | 的 → trợ từ định ngữ (bắt buộc với tính từ 2 âm tiết)" },
  { id: "ec-015", grammarId: "B7-NP7", type: "error-correction", lesson: 7,
    tokens: ["这", "是", "很好", "电影", "。"], errorIndex: 2,
    correction: ["这", "是", "很好", "的", "电影", "。"],
    explanation: "Có phó từ 很 trước Adj 1 âm tiết 好 → cụm 很好 BẮT BUỘC có 的 trước danh từ. Đúng: 很好的电影 = 'phim rất hay'. Lưu ý: chỉ 好电影 (không có 很) thì không cần 的.",
    hanVietHint: "很 → rất | 好 → HẢO | 的 → bắt buộc khi có Adv trước Adj 1 âm tiết" },
  { id: "ec-016", grammarId: "B7-NP12", type: "error-correction", lesson: 7,
    tokens: ["我", "去", "图书馆", "和", "朋友", "。"], errorIndex: 3,
    correction: ["我", "和", "朋友", "去", "图书馆", "。"],
    explanation: "Sai trật tự — '和 + người' phải đặt TRƯỚC động từ, không đặt sau. Đúng: 我 + 和 + 朋友 + 去 + 图书馆 = 'Tôi đi thư viện với bạn'.",
    hanVietHint: "和 → HÒA (với) — cụm '和+người' đứng trước V, không đứng sau" },

  // ── Pattern Matching ──
  { id: "pm-001", grammarId: null, type: "pattern-match", lesson: 1,
    pairs: [
      { left: "CN + 是 + DT",     right: "Cô ấy là giáo viên." },
      { left: "CN + 不是 + DT",   right: "Bạn không phải là học sinh." },
      { left: "CN + 很 + TT",     right: "Tôi rất vui." },
      { left: "CN + VN + 吗？",   right: "Bạn có phải là lưu học sinh không?" }
    ],
    explanation: "是 chỉ dùng với DT. 很 chỉ dùng với TT. 吗 thêm vào cuối câu để hỏi." },
  { id: "pm-002", grammarId: null, type: "pattern-match", lesson: 2,
    pairs: [
      { left: "ĐN + 的 + DT",         right: "sách của tôi / 我的书" },
      { left: "CN + 也 + VN",          right: "Tôi cũng là người Trung Quốc." },
      { left: "[chủ đề] + 呢？",       right: "Còn bạn thì sao?" },
      { left: "CN + 不 + ĐT + TN",    right: "Tôi không quen anh ấy." }
    ],
    explanation: null },
  { id: "pm-003", grammarId: null, type: "pattern-match", lesson: 3,
    pairs: [
      { left: "谁的 + DT",      right: "Đây là sách của ai?" },
      { left: "什么 + DT",      right: "Đây là tạp chí gì?" },
      { left: "哪 + 本 + DT",   right: "Cuốn sách nào là của bạn?" },
      { left: "X，就是 Y",      right: "Từ điển Hán-Nhật, tức là từ điển TQ-NB." }
    ],
    explanation: "谁的/什么/哪 là đại từ nghi vấn — câu hỏi KHÔNG dùng 吗 thêm vào." },
  { id: "pm-004", grammarId: null, type: "pattern-match", lesson: 3,
    pairs: [
      { left: "你会说什么语言？",      right: "会 + ĐT (biết làm)" },
      { left: "我喜欢听音乐。",        right: "喜欢 + ĐT (thích làm)" },
      { left: "这本书是我的。",        right: "Số/ĐT chỉ định + 本 + DT" },
      { left: "你认识他吗？",          right: "S + V + O + 吗 (câu hỏi cơ bản)" }
    ],
    explanation: null },
  { id: "pm-005", grammarId: null, type: "pattern-match", lesson: 4,
    pairs: [
      { left: "CN + 在 + DT",          right: "Thư viện ở bên trái." },
      { left: "DT + 是 + CN",          right: "Bên trái là thư viện." },
      { left: "CN + 在哪儿？",         right: "Ký túc xá ở đâu?" },
      { left: "请问 + [câu hỏi]",      right: "Xin hỏi, thư viện ở đâu?" }
    ],
    explanation: "在 hỏi/trả lời 'ở đâu'. 是 hỏi/trả lời 'là gì'. Hai cấu trúc KHÔNG hoán đổi cho nhau." },
  { id: "pm-006", grammarId: null, type: "pattern-match", lesson: 4,
    pairs: [
      { left: "左边",    right: "bên trái" },
      { left: "右边",    right: "bên phải" },
      { left: "上边",    right: "phía trên" },
      { left: "下边",    right: "phía dưới" },
      { left: "北边",    right: "phía bắc" }
    ],
    explanation: "Phương vị từ: gốc chỉ hướng + 边." },
  { id: "pm-007", grammarId: null, type: "pattern-match", lesson: 4,
    pairs: [
      { left: "我知道他是学生。",       right: "知道 — biết thông tin/sự kiện" },
      { left: "我会说汉语。",           right: "会 — biết kỹ năng (qua học)" },
      { left: "对不起！没关系。",       right: "对不起/没关系 — xin lỗi & đáp lại" },
      { left: "那个人是谁？",           right: "个 — lượng từ chung cho người" }
    ],
    explanation: null },

  // ── Translation ──
  { id: "tr-001", grammarId: "B1-NP2", type: "translation", lesson: 1,
    direction: "vi-to-zh", sourceText: "Cô ấy là giáo viên.", targetText: "她是老师。",
    acceptedVariants: ["她是老师"],
    hanVietHint: "老师 → LÃO SƯ | 她 = cô ấy",
    explanation: "CN + 是 + DT. 是 bắt buộc — không được bỏ qua!" },
  { id: "tr-002", grammarId: "B1-NP3", type: "translation", lesson: 1,
    direction: "vi-to-zh", sourceText: "Bạn có phải là lưu học sinh không?", targetText: "你是留学生吗？",
    acceptedVariants: ["你是留学生吗"],
    hanVietHint: "留学生 → LƯU HỌC SINH ✨",
    explanation: "Thêm 吗 vào cuối câu khẳng định, trật tự từ giữ nguyên." },
  { id: "tr-003", grammarId: "B2-NP6", type: "translation", lesson: 2,
    direction: "vi-to-zh", sourceText: "Tôi là người Việt Nam.", targetText: "我是越南人。",
    acceptedVariants: ["我是越南人"],
    hanVietHint: "越南 → VIỆT NAM ✨ | 人 → NHÂN",
    explanation: "Tên quốc gia + 人 = người nước đó." },
  { id: "tr-004", grammarId: "B2-NP3", type: "translation", lesson: 2,
    direction: "vi-to-zh", sourceText: "Tôi cũng rất vui.", targetText: "我也很高兴。",
    acceptedVariants: ["我也很高兴"],
    hanVietHint: "高兴 → CAO HỨNG ✨ | 也 → DÃ",
    explanation: "也 đứng trước 很, 很 đứng trước tính từ. Trật tự: CN + 也 + 很 + TT." },
  { id: "tr-005", grammarId: "B3-NP1", type: "translation", lesson: 3,
    direction: "vi-to-zh", sourceText: "Đó là từ điển của bạn tôi.", targetText: "那是我朋友的词典。",
    acceptedVariants: ["那是我朋友的词典", "那是我的朋友的词典"],
    hanVietHint: "词典 → TỪ ĐIỂN ✨ | 朋友 → BẰNG HỮU ✨",
    explanation: "那 + 是 + [ĐN]的 + DT. 我朋友的 = của bạn tôi." },
  { id: "tr-006", grammarId: "CB-NP2", type: "translation", lesson: 3,
    direction: "vi-to-zh", sourceText: "Bạn biết nói ngôn ngữ gì?", targetText: "你会说什么语言？",
    acceptedVariants: ["你会说什么语言"],
    hanVietHint: "语言 → NGỮ NGÔN ✨ | 说 → THUYẾT",
    explanation: "会说 = biết nói. 什么语言 = ngôn ngữ gì — đại từ nghi vấn giữ nguyên vị trí." },
  { id: "tr-007", grammarId: "B2-NP2", type: "translation", lesson: 2,
    direction: "zh-to-vi", sourceText: "那是你的词典吗？", targetText: "Đó có phải từ điển của bạn không?",
    acceptedVariants: null,
    hanVietHint: "词典 → TỪ ĐIỂN ✨",
    explanation: "那 = đó/kia. 你的词典 = từ điển của bạn. 吗 = câu hỏi có/không." },
  { id: "tr-008", grammarId: "B4-NP1", type: "translation", lesson: 4,
    direction: "vi-to-zh", sourceText: "Xin hỏi, thư viện ở đâu?", targetText: "请问，图书馆在哪儿？",
    acceptedVariants: ["请问，图书馆在哪里？", "请问图书馆在哪儿？", "请问图书馆在哪里？"],
    hanVietHint: "请问 → THỈNH VẤN ✨ | 图书馆 → ĐỒ THƯ QUÁN | 哪儿 = 哪里",
    explanation: "请问 đầu câu → câu hỏi bình thường. 在哪儿？= 在哪里？ (ở đâu?)." },
  { id: "tr-009", grammarId: "B4-NP1", type: "translation", lesson: 4,
    direction: "vi-to-zh", sourceText: "Bên trái là ký túc xá.", targetText: "左边是宿舍。",
    acceptedVariants: ["左边是宿舍"],
    hanVietHint: "宿舍 → TÚC XÁ ✨ (ký túc xá) | 左边 → TẢ BIÊN",
    explanation: "Địa điểm làm chủ ngữ → dùng 是: 左边 (địa điểm) + 是 + 宿舍 (tên nơi)." },
  { id: "tr-010", grammarId: "B4-NP2", type: "translation", lesson: 4,
    direction: "vi-to-zh", sourceText: "Trường học ở bên phải thư viện.", targetText: "学校在图书馆的右边。",
    acceptedVariants: ["学校在图书馆右边。", "学校在图书馆的右边"],
    hanVietHint: "右边 → HỮU BIÊN (bên phải)",
    explanation: "N + 的 + phương vị từ: 图书馆的右边 = 'bên phải của thư viện'. Trật tự N + 的 trước phương vị từ." },
  { id: "tr-011", grammarId: "CB-NP6", type: "translation", lesson: 4,
    direction: "vi-to-zh", sourceText: "Người tôi thích là cô ấy.", targetText: "我喜欢的人是她。",
    acceptedVariants: ["我喜欢的人是她"],
    hanVietHint: "喜欢 → HỶ HOAN ✨ | [CN+ĐT] + 的 + DT = mệnh đề quan hệ",
    explanation: "Cụm ĐT làm định ngữ: [我喜欢] + 的 + 人. Tiếng Trung đặt mệnh đề quan hệ TRƯỚC danh từ — ngược với tiếng Việt ('người *mà tôi thích*' → đặt sau)." },
  { id: "tr-012", grammarId: "B6-NP8", type: "translation", lesson: 6,
    direction: "vi-to-zh", sourceText: "Tôi mỗi ngày ngủ trưa.", targetText: "我每天睡午觉。",
    acceptedVariants: ["我每天睡午觉"],
    hanVietHint: "每天 → MỖI THIÊN (mỗi ngày) | 睡午觉 → ngủ trưa",
    explanation: "睡觉 tách rời, chèn 午 vào giữa: 睡 + 午 + 觉. 每天 (mỗi ngày) đứng sau CN, trước cụm động từ." },
  { id: "tr-013", grammarId: "B6-NP9", type: "translation", lesson: 6,
    direction: "vi-to-zh", sourceText: "Tôi 8 giờ học tiếng Hán.", targetText: "我八点上汉语课。",
    acceptedVariants: ["我八点上汉语课"],
    hanVietHint: "上课 → THƯỢNG KHÓA | 汉语 → HÁN NGỮ | 八点 → BÁT ĐIỂM (8 giờ)",
    explanation: "Time + V tách rời: 八点 (giờ) + 上汉语课 (上 + 汉语 + 课). Giờ đứng trước cụm động từ tách rời; tên môn chèn giữa 上 và 课." },
  { id: "tr-014", grammarId: "B6-NP10", type: "translation", lesson: 6,
    direction: "vi-to-zh", sourceText: "Lát nữa gặp nhé!", targetText: "一会儿见！",
    acceptedVariants: ["一会儿见", "一下儿见！", "一下儿见"],
    hanVietHint: "一会儿 → NHẤT HỘI (một lát) | 见 → KIẾN | 一下儿见 cũng được dùng",
    explanation: "Time + 见: 一会儿 (= 一下儿 trong khẩu ngữ) đặt TRƯỚC 见. Cả 一会儿见 và 一下儿见 đều đúng và đồng nghĩa." },
  { id: "tr-015", grammarId: "B7-NP1", type: "translation", lesson: 7,
    direction: "vi-to-zh", sourceText: "Cô ấy nói với tôi về chuyện này.", targetText: "她跟我说了这件事。",
    acceptedVariants: ["她和我说了这件事。", "她跟我说了这件事", "她和我说了这件事"],
    hanVietHint: "跟/和 → 'với' | 说 → THUYẾT | 件 → KIỆN (lượng từ cho 事)",
    explanation: "跟/和 + 我 + 说 + 这件事: 'nói với tôi chuyện này'. 件 là lượng từ cho 事 (sự việc). 了 sau 说 đánh dấu hành động đã xảy ra." },
  { id: "tr-016", grammarId: "B7-NP2", type: "translation", lesson: 7,
    direction: "vi-to-zh", sourceText: "Tối nay tôi không có thời gian.", targetText: "今晚我没有时间。",
    acceptedVariants: ["今晚我没有时间", "今天晚上我没有时间。", "今天晚上我没有时间"],
    hanVietHint: "今晚 = 今天晚上 (tối nay) | 时间 → THỜI GIAN",
    explanation: "今晚 là dạng rút gọn khẩu ngữ của 今天晚上. Cả hai đều đúng — đây là điểm chính của B7-NP2." },
  { id: "tr-017", grammarId: "B7-NP3", type: "translation", lesson: 7,
    direction: "vi-to-zh", sourceText: "Tôi mỗi ngày đi xe đạp đến trường.", targetText: "我每天骑自行车去学校。",
    acceptedVariants: ["我每天骑自行车去学校"],
    hanVietHint: "骑 → KỴ (cưỡi/đi xe 2 bánh) | 自行车 → TỰ HÀNH XA",
    explanation: "Xe đạp 2 bánh → dùng 骑. 每天 (mỗi ngày) đặt sau CN, trước cụm động từ chính." },
  { id: "tr-018", grammarId: "B7-NP4", type: "translation", lesson: 7,
    direction: "vi-to-zh", sourceText: "Trong phòng có người.", targetText: "房间里有人。",
    acceptedVariants: ["房间里有人"],
    hanVietHint: "里 → LÝ (trong) | 房间 → PHÒNG GIAN (phòng) | 有人 → có người",
    explanation: "N + 里 + 有 + ... = cấu trúc 'trong N có ...'. 里 đặt trực tiếp sau danh từ địa điểm (không cần 的)." },
  { id: "tr-019", grammarId: "B7-NP5", type: "translation", lesson: 7,
    direction: "vi-to-zh", sourceText: "Anh ấy ở trước tòa nhà.", targetText: "他在楼前。",
    acceptedVariants: ["他在楼前"],
    hanVietHint: "在 → TẠI (ở) | 楼 → LÂU (tòa nhà) | 前 → TIỀN (trước)",
    explanation: "CN + 在 + N + phương vị từ: 他 + 在 + 楼 + 前. Không có động từ khác — câu mô tả vị trí." },
  { id: "tr-020", grammarId: "B7-NP6", type: "translation", lesson: 7,
    direction: "vi-to-zh", sourceText: "Anh ấy ăn cơm ở nhà.", targetText: "他在家吃饭。",
    acceptedVariants: ["他在家吃饭"],
    hanVietHint: "在 → TẠI (ở) | 家 → GIA (nhà) | 吃饭 → KHIẾT PHẠN (ăn cơm)",
    explanation: "S + 在 + nơi chốn + V: '在家' (ở nhà) đặt TRƯỚC động từ '吃饭'. Không nói '他吃饭在家'." },
  { id: "tr-021", grammarId: "B7-NP7", type: "translation", lesson: 7,
    direction: "vi-to-zh", sourceText: "Anh ấy là người nổi tiếng.", targetText: "他是有名的人。",
    acceptedVariants: ["他是有名的人"],
    hanVietHint: "有名 → HỮU DANH (nổi tiếng) | 的 → trợ từ định ngữ | 人 → NHÂN",
    explanation: "Tính từ 2 âm tiết (有名) cần 的 khi đứng trước danh từ: 有名 + 的 + 人 = 'người nổi tiếng'." },
  { id: "tr-022", grammarId: "B7-NP8", type: "translation", lesson: 7,
    direction: "vi-to-zh", sourceText: "Tôi thích xem phim, nhưng không có thời gian.", targetText: "我喜欢看电影，可是没有时间。",
    acceptedVariants: ["我喜欢看电影，可是没有时间", "我喜欢看电影,可是没有时间。", "我喜欢看电影,可是没有时间"],
    hanVietHint: "可是 → KHẢ THỊ (nhưng) | 喜欢 → HỶ HOAN | 时间 → THỜI GIAN",
    explanation: "Hai mệnh đề đối lập nối bằng 可是: [喜欢看电影] + , + 可是 + [没有时间]." },
  { id: "tr-023", grammarId: "B7-NP9", type: "translation", lesson: 7,
    direction: "vi-to-zh", sourceText: "Tất nhiên anh ấy biết nói tiếng Hán.", targetText: "他当然会说汉语。",
    acceptedVariants: ["他当然会说汉语", "当然他会说汉语。", "当然他会说汉语"],
    hanVietHint: "当然 → ĐƯƠNG NHIÊN | 会说 → biết nói | 汉语 → HÁN NGỮ",
    explanation: "当然 làm phó từ giữa CN và động từ: 他 + 当然 + 会说 + 汉语. Có thể đứng đầu câu để nhấn mạnh." },
  { id: "tr-024", grammarId: "B7-NP10", type: "translation", lesson: 7,
    direction: "vi-to-zh", sourceText: "Bạn là học sinh đúng không?", targetText: "你是学生吧？",
    acceptedVariants: ["你是学生吧", "你是学生吧?"],
    hanVietHint: "吧 — hỏi xác nhận ('đúng không?') | so sánh: 你是学生吗? = hỏi thuần ('có phải...không?')",
    explanation: "Khi đã đoán biết và xin xác nhận → dùng 吧 (KHÔNG dùng 吗). 'Đúng không?' chính là dấu hiệu của 吧." },
  { id: "tr-025", grammarId: "B7-NP11", type: "translation", lesson: 7,
    direction: "vi-to-zh", sourceText: "Bạn mấy giờ tan làm?", targetText: "你几点下班？",
    acceptedVariants: ["你几点下班", "你几点下班?"],
    hanVietHint: "下班 → HẠ BAN (tan làm) | 几点 → mấy giờ",
    explanation: "Hỏi giờ + động từ tách rời: 几点 + 下班. Không thêm 吗 vì 几 đã là đại từ nghi vấn." },
];
