/**
 * Chinese Vocabulary Data
 *
 * To add a new word, just append to the array — `n` is assigned automatically.
 *   { char: "汉字", pinyin: "pīnyīn", pos: "n.", viet: "nghĩa tiếng Việt", lesson: <number> }
 *
 * pos options: n. (noun), v. (verb), pron. (pronoun), adv. (adverb), adj. (adjective), part. (particle), suff. (suffix), q. (quantifier), or "" (none)
 *
 * Optional fields:
 *   hv: "<Hán Việt explanation>"
 *   radical: "<char1 = radical breakdown | char2 = ...>" (use | between characters)
 *   examples: [{ zh: "Chinese sentence", vi: "Vietnamese translation" }, ...]
 */
const words = [
  // ── Lesson 1 ──
  { char:"你好",   pinyin:"nǐ hǎo",       pos:"",      viet:"chào bạn",                                          lesson:1, hv:"NỄ HẢO — lit. 'bạn tốt' = chào", radical:"你 = 亻(NHÂN — người) + 尔(NHĨ — bạn) → một người gọi 'bạn' | 好 = 女(NỮ — phụ nữ) + 子(TỬ — con) → mẹ bồng con = tốt/lành", examples:[{ zh:"你好，老师！", vi:"Chào thầy/cô!" }] },
  { char:"好",     pinyin:"hǎo",           pos:"adj.",  viet:"tốt, khỏe, hay, ngon",                              lesson:1, hv:"HẢO — tốt (như 'hảo cảm', 'hảo hán')", radical:"女(NỮ — phụ nữ) + 子(TỬ — con) → mẹ bồng con = tốt/lành" },
  { char:"你",     pinyin:"nǐ",            pos:"pron.", viet:"bạn, anh, chị... (ngôi thứ 2 số ít)",               lesson:1, hv:"NỄ — bạn (đại từ ngôi 2)", radical:"亻(NHÂN — người) + 尔(NHĨ — bạn) → một người gọi 'bạn'", examples:[{ zh:"你叫什么名字？", vi:"Bạn tên là gì?" }] },
  { char:"是",     pinyin:"shì",           pos:"v.",    viet:"là, thì...",                                         lesson:1, hv:"THỊ — là (như 'thị phi', 'như thị')", radical:"日(NHẬT — mặt trời) + 正(CHÍNH — đúng/thẳng) → mặt trời đứng thẳng = đúng/là", examples:[{ zh:"我是学生。", vi:"Tôi là học sinh." }] },
  { char:"老师",   pinyin:"lǎoshī",        pos:"n.",    viet:"giáo viên, thầy/cô giáo",                           lesson:1, hv:"LÃO SƯ — thầy/cô (dùng trong võ thuật, văn học)", radical:"老 = 土(THỔ — đất) + 人(NHÂN — người) + 匕 → người già bám rễ trên đất | 师 = 帀 + 巾(CÂN — vải) → sư phụ truyền dạy", examples:[{ zh:"她是老师。", vi:"Cô ấy là giáo viên." }] },
  { char:"吗",     pinyin:"ma",            pos:"part.", viet:"...không? ...à? (trợ từ nghi vấn)",                  lesson:1, hv:"MA — trợ từ nghi vấn (HV ít dùng)", radical:"口(KHẨU — miệng) + 马(MÃ — ngựa) → trợ từ phiên âm — coi như ký hiệu nghi vấn", examples:[{ zh:"你是学生吗？", vi:"Bạn có phải là học sinh không?" }] },
  { char:"了",     pinyin:"le",            pos:"part.", viet:"rồi, đã (trợ từ chỉ hoàn thành/biến đổi)",            lesson:1, hv:"LIỄU — hoàn thành (như 'liễu kết', 'liễu giải')", radical:"móc 2 nét đơn — coi như ký hiệu của 'hoàn thành'" },
  { char:"不",     pinyin:"bù",            pos:"adv.",  viet:"không (trợ từ phủ định)",                            lesson:1, hv:"BẤT — không (như 'bất công', 'bất an')", radical:"tượng hình con chim bay lên không tới = không/chưa", examples:[{ zh:"我不是老师。", vi:"Tôi không phải là giáo viên." }] },
  { char:"我",     pinyin:"wǒ",            pos:"pron.", viet:"tôi, tớ, mình... (ngôi thứ nhất số ít)",            lesson:1, hv:"NGÃ — tôi (như 'bản ngã', 'tự ngã')", radical:"tượng hình bàn tay (手) cầm vũ khí (戈 — giáo) → 'cầm giáo bảo vệ mình' = tôi/ta", examples:[{ zh:"我叫大卫。", vi:"Tôi tên là David." }] },
  { char:"学生",   pinyin:"xuésheng",      pos:"n.",    viet:"học sinh",                                           lesson:1, hv:"HỌC SINH — giống hệt tiếng Việt!", radical:"学 = 冖(MIÊN — mái) + 子(TỬ — con) + 爻(học vấn) → đứa trẻ dưới mái học chữ | 生 = 土(THỔ — đất) + 丿 → cây con mọc lên khỏi đất = sinh/sống" },
  { char:"她",     pinyin:"tā",            pos:"pron.", viet:"cô ấy, chị ấy, nó (nữ, ngôi thứ 3 số ít)",         lesson:1, hv:"THA — cô ấy (như 'tha hương', 'tha nhân')", radical:"女(NỮ — phụ nữ) + 也(DÃ — cũng) → cô ấy (dạng nữ của 他)" },
  { char:"谢谢",   pinyin:"xièxie",        pos:"v.",    viet:"cảm ơn",                                            lesson:1, hv:"TẠ TẠ — cảm tạ (lặp 2 lần)", radical:"讠(NGÔN — lời nói) + 射(XẠ — bắn) → bắn ra lời cảm ơn (lặp 2 lần để nhấn mạnh)", examples:[{ zh:"谢谢老师！", vi:"Cảm ơn thầy/cô!" }] },
  { char:"不客气", pinyin:"bú kèqi",        pos:"",      viet:"đừng khách sáo",                                    lesson:1, hv:"BẤT KHÁCH KHÍ — đừng khách khí", radical:"不(BẤT — không) | 客(KHÁCH) = 宀(MIÊN — mái) + 各(CÁC — chỉ thanh) → khách dưới mái | 气(KHÍ — khí/thái độ) → 'không khách khí' = đừng khách sáo" },
  { char:"您",     pinyin:"nín",           pos:"pron.", viet:"ông, bà, cô, chú, anh, chị... (trang trọng, số ít)", lesson:1, hv:"kính ngữ của 你 (NỄ) — HV ít dùng", radical:"你(NỄ — bạn) đặt trên 心(TÂM — tim) → 'gọi bạn từ trái tim' = bạn (kính ngữ)" },
  { char:"留学生", pinyin:"liúxuéshēng",    pos:"n.",    viet:"lưu học sinh",                                      lesson:1, hv:"LƯU HỌC SINH — giống hệt tiếng Việt!", radical:"留 = 田(ĐIỀN — ruộng) + 刀 + 口 → ở lại làm việc trên đồng ruộng | 学 = đứa trẻ dưới mái học chữ | 生 = cây con mọc lên = người" },
  { char:"叫",     pinyin:"jiào",          pos:"v.",    viet:"gọi, kêu",                                           lesson:1, hv:"KHIẾU — gọi (như 'khiếu nại')", radical:"口(KHẨU — miệng) + 丩(âm xoắn) → miệng kêu lên = gọi/kêu" },
  { char:"什么",   pinyin:"shénme",        pos:"pron.", viet:"gì, cái gì?",                                        lesson:1, hv:"THẬM MA — gì (HV ít dùng)" },
  { char:"名字",   pinyin:"míngzi",        pos:"n.",    viet:"tên, họ tên",                                        lesson:1, hv:"DANH TỰ — tên (danh=tên, tự=chữ)", radical:"名 = 夕(TỊCH — chiều tối) + 口(KHẨU — miệng) → gọi tên trong bóng tối | 字 = 宀(MIÊN — mái) + 子(TỬ — con) → đứa trẻ dưới mái học chữ" },
  { char:"大卫",   pinyin:"Dàwèi",         pos:"n.",    viet:"David (tên người)",                                  lesson:1, hv:"ĐẠI VỆ — phiên âm 'David'" },
  { char:"王",     pinyin:"Wáng",          pos:"n.",    viet:"Vương (họ)",                                          lesson:1, hv:"VƯƠNG — vua / họ Vương (như 'vương quốc')" },
  { char:"李军",   pinyin:"Lǐ Jūn",        pos:"n.",    viet:"Lý Quân (tên người)",                                lesson:1, hv:"LÝ QUÂN — họ Lý + tên Quân" },
  { char:"还没",   pinyin:"hái méi",       pos:"adv.",  viet:"chưa",                                                lesson:1, hv:"HOÀN MỘT — vẫn chưa (HOÀN = vẫn, MỘT = không)", radical:"还 = 辶(SƯỚC — di chuyển) + 不 → vẫn đi, chưa tới | 没 = 氵(THỦY — nước) + 殳 → bị chìm = chưa/không" },
  { char:"工作",   pinyin:"gōngzuò",       pos:"v./n.", viet:"đi làm, công việc",                                   lesson:1, hv:"CÔNG TÁC — công việc / công tác", radical:"工 = thước thợ mộc = công việc | 作 = 亻(NHÂN — người) + 乍(thoắt) → người làm gì đó = chế tạo/làm" },

  // ── Lesson 2 ──
  { char:"同学",   pinyin:"tóngxué",       pos:"n.",    viet:"bạn cùng học",                                       lesson:2, hv:"ĐỒNG HỌC — bạn cùng lớp", radical:"同 = 冂(khung) + 口(KHẨU — miệng) → các miệng trong cùng khung = cùng nhau | 学 = đứa trẻ dưới mái học chữ" },
  { char:"们",     pinyin:"men",           pos:"suff.", viet:"hậu tố chỉ người ở số nhiều",                        lesson:2, hv:"MÔN — hậu tố số nhiều (HV ít dùng)", radical:"亻(NHÂN — người) + 门(MÔN — cửa) → người người qua cửa = hậu tố số nhiều" },
  { char:"来",     pinyin:"lái",           pos:"v.",    viet:"đến, tới",                                            lesson:2, hv:"LAI — đến (như 'tương lai', 'lai lịch')", radical:"tượng hình bông lúa — hạt lúa đến = đến/tới", examples:[{ zh:"我来中国了。", vi:"Tôi đã đến Trung Quốc rồi." },{ zh:"他来介绍一下儿。", vi:"Anh ấy đến giới thiệu một chút." }] },
  { char:"介绍",   pinyin:"jièshào",       pos:"v.",    viet:"giới thiệu",                                         lesson:2, hv:"GIỚI THIỆU — giống hệt tiếng Việt!", radical:"介(GIỚI — đứng giữa) = 人 + 八 → người đứng giữa | 绍(THIỆU) = 纟(MỊCH — sợi) + 召(TRIỆU — chỉ thanh) → kết nối → 'người đứng giữa kết nối' = giới thiệu" },
  { char:"一下儿", pinyin:"yíxiàr",         pos:"q.",    viet:"một chút",                                           lesson:2, hv:"NHẤT HẠ — một chút (lit. 'một lần xuống')", radical:"一(NHẤT — một) | 下(HẠ) = nét dưới đường ngang → dưới/xuống → 'một lần xuống' = một chút" },
  { char:"姓",     pinyin:"xìng",          pos:"v./n.", viet:"họ (của tên)",                                        lesson:2, hv:"TÍNH — họ (như 'họ tên')", radical:"女(NỮ — phụ nữ) + 生(SINH — sinh) → họ truyền qua bên mẹ = họ" },
  { char:"的",     pinyin:"de",            pos:"part.", viet:"trợ từ",                                              lesson:2, hv:"ĐÍCH — trợ từ sở hữu (HV gốc nhưng nghĩa khác)" },
  { char:"哪",     pinyin:"nǎ",            pos:"pron.", viet:"nào",                                                lesson:2, hv:"NA — nào (đại từ nghi vấn)", radical:"口(KHẨU — miệng) + 那(kia) → miệng hỏi 'cái nào?'", examples:[{ zh:"你是哪国人？", vi:"Bạn là người nước nào?" },{ zh:"他是哪国人？", vi:"Anh ấy là người nước nào?" }] },
  { char:"国",     pinyin:"guó",           pos:"n.",    viet:"nước, quốc gia",                                     lesson:2, hv:"QUỐC — nước (như 'quốc gia', 'quốc tế')", radical:"囗(viền/biên) + 玉(NGỌC — ngọc) → ngọc quý trong biên giới = nước" },
  { char:"人",     pinyin:"rén",           pos:"n.",    viet:"người",                                               lesson:2, hv:"NHÂN — người (như 'nhân loại', 'nhân văn')", radical:"tượng hình người đứng dang chân" },
  { char:"他",     pinyin:"tā",            pos:"pron.", viet:"anh ấy, ông ấy...",                                  lesson:2, hv:"THA — anh ấy (như 'tha nhân')", radical:"亻(NHÂN — người) + 也(DÃ — cũng) → anh ấy (dạng nam của 她)" },
  { char:"认识",   pinyin:"rènshi",        pos:"v.",    viet:"quen biết",                                           lesson:2, hv:"NHẬN THỨC — quen biết", radical:"认(NHẬN) = 讠(NGÔN — lời) + 人(chỉ thanh) → nhận biết | 识(THỨC) = 讠(NGÔN — lời) + 只(chỉ thanh) → biết → 'nhận + biết' = quen biết", examples:[{ zh:"认识你很高兴。", vi:"Rất vui được quen biết bạn." },{ zh:"我认识他。", vi:"Tôi quen biết anh ấy." }] },
  { char:"很",     pinyin:"hěn",           pos:"adv.",  viet:"rất",                                                lesson:2, hv:"NGẪN — rất (HV ít dùng)", radical:"彳(SÁCH — bước) + 艮(CẤN — vững) → bước đi vững chắc = rất" },
  { char:"高兴",   pinyin:"gāoxìng",       pos:"adj.",  viet:"vui mừng",                                           lesson:2, hv:"CAO HỨNG — vui, hứng khởi", radical:"高(CAO) = hình tòa nhà cao = cao | 兴(HƯNG) = tượng hình bốn tay cùng nâng vật lên = hưng phấn → 'lòng dâng cao' = vui mừng", examples:[{ zh:"同学们很高兴。", vi:"Các bạn cùng học rất vui." },{ zh:"我也很高兴。", vi:"Tôi cũng rất vui." }] },
  { char:"也",     pinyin:"yě",            pos:"adv.",  viet:"cũng",                                               lesson:2, hv:"DÃ — cũng (như 'dã thị')", radical:"nét cong đơn — trợ từ 'cũng', coi như ký hiệu" },
  { char:"呢",     pinyin:"ne",            pos:"part.", viet:"trợ từ",                                              lesson:2, hv:"NỊ — trợ từ (HV ít dùng)" },
  { char:"中国",   pinyin:"Zhōngguó",      pos:"n.",    viet:"Trung Quốc",                                         lesson:2, hv:"TRUNG QUỐC — giống hệt tiếng Việt!", radical:"中 = nét dọc xuyên giữa hình chữ nhật → trúng tâm | 国 = ngọc trong biên giới" },
  { char:"美国",   pinyin:"Měiguó",        pos:"n.",    viet:"Mỹ",                                                  lesson:2, hv:"MỸ QUỐC — giống hệt tiếng Việt!", radical:"美 = 羊(DƯƠNG — cừu) + 大(ĐẠI — to) → cừu to đẹp = đẹp | 国 = nước" },
  { char:"英国",   pinyin:"Yīngguó",       pos:"n.",    viet:"Anh",                                                 lesson:2, hv:"ANH QUỐC — giống hệt tiếng Việt!", radical:"英(ANH — bông hoa nổi bật / Anh quốc) — bộ 艹(THẢO — cỏ) gợi hoa | 国 = nước → nước Anh" },
  { char:"法国",   pinyin:"Fǎguó",         pos:"n.",    viet:"Pháp",                                                lesson:2, hv:"PHÁP QUỐC — giống hệt tiếng Việt!", radical:"法(PHÁP — pháp luật/cách thức) — bộ 氵(THỦY — nước) | 国(QUỐC — nước) → 'pháp quốc' = nước Pháp" },
  { char:"加拿大", pinyin:"Jiānádà",        pos:"n.",    viet:"Canada",                                              lesson:2, hv:"GIA NÃ ĐẠI — phiên âm 'Canada'" },
  { char:"日本",   pinyin:"Rìběn",         pos:"n.",    viet:"Nhật Bản",                                            lesson:2, hv:"NHẬT BẢN — giống hệt tiếng Việt!", radical:"日(NHẬT — mặt trời) | 本 = 木(MỘC — cây) + 一 → vạch ở gốc cây = gốc/nguồn" },
  { char:"韩国",   pinyin:"Hánguó",        pos:"n.",    viet:"Hàn Quốc",                                            lesson:2, hv:"HÀN QUỐC — giống hệt tiếng Việt!", radical:"韩 = chữ phức tạp — nhận biết hình dạng | 国 = nước" },
  { char:"越南",   pinyin:"Yuènán",        pos:"n.",    viet:"Việt Nam",                                            lesson:2, hv:"VIỆT NAM — giống hệt tiếng Việt!", radical:"越 = 走(TẨU — đi) + 戉(VIỆT — rìu) → đi vượt qua | 南 = 十 + 冂 + 里 → dấu hướng = phía nam" },

  // ── Lesson 3 ──
  { char:"那",     pinyin:"nà",            pos:"pron.", viet:"kia, đó",                                            lesson:3, hv:"NA — kia/đó (đại từ chỉ định xa)", radical:"阝(PHỤ — thành/đất) + 冉(NHIỄM — chậm) → nơi xa kia = đó/kia" },
  { char:"谁",     pinyin:"shéi/shuí",     pos:"pron.", viet:"ai, người nào",                                      lesson:3, hv:"THÙY — ai (văn cổ, như 'thùy hỉ')", radical:"讠(NGÔN — lời, bộ thủ) + 隹(CHUỲ — chim đuôi ngắn, chỉ thanh) → từ nghi vấn = ai" },
  { char:"书",     pinyin:"shū",           pos:"n.",    viet:"quyển sách",                                         lesson:3, hv:"THƯ — sách (như 'thư viện', 'thư từ')", radical:"tượng hình bút lông đang viết = sách", examples:[{ zh:"这是我的书。", vi:"Đây là sách của tôi." },{ zh:"那是谁的书？", vi:"Đó là sách của ai?" }] },
  { char:"同屋",   pinyin:"tóngwū",        pos:"n.",    viet:"bạn cùng phòng",                                     lesson:3, hv:"ĐỒNG ỐC — cùng nhà/phòng", radical:"同(ĐỒNG — cùng) | 屋(ỐC) = 尸(THI — mái nhà cách điệu) + 至(CHÍ — đến) → 'đến dưới một mái' = phòng → bạn cùng phòng" },
  { char:"汉语",   pinyin:"Hànyǔ",         pos:"n.",    viet:"tiếng Hán",                                          lesson:3, hv:"HÁN NGỮ — tiếng Hán/tiếng Trung", radical:"汉(HÁN — dân tộc Hán / sông Hán) — bộ 氵(THỦY — nước) | 语(NGỮ) = 讠(NGÔN — lời) + 吾(NGÔ — chỉ thanh) → ngôn ngữ → tiếng Hán" },
  { char:"课本",   pinyin:"kèběn",         pos:"n.",    viet:"sách giáo khoa, giáo trình",                         lesson:3, hv:"KHÓA BẢN — bản của bài học (sách giáo trình)", radical:"课(KHÓA) = 讠(NGÔN — lời) + 果(QUẢ — chỉ thanh) → bài học | 本(BẢN) = 木(MỘC — cây) + 一 → vạch ở gốc cây = sách/cuốn → sách giáo khoa" },
  { char:"词典",   pinyin:"cídiǎn",        pos:"n.",    viet:"từ điển",                                             lesson:3, hv:"TỪ ĐIỂN — giống hệt tiếng Việt!", radical:"词(TỪ) = 讠(NGÔN — lời) + 司(TƯ — chỉ thanh, gợi 'quản') → từ ngữ | 典(ĐIỂN — sách kinh điển) → 'sách quản từ' = từ điển" },
  { char:"就是",   pinyin:"jiù shì",       pos:"",      viet:"điều đó nghĩa là",                                   lesson:3, hv:"TỰU THỊ — chính là (TỰU = liền/ngay, THỊ = là)", radical:"就 = 京(KINH — kinh đô) + 尤(VƯU — đặc biệt) → đúng tại kinh đô = tức là | 是 = mặt trời thẳng = là" },
  { char:"日语",   pinyin:"Rìyǔ",          pos:"n.",    viet:"tiếng Nhật",                                         lesson:3, hv:"NHẬT NGỮ — tiếng Nhật", radical:"日(NHẬT — mặt trời/Nhật Bản) | 语(NGỮ) = 讠(NGÔN — lời) + 吾(NGÔ — chỉ thanh) → ngôn ngữ → tiếng Nhật" },
  { char:"这",     pinyin:"zhè",           pos:"pron.", viet:"này, đây",                                           lesson:3, hv:"GIÁ — này/đây (đại từ chỉ định gần)", radical:"辶(SƯỚC — di chuyển) + 文(VĂN — chữ/văn) → di chuyển về phía này = này" },
  { char:"杂志",   pinyin:"zázhì",         pos:"n.",    viet:"tạp chí",                                             lesson:3, hv:"TẠP CHÍ — giống hệt tiếng Việt!", radical:"杂(TẠP — pha trộn) | 志(CHÍ — ghi chép) = 士(SĨ — kẻ sĩ) + 心(TÂM — tim) → 'ghi chép pha tạp' = tạp chí" },
  { char:"音乐",   pinyin:"yīnyuè",        pos:"n.",    viet:"âm nhạc",                                            lesson:3, hv:"ÂM NHẠC — giống hệt tiếng Việt!", radical:"音(ÂM — âm thanh) = 立 + 日 | 乐(NHẠC) — tượng hình nhạc cụ có dây trên giá gỗ → âm + nhạc" },
  { char:"朋友",   pinyin:"péngyou",       pos:"n.",    viet:"bạn, bạn bè",                                        lesson:3, hv:"BẰNG HỮU — bạn bè (văn học)", radical:"朋 = hai 月(NGUYỆT — trăng) cạnh nhau → hai trăng kề bên = bạn | 友 = 又(HỰU — tay) + 又 → hai tay nắm = bạn", examples:[{ zh:"她是我的朋友。", vi:"Cô ấy là bạn của tôi." },{ zh:"他也是我的同屋。", vi:"Anh ấy cũng là bạn cùng phòng của tôi." }] },
  { char:"语言",   pinyin:"yǔyán",        pos:"n.",    viet:"ngôn ngữ",                                           lesson:3, hv:"NGỮ NGÔN — = ngôn ngữ (đảo vị trí)", radical:"语 = 讠(NGÔN — lời) + 吾(NGÔ — tôi) → lời của tôi | 言 = 口(KHẨU — miệng) + nét ngang → lời từ miệng = lời nói" },
  { char:"说",     pinyin:"shuō",         pos:"v.",    viet:"nói",                                                 lesson:3, hv:"THUYẾT — nói (như 'thuyết minh', 'tiểu thuyết')", radical:"讠(NGÔN — lời, bộ thủ) + 兑(ĐOÀI — chỉ thanh) → nói" },
  { char:"会",     pinyin:"huì",          pos:"v.",    viet:"biết (qua rèn luyện, học hỏi)",                       lesson:3, hv:"HỘI — biết qua học (như 'lĩnh hội', 'cơ hội')", radical:"亼(tụ tập) + 曰(VIẾT — nói) → người tụ lại để nói = biết/hội", examples:[{ zh:"我会说汉语。", vi:"Tôi biết nói tiếng Trung." },{ zh:"他不会说日语。", vi:"Anh ấy không biết nói tiếng Nhật." }] },
  { char:"本",     pinyin:"běn",          pos:"mw.",   viet:"cuốn, quyển",                                         lesson:3, hv:"BẢN — cuốn/quyển (như 'phiên bản', 'cơ bản')", radical:"木(MỘC — cây) + 一 → vạch tại gốc cây = gốc/quyển (lượng từ)" },
  { char:"喜欢",   pinyin:"xǐhuan",       pos:"v.",    viet:"thích",                                               lesson:3, hv:"HỶ HOAN — vui thích", radical:"喜 = 壴(trống) + 口(KHẨU — miệng) → miệng bên trống = vui | 欢 = 又(HỰU — tay) + 欠(KHIẾM — há miệng) → dang tay đón = vui mừng", examples:[{ zh:"我喜欢听音乐。", vi:"Tôi thích nghe nhạc." },{ zh:"你喜欢看什么杂志？", vi:"Bạn thích đọc tạp chí gì?" }] },
  { char:"看",     pinyin:"kàn",          pos:"v.",    viet:"xem, nhìn, đọc",                                      lesson:3, hv:"KHÁN — xem (như 'khán giả', 'khán đài')", radical:"手(THỦ — tay) trên 目(MỤC — mắt) → tay che mắt nhìn xa = xem" },
  { char:"听",     pinyin:"tīng",         pos:"v.",    viet:"nghe",                                                lesson:3, hv:"THÍNH — nghe (như 'thính giả')", radical:"口(KHẨU — miệng, bộ thủ) + 斤(CÂN — chỉ thanh) → giản thể của 聽 (gốc phức tạp) = nghe" },

  // ── Lesson 4 ──
  { char:"请问",   pinyin:"qǐngwèn",      pos:"v.",    viet:"xin hỏi",                                             lesson:4, hv:"THỈNH VẤN — xin hỏi", radical:"请(THỈNH) = 讠(NGÔN — lời) + 青(THANH — chỉ thanh) → lời lịch sự = xin/mời | 问(VẤN) = 门(MÔN — cửa) + 口(KHẨU — miệng) → miệng hỏi tại cửa = hỏi", examples:[{ zh:"请问，图书馆在哪儿？", vi:"Xin hỏi, thư viện ở đâu?" },{ zh:"请问，您叫什么名字？", vi:"Xin hỏi, ngài tên là gì?" }] },
  { char:"图书馆", pinyin:"túshūguǎn",    pos:"n.",    viet:"thư viện",                                            lesson:4, hv:"ĐỒ THƯ QUÁN — thư viện (lit. 'quán đồ thư')", radical:"图 = 囗(biên) + 冬(họa tiết) → họa tiết khép kín = bản đồ | 书 = bút lông viết = sách | 馆 = 饣(THỰC — ăn) + 官(QUAN — quan) → quán quan tiếp khách = quán/viện" },
  { char:"在",     pinyin:"zài",          pos:"v./adv.", viet:"ở, đang",                                           lesson:4, hv:"TẠI — ở (như 'hiện tại', 'tồn tại')", radical:"才(TÀI — tài năng/tay) + 土(THỔ — đất) → tay cắm xuống đất = ở/đang", examples:[{ zh:"图书馆在学校的左边。", vi:"Thư viện ở bên trái trường học." },{ zh:"宿舍在哪儿？", vi:"Ký túc xá ở đâu?" }] },
  { char:"哪儿",   pinyin:"nǎr",          pos:"pron.", viet:"ở đâu, chỗ nào",                                      lesson:4, hv:"NA NHI — ở đâu", radical:"口(KHẨU — miệng) + 那(kia) → giống 哪, hỏi 'nơi nào?' (儿 = hậu tố Bắc Kinh)" },
  { char:"哪里",   pinyin:"nǎli",         pos:"pron.", viet:"ở đâu, chỗ nào",                                      lesson:4, hv:"NA LÝ — ở đâu", radical:"哪 = hỏi 'nào' | 里 = 田(ĐIỀN — ruộng) + 土(THỔ — đất) → trong làng = trong/nơi" },
  { char:"对不起", pinyin:"duìbuqǐ",      pos:"v.",    viet:"xin lỗi",                                             lesson:4, hv:"ĐỐI BẤT KHỞI — xin lỗi (lit. 'không thể đối lại')", radical:"对 = 又(HỰU — tay) + 寸(THỐN — tấc) → tay chính xác = đối/đối diện | 不 = phủ định | 起 = 走(TẨU — đi) + 己(KỶ — mình) → mình đứng dậy = khởi" },
  { char:"个",     pinyin:"gè",           pos:"mw.",   viet:"lượng từ chung (cho người, đồ vật)",                 lesson:4, hv:"CÁ — lượng từ chung (như 'cá nhân')", radical:"亻(NHÂN — người) + 丨(nét dọc) → đơn vị một người — lượng từ chung" },
  { char:"学校",   pinyin:"xuéxiào",      pos:"n.",    viet:"trường học",                                          lesson:4, hv:"HỌC HIỆU — trường học", radical:"学(HỌC) = đứa trẻ dưới mái học chữ | 校(HIỆU) = 木(MỘC — gỗ, bộ thủ) + 交(GIAO — chỉ thanh) → công trình gỗ học tập = trường" },
  { char:"知道",   pinyin:"zhīdào",       pos:"v.",    viet:"biết",                                                lesson:4, hv:"TRI ĐẠO — biết (như 'tri thức')", radical:"知 = 矢(THỈ — mũi tên) + 口(KHẨU — miệng) → lời thẳng như tên = biết | 道 = 辶(SƯỚC — di chuyển) + 首(THỦ — đầu) → đầu dẫn đường = đường/đạo", examples:[{ zh:"你知道图书馆在哪儿吗？", vi:"Bạn có biết thư viện ở đâu không?" },{ zh:"我不知道。", vi:"Tôi không biết." }] },
  { char:"没关系", pinyin:"méi guānxi",   pos:"",      viet:"không sao, không có gì",                              lesson:4, hv:"MỘT QUAN HỆ — không sao (lit. 'không có quan hệ gì')", radical:"没 = không có | 关(QUAN — liên quan, đóng/mở) | 系(HỆ) = 纟(MỊCH — sợi) → mối nối → 'không có quan hệ' = không sao" },
  { char:"这儿",   pinyin:"zhèr",         pos:"pron.", viet:"chỗ này, nơi này",                                    lesson:4, hv:"GIÁ NHI — chỗ này", radical:"这 = di chuyển về này = này (儿 = hậu tố Bắc Kinh)" },
  { char:"这里",   pinyin:"zhèli",        pos:"pron.", viet:"chỗ này, nơi này",                                    lesson:4, hv:"GIÁ LÝ — chỗ này", radical:"这 = này | 里 = trong/nơi → nơi này" },
  { char:"教学",   pinyin:"jiàoxué",      pos:"n.",    viet:"dạy học",                                             lesson:4, hv:"GIÁO HỌC — giống hệt tiếng Việt!", radical:"教 = 爻(học vấn) + 子(TỬ — con) + 攴(gõ nhẹ) → gõ nhắc trẻ học = dạy | 学 = đứa trẻ dưới mái học" },
  { char:"楼",     pinyin:"lóu",          pos:"n.",    viet:"tòa nhà",                                             lesson:4, hv:"LÂU — tòa nhà (như 'lâu đài', 'cao lâu')", radical:"木(MỘC — gỗ, bộ thủ) + 娄(LÂU — chỉ thanh) → công trình gỗ nhiều tầng = lầu/tầng", examples:[{ zh:"那个楼是教学楼。", vi:"Tòa nhà đó là tòa nhà giảng dạy." }] },
  { char:"那儿",   pinyin:"nàr",          pos:"pron.", viet:"chỗ kia, nơi kia",                                    lesson:4, hv:"NA NHI — chỗ kia", radical:"那 = đó/kia (儿 = hậu tố Bắc Kinh)" },
  { char:"那里",   pinyin:"nàli",         pos:"pron.", viet:"chỗ kia, nơi kia",                                    lesson:4, hv:"NA LÝ — chỗ kia", radical:"那 = đó | 里 = nơi → nơi đó" },
  { char:"宿舍",   pinyin:"sùshè",        pos:"n.",    viet:"ký túc xá",                                           lesson:4, hv:"TÚC XÁ — giống hệt tiếng Việt!", radical:"宿(TÚC — trú đêm) = 宀(MIÊN — mái) + 亻(NHÂN — người) + 百(BÁCH — trăm) → 'nhiều người dưới một mái' | 舍(XÁ — nhà trọ giản đơn) → ký túc xá" },
  { char:"北边",   pinyin:"běibian",      pos:"n.",    viet:"phía bắc",                                            lesson:4, hv:"BẮC BIÊN — phía bắc", radical:"北 = hai người đứng quay lưng → quay đi = bắc | 边 = 辶(SƯỚC — di chuyển) + 力(LỰC — sức) → cạnh/phía" },
  { char:"左边",   pinyin:"zuǒbian",      pos:"n.",    viet:"bên trái",                                            lesson:4, hv:"TẢ BIÊN — bên trái", radical:"左 = 工(CÔNG — thợ) + 手(THỦ — tay) → tay làm việc (theo lịch sử là tay trái) | 边 = phía" },
  { char:"右边",   pinyin:"yòubian",      pos:"n.",    viet:"bên phải",                                            lesson:4, hv:"HỮU BIÊN — bên phải", radical:"右 = 口(KHẨU — miệng) + 手(THỦ — tay) → tay ăn/nói (theo lịch sử là tay phải) | 边 = phía" },
  { char:"上边",   pinyin:"shàngbian",    pos:"n.",    viet:"phía trên",                                           lesson:4, hv:"THƯỢNG BIÊN — phía trên", radical:"上(THƯỢNG) = vạch trên đường ngang → trên/phía trên | 边 = phía" },
  { char:"下边",   pinyin:"xiàbian",      pos:"n.",    viet:"phía dưới",                                           lesson:4, hv:"HẠ BIÊN — phía dưới", radical:"下(HẠ) = vạch dưới đường ngang → dưới/phía dưới | 边 = phía" },
  { char:"不用谢", pinyin:"búyòng xiè",   pos:"",      viet:"không cần cảm ơn, không có gì",                       lesson:4, hv:"BẤT DỤNG TẠ — không cần cảm tạ", radical:"不(BẤT — không) | 用(DỤNG — cần dùng) | 谢(TẠ — cảm ơn) = 讠(NGÔN — lời) + 射(XẠ — chỉ thanh) → 'không cần tạ' = không có gì" },
  { char:"不用",   pinyin:"búyòng",       pos:"adv.",  viet:"không cần",                                           lesson:4, hv:"BẤT DỤNG — không cần", radical:"不(BẤT — không) | 用(DỤNG — dùng/cần) → không cần" },
  { char:"对",     pinyin:"duì",          pos:"adj.",  viet:"đúng",                                                lesson:4, hv:"ĐỐI — đúng (như 'đối phó', 'đối với')", radical:"又(HỰU — tay) + 寸(THỐN — tấc) → đo lường chính xác = đúng/đối diện" },

  // ── Lesson 5 ──
  { char:"有",     pinyin:"yǒu",          pos:"v.",    viet:"có",                                                  lesson:5, hv:"HỮU — có (giống tiếng Việt!)", radical:"月(NGUYỆT — trăng) + 又(HỰU — tay) → tay nắm trăng = có", examples:[{ zh:"学校有图书馆。", vi:"Trường học có thư viện." },{ zh:"我没有空儿。", vi:"Tôi không có thời gian rảnh." }] },
  { char:"有用",   pinyin:"yǒuyòng",      pos:"adj.",  viet:"có ích, hữu dụng",                                    lesson:5, hv:"HỮU DỤNG — giống hệt tiếng Việt!", radical:"有 = có | 用(DỤNG) = dụng cụ = dùng → có ích" },
  { char:"有名",   pinyin:"yǒumíng",      pos:"adj.",  viet:"nổi tiếng",                                           lesson:5, hv:"HỮU DANH — có danh tiếng", radical:"有 = có | 名 = 夕(TỊCH — chiều tối) + 口(KHẨU — miệng) → gọi tên trong tối = nổi danh" },
  { char:"空儿",   pinyin:"kòngr",        pos:"n.",    viet:"thời gian rảnh, lúc rảnh",                            lesson:5, hv:"KHÔNG — trống, rảnh (như 'không khí', 'không gian')", radical:"空(KHÔNG) = 穴(HUYỆT — hang) + 工(CÔNG — chỉ thanh) → khoảng trống = rảnh/trống" },
  { char:"时候",   pinyin:"shíhou",       pos:"n.",    viet:"lúc, khi, thời gian",                                 lesson:5, hv:"THỜI HẦU — lúc/khi", radical:"时(THỜI) = 日(NHẬT — mặt trời) + 寺(TỰ — chỉ thanh) → mặt trời / thời gian | 候(HẦU) = 亻(NHÂN — người) + chỉ thanh → 'người đợi thời gian' = lúc/khoảnh khắc" },
  { char:"欢迎",   pinyin:"huānyíng",     pos:"v.",    viet:"hoan nghênh, chào đón",                               lesson:5, hv:"HOAN NGHÊNH — giống hệt tiếng Việt!", radical:"欢 = 又(HỰU — tay) + 欠(KHIẾM — há miệng) → dang tay đón = vui | 迎 = 辶(SƯỚC — di chuyển) + 卬(người ngước nhìn) → ra đón = nghênh", examples:[{ zh:"欢迎你来中国！", vi:"Chào đón bạn đến Trung Quốc!" }] },
  { char:"去",     pinyin:"qù",           pos:"v.",    viet:"đi",                                                  lesson:5, hv:"KHỨ — đi (trong 'quá khứ')", radical:"土(THỔ — đất) + 厶(TƯ — riêng/rời) → 'rời đất ra đi' = đi", examples:[{ zh:"我去图书馆。", vi:"Tôi đi thư viện." },{ zh:"你去哪儿？", vi:"Bạn đi đâu?" }] },
  { char:"玩儿",   pinyin:"wánr",         pos:"v.",    viet:"chơi",                                                lesson:5, hv:"NGOẠN — chơi (như 'ngoạn mục', 'du ngoạn')", radical:"玩(NGOẠN) = 王(VƯƠNG/NGỌC — bộ ngọc, gợi 'vật quý') + 元(NGUYÊN — chỉ thanh) → chơi (xưa quý tộc chơi ngọc)" },
  { char:"卫生间", pinyin:"wèishēngjiān", pos:"n.",    viet:"nhà vệ sinh",                                         lesson:5, hv:"VỆ SINH GIAN — giống tiếng Việt!", radical:"卫 = 行(HÀNH — đi) + 口 → bảo vệ di chuyển = vệ | 生(SINH) = sinh sôi = vệ sinh | 间 = 门(MÔN — cửa) + 日(NHẬT — mặt trời) → ánh sáng qua cửa = phòng/khoảng" },
  { char:"教室",   pinyin:"jiàoshì",      pos:"n.",    viet:"phòng học, lớp học",                                  lesson:5, hv:"GIÁO THẤT — phòng học", radical:"教(GIÁO — dạy, gõ nhắc trẻ học) | 室(THẤT — phòng) = 宀(MIÊN — mái) + 至(CHÍ — đến) → 'phòng để dạy' = lớp học" },
  { char:"旁边",   pinyin:"pángbiān",     pos:"n.",    viet:"bên cạnh",                                            lesson:5, hv:"BÀNG BIÊN — bên cạnh", radical:"旁(BÀNG — bên cạnh) | 边(BIÊN — cạnh/phía) → 'bàng biên' = phía bên cạnh" },
  { char:"西边",   pinyin:"xībiān",       pos:"n.",    viet:"phía tây",                                            lesson:5, hv:"TÂY BIÊN — phía tây", radical:"西(TÂY) — tượng hình chim đậu vào tổ lúc hoàng hôn = hướng tây | 边 = cạnh/phía" },
  { char:"小",     pinyin:"xiǎo",         pos:"adj.",  viet:"nhỏ, bé",                                             lesson:5, hv:"TIỂU — nhỏ (như 'tiểu học', 'tiểu thuyết')", radical:"nét giữa với hai chấm hai bên — trông nhỏ = nhỏ" },
  { char:"中",     pinyin:"zhōng",        pos:"adj.",  viet:"vừa, trung bình",                                     lesson:5, hv:"TRUNG — giữa (như 'trung học', 'trung tâm')", radical:"nét dọc xuyên giữa hình chữ nhật = giữa/trung tâm" },
  { char:"大",     pinyin:"dà",           pos:"adj.",  viet:"to, lớn",                                             lesson:5, hv:"ĐẠI — lớn (như 'đại học', 'đại sứ')", radical:"人(NHÂN — người) dang tay rộng = to/lớn", examples:[{ zh:"这是大教室。", vi:"Đây là phòng học lớn." },{ zh:"图书馆很大。", vi:"Thư viện rất lớn." }] },
  { char:"没有",   pinyin:"méiyǒu",       pos:"v.",    viet:"không có",                                            lesson:5, hv:"MỘT HỮU — phủ định của 有 (có)", radical:"没 = 氵(THỦY — nước) + 殳 → bị chìm = không/thiếu | 有 = có → không có" },
  { char:"北京",   pinyin:"Běijīng",      pos:"n.",    viet:"Bắc Kinh",                                            lesson:5, hv:"BẮC KINH — giống hệt tiếng Việt!", radical:"北 = hai người quay lưng = bắc | 京(KINH) = 亠 + 口 + 小 → tòa nhà cao trong kinh đô" },

  // ── Lesson 6 ──
  { char:"一",     pinyin:"yī (yāo khi đọc số)", pos:"num.",  viet:"một, 1 (đọc 'yāo' khi đọc rời từng chữ số trong số điện thoại / mã số — xem B8-NP8)", lesson:6, hv:"NHẤT — một (như 'nhất quán', 'thứ nhất')", radical:"một nét ngang đơn = một" },
  { char:"二",     pinyin:"èr",           pos:"num.",  viet:"hai, 2",                                              lesson:6, hv:"NHỊ — hai (như 'nhị thập', 'thứ nhị')", radical:"hai nét ngang = hai" },
  { char:"三",     pinyin:"sān",          pos:"num.",  viet:"ba, 3",                                               lesson:6, hv:"TAM — ba (như 'tam giác', 'tam quốc')", radical:"ba nét ngang = ba" },
  { char:"四",     pinyin:"sì",           pos:"num.",  viet:"bốn, 4",                                              lesson:6, hv:"TỨ — bốn (như 'tứ giác', 'tứ phương')", radical:"囗(biên) + 儿(hai chân) → bốn chân trong hộp = bốn" },
  { char:"五",     pinyin:"wǔ",           pos:"num.",  viet:"năm, 5",                                              lesson:6, hv:"NGŨ — năm (như 'ngũ vị', 'ngũ hành')", radical:"tiến hóa từ vạch đếm 5 nét" },
  { char:"六",     pinyin:"liù",          pos:"num.",  viet:"sáu, 6",                                              lesson:6, hv:"LỤC — sáu (như 'lục địa', 'lục giác')", radical:"亠(chấm trên) + 八(BÁT — chia/tám) → hình của số sáu" },
  { char:"七",     pinyin:"qī",           pos:"num.",  viet:"bảy, 7",                                              lesson:6, hv:"THẤT — bảy (như 'thất bại', 'thất tịch')", radical:"nhìn như số 7 ngược — neo thị giác đơn giản" },
  { char:"八",     pinyin:"bā",           pos:"num.",  viet:"tám, 8",                                              lesson:6, hv:"BÁT — tám (như 'bát giác')", radical:"hai nét tách ra = chia/tám" },
  { char:"九",     pinyin:"jiǔ",          pos:"num.",  viet:"chín, 9",                                             lesson:6, hv:"CỬU — chín (như 'cửu vạn')", radical:"nét móc đơn = gần mười = chín" },
  { char:"十",     pinyin:"shí",          pos:"num.",  viet:"mười, 10",                                            lesson:6, hv:"THẬP — mười (như 'thập kỷ', 'thập niên')", radical:"chữ thập hoàn chỉnh = mười (đối xứng)" },
  { char:"两",     pinyin:"liǎng",        pos:"num.",  viet:"hai (dùng trước lượng từ)",                           lesson:6, hv:"LƯỠNG — hai (như 'lưỡng tính', 'lưỡng cực')", radical:"一 + 冂(khung) + 2 人 bên trong → hai người trong khung = hai (dùng trước lượng từ)" },
  { char:"零",     pinyin:"líng",         pos:"num.",  viet:"số không, 0",                                         lesson:6, hv:"LINH — số 0", radical:"雨(VŨ — mưa) + 令(LỆNH) → giọt mưa rải rác = số không/lẻ" },
  { char:"百",     pinyin:"bǎi",          pos:"num.",  viet:"trăm, 100",                                           lesson:6, hv:"BÁCH — trăm (như 'bách khoa', 'bách phân')", radical:"一(NHẤT — một) + 白(BẠCH — chỉ thanh) → ký hiệu chỉ số đếm = trăm" },
  { char:"点",     pinyin:"diǎn",         pos:"n.",    viet:"giờ (đơn vị thời gian)",                              lesson:6, hv:"ĐIỂM — giờ (điểm trên đồng hồ)", radical:"灬(HỎA — chấm lửa, bộ thủ) + 占(CHIẾM — chỉ thanh) → chấm nhỏ trên mặt đồng hồ = giờ/điểm" },
  { char:"分",     pinyin:"fēn",          pos:"n.",    viet:"phút",                                                lesson:6, hv:"PHÂN — phút (chia nhỏ giờ)", radical:"八(BÁT — chia) + 刀(ĐAO — dao) → dao chia = phút/phần" },
  { char:"半",     pinyin:"bàn",          pos:"n.",    viet:"rưỡi (30 phút), một nửa",                             lesson:6, hv:"BÁN — nửa (như 'bán cầu', 'bán đảo')", radical:"八(BÁT — chia) + 丷 + 十(THẬP — mười) → mười chia đôi = nửa/30 phút" },
  { char:"刻",     pinyin:"kè",           pos:"n.",    viet:"khắc (15 phút)",                                      lesson:6, hv:"KHẮC — giống hệt tiếng Việt!", radical:"刂/刀(ĐAO — dao, bộ thủ) + 亥(HỢI — chỉ thanh, không liên quan heo) → dao khắc dấu = khắc / 15 phút" },
  { char:"差",     pinyin:"chà",          pos:"v.",    viet:"thiếu, kém",                                          lesson:6, hv:"SAI — thiếu, chênh lệch (như 'sai số')", radical:"羊(DƯƠNG — cừu) bị lệch + 工(CÔNG — chỉ thanh) → 'cừu lạc đàn' = sai/thiếu/lệch" },
  { char:"早",     pinyin:"zǎo",          pos:"adj./n.", viet:"sớm; buổi sáng (như 早上)",                          lesson:6, hv:"TẢO — sớm (như 'tảo hôn')", radical:"日(NHẬT — mặt trời) + 十(THẬP — mười) → mặt trời vừa nhú trên đường chân trời = sớm/sáng" },
  { char:"几",     pinyin:"jǐ",           pos:"pron.", viet:"mấy, bao nhiêu (như 几点)",                            lesson:6, hv:"KỶ — mấy/bao nhiêu (số lượng nhỏ)", radical:"hình bàn nhỏ chân cong = mấy/bao nhiêu" },
  { char:"上课",   pinyin:"shàngkè",      pos:"v.",    viet:"vào lớp, đi học",                                     lesson:6, hv:"THƯỢNG KHÓA — lên lớp", radical:"上(THƯỢNG) = vạch trên = lên/bắt đầu | 课(KHÓA) = 讠(NGÔN — lời) + 果(QUẢ — quả) → bài học có kết quả → đi lên lớp" },
  { char:"下课",   pinyin:"xiàkè",        pos:"v.",    viet:"tan học, hết tiết",                                   lesson:6, hv:"HẠ KHÓA — xuống lớp", radical:"下(HẠ) = vạch dưới = xuống/kết thúc | 课(KHÓA) = bài học → lớp xuống/giải tán" },
  { char:"部分",   pinyin:"bùfèn",        pos:"n.",    viet:"phần (như 大部分 = phần lớn)",                          lesson:6, hv:"BỘ PHẬN — giống hệt tiếng Việt!", radical:"部(BỘ — bộ phận, nhóm) | 分(PHÂN) = 八(BÁT — chia) + 刀(ĐAO — dao) → 'một bộ chia ra' = phần" },
  { char:"讲座",   pinyin:"jiǎngzuò",     pos:"n.",    viet:"bài giảng, buổi diễn giảng",                          lesson:6, hv:"GIẢNG TỌA — bài giảng (chỗ giảng)", radical:"讲(GIẢNG) = 讠(NGÔN — lời) + chỉ thanh → giảng giải | 座(TỌA) = 广(NGHIỄM — mái) + 坐(TỌA — ngồi) → 'chỗ ngồi nghe giảng' = bài giảng/buổi giảng" },
  { char:"太",     pinyin:"tài",          pos:"adv.",  viet:"quá (dùng trong 太……了)",                              lesson:6, hv:"THÁI — quá (như 'thái quá')", radical:"大(ĐẠI — lớn) + 丶(chấm) → lớn cộng thêm chút nữa = quá", examples:[{ zh:"太好了！", vi:"Tuyệt quá!" },{ zh:"这本书太大了。", vi:"Cuốn sách này quá to." }] },
  { char:"开始",   pinyin:"kāishǐ",       pos:"v.",    viet:"bắt đầu",                                             lesson:6, hv:"KHAI THỦY — mở đầu", radical:"开(KHAI — mở) = hai tay đẩy cánh cửa mở | 始(THỦY) = 女(NỮ — bộ nữ, gốc gắn với sinh nở) + 台(ĐÀI — chỉ thanh) → khởi đầu → 'mở + khởi' = bắt đầu" },
  { char:"现在",   pinyin:"xiànzài",      pos:"n./adv.", viet:"bây giờ, hiện tại",                                 lesson:6, hv:"HIỆN TẠI — giống hệt tiếng Việt!", radical:"现(HIỆN) = 王(VƯƠNG/NGỌC — bộ ngọc) + 见(KIẾN — thấy) → 'ngọc lộ ra trước mắt' = hiện ra | 在(TẠI — đang ở) → 'hiện đang' = bây giờ", examples:[{ zh:"现在几点？", vi:"Bây giờ mấy giờ?" },{ zh:"现在开始上课。", vi:"Bây giờ bắt đầu vào lớp." }] },
  { char:"一会儿", pinyin:"yíhuìr",       pos:"q.",    viet:"một lát, một chốc",                                   lesson:6, hv:"NHẤT HỘI — một lát", radical:"一(NHẤT — một) + 会(HỘI — gặp/khoảnh khắc) + 儿(hậu tố) → 'một thoáng' = một lát" },
  { char:"见",     pinyin:"jiàn",         pos:"v.",    viet:"gặp, thấy",                                           lesson:6, hv:"KIẾN — thấy/gặp (như 'kiến thức', 'tái kiến')", radical:"目(MỤC — mắt) + 儿(hai chân) → mắt có chân đi gặp = thấy/gặp" },
  { char:"晚",     pinyin:"wǎn",          pos:"adj./n.", viet:"muộn, tối; buổi tối (như 晚上)",                     lesson:6, hv:"VÃN — muộn (như 'vãn cảnh')", radical:"日(NHẬT — mặt trời) + 免(MIỄN — chỉ thanh, gợi 'lánh đi') → mặt trời đã lánh xuống = muộn/tối" },
  { char:"午",     pinyin:"wǔ",           pos:"n.",    viet:"giữa trưa, giờ ngọ (trong 上午/中午/下午)",              lesson:6, hv:"NGỌ — giữa trưa (như 'giờ ngọ', 'chính ngọ')", radical:"tượng hình chày — dùng giã gạo lúc trưa = giờ ngọ/giữa trưa" },
  { char:"吃",     pinyin:"chī",          pos:"v.",    viet:"ăn",                                                  lesson:6, hv:"KHIẾT — ăn (HV ít dùng)", radical:"口(KHẨU — miệng, bộ thủ) + 乞(KHẤT — chỉ thanh) → hành động của miệng = ăn" },
  { char:"饭",     pinyin:"fàn",          pos:"n.",    viet:"cơm, bữa ăn",                                         lesson:6, hv:"PHẠN — cơm (như 'phạn điếm')", radical:"饣(THỰC — đồ ăn, bộ thủ) + 反(PHẢN — chỉ thanh) → đồ ăn = cơm/bữa" },
  { char:"吃饭",   pinyin:"chī fàn",      pos:"v.",    viet:"ăn cơm, dùng bữa",                                    lesson:6, hv:"KHIẾT PHẠN — ăn cơm", radical:"吃 = miệng xin ăn = ăn | 饭 = cơm chín = cơm → ăn cơm", examples:[{ zh:"我们现在吃饭。", vi:"Chúng ta ăn cơm bây giờ." },{ zh:"他一会儿来吃饭。", vi:"Anh ấy lát nữa đến ăn cơm." }] },
  { char:"睡觉",   pinyin:"shuìjiào",     pos:"v.",    viet:"đi ngủ, ngủ (động từ tách rời: 睡 + 觉)",               lesson:6, hv:"THỤY GIÁC — ngủ (觉 = giấc; tách 早/午/晚 vào giữa)", radical:"睡 = 目(MỤC — mắt) + 垂(THÙY — rũ xuống) → mắt rũ xuống = buồn ngủ | 觉 = 爫(trảo — móng tay) + 冖 + 见(KIẾN — thấy) → cảm giác/giấc → kết hợp: ngủ-cảm giác = đi ngủ", examples:[{ zh:"你几点睡觉？", vi:"Bạn mấy giờ đi ngủ?" },{ zh:"我十点睡觉。", vi:"Tôi đi ngủ lúc 10 giờ." }] },
  { char:"再",     pinyin:"zài",          pos:"adv.",  viet:"lại, một lần nữa, tiếp (như 再见, 再说)",                lesson:6, hv:"TÁI — lại (như 'tái phát', 'tái diễn')", radical:"一 + 冂 + 土 → một lớp xếp chồng thêm = lại" },
  { char:"再见",   pinyin:"zàijiàn",      pos:"v./int.", viet:"tạm biệt (lit. 'gặp lại')",                          lesson:6, hv:"TÁI KIẾN — gặp lại (lời chia tay)", radical:"再 = lại | 见 = mắt có chân đi gặp → gặp lại = tạm biệt" },

  // ── Lesson 7 ──
  // General / misc
  { char:"课",     pinyin:"kè",           pos:"n.",    viet:"bài học, tiết học",                                   lesson:7, hv:"KHÓA — như 'khóa học'", radical:"讠(NGÔN — lời, bộ thủ) + 果(QUẢ — chỉ thanh) → bài học/lớp" },
  { char:"班",     pinyin:"bān",          pos:"n.",    viet:"ban, lớp, ca làm việc",                                lesson:7, hv:"BAN — như 'ban điều hành', 'ban giám hiệu'", radical:"王 + 刂(ĐAO — dao) + 王 → tượng hình mảnh ngọc bị tách bằng dao → chia thành nhóm = ban/lớp" },
  { char:"上班",   pinyin:"shàngbān",     pos:"v.",    viet:"đi làm, bắt đầu ca làm (động từ tách rời)",            lesson:7, hv:"THƯỢNG BAN — lên ca (cùng họ với 上课 = vào lớp)", radical:"上(THƯỢNG) = lên/vào | 班(BAN) = ban/ca → 'lên ca' = đi làm" },
  { char:"下班",   pinyin:"xiàbān",       pos:"v.",    viet:"tan làm, hết ca (động từ tách rời)",                   lesson:7, hv:"HẠ BAN — xuống ca (cùng họ với 下课 = tan học)", radical:"下(HẠ) = xuống/kết thúc | 班(BAN) = ban/ca → 'xuống ca' = tan làm" },
  { char:"件",     pinyin:"jiàn",         pos:"q.",    viet:"lượng từ (cho 事, 衣服...)",                            lesson:7, hv:"KIỆN — như 'kiện hàng', 'sự kiện'", radical:"亻(NHÂN — bộ người, chỉ vật/sự) + 牛(NGƯU — chỉ thanh, không liên quan nghĩa 'bò') → lượng từ cho việc, đồ rời" },
  { char:"事",     pinyin:"shì",          pos:"n.",    viet:"việc, chuyện",                                         lesson:7, hv:"SỰ — như 'sự việc', 'sự kiện'", radical:"tượng hình tay cầm cờ/bút lông — vốn chỉ chức vụ → việc/sự" },
  { char:"可是",   pinyin:"kěshi",        pos:"conj.", viet:"nhưng, tuy nhiên",                                     lesson:7, hv:"KHẢ THỊ — HV ít dùng", radical:"可(KHẢ — có thể) | 是(THỊ — là, đúng) → 'có thể là vậy nhưng...' = nhưng/tuy nhiên" },
  { char:"没问题", pinyin:"méi wèntí",    pos:"",      viet:"không có vấn đề",                                      lesson:7, hv:"MỘT VẤN ĐỀ — giống tiếng Việt!", radical:"没 = 氵(THỦY — nước) + 殳 → bị chìm = không có | 问(VẤN) = 门(MÔN — cửa) + 口(KHẨU — miệng) → miệng hỏi tại cửa = hỏi | 题(ĐỀ) = 是(THỊ — đúng) + 页(HIỆT — trang/đầu) → chủ đề trên trang = vấn đề" },
  { char:"钥匙",   pinyin:"yàoshi",       pos:"n.",    viet:"chìa khóa",                                            lesson:7, hv:"THƯỢC THI — HV ít dùng", radical:"钥(THƯỢC) = 钅(KIM — kim loại) → mảnh kim loại mở khóa | 匙(THI) = 匕(THUỶ — thìa) → vật giống chiếc thìa nhỏ → chìa khóa" },
  { char:"里",     pinyin:"lǐ",           pos:"n.",    viet:"trong, bên trong",                                     lesson:7, hv:"LÝ — trong (như 'nội lý')", radical:"田(ĐIỀN — ruộng) + 土(THỔ — đất) → trong làng/đồng = trong/bên trong" },
  { char:"外",     pinyin:"wài",          pos:"n.",    viet:"ngoài, bên ngoài",                                     lesson:7, hv:"NGOẠI — ngoài (như 'ngoại lai', 'ngoại quốc')", radical:"夕(TỊCH — chiều tối) + 卜(BỐC — bói toán) → 'bói lúc chiều tối, ra ngoài cửa' = ngoài/bên ngoài" },
  { char:"上",     pinyin:"shàng",        pos:"n.",    viet:"trên, phía trên",                                      lesson:7, hv:"THƯỢNG — trên (như 'thượng đẳng', 'thượng nguồn')", radical:"vạch nhỏ phía trên đường ngang → trên/phía trên" },
  { char:"下",     pinyin:"xià",          pos:"n.",    viet:"dưới, phía dưới",                                      lesson:7, hv:"HẠ — dưới (như 'hạ giới', 'hạ tầng')", radical:"vạch nhỏ phía dưới đường ngang → dưới/phía dưới" },
  { char:"前",     pinyin:"qián",         pos:"n.",    viet:"trước, phía trước",                                    lesson:7, hv:"TIỀN — trước (như 'tiền tuyến', 'tiền nhân')", radical:"chữ gốc 歬 = 止(CHỈ — chân) + 舟(CHU — thuyền) → 'chân trên thuyền tiến tới' = phía trước" },
  { char:"后",     pinyin:"hòu",          pos:"n.",    viet:"sau, phía sau",                                        lesson:7, hv:"HẬU — sau (như 'hậu phương', 'hậu trường')", radical:"chữ giản thể của 後 (HẬU) — chỉ phía sau / sau lưng" },
  { char:"后边",   pinyin:"hòubian",      pos:"n.",    viet:"phía sau",                                             lesson:7, hv:"HẬU BIÊN — phía sau (hậu=sau)", radical:"后(HẬU — phía sau, như 'hậu phương') | 边(BIÊN — cạnh/phía) → phía sau" },
  { char:"和",     pinyin:"hé",           pos:"conj./prep.", viet:"và, với (liên từ)",                              lesson:7, hv:"HÒA — như 'hòa bình', 'hòa hợp'", radical:"禾(HÒA — lúa) + 口(KHẨU — miệng) → cùng ăn lúa = hòa thuận/và/với" },
  { char:"跟",     pinyin:"gēn",          pos:"prep.", viet:"cùng với, theo (giới từ)",                             lesson:7, hv:"CĂN — HV ít dùng (gốc/theo)", radical:"足(TÚC — chân, bộ thủ) + 艮(CẤN — chỉ thanh) → chân theo sau = theo/cùng" },
  { char:"听说",   pinyin:"tīngshuō",     pos:"v.",    viet:"nghe nói",                                             lesson:7, hv:"THÍNH THUYẾT — nghe người ta nói", radical:"听 = 口(KHẨU — miệng) + 斤(CÂN — rìu) → tai nghe sắc bén = nghe | 说 = 讠(NGÔN — lời) + 兑(ĐOÀI — đổi) → trao đổi lời = nói → 'nghe-nói' = nghe nói/người ta đồn" },
  { char:"当然",   pinyin:"dāngrán",      pos:"adv.",  viet:"tất nhiên, dĩ nhiên",                                  lesson:7, hv:"ĐƯƠNG NHIÊN — giống hệt tiếng Việt!", radical:"当(ĐƯƠNG — nên/đáng) | 然(NHIÊN — như vậy) → 'nên là vậy' = đương nhiên (HV trùng tiếng Việt!)" },
  { char:"吧",     pinyin:"ba",           pos:"part.", viet:"trợ từ gợi ý, yêu cầu",                                lesson:7, hv:"BA — HV ít dùng", radical:"口(KHẨU — miệng) + 巴(BA — phiên âm) → trợ từ dịu giọng từ miệng = đề nghị/yêu cầu" },

  // Time / day (chronological)
  { char:"昨天",   pinyin:"zuótiān",      pos:"n.",    viet:"hôm qua",                                              lesson:7, hv:"TẠC THIÊN — ngày hôm qua (tạc=qua)", radical:"昨(TẠC) = 日(NHẬT — mặt trời) + 乍(SẠ — thoáng) → 'mặt trời vừa qua' = hôm qua | 天(THIÊN) = trời/ngày → 'ngày đã qua' = hôm qua" },
  { char:"今天",   pinyin:"jīntiān",      pos:"n.",    viet:"hôm nay",                                              lesson:7, hv:"KIM THIÊN — ngày nay (kim=nay)", radical:"今(KIM — nay) | 天(THIÊN — trời/ngày) → 'ngày nay' = hôm nay", examples:[{ zh:"今天我有课。", vi:"Hôm nay tôi có tiết học." },{ zh:"今天没有时间。", vi:"Hôm nay không có thời gian." }] },
  { char:"明天",   pinyin:"míngtiān",     pos:"n.",    viet:"ngày mai",                                            lesson:7, hv:"MINH THIÊN — ngày sáng (minh=sáng, thiên=trời/ngày)", radical:"明 = 日(NHẬT — mặt trời) + 月(NGUYỆT — trăng) → mặt trời và mặt trăng = sáng/rõ | 天 = 一(vạch trên) + 大(ĐẠI — to/người) → trên đầu người = trời/ngày" },
  { char:"上午",   pinyin:"shàngwǔ",      pos:"n.",    viet:"buổi sáng",                                            lesson:7, hv:"THƯỢNG NGỌ — trước giờ ngọ", radical:"上(THƯỢNG) = vạch trên = trước | 午(NGỌ) = chày giã gạo lúc trưa → 'trước giờ ngọ' = buổi sáng", examples:[{ zh:"我上午八点上课。", vi:"Tôi vào lớp lúc 8 giờ sáng." },{ zh:"上午没有课，下午有课。", vi:"Buổi sáng không có tiết, buổi chiều có tiết." }] },
  { char:"下午",   pinyin:"xiàwǔ",        pos:"n.",    viet:"buổi chiều",                                           lesson:7, hv:"HẠ NGỌ — sau giờ ngọ", radical:"下(HẠ) = vạch dưới = sau | 午(NGỌ) = giờ trưa → 'sau giờ ngọ' = buổi chiều" },
  { char:"晚上",   pinyin:"wǎnshang",     pos:"n.",    viet:"buổi tối",                                             lesson:7, hv:"VÃN THƯỢNG — trên buổi tối", radical:"晚(VÃN) = 日(NHẬT — mặt trời) + 免(MIỄN — thỏ chạy) → mặt trời đuổi thỏ (hoàng hôn) = muộn/tối | 上(THƯỢNG) = trên/lên → 'trên buổi tối' = đêm" },
  { char:"时间",   pinyin:"shíjiān",      pos:"n.",    viet:"thời gian",                                            lesson:7, hv:"THỜI GIAN — giống hệt tiếng Việt!", radical:"时(THỜI) = 日(NHẬT — mặt trời) + 寺(TỰ — chùa) → mặt trời tại chùa (đo bằng chuông) = thời gian | 间(GIAN) = 门(MÔN — cửa) + 日(NHẬT) → ánh sáng qua cửa = khoảng/giữa → 'khoảng thời gian' = thời lượng" },

  // Entertainment
  { char:"电影",   pinyin:"diànyǐng",     pos:"n.",    viet:"phim, điện ảnh",                                       lesson:7, hv:"ĐIỆN ẢNH — giống hệt tiếng Việt!", radical:"电(ĐIỆN) = tia chớp = điện | 影(ẢNH) = 景(CẢNH) + 彡(tia) → hình ảnh chuyển động = phim/bóng → 'hình điện' = phim", examples:[{ zh:"我们去看电影吧。", vi:"Chúng ta đi xem phim đi." },{ zh:"你喜欢看电影吗？", vi:"Bạn có thích xem phim không?" }] },
  { char:"电影院", pinyin:"diànyǐngyuàn", pos:"n.",    viet:"rạp chiếu phim",                                       lesson:7, hv:"ĐIỆN ẢNH VIỆN — viện chiếu phim điện", radical:"电(ĐIỆN) = tượng hình tia chớp = điện | 影(ẢNH) = 景(CẢNH) + 彡(tia sáng) → hình ảnh do tia tạo = phim/bóng | 院(VIỆN) = 阝(PHỤ — đất) + 完(HOÀN — đầy đủ) → nơi khép kín = viện → 'viện chiếu phim điện' = rạp chiếu phim" },

  // Vehicles (general → specific → place → quantifier → verbs)
  { char:"车",     pinyin:"chē",          pos:"n.",    viet:"xe, phương tiện",                                      lesson:7, hv:"XA — xe (như 'xa lộ', 'xe')", radical:"tượng hình chiếc xe ngựa cổ nhìn từ trên (bánh + trục) = xe" },
  { char:"自行车", pinyin:"zìxíngchē",    pos:"n.",    viet:"xe đạp",                                              lesson:7, hv:"TỰ HÀNH XA — xe tự đi", radical:"自(TỰ) = tượng hình mũi chỉ vào mình = tự | 行(HÀNH) = tượng hình ngã tư = đi/hành | 车(XA) = tượng hình xe (bánh + trục) = xe → 'xe tự đi' = xe đạp" },
  { char:"摩托车", pinyin:"mótuōchē",     pos:"n.",    viet:"xe máy",                                               lesson:7, hv:"MA THÁ XA — phiên âm 'moto' + xe", radical:"摩(MA) = 麻(MA — gai) + 手(THỦ — tay) → cọ xát (phiên âm 'mo') | 托(THÁ) = 扌(THỦ — tay) + 乇 → đỡ/giao (phiên âm 'tuo') | 车(XA) = xe → 摩托 phiên âm 'moto' + xe = xe máy" },
  { char:"汽车",   pinyin:"qìchē",        pos:"n.",    viet:"ô tô",                                                 lesson:7, hv:"KHÍ XA — xe hơi (khí=hơi nước/động cơ)", radical:"汽(KHÍ) = 氵(THỦY — nước) + 气(KHÍ — hơi/gas) → hơi nước | 车(XA) = xe → 'xe hơi nước' = ô tô (vốn chạy bằng hơi nước)" },
  { char:"车棚",   pinyin:"chēpéng",      pos:"n.",    viet:"chỗ để xe",                                            lesson:7, hv:"XA BỒNG — mái che xe", radical:"车(XA) = xe | 棚(BỒNG) = 木(MỘC — gỗ) + 朋(BẰNG — đôi) → ván gỗ kề bên nhau = mái che → 'mái che xe' = chỗ để xe" },
  { char:"辆",     pinyin:"liàng",        pos:"q.",    viet:"lượng từ cho xe cộ",                                   lesson:7, hv:"LƯỢNG — lượng từ (HV ít dùng)", radical:"车(XA — xe, bộ thủ) + 两(LƯỠNG — đôi, gợi 'hai bánh/trục') → lượng từ chuyên cho xe cộ" },
  { char:"骑",     pinyin:"qí",           pos:"v.",    viet:"cưỡi, đi (xe đạp, ngựa...)",                            lesson:7, hv:"KỴ — cưỡi (như 'kỵ binh')", radical:"马(MÃ — ngựa, bộ thủ) + 奇(KỲ — chỉ thanh) → động từ về cưỡi ngựa / đi xe 2 bánh = cưỡi", examples:[{ zh:"他骑自行车去学校。", vi:"Anh ấy đi xe đạp đến trường." }] },
  { char:"开",     pinyin:"kāi",          pos:"v.",    viet:"lái (xe có động cơ); mở, khởi động",                  lesson:7, hv:"KHAI — mở, khởi động (như 'khai mạc')", radical:"一 + 廾(hai tay đẩy mở) → tay đẩy cánh cửa = mở/bắt đầu/lái" },

  // ── Lesson 8 ──
  // Communication
  { char:"电话",   pinyin:"diànhuà",      pos:"n.",    viet:"điện thoại",                                          lesson:8, hv:"ĐIỆN THOẠI — giống hệt tiếng Việt!", radical:"电(ĐIỆN) = tia chớp = điện | 话(THOẠI) = 讠(NGÔN — lời) + 舌(THIỆT — lưỡi) → lời từ lưỡi = cuộc nói/lời nói", examples:[{ zh:"你的电话号码是多少？", vi:"Số điện thoại của bạn là bao nhiêu?" }] },
  { char:"手机",   pinyin:"shǒujī",       pos:"n.",    viet:"điện thoại di động",                                  lesson:8, hv:"THỦ CƠ — máy cầm tay", radical:"手(THỦ — tay) | 机(CƠ — máy) = 木(MỘC — gỗ) + 几(KỶ — chỉ thanh) → 'máy cầm tay' = điện thoại di động" },
  { char:"护照",   pinyin:"hùzhào",       pos:"n.",    viet:"hộ chiếu",                                            lesson:8, hv:"HỘ CHIẾU — giống hệt tiếng Việt!", radical:"护(HỘ — bảo vệ) = 扌(THỦ — tay, bộ thủ) + 户(HỘ — chỉ thanh) → tay che chở | 照(CHIẾU — chiếu/giấy chứng) = 召(TRIỆU — chỉ thanh) + 灬(HỎA — lửa) → 'ánh sáng chiếu giấy' → 'giấy bảo vệ' = hộ chiếu" },
  { char:"作业",   pinyin:"zuòyè",        pos:"n.",    viet:"bài tập, bài tập về nhà",                              lesson:8, hv:"TÁC NGHIỆP — bài tập (tác = làm, nghiệp = công việc)", radical:"作(TÁC) = 亻(NHÂN — người) + 乍(SẠ — chỉ thanh) → người làm việc gì = làm/tác | 业(NGHIỆP) — tượng hình giá nhạc cụ cổ → công việc/sự nghiệp → 'công việc phải làm' = bài tập" },
  { char:"号",     pinyin:"hào",          pos:"n.",    viet:"số (thứ tự, địa chỉ, ngày)",                          lesson:8, hv:"HIỆU — số/ký hiệu (như 'tín hiệu')", radical:"口(KHẨU — miệng) + 丂 → tiếng kêu/ký hiệu = số/hiệu" },
  { char:"号码",   pinyin:"hàomǎ",        pos:"n.",    viet:"số, mã số (số điện thoại, mã hàng)",                  lesson:8, hv:"HIỆU MÃ — mã số", radical:"号(HIỆU — số) | 码(MÃ) = 石(THẠCH — đá) + 马(MÃ — chỉ thanh) → đá khắc số = mã/số" },
  { char:"多少",   pinyin:"duōshao",      pos:"pron.", viet:"bao nhiêu (hỏi số lượng — số lớn)",                   lesson:8, hv:"ĐA THIỂU — nhiều ít", radical:"多(ĐA — nhiều) + 少(THIỂU — ít) → 'nhiều-ít' = hỏi số lượng" },

  // Time
  { char:"周末",   pinyin:"zhōumò",       pos:"n.",    viet:"cuối tuần",                                            lesson:8, hv:"CHU MẠT — cuối tuần (chu = chu kỳ, mạt = ngọn/cuối)", radical:"周(CHU — tuần/chu kỳ) | 末(MẠT — ngọn) = 木(MỘC — cây) + 一 (vạch trên ngọn) → 'cuối chu kỳ' = cuối tuần" },
  { char:"分钟",   pinyin:"fēnzhōng",     pos:"n.",    viet:"phút (đơn vị thời gian đếm số phút)",                 lesson:8, hv:"PHÂN CHUNG — phút (đơn vị)", radical:"分(PHÂN — chia/phút) | 钟(CHUNG) = 钅(KIM — kim loại) + 中(TRUNG — chỉ thanh) → đồng hồ → 'phần chia trên đồng hồ' = phút" },
  { char:"小时",   pinyin:"xiǎoshí",      pos:"n.",    viet:"tiếng, giờ (thời lượng — 1/24 ngày)",                  lesson:8, hv:"TIỂU THỜI — giờ (đơn vị nhỏ của thời gian)", radical:"小(TIỂU — nhỏ) + 时(THỜI — thời gian) → 'phần thời gian nhỏ' (= 1/24 ngày) = tiếng/giờ. Song song với 分钟 (phút thời lượng)" },

  // Conjunction / adverb
  { char:"不过",   pinyin:"búguò",        pos:"conj.", viet:"nhưng, tuy nhiên (nhẹ hơn 可是)",                      lesson:8, hv:"BẤT QUÁ — không quá (nhưng cũng không quá nghiêm trọng)", radical:"不(BẤT — không) | 过(QUÁ) = 辶(SƯỚC — di chuyển) + 寸(THỐN — chỉ thanh) → 'không vượt quá' = nhưng (nhẹ)" },
  { char:"就",     pinyin:"jiù",          pos:"adv.",  viet:"thì, liền, ngay (nhấn ngay sau đó/chính là)",          lesson:8, hv:"TỰU — liền/thì (như 'tựu trung')", radical:"京(KINH — kinh đô) + 尤(VƯU — chỉ thanh) → 'đến ngay kinh đô' = liền/ngay" },
  { char:"都",     pinyin:"dōu",          pos:"adv.",  viet:"đều, tất cả, cả",                                      lesson:8, hv:"ĐÔ — đều (khi đọc dū thì là thủ đô)", radical:"者(GIẢ — kẻ/ngươi) + 阝(PHỤ — đất/thành) → 'tất cả mọi người ở đó' = đều" },
  { char:"等",     pinyin:"děng",         pos:"v.",    viet:"chờ, đợi; vân vân; cấp bậc",                           lesson:8, hv:"ĐẲNG — đợi/đẳng cấp (như 'đẳng cấp', 'bình đẳng')", radical:"竹(TRÚC — tre, bộ thủ) + 寺(TỰ — chỉ thanh) → nén tre đo thời gian = chờ/đợi" },

  // Interrogative
  { char:"怎么",   pinyin:"zěnme",        pos:"pron.", viet:"làm thế nào, làm sao",                                lesson:8, hv:"HV ít dùng — đại từ nghi vấn", radical:"怎 = 乍(SẠ — thoáng) + 心(TÂM — tim) → 'đột nhiên thắc mắc trong lòng' | 么 = trợ từ phiên âm → đại từ 'thế nào'" },

  // Movement / transport
  { char:"走",     pinyin:"zǒu",          pos:"v.",    viet:"dịch chuyển, rời khỏi (đi nói chung, không nhất thiết là đi bộ)", lesson:8, hv:"TẨU — đi/chạy (như 'tẩu thoát')", radical:"土(THỔ — đất) + 龰(người dang chân) → người bước trên đất = đi/dịch chuyển" },
  { char:"走路",   pinyin:"zǒulù",        pos:"v.",    viet:"đi bộ (hình thức đi lại bằng chân — động từ tách rời)", lesson:8, hv:"TẨU LỘ — đi đường (đi bộ)", radical:"走(TẨU — đi) + 路(LỘ — đường) → 'đi trên đường' = đi bộ (cách di chuyển bằng chân)" },
  { char:"路",     pinyin:"lù",           pos:"n.",    viet:"đường, con đường, tuyến đường",                       lesson:8, hv:"LỘ — đường (như 'lộ trình', 'đại lộ')", radical:"足(TÚC — chân, bộ thủ) + 各(CÁC — chỉ thanh) → 'chân đi qua' = đường" },
  { char:"公共汽车", pinyin:"gōnggòng qìchē", pos:"n.", viet:"xe bus",                                              lesson:8, hv:"CÔNG CỘNG KHÍ XA — xe chạy hơi (ô tô) công cộng", radical:"公(CÔNG — chung) + 共(CỘNG — cùng) → công cộng | 汽车 → ô tô → 'ô tô công cộng' = xe bus" },
  { char:"到",     pinyin:"dào",          pos:"v.",    viet:"đến, tới",                                             lesson:8, hv:"ĐÁO — đến (như 'đáo hạn', 'đáo nhậm')", radical:"至(CHÍ — đến) + 刂(ĐAO — chỉ thanh) → 'đến nơi' = đến/tới" },

  // Adjective / quantifier
  { char:"快",     pinyin:"kuài",         pos:"adj.",  viet:"nhanh, mau",                                           lesson:8, hv:"KHOÁI — nhanh (như 'khoái lạc', 'khoái mã')", radical:"忄(TÂM — tim, bộ thủ) + 夬(QUYẾT — chỉ thanh) → 'lòng phấn khởi, nhanh' = nhanh", examples:[{ zh:"公共汽车很慢，不快。", vi:"Xe bus rất chậm, không nhanh." },{ zh:"他走路很快。", vi:"Anh ấy đi bộ rất nhanh." }] },
  { char:"慢",     pinyin:"màn",          pos:"adj.",  viet:"chậm (đối lập với 快)",                                lesson:8, hv:"MẠN — chậm (như 'mạn tính', 'tản mạn')", radical:"忄(TÂM — tim, bộ thủ) + 曼(MẠN — chỉ thanh) → 'lòng kéo dài, không vội' = chậm" },

  // Direction
  { char:"东",     pinyin:"dōng",         pos:"n.",    viet:"đông (hướng), phía đông",                              lesson:8, hv:"ĐÔNG — phía đông (như 'phương đông', 'đông á')", radical:"giản thể của 東 — gốc: 日(NHẬT — mặt trời) qua 木(MỘC — cây) → mặt trời mọc qua cây = hướng đông" },
  { char:"东南",   pinyin:"dōngnán",      pos:"n.",    viet:"đông nam (hướng)",                                     lesson:8, hv:"ĐÔNG NAM — đông nam", radical:"东(ĐÔNG) + 南(NAM) → 'đông + nam' = hướng đông nam" },

  // Place
  { char:"房间",   pinyin:"fángjiān",     pos:"n.",    viet:"phòng, căn phòng",                                     lesson:8, hv:"PHÒNG GIAN — gian phòng", radical:"房(PHÒNG) = 户(HỘ — cửa) + 方(PHƯƠNG — chỉ thanh) → khu vực có cửa = phòng | 间(GIAN) = 门(MÔN — cửa) + 日(NHẬT) → khoảng giữa các cửa = gian" },
  { char:"室",     pinyin:"shì",          pos:"n.",    viet:"phòng (trong cụm: 教室, 卧室, 办公室)",                  lesson:8, hv:"THẤT — phòng (như 'lễ thất', 'phòng thất')", radical:"宀(MIÊN — mái nhà) + 至(CHÍ — đến) → 'nơi đến dưới mái' = phòng" },
  { char:"校园",   pinyin:"xiàoyuán",     pos:"n.",    viet:"khuôn viên trường, sân trường",                       lesson:8, hv:"HIỆU VIÊN — sân trường", radical:"校(HIỆU — trường) | 园(VIÊN) = 囗(viền — rào quanh) + 元(NGUYÊN — chỉ thanh) → vườn có rào → 'vườn của trường' = khuôn viên trường" },
  { char:"写",     pinyin:"xiě",          pos:"v.",    viet:"viết",                                                lesson:8, hv:"TẢ — viết (như 'tả thực', 'sao tả')", radical:"chữ giản thể của 寫 — 冖(MIÊN — mái) + 与 (chỉ thanh đơn giản hóa) → 'dưới mái cầm bút' = viết", examples:[{ zh:"我在房间写作业。", vi:"Tôi viết bài tập trong phòng." },{ zh:"你现在写作业吗？", vi:"Bạn có đang viết bài tập không?" }] },
  { char:"读",     pinyin:"dú",           pos:"v.",    viet:"đọc",                                                 lesson:8, hv:"ĐỘC — đọc (như 'độc giả', 'độc thư')", radical:"讠(NGÔN — lời, bộ thủ) + 卖(MÃI — chỉ thanh, đơn giản hóa từ 賣) → 'lời thoát ra' = đọc thành tiếng" },
  { char:"坐",     pinyin:"zuò",          pos:"v.",    viet:"ngồi; đi xe làm HÀNH KHÁCH (không tự cầm lái — khác 开 lái xe, 骑 cưỡi xe 2 bánh)", lesson:8, hv:"TỌA — ngồi (như 'tọa lạc', 'tọa thiền')", radical:"人 + 人 + 土(THỔ — đất) → 'hai người ngồi trên đất' = ngồi. Mở rộng: đi xe (= 'ngồi trên xe' với tư cách hành khách): 坐公共汽车 đi xe buýt, 坐火车 đi tàu, 坐出租车 đi taxi", examples:[{ zh:"我坐公共汽车去学校。", vi:"Tôi đi xe bus đến trường." },{ zh:"你怎么去学校？", vi:"Bạn đi đến trường bằng cách nào?" }] },

  // ── Lesson 9 ──
  // Người / cách xưng hô
  { char:"师傅",   pinyin:"shīfu",        pos:"n.",    viet:"thầy, anh (xưng hô lịch sự với người làm dịch vụ / bán hàng)", lesson:9, hv:"SƯ PHỤ — thầy (gọi người có nghề/dịch vụ)", radical:"师(SƯ — thầy) | 傅(PHỤ — người dạy/phụ trợ) → người làm nghề có tay nghề" },
  { char:"小姐",   pinyin:"xiǎojiě",      pos:"n.",    viet:"cô, cô gái (xưng hô lịch sự)",                         lesson:9, hv:"TIỂU TỶ — cô gái (tiểu = nhỏ, tỷ = chị)", radical:"小(TIỂU — nhỏ) + 姐(TỶ) = 女(NỮ) + 且(THẢ — chỉ thanh) → cô gái = miss/cô" },
  { char:"售货",   pinyin:"shòuhuò",      pos:"v.",    viet:"bán hàng (động từ; ghép với 员 → 售货员 nhân viên bán hàng)", lesson:9, hv:"THỤ HÓA — bán hàng (thụ = bán, hóa = hàng)", radical:"售(THỤ — bán) = 隹(CHUỲ — chim) + 口(KHẨU — miệng) → 'miệng giao chim' = bán | 货(HÓA — hàng hóa) = 化 + 贝(BỐI — tiền/vỏ sò) → 'đổi tiền lấy hàng' = hàng" },
  { char:"员",     pinyin:"yuán",         pos:"suff.", viet:"viên, nhân viên (hậu tố: 售货员, 服务员, 演员...)",      lesson:9, hv:"VIÊN — viên (như 'nhân viên', 'thành viên')", radical:"口(KHẨU — miệng) + 贝(BỐI — vỏ sò/tiền) → người tham gia trong nhóm = thành viên/viên" },

  // Mua bán / hành động
  { char:"买",     pinyin:"mǎi",          pos:"v.",    viet:"mua",                                                  lesson:9, hv:"MÃI — mua (như 'mãi võ' = bán/biểu diễn võ kiếm tiền)", radical:"chữ giản thể của 買 — gốc tượng hình 贝(BỐI — vỏ sò = tiền) → đổi tiền lấy đồ = mua", examples:[{ zh:"我想买一本书。", vi:"Tôi muốn mua một cuốn sách." },{ zh:"你买什么？", vi:"Bạn mua gì?" }] },
  { char:"给",     pinyin:"gěi",          pos:"v./prep.", viet:"cho, đưa, tính tiền cho",                            lesson:9, hv:"CẤP — cấp/cho (như 'cung cấp', 'cấp dưỡng')", radical:"纟(MỊCH — sợi, bộ thủ) + 合(HỢP — chỉ thanh) → trao/cho", examples:[{ zh:"给我一杯水。", vi:"Cho tôi một cốc nước." },{ zh:"我给你钱。", vi:"Tôi đưa tiền cho bạn." }] },
  { char:"要",     pinyin:"yào",          pos:"v./aux.", viet:"muốn, cần, lấy (động từ); sẽ (trợ động từ chỉ tương lai)", lesson:9, hv:"YÊU — muốn (như 'yêu cầu')", radical:"西(TÂY — phía tây) + 女(NỮ — phụ nữ) → tượng hình lưng eo phụ nữ → mở rộng: 'cần / muốn'", examples:[{ zh:"我要一瓶啤酒。", vi:"Tôi lấy một chai bia." },{ zh:"你要什么？", vi:"Bạn muốn gì?" }] },
  { char:"想",     pinyin:"xiǎng",        pos:"v./aux.", viet:"muốn, định (trợ động từ — mong muốn); nghĩ; nhớ (miss someone)", lesson:9, hv:"TƯỞNG — nghĩ (như 'tưởng tượng', 'suy tưởng')", radical:"相(TƯƠNG — chỉ thanh) + 心(TÂM — tim, bộ thủ dưới) → 'trong lòng nghĩ ngợi' = nghĩ/muốn/nhớ. Ba nghĩa: muốn (我想去), nghĩ (我想他对), nhớ (我想你)" },

  // Đồ vật / hàng hóa
  { char:"啤酒",   pinyin:"píjiǔ",        pos:"n.",    viet:"bia",                                                  lesson:9, hv:"BÌ TỬU — bia (bì = phiên âm 'pi' từ 'beer', tửu = rượu)", radical:"啤(BÌ) = 口 + 卑(BI — chỉ thanh) → phiên âm 'pi' của 'beer' | 酒(TỬU — rượu) = 氵(THỦY — nước) + 酉(DẬU — bình rượu)" },
  { char:"水",     pinyin:"shuǐ",         pos:"n.",    viet:"nước",                                                 lesson:9, hv:"THỦY — nước (như 'thủy điện', 'thủy quân')", radical:"tượng hình dòng nước chảy với các giọt — chữ pictograph cổ" },

  // Lượng từ
  { char:"瓶",     pinyin:"píng",         pos:"q.",    viet:"chai (lượng từ cho chất lỏng đựng trong chai)",        lesson:9, hv:"BÌNH — chai/bình (như 'bình hoa', 'bình thủy')", radical:"并(BÍNH — chỉ thanh) + 瓦(NGÕA — ngói/đất nung) → bình bằng đất nung = chai/bình" },
  { char:"瓶子",   pinyin:"píngzi",       pos:"n.",    viet:"cái chai, cái bình (vật — khác 瓶 là lượng từ)",        lesson:9, hv:"BÌNH TỬ — cái chai (子 = hậu tố danh từ)", radical:"瓶(BÌNH — chai) + 子(TỬ — hậu tố danh từ chỉ vật) → cái chai/bình (danh từ chỉ vật cụ thể, khác lượng từ 瓶)" },
  { char:"杯",     pinyin:"bēi",          pos:"q.",    viet:"cốc, ly (lượng từ cho chất lỏng đựng trong cốc/ly)",    lesson:9, hv:"BÔI — chén/cốc (như 'kim bôi' = chén vàng)", radical:"木(MỘC — gỗ, bộ thủ) + 不(BẤT — chỉ thanh) → cốc bằng gỗ. Như lượng từ: 一杯水 = một cốc nước" },
  { char:"杯子",   pinyin:"bēizi",        pos:"n.",    viet:"cốc, ly, chén (vật — khác 杯 là lượng từ)",             lesson:9, hv:"BÔI TỬ — cái cốc/ly", radical:"杯(BÔI — cốc) + 子(TỬ — hậu tố danh từ) → cái cốc/ly (danh từ chỉ vật, khác lượng từ 杯)" },
  { char:"把",     pinyin:"bǎ",           pos:"q.",    viet:"chiếc, cái (lượng từ cho vật có TAY CẦM: chìa khóa, dao, ô, ghế, bàn chải...)", lesson:9, hv:"BẢ — nắm/cầm (như 'bả vai', 'bả chủ')", radical:"扌(THỦ — tay, bộ thủ) + 巴(BA — chỉ thanh) → 'cái dùng tay nắm' = lượng từ cho vật có tay cầm. Ví dụ: 一把钥匙 (một chiếc chìa khóa), 一把椅子 (một chiếc ghế), 一把伞 (một cây dù)" },
  { char:"位",     pinyin:"wèi",          pos:"q.",    viet:"vị (lượng từ cho người — LỊCH SỰ, thay 个; dùng cho thầy cô, khách, người lớn tuổi)", lesson:9, hv:"VỊ — vị (như 'quý vị', 'chư vị', 'các vị')", radical:"亻(NHÂN — người, bộ thủ) + 立(LẬP — đứng) → 'người đứng / có địa vị' = vị/người (lịch sự). Ví dụ: 这位老师 (vị thầy cô này), 几位 (mấy vị?), 三位客人 (ba vị khách)" },

  // Tiền / thanh toán
  { char:"钱",     pinyin:"qián",         pos:"n.",    viet:"tiền",                                                 lesson:9, hv:"TIỀN — tiền (như 'kim tiền')", radical:"钅(KIM — kim loại, bộ thủ) + 戋(TIỀN — chỉ thanh) → 'kim loại làm tiền' = tiền", examples:[{ zh:"一共多少钱？", vi:"Tổng cộng bao nhiêu tiền?" },{ zh:"这些一共多少钱？", vi:"Tất cả những thứ này tổng cộng bao nhiêu tiền?" }] },
  { char:"元",     pinyin:"yuán",         pos:"q.",    viet:"YUAN — đơn vị tiền tệ chính thức của Trung Quốc (Nhân dân tệ RMB, ¥). Như 'dollar' trong tiếng Anh", lesson:9, hv:"NGUYÊN — gốc/nguyên đầu. Khi chỉ tiền, 元 là TÊN CHÍNH THỨC của đơn vị tiền", radical:"二 + 儿(NHI — hai chân) → 'người đứng đầu' = nguyên / đơn vị cơ bản. Mở rộng: tên đơn vị tiền chính (Yuán)" },
  { char:"块",     pinyin:"kuài",         pos:"q.",    viet:"khối/cục; ĐỒNG (từ khẩu ngữ thay 元 — giống 'buck' thay 'dollar' trong tiếng Anh)", lesson:9, hv:"KHỐI — khối/cục (như 'khối lượng')", radical:"土(THỔ — đất) + 鬼(QUỶ — chỉ thanh) → cục đất → 'một cục' tiền (khẩu ngữ). Trong nói chuyện hằng ngày, 块 ngày nay phổ biến hơn 元" },
  { char:"块钱",   pinyin:"kuài qián",    pos:"q.",    viet:"đồng (cách nói ĐẦY ĐỦ của 块 — thường thấy ở vị trí cuối số tiền). Ví dụ: 五块钱 = 5 đồng", lesson:9, hv:"KHỐI TIỀN — đồng tiền (đầy đủ)", radical:"块(KHỐI — đồng, khẩu ngữ) + 钱(TIỀN — tiền) → 'cục tiền' = dạng đầy đủ của 块. Có thể bỏ 钱 nếu rõ ngữ cảnh: 五块 = 五块钱" },
  { char:"角",     pinyin:"jiǎo",         pos:"q.",    viet:"JIAO — đơn vị tiền chính thức = 1/10 元 (0.1 đồng). Trên hóa đơn / biển giá", lesson:9, hv:"GIÁC — góc/sừng (đơn vị nhỏ)", radical:"tượng hình cái sừng → mở rộng: 'một phần nhỏ'. Là đơn vị 角 chính thức của RMB (0.1 元)" },
  { char:"毛",     pinyin:"máo",          pos:"q.",    viet:"hào (từ khẩu ngữ thay 角 — giống 'dime' thay '10 cents'). 1 毛 = 1 角 = 0.1 元", lesson:9, hv:"MAO — lông (đơn vị tiền nhỏ, khẩu ngữ)", radical:"tượng hình sợi lông → mở rộng nghĩa 'đơn vị nhỏ' (1/10 đồng — khẩu ngữ thay 角)" },
  { char:"毛钱",   pinyin:"máo qián",     pos:"q.",    viet:"hào (cách nói ĐẦY ĐỦ của 毛). Ví dụ: 五毛钱 = 0.5 đồng (5 hào)", lesson:9, hv:"MAO TIỀN — hào tiền (đầy đủ)", radical:"毛(MAO — hào, khẩu ngữ) + 钱(TIỀN — tiền) → dạng đầy đủ của 毛. Ví dụ: 三块五毛钱 = 3.5 đồng" },
  { char:"一共",   pinyin:"yīgòng",       pos:"adv.",  viet:"tổng cộng, tất cả, hết thảy",                          lesson:9, hv:"NHẤT CỘNG — tổng cộng", radical:"一(NHẤT — một) + 共(CỘNG — cùng/tổng) = 廾 + 八 → 'cùng cộng lại' = tổng cộng" },

  // Khác
  { char:"这些",   pinyin:"zhèxiē",       pos:"pron.", viet:"những cái này, các (số nhiều của 这)",                 lesson:9, hv:"GIÁ TA — những cái này", radical:"这(GIÁ — này) | 些(TA — chút/một số) = 此(THỬ — này) + 二(NHỊ — hai) → 'một ít, số nhiều'" },
  { char:"玛丽",   pinyin:"Mǎlì",         pos:"n.",    viet:"Mary (tên người — phiên âm)",                          lesson:9, hv:"MÃ LỆ — phiên âm 'Mary'" },

  // ── Lesson 10 ──
  // Gia đình / Family
  { char:"照片",   pinyin:"zhàopiàn",     pos:"n.",    viet:"ảnh, bức ảnh",                                              lesson:10, hv:"CHIẾU PHIẾN — ảnh (chiếu=chiếu sáng/chụp, phiến=tờ mỏng)", radical:"照(CHIẾU) = 昭(日+刀+口, chỉ thanh) + 灬(HỎA — lửa phía dưới) → 'ánh sáng chiếu xuống' = soi/chụp | 片(PHIẾN) = tượng hình mảnh mỏng → tờ/tấm ảnh" },
  { char:"家",     pinyin:"jiā",          pos:"n.",    viet:"nhà, gia đình",                                             lesson:10, hv:"GIA — nhà/gia đình (như 'gia đình', 'gia tộc', 'gia sản')", radical:"宀(MIÊN — mái nhà, bộ thủ) + 豕(THỈ — lợn) → 'nhà có nuôi lợn' = gia đình (thời cổ, nhà có lợn = gia đình đủ ăn)", examples:[{ zh:"我家有三口人。", vi:"Nhà tôi có ba người." },{ zh:"你家有几口人？", vi:"Nhà bạn có mấy người?" }] },
  { char:"口",     pinyin:"kǒu",          pos:"n./q.", viet:"miệng; lượng từ đếm người trong gia đình (三口人 = gia đình 3 người)",  lesson:10, hv:"KHẨU — miệng (như 'khẩu ngữ', 'nhân khẩu', 'nhập khẩu')", radical:"tượng hình cái miệng mở → bộ thủ 口 xuất hiện trong hàng trăm chữ liên quan miệng/lời. Làm lượng từ: 三口人 = ba miệng ăn = gia đình ba người" },
  { char:"爷爷",   pinyin:"yéye",         pos:"n.",    viet:"ông nội (bố của bố)",                                       lesson:10, hv:"DA DA — ông nội (HV ít dùng; 爷 = cha già, người lớn tuổi)", radical:"父(PHỤ — cha, bộ thủ) + 耶(DA — chỉ thanh) → 'cha già' = ông. Lặp 爷爷 = cách xưng hô thân mật. Lưu ý: 爷爷 = ông nội (bố của bố) ≠ 外公 = ông ngoại (bố của mẹ)" },
  { char:"奶奶",   pinyin:"nǎinai",       pos:"n.",    viet:"bà nội (mẹ của bố)",                                        lesson:10, hv:"NÃI NÃI — bà nội (HV ít dùng; 奶 = vú/bú, gốc chỉ bà nuôi dưỡng)", radical:"女(NỮ — phụ nữ, bộ thủ) + 乃(NÃI — chỉ thanh) → 'người phụ nữ lớn tuổi trong nhà cha' = bà nội. Lưu ý: 奶奶 = bà nội ≠ 外婆 = bà ngoại" },
  { char:"爸爸",   pinyin:"bàba",         pos:"n.",    viet:"bố, cha",                                                   lesson:10, hv:"BA BA — bố (HV ít dùng; từ khẩu ngữ)", radical:"父(PHỤ — cha, bộ thủ) + 巴(BA — chỉ thanh) → bố", examples:[{ zh:"我爸爸是老师。", vi:"Bố tôi là giáo viên." },{ zh:"我的爸爸妈妈在中国。", vi:"Bố mẹ tôi ở Trung Quốc." }] },
  { char:"妈妈",   pinyin:"māma",         pos:"n.",    viet:"mẹ",                                                        lesson:10, hv:"MA MA — mẹ (HV ít dùng; từ khẩu ngữ)", radical:"女(NỮ — phụ nữ, bộ thủ) + 马(MÃ — ngựa, chỉ thanh) → mẹ" },
  { char:"哥哥",   pinyin:"gēge",         pos:"n.",    viet:"anh trai",                                                  lesson:10, hv:"CA CA — anh trai (HV ít dùng)", radical:"可(KHẢ — chỉ thanh) lặp đôi × 2 → 'người đứng trước/trên' = anh trai" },
  { char:"姐姐",   pinyin:"jiějie",       pos:"n.",    viet:"chị gái",                                                   lesson:10, hv:"TỶ TỶ — chị gái (như 'tỷ muội' = chị em gái)", radical:"女(NỮ — phụ nữ, bộ thủ) + 且(THẢ — chỉ thanh) → 'người phụ nữ lớn hơn mình' = chị gái" },
  { char:"弟弟",   pinyin:"dìdi",         pos:"n.",    viet:"em trai",                                                   lesson:10, hv:"ĐỆ ĐỆ — em trai (như 'huynh đệ' = anh em trai)", radical:"弓(CUNG — uốn) + 八 + 丨 → tượng hình dây buộc theo thứ tự → 'người xếp sau' = em trai" },
  { char:"妹妹",   pinyin:"mèimei",       pos:"n.",    viet:"em gái",                                                    lesson:10, hv:"MUỘI MUỘI — em gái (như 'tỷ muội' = chị em)", radical:"女(NỮ — phụ nữ, bộ thủ) + 未(VỊ — chỉ thanh, cũng nghĩa 'chưa đến thời') → 'cô gái chưa lớn' = em gái" },

  // Gia đình / Home
  { char:"家庭",   pinyin:"jiātíng",      pos:"n.",    viet:"gia đình (từ chính thức/văn viết — so với 家 = khẩu ngữ)",  lesson:10, hv:"GIA ĐÌNH — gia đình (giống hệt tiếng Việt!)", radical:"家(GIA — nhà) | 庭(ĐÌNH) = 广(NGHIỄM — mái nhà) + 廷(ĐÌNH — triều đình, chỉ thanh) → 'sân trong của nhà' = gia đình (formal)" },
  { char:"一般",   pinyin:"yībān",        pos:"adv./adj.", viet:"thường, nói chung, bình thường (không đặc biệt)",       lesson:10, hv:"NHẤT BÀNG — thông thường (một kiểu bình thường)", radical:"一(NHẤT — một) | 般(BÀN) = 舟(CHU — thuyền) + 殳(THÙ — chỉ thanh) → 'kiểu thông thường nhất' = bình thường/nói chung" },
  { char:"只",     pinyin:"zhǐ",          pos:"adv.",   viet:"chỉ, chỉ là (phó từ giới hạn: 只有 chỉ có, 只是 chỉ là, 只要 chỉ cần)",  lesson:10, hv:"CHỈ — chỉ/duy nhất (HV ít dùng)", radical:"口(KHẨU) + 八(BÁT — chia tách) → 'chỉ một miệng' = duy nhất/chỉ (phó từ). Cùng chữ 只 đọc zhī = lượng từ (xem từ tiếp theo)" },
  { char:"只",     pinyin:"zhī",          pos:"q.",    viet:"lượng từ cho động vật (nhỏ, chim): 一只狗 một con chó, 一只鸟 một con chim, 两只猫 hai con mèo", lesson:10, hv:"CHỈ — lượng từ (HV ít dùng)", radical:"giản thể từ 隻 = 隹(CHUỲ — chim) + 又(HỮU — tay) → 'tay cầm một con chim' = lượng từ cho động vật. Cùng chữ 只 đọc zhǐ = chỉ (phó từ, xem từ trước)" },

  // Con vật / Animals
  { char:"孩子",   pinyin:"háizi",        pos:"n.",    viet:"con, trẻ em, đứa trẻ",                                      lesson:10, hv:"HÀI TỬ — đứa trẻ (hài = trẻ con, tử = đứa/con)", radical:"孩(HÀI) = 子(TỬ — con trẻ, bộ thủ) + 亥(HỢI — địa chi thứ 12, chỉ thanh) → 'đứa con' | 子(TỬ — hậu tố danh từ)" },
  { char:"还",     pinyin:"hái",          pos:"adv.",  viet:"còn, vẫn, cũng (phó từ: 还有 còn nữa, 还是 vẫn là, 还好 vẫn tốt)", lesson:10, hv:"HOÀN — còn/vẫn (HV ít dùng trong nghĩa này)", radical:"giản thể của 還 — 辶(SƯỚC — đi bộ, bộ thủ) + 不(giản lược) → 'chưa đi hết' = vẫn còn. Cùng chữ 还 đọc huán = trả lại (xem từ tiếp theo)", examples:[{ zh:"我还有一个弟弟。", vi:"Tôi còn có một người em trai." },{ zh:"她还有妹妹吗？", vi:"Cô ấy còn có em gái không?" }] },
  { char:"还",     pinyin:"huán",         pos:"v.",    viet:"trả lại, hoàn trả (还书 trả sách, 还钱 trả tiền, 还债 trả nợ)", lesson:10, hv:"HOÀN — hoàn/trả lại (như 'hoàn trả', 'hoàn lại')", radical:"giản thể của 還 — 辶(SƯỚC — đi bộ, bộ thủ) + 不(giản lược) → 'đi rồi quay về, đưa lại' = trả lại. Cùng chữ 还 đọc hái = còn/vẫn (xem từ trước)" },
  { char:"条",     pinyin:"tiáo",         pos:"q.",    viet:"lượng từ cho vật dài/mảnh (一条狗 một con chó, 一条河 một con sông, 一条路 một con đường)", lesson:10, hv:"ĐIỀU — điều/lượng từ dài (như 'điều kiện', 'điều khoản', 'điều tra')", radical:"giản thể của 條 — 木(MỘC — gỗ, bộ thủ) + 攸(DU — chỉ thanh) → 'cành cây dài, mảnh' = lượng từ cho vật dài" },
  { char:"狗",     pinyin:"gǒu",          pos:"n.",    viet:"chó",                                                       lesson:10, hv:"CẨU — chó (như 'cẩu nhục' = thịt chó)", radical:"犭(KHUYỂN — chó, bộ thủ; dạng đứng của 犬) + 句(CÚ — chỉ thanh) → chó", examples:[{ zh:"我家有一只狗。", vi:"Nhà tôi có một con chó." }] },
  { char:"这样",   pinyin:"zhèyàng",      pos:"pron./adv.", viet:"như vậy, như thế này, kiểu này (chỉ cách thức/tình huống gần người nói)", lesson:10, hv:"GIÁ DẠNG — kiểu này (giá = này, dạng = kiểu/dáng)", radical:"这(GIÁ — này) | 样(DẠNG) = 木(MỘC — gỗ, bộ thủ) + 羊(DƯƠNG — chỉ thanh) → 'hình dáng, kiểu' → 'kiểu như thế này' = như vậy" },

  { char:"千",     pinyin:"qiān",         pos:"num.",  viet:"nghìn, một nghìn (1000)",                               lesson:10, hv:"THIÊN — nghìn (như 'thiên thu' = ngàn năm, 'bách thiên' = trăm nghìn)", radical:"tượng hình người đứng với một vạch ngang → 'một người đứng vững' = đơn vị lớn. Hệ số: 一千(1000), 两千(2000), 一万(10000)" },

  // ── Lesson 11 ──
  // Thời tiết / Weather
  { char:"天气",   pinyin:"tiānqì",       pos:"n.",    viet:"thời tiết",                                                 lesson:11, hv:"THIÊN KHÍ — thời tiết (thiên = trời, khí = khí hậu/hơi)", radical:"天(THIÊN — trời) | 气(KHÍ) = tượng hình hơi nước bốc lên → 'khí của trời' = thời tiết. 气 giản thể của 氣 (có 米=gạo bên trong → hơi thở + thức ăn = sinh khí)", examples:[{ zh:"今天天气怎么样？", vi:"Hôm nay thời tiết thế nào?" },{ zh:"今天天气很好。", vi:"Hôm nay thời tiết rất đẹp." }] },
  { char:"怎么样", pinyin:"zěnmeyàng",    pos:"pron.", viet:"như thế nào, ra sao (hỏi về tình trạng hoặc đánh giá: 天气怎么样？= Thời tiết thế nào?)", lesson:11, hv:"TỬM MA DẠNG — như thế nào (HV ít dùng)", radical:"怎(TỬM) = 乍(TÁC — chỉ thanh) + 心(TÂM — tim) → 'lòng tự hỏi' = sao/thế nào | 么(MA — hậu tố nhẹ) | 样(DẠNG) = 木(MỘC) + 羊(DƯƠNG — chỉ thanh) → hình dáng/kiểu" },
  { char:"不太",   pinyin:"bú tài",       pos:"adv.",  viet:"không... lắm, không quá (phủ định nhẹ mức độ: 不太冷 = không lạnh lắm, 不太好 = không tốt lắm)", lesson:11, hv:"BẤT THÁI — không quá (bất = không, thái = quá)", radical:"不(BẤT — không) + 太(THÁI — quá; 大 + 一 → 'người lớn thêm một bậc' = quá) → phủ định mức độ. Xem thêm ngữ pháp 太...了 vs 不太 (B6-NP3)" },
  { char:"风",     pinyin:"fēng",         pos:"n.",    viet:"gió",                                                       lesson:11, hv:"PHONG — gió (như 'phong trào', 'phong cách', 'phong ba')", radical:"giản thể của 風 — 几(KỶ) + 虫(TRÙNG — sâu) → tượng hình gió cuốn bay sâu bọ = gió. Bộ 风 xuất hiện trong: 风暴(bão), 台风(bão nhiệt đới)" },
  { char:"雨",     pinyin:"yǔ",           pos:"n.",    viet:"mưa",                                                       lesson:11, hv:"VŨ — mưa (như 'phong vũ' = gió mưa, 'vũ lượng' = lượng mưa)", radical:"tượng hình giọt mưa rơi dưới đám mây — bộ thủ 雨(VŨ) xuất hiện trong: 雪(tuyết), 雷(sấm), 霜(sương giá)" },
  { char:"冷",     pinyin:"lěng",         pos:"adj.",  viet:"lạnh",                                                      lesson:11, hv:"LÃNH — lạnh (như 'lãnh đạm', 'lạnh lùng', 'băng lãnh')", radical:"冫(BĂNG — băng, bộ thủ; hai chấm lạnh) + 令(LỆNH — chỉ thanh) → 'lạnh như băng' = lạnh", examples:[{ zh:"冬天很冷。", vi:"Mùa đông rất lạnh." },{ zh:"北京冬天最冷。", vi:"Mùa đông Bắc Kinh lạnh nhất." }] },
  { char:"度",     pinyin:"dù",           pos:"n./q.", viet:"độ (đơn vị đo nhiệt độ: 三十度 = 30°C; cũng dùng trong: 温度, 态度, 度假)",                lesson:11, hv:"ĐỘ — độ (như 'nhiệt độ', 'độ cao', 'thái độ')", radical:"广(NGHIỄM — mái rộng, bộ thủ) + 廿(NIỆM — hai mươi) + 又(HỮU — tay) → 'đo đếm, đong lường dưới mái' = mức/độ" },

  // Tính chất thời tiết / Weather conditions
  { char:"热",     pinyin:"rè",           pos:"adj.",  viet:"nóng, nóng bức",                                            lesson:11, hv:"NHIỆT — nóng (như 'nhiệt độ', 'nhiệt tình', 'nhiệt đới')", radical:"giản thể của 熱 — 执(CHẤP — cầm) + 灬(HỎA — lửa phía dưới) → 'cầm vật có lửa bên dưới' = nóng. Bộ 灬(bốn chấm lửa) xuất hiện trong: 热, 熟(chín), 烫(bỏng)" },
  { char:"舒服",   pinyin:"shūfu",        pos:"adj.",  viet:"thoải mái, dễ chịu",                                        lesson:11, hv:"THƯ PHỤC — thoải mái (thư = thư thái, phục = phục hồi/an ổn)", radical:"舒(THƯ) = 舍(XÁ — buông/nhà) + 予(DỮ — cho) → 'buông bỏ, nhẹ nhõm' = thư thái | 服(PHỤC) = 月(NGUYỆT — thịt/cơ thể) + 又(HỮU — tay) → cơ thể thoải mái" },
  { char:"最",     pinyin:"zuì",          pos:"adv.",  viet:"nhất (siêu cấp — trước tính từ: 最好 tốt nhất, 最冷 lạnh nhất, 最喜欢 thích nhất)",         lesson:11, hv:"TỐI — nhất/cực (như 'tối cao', 'tối ưu', 'tối đa')", radical:"日(NHẬT — mặt trời) + 取(THỦ = 耳+又 — lấy/giành được) → 'lấy được vị trí cao như mặt trời' = nhất/tối", examples:[{ zh:"我最喜欢秋天。", vi:"Tôi thích mùa thu nhất." },{ zh:"秋天的天气最舒服。", vi:"Thời tiết mùa thu thoải mái nhất." }] },
  { char:"季节",   pinyin:"jìjié",        pos:"n.",    viet:"mùa, mùa vụ (bốn mùa: 春夏秋冬)",                           lesson:11, hv:"QUÝ TIẾT — mùa (quý = quý/kỳ theo mùa, tiết = tiết khí)", radical:"季(QUÝ) = 禾(HÒA — lúa) + 子(TỬ — con) → 'cây lúa non đang mọc' = quý/mùa | 节(TIẾT) = 艹(THẢO — cỏ) + 即(TỨC — chỉ thanh) → tiết khí/mùa. Giản thể của 節" },
  { char:"比较",   pinyin:"bǐjiào",       pos:"adv./v.", viet:"tương đối, khá (phó từ: 比较冷 = khá lạnh); so sánh (động từ: 比较一下 = so một chút)", lesson:11, hv:"TỶ GIÁO — so sánh (tỷ = so, giáo = đối chiếu)", radical:"比(TỶ) = tượng hình hai người đứng sát nhau → so sánh | 较(GIÁO) = 车(XA — xe) + 交(GIAO — chỉ thanh) → 'xe ganh đua nhau' = so/tương đối. Giản thể của 較" },
  { char:"差不多", pinyin:"chàbuduō",     pos:"adv./adj.", viet:"xấp xỉ, gần như vậy, không chênh lệch mấy (差 = sai lệch, 不多 = không nhiều → 'sai lệch không đáng kể')", lesson:11, hv:"SAI BẤT ĐA — không sai mấy (sai = sai lệch, bất = không, đa = nhiều)", radical:"差(SAI) = 羊(DƯƠNG — dê) + 工(CÔNG — chỉ thanh) → sai lệch/khác biệt | 不(BẤT — không) | 多(ĐA) = 夕(TỊCH — buổi tối) × 2 → nhiều. Tổng: 'sai lệch không nhiều' = gần như nhau" },

  // Mùa vụ / Seasons
  { char:"常",     pinyin:"cháng",        pos:"adv.",  viet:"thường, hay (tần suất vừa — ít thường xuyên hơn 常常/经常)",  lesson:11, hv:"THƯỜNG — thường (như 'thường ngày', 'thường xuyên', 'phi thường')", radical:"巾(CÂN — khăn, bộ thủ dưới) + 尚(THƯỢNG — chỉ thanh) → 'quy tắc thường ngày' = thường" },
  { char:"常常",   pinyin:"chángcháng",   pos:"adv.",  viet:"thường xuyên, hay hay (tần suất cao hơn 常)",                lesson:11, hv:"THƯỜNG THƯỜNG — thường xuyên", radical:"常(THƯỜNG — thường) × 2 → nhấn mạnh tần suất cao. Thang độ: 有时候(đôi khi) < 常/常常 ≈ 经常(thường xuyên) < 总是(luôn luôn)", examples:[{ zh:"夏天常常下雨。", vi:"Mùa hè thường xuyên có mưa." },{ zh:"我常常去游泳。", vi:"Tôi thường xuyên đi bơi." }] },
  { char:"春天",   pinyin:"chūntiān",     pos:"n.",    viet:"mùa xuân (cũng: 春季 chūnjì — 季 dùng trang trọng hơn)",    lesson:11, hv:"XUÂN THIÊN — mùa xuân (như 'xuân nhật', 'mùa xuân')", radical:"春(XUÂN) = 艹(THẢO — cỏ) + 日(NHẬT — mặt trời) + 屯(TRUÂN — chỉ thanh) → 'mặt trời làm cỏ mọc' = mùa xuân | 天(THIÊN — trời/ngày). X天 = khẩu ngữ; X季 = văn viết/trang trọng" },
  { char:"夏天",   pinyin:"xiàtiān",      pos:"n.",    viet:"mùa hè (cũng: 夏季 xiàjì — 季 dùng trang trọng hơn)",        lesson:11, hv:"HẠ THIÊN — mùa hè (như 'hạ chí', 'mùa hạ')", radical:"夏(HẠ) = tượng hình người đứng xòe tay chân to lớn dưới nắng = mùa nóng. Lưu ý: 夏 khác 下午(下=xuống, âm khác). X天 = khẩu ngữ; X季 = văn viết/trang trọng | 天(THIÊN)" },
  { char:"秋天",   pinyin:"qiūtiān",      pos:"n.",    viet:"mùa thu (cũng: 秋季 qiūjì — 季 dùng trang trọng hơn)",       lesson:11, hv:"THU THIÊN — mùa thu (như 'thu phân', 'mùa thu')", radical:"秋(THU) = 禾(HÒA — lúa, bộ thủ) + 火(HỎA — lửa) → 'lúa chín đỏ như lửa' = mùa thu | 天(THIÊN). X天 = khẩu ngữ; X季 = văn viết/trang trọng" },
  { char:"冬天",   pinyin:"dōngtiān",     pos:"n.",    viet:"mùa đông (cũng: 冬季 dōngjì — 季 dùng trang trọng hơn)",     lesson:11, hv:"ĐÔNG THIÊN — mùa đông (như 'đông chí', 'mùa đông')", radical:"冬(ĐÔNG) = 夂(TUẾ — chân bước) + 冫(BĂNG — băng lạnh bên dưới) → 'đi trong băng giá' = mùa đông | 天(THIÊN). X天 = khẩu ngữ; X季 = văn viết/trang trọng" },
  { char:"雪",     pinyin:"xuě",          pos:"n.",    viet:"tuyết",                                                      lesson:11, hv:"TUYẾT — tuyết (như 'băng tuyết', 'tuyết trắng')", radical:"雨(VŨ — mưa, bộ thủ) + 彗(HUỆ — chổi, chỉ thanh) → 'mưa trắng như quét bằng chổi' = tuyết. Dùng với 下: 下雪 = tuyết rơi" },
  { char:"游泳",   pinyin:"yóuyǒng",      pos:"v.",    viet:"bơi lội",                                                    lesson:11, hv:"DU VỊNH — bơi lội (du = bơi/dạo trong nước, vịnh = vịnh/bơi)", radical:"游(DU) = 氵(THỦY — nước, bộ thủ) + 斿(DU — chỉ thanh) → 'chuyển động trong nước' = bơi | 泳(VỊNH) = 氵(THỦY) + 永(VĨNH — lâu dài, chỉ thanh) → 'bơi dài trong nước' = bơi lội" },

  { char:"晴天",   pinyin:"qíngtiān",     pos:"n.",    viet:"trời nắng, ngày đẹp trời (không mưa, không mây)",          lesson:11, hv:"TÌNH THIÊN — trời quang (tình = trời trong, quang đãng)", radical:"晴(TÌNH) = 日(NHẬT — mặt trời, bộ thủ) + 青(THANH — xanh, chỉ thanh) → 'mặt trời trên bầu trời xanh' = trời nắng/quang | 天(THIÊN — trời/ngày)" },
  { char:"阴天",   pinyin:"yīntiān",      pos:"n.",    viet:"trời âm u, trời nhiều mây (không nắng, không mưa — giữa 晴天 và 雨天)", lesson:11, hv:"ÂM THIÊN — trời âm u (âm = tối/âm, thiên = trời)", radical:"阴(ÂM) = 阝(PHỤ — gò đất, bộ thủ) + 月(NGUYỆT — trăng/tối) → 'phía tối của gò' = âm/tối. Giản thể của 陰. Đối lập: 晴天(nắng) ↔ 阴天(âm u) ↔ 雨天(mưa) | 天(THIÊN)" },

  // ── Add new words below ──
];

// Auto-assign `n` from array index
words.forEach((w, i) => w.n = i + 1);
