/**
 * Chinese Vocabulary Data
 *
 * To add a new word, just append to the array — `n` is assigned automatically.
 *   { char: "汉字", pinyin: "pīnyīn", pos: "n.", viet: "nghĩa tiếng Việt", lesson: <number> }
 *
 * pos options: n. (noun), v. (verb), pron. (pronoun), adv. (adverb), adj. (adjective), part. (particle), suff. (suffix), q. (quantifier), or "" (none)
 */
const words = [
  // ── Lesson 1 ──
  { char:"你好",   pinyin:"nǐ hǎo",       pos:"",      viet:"chào bạn",                                          lesson:1, hv:"NỄ HẢO — lit. 'bạn tốt' = chào" },
  { char:"好",     pinyin:"hǎo",           pos:"adj.",  viet:"tốt, khỏe, hay, ngon",                              lesson:1, hv:"HẢO — tốt (như 'hảo cảm', 'hảo hán')" },
  { char:"你",     pinyin:"nǐ",            pos:"pron.", viet:"bạn, anh, chị... (ngôi thứ 2 số ít)",               lesson:1, hv:"NỄ — bạn (đại từ ngôi 2)" },
  { char:"是",     pinyin:"shì",           pos:"v.",    viet:"là, thì...",                                         lesson:1, hv:"THỊ — là (như 'thị phi', 'như thị')" },
  { char:"老师",   pinyin:"lǎoshī",        pos:"n.",    viet:"giáo viên, thầy/cô giáo",                           lesson:1, hv:"LÃO SƯ — thầy/cô (dùng trong võ thuật, văn học)" },
  { char:"吗",     pinyin:"ma",            pos:"part.", viet:"...không? ...à? (trợ từ nghi vấn)",                  lesson:1, hv:"MA — trợ từ nghi vấn (HV ít dùng)" },
  { char:"了",     pinyin:"le",            pos:"part.", viet:"rồi, đã (trợ từ chỉ hoàn thành/biến đổi)",            lesson:1, hv:"LIỄU — hoàn thành (như 'liễu kết', 'liễu giải')" },
  { char:"不",     pinyin:"bù",            pos:"adv.",  viet:"không (trợ từ phủ định)",                            lesson:1, hv:"BẤT — không (như 'bất công', 'bất an')" },
  { char:"我",     pinyin:"wǒ",            pos:"pron.", viet:"tôi, tớ, mình... (ngôi thứ nhất số ít)",            lesson:1, hv:"NGÃ — tôi (như 'bản ngã', 'tự ngã')" },
  { char:"学生",   pinyin:"xuésheng",      pos:"n.",    viet:"học sinh",                                           lesson:1, hv:"HỌC SINH — giống hệt tiếng Việt!" },
  { char:"她",     pinyin:"tā",            pos:"pron.", viet:"cô ấy, chị ấy, nó (nữ, ngôi thứ 3 số ít)",         lesson:1, hv:"THA — cô ấy (như 'tha hương', 'tha nhân')" },
  { char:"谢谢",   pinyin:"xièxie",        pos:"v.",    viet:"cảm ơn",                                            lesson:1, hv:"TẠ TẠ — cảm tạ (lặp 2 lần)" },
  { char:"不客气", pinyin:"bú kèqi",        pos:"",      viet:"đừng khách sáo",                                    lesson:1, hv:"BẤT KHÁCH KHÍ — đừng khách khí" },
  { char:"您",     pinyin:"nín",           pos:"pron.", viet:"ông, bà, cô, chú, anh, chị... (trang trọng, số ít)", lesson:1, hv:"kính ngữ của 你 (NỄ) — HV ít dùng" },
  { char:"留学生", pinyin:"liúxuéshēng",    pos:"n.",    viet:"lưu học sinh",                                      lesson:1, hv:"LƯU HỌC SINH — giống hệt tiếng Việt!" },
  { char:"叫",     pinyin:"jiào",          pos:"v.",    viet:"gọi, kêu",                                           lesson:1, hv:"KHIẾU — gọi (như 'khiếu nại')" },
  { char:"什么",   pinyin:"shénme",        pos:"pron.", viet:"gì, cái gì?",                                        lesson:1, hv:"THẬM MA — gì (HV ít dùng)" },
  { char:"名字",   pinyin:"míngzi",        pos:"n.",    viet:"tên, họ tên",                                        lesson:1, hv:"DANH TỰ — tên (danh=tên, tự=chữ)" },
  { char:"大卫",   pinyin:"Dàwèi",         pos:"n.",    viet:"David (tên người)",                                  lesson:1, hv:"ĐẠI VỆ — phiên âm 'David'" },
  { char:"王",     pinyin:"Wáng",          pos:"n.",    viet:"Vương (họ)",                                          lesson:1, hv:"VƯƠNG — vua / họ Vương (như 'vương quốc')" },
  { char:"李军",   pinyin:"Lǐ Jūn",        pos:"n.",    viet:"Lý Quân (tên người)",                                lesson:1, hv:"LÝ QUÂN — họ Lý + tên Quân" },
  { char:"还没",   pinyin:"hái méi",       pos:"adv.",  viet:"chưa",                                                lesson:1, hv:"HOÀN MỘT — vẫn chưa (HOÀN = vẫn, MỘT = không)" },
  { char:"工作",   pinyin:"gōngzuò",       pos:"v./n.", viet:"đi làm, công việc",                                   lesson:1, hv:"CÔNG TÁC — công việc / công tác" },

  // ── Lesson 2 ──
  { char:"同学",   pinyin:"tóngxué",       pos:"n.",    viet:"bạn cùng học",                                       lesson:2, hv:"ĐỒNG HỌC — bạn cùng lớp" },
  { char:"们",     pinyin:"men",           pos:"suff.", viet:"hậu tố chỉ người ở số nhiều",                        lesson:2, hv:"MÔN — hậu tố số nhiều (HV ít dùng)" },
  { char:"来",     pinyin:"lái",           pos:"v.",    viet:"đến, tới",                                            lesson:2, hv:"LAI — đến (như 'tương lai', 'lai lịch')" },
  { char:"介绍",   pinyin:"jièshào",       pos:"v.",    viet:"giới thiệu",                                         lesson:2, hv:"GIỚI THIỆU — giống hệt tiếng Việt!" },
  { char:"一下儿", pinyin:"yíxiàr",         pos:"q.",    viet:"một chút",                                           lesson:2, hv:"NHẤT HẠ — một chút (lit. 'một lần xuống')" },
  { char:"姓",     pinyin:"xìng",          pos:"v./n.", viet:"họ (của tên)",                                        lesson:2, hv:"TÍNH — họ (như 'họ tên')" },
  { char:"的",     pinyin:"de",            pos:"part.", viet:"trợ từ",                                              lesson:2, hv:"ĐÍCH — trợ từ sở hữu (HV gốc nhưng nghĩa khác)" },
  { char:"哪",     pinyin:"nǎ",            pos:"pron.", viet:"nào",                                                lesson:2, hv:"NA — nào (đại từ nghi vấn)" },
  { char:"国",     pinyin:"guó",           pos:"n.",    viet:"nước, quốc gia",                                     lesson:2, hv:"QUỐC — nước (như 'quốc gia', 'quốc tế')" },
  { char:"人",     pinyin:"rén",           pos:"n.",    viet:"người",                                               lesson:2, hv:"NHÂN — người (như 'nhân loại', 'nhân văn')" },
  { char:"他",     pinyin:"tā",            pos:"pron.", viet:"anh ấy, ông ấy...",                                  lesson:2, hv:"THA — anh ấy (như 'tha nhân')" },
  { char:"认识",   pinyin:"rènshi",        pos:"v.",    viet:"quen biết",                                           lesson:2, hv:"NHẬN THỨC — quen biết" },
  { char:"很",     pinyin:"hěn",           pos:"adv.",  viet:"rất",                                                lesson:2, hv:"NGẪN — rất (HV ít dùng)" },
  { char:"高兴",   pinyin:"gāoxìng",       pos:"adj.",  viet:"vui mừng",                                           lesson:2, hv:"CAO HỨNG — vui, hứng khởi" },
  { char:"也",     pinyin:"yě",            pos:"adv.",  viet:"cũng",                                               lesson:2, hv:"DÃ — cũng (như 'dã thị')" },
  { char:"呢",     pinyin:"ne",            pos:"part.", viet:"trợ từ",                                              lesson:2, hv:"NỊ — trợ từ (HV ít dùng)" },
  { char:"中国",   pinyin:"Zhōngguó",      pos:"n.",    viet:"Trung Quốc",                                         lesson:2, hv:"TRUNG QUỐC — giống hệt tiếng Việt!" },
  { char:"美国",   pinyin:"Měiguó",        pos:"n.",    viet:"Mỹ",                                                  lesson:2, hv:"MỸ QUỐC — giống hệt tiếng Việt!" },
  { char:"英国",   pinyin:"Yīngguó",       pos:"n.",    viet:"Anh",                                                 lesson:2, hv:"ANH QUỐC — giống hệt tiếng Việt!" },
  { char:"法国",   pinyin:"Fǎguó",         pos:"n.",    viet:"Pháp",                                                lesson:2, hv:"PHÁP QUỐC — giống hệt tiếng Việt!" },
  { char:"加拿大", pinyin:"Jiānádà",        pos:"n.",    viet:"Canada",                                              lesson:2, hv:"GIA NÃ ĐẠI — phiên âm 'Canada'" },
  { char:"日本",   pinyin:"Rìběn",         pos:"n.",    viet:"Nhật Bản",                                            lesson:2, hv:"NHẬT BẢN — giống hệt tiếng Việt!" },
  { char:"韩国",   pinyin:"Hánguó",        pos:"n.",    viet:"Hàn Quốc",                                            lesson:2, hv:"HÀN QUỐC — giống hệt tiếng Việt!" },
  { char:"越南",   pinyin:"Yuènán",        pos:"n.",    viet:"Việt Nam",                                            lesson:2, hv:"VIỆT NAM — giống hệt tiếng Việt!" },

  // ── Lesson 3 ──
  { char:"那",     pinyin:"nà",            pos:"pron.", viet:"kia, đó",                                            lesson:3, hv:"NA — kia/đó (đại từ chỉ định xa)" },
  { char:"谁",     pinyin:"shéi/shuí",     pos:"pron.", viet:"ai, người nào",                                      lesson:3, hv:"THÙY — ai (văn cổ, như 'thùy hỉ')" },
  { char:"书",     pinyin:"shū",           pos:"n.",    viet:"quyển sách",                                         lesson:3, hv:"THƯ — sách (như 'thư viện', 'thư từ')" },
  { char:"同屋",   pinyin:"tóngwū",        pos:"n.",    viet:"bạn cùng phòng",                                     lesson:3, hv:"ĐỒNG ỐC — cùng nhà/phòng" },
  { char:"汉语",   pinyin:"Hànyǔ",         pos:"n.",    viet:"tiếng Hán",                                          lesson:3, hv:"HÁN NGỮ — tiếng Hán/tiếng Trung" },
  { char:"课本",   pinyin:"kèběn",         pos:"n.",    viet:"sách giáo khoa, giáo trình",                         lesson:3, hv:"KHÓA BẢN — bản của bài học (sách giáo trình)" },
  { char:"词典",   pinyin:"cídiǎn",        pos:"n.",    viet:"từ điển",                                             lesson:3, hv:"TỪ ĐIỂN — giống hệt tiếng Việt!" },
  { char:"就是",   pinyin:"jiù shì",       pos:"",      viet:"điều đó nghĩa là",                                   lesson:3, hv:"TỰU THỊ — chính là (TỰU = liền/ngay, THỊ = là)" },
  { char:"日语",   pinyin:"Rìyǔ",          pos:"n.",    viet:"tiếng Nhật",                                         lesson:3, hv:"NHẬT NGỮ — tiếng Nhật" },
  { char:"这",     pinyin:"zhè",           pos:"pron.", viet:"này, đây",                                           lesson:3, hv:"GIÁ — này/đây (đại từ chỉ định gần)" },
  { char:"杂志",   pinyin:"zázhì",         pos:"n.",    viet:"tạp chí",                                             lesson:3, hv:"TẠP CHÍ — giống hệt tiếng Việt!" },
  { char:"音乐",   pinyin:"yīnyuè",        pos:"n.",    viet:"âm nhạc",                                            lesson:3, hv:"ÂM NHẠC — giống hệt tiếng Việt!" },
  { char:"朋友",   pinyin:"péngyou",       pos:"n.",    viet:"bạn, bạn bè",                                        lesson:3, hv:"BẰNG HỮU — bạn bè (văn học)" },
  { char:"语言",   pinyin:"yǔyán",        pos:"n.",    viet:"ngôn ngữ",                                           lesson:3, hv:"NGỮ NGÔN — = ngôn ngữ (đảo vị trí)" },
  { char:"说",     pinyin:"shuō",         pos:"v.",    viet:"nói",                                                 lesson:3, hv:"THUYẾT — nói (như 'thuyết minh', 'tiểu thuyết')" },
  { char:"会",     pinyin:"huì",          pos:"v.",    viet:"biết (qua rèn luyện, học hỏi)",                       lesson:3, hv:"HỘI — biết qua học (như 'lĩnh hội', 'cơ hội')" },
  { char:"本",     pinyin:"běn",          pos:"mw.",   viet:"cuốn, quyển",                                         lesson:3, hv:"BẢN — cuốn/quyển (như 'phiên bản', 'cơ bản')" },
  { char:"喜欢",   pinyin:"xǐhuan",       pos:"v.",    viet:"thích",                                               lesson:3, hv:"HỶ HOAN — vui thích" },
  { char:"看",     pinyin:"kàn",          pos:"v.",    viet:"xem, nhìn, đọc",                                      lesson:3, hv:"KHÁN — xem (như 'khán giả', 'khán đài')" },
  { char:"听",     pinyin:"tīng",         pos:"v.",    viet:"nghe",                                                lesson:3, hv:"THÍNH — nghe (như 'thính giả')" },

  // ── Lesson 4 ──
  { char:"请问",   pinyin:"qǐngwèn",      pos:"v.",    viet:"xin hỏi",                                             lesson:4, hv:"THỈNH VẤN — xin hỏi" },
  { char:"图书馆", pinyin:"túshūguǎn",    pos:"n.",    viet:"thư viện",                                            lesson:4, hv:"ĐỒ THƯ QUÁN — thư viện (lit. 'quán đồ thư')" },
  { char:"在",     pinyin:"zài",          pos:"v./adv.", viet:"ở, đang",                                           lesson:4, hv:"TẠI — ở (như 'hiện tại', 'tồn tại')" },
  { char:"哪儿",   pinyin:"nǎr",          pos:"pron.", viet:"ở đâu, chỗ nào",                                      lesson:4, hv:"NA NHI — ở đâu" },
  { char:"哪里",   pinyin:"nǎli",         pos:"pron.", viet:"ở đâu, chỗ nào",                                      lesson:4, hv:"NA LÝ — ở đâu" },
  { char:"对不起", pinyin:"duìbuqǐ",      pos:"v.",    viet:"xin lỗi",                                             lesson:4, hv:"ĐỐI BẤT KHỞI — xin lỗi (lit. 'không thể đối lại')" },
  { char:"个",     pinyin:"gè",           pos:"mw.",   viet:"lượng từ chung (cho người, đồ vật)",                 lesson:4, hv:"CÁ — lượng từ chung (như 'cá nhân')" },
  { char:"学校",   pinyin:"xuéxiào",      pos:"n.",    viet:"trường học",                                          lesson:4, hv:"HỌC HIỆU — trường học" },
  { char:"知道",   pinyin:"zhīdào",       pos:"v.",    viet:"biết",                                                lesson:4, hv:"TRI ĐẠO — biết (như 'tri thức')" },
  { char:"没关系", pinyin:"méi guānxi",   pos:"",      viet:"không sao, không có gì",                              lesson:4, hv:"MỘT QUAN HỆ — không sao (lit. 'không có quan hệ gì')" },
  { char:"这儿",   pinyin:"zhèr",         pos:"pron.", viet:"chỗ này, nơi này",                                    lesson:4, hv:"GIÁ NHI — chỗ này" },
  { char:"这里",   pinyin:"zhèli",        pos:"pron.", viet:"chỗ này, nơi này",                                    lesson:4, hv:"GIÁ LÝ — chỗ này" },
  { char:"教学",   pinyin:"jiàoxué",      pos:"n.",    viet:"dạy học",                                             lesson:4, hv:"GIÁO HỌC — giống hệt tiếng Việt!" },
  { char:"楼",     pinyin:"lóu",          pos:"n.",    viet:"tòa nhà",                                             lesson:4, hv:"LÂU — tòa nhà (như 'lâu đài', 'cao lâu')" },
  { char:"那儿",   pinyin:"nàr",          pos:"pron.", viet:"chỗ kia, nơi kia",                                    lesson:4, hv:"NA NHI — chỗ kia" },
  { char:"那里",   pinyin:"nàli",         pos:"pron.", viet:"chỗ kia, nơi kia",                                    lesson:4, hv:"NA LÝ — chỗ kia" },
  { char:"宿舍",   pinyin:"sùshè",        pos:"n.",    viet:"ký túc xá",                                           lesson:4, hv:"TÚC XÁ — giống hệt tiếng Việt!" },
  { char:"北边",   pinyin:"běibian",      pos:"n.",    viet:"phía bắc",                                            lesson:4, hv:"BẮC BIÊN — phía bắc" },
  { char:"左边",   pinyin:"zuǒbian",      pos:"n.",    viet:"bên trái",                                            lesson:4, hv:"TẢ BIÊN — bên trái" },
  { char:"右边",   pinyin:"yòubian",      pos:"n.",    viet:"bên phải",                                            lesson:4, hv:"HỮU BIÊN — bên phải" },
  { char:"上边",   pinyin:"shàngbian",    pos:"n.",    viet:"phía trên",                                           lesson:4, hv:"THƯỢNG BIÊN — phía trên" },
  { char:"下边",   pinyin:"xiàbian",      pos:"n.",    viet:"phía dưới",                                           lesson:4, hv:"HẠ BIÊN — phía dưới" },
  { char:"不用谢", pinyin:"búyòng xiè",   pos:"",      viet:"không cần cảm ơn, không có gì",                       lesson:4, hv:"BẤT DỤNG TẠ — không cần cảm tạ" },
  { char:"不用",   pinyin:"búyòng",       pos:"adv.",  viet:"không cần",                                           lesson:4, hv:"BẤT DỤNG — không cần" },
  { char:"对",     pinyin:"duì",          pos:"adj.",  viet:"đúng",                                                lesson:4, hv:"ĐỐI — đúng (như 'đối phó', 'đối với')" },

  // ── Lesson 5 ──
  { char:"有",     pinyin:"yǒu",          pos:"v.",    viet:"có",                                                  lesson:5, hv:"HỮU — có (giống tiếng Việt!)" },
  { char:"有用",   pinyin:"yǒuyòng",      pos:"adj.",  viet:"có ích, hữu dụng",                                    lesson:5, hv:"HỮU DỤNG — giống hệt tiếng Việt!" },
  { char:"有名",   pinyin:"yǒumíng",      pos:"adj.",  viet:"nổi tiếng",                                           lesson:5, hv:"HỮU DANH — có danh tiếng" },
  { char:"空儿",   pinyin:"kòngr",        pos:"n.",    viet:"thời gian rảnh, lúc rảnh",                            lesson:5, hv:"KHÔNG — trống, rảnh (như 'không khí', 'không gian')" },
  { char:"时候",   pinyin:"shíhou",       pos:"n.",    viet:"lúc, khi, thời gian",                                 lesson:5, hv:"THỜI HẦU — lúc/khi" },
  { char:"欢迎",   pinyin:"huānyíng",     pos:"v.",    viet:"hoan nghênh, chào đón",                               lesson:5, hv:"HOAN NGHÊNH — giống hệt tiếng Việt!" },
  { char:"去",     pinyin:"qù",           pos:"v.",    viet:"đi",                                                  lesson:5, hv:"KHỨ — đi (trong 'quá khứ')" },
  { char:"玩儿",   pinyin:"wánr",         pos:"v.",    viet:"chơi",                                                lesson:5, hv:"NGOẠN — chơi (như 'ngoạn mục', 'du ngoạn')" },
  { char:"卫生间", pinyin:"wèishēngjiān", pos:"n.",    viet:"nhà vệ sinh",                                         lesson:5, hv:"VỆ SINH GIAN — giống tiếng Việt!" },
  { char:"教室",   pinyin:"jiàoshì",      pos:"n.",    viet:"phòng học, lớp học",                                  lesson:5, hv:"GIÁO THẤT — phòng học" },
  { char:"旁边",   pinyin:"pángbiān",     pos:"n.",    viet:"bên cạnh",                                            lesson:5, hv:"BÀNG BIÊN — bên cạnh" },
  { char:"西边",   pinyin:"xībiān",       pos:"n.",    viet:"phía tây",                                            lesson:5, hv:"TÂY BIÊN — phía tây" },
  { char:"小",     pinyin:"xiǎo",         pos:"adj.",  viet:"nhỏ, bé",                                             lesson:5, hv:"TIỂU — nhỏ (như 'tiểu học', 'tiểu thuyết')" },
  { char:"中",     pinyin:"zhōng",        pos:"adj.",  viet:"vừa, trung bình",                                     lesson:5, hv:"TRUNG — giữa (như 'trung học', 'trung tâm')" },
  { char:"大",     pinyin:"dà",           pos:"adj.",  viet:"to, lớn",                                             lesson:5, hv:"ĐẠI — lớn (như 'đại học', 'đại sứ')" },
  { char:"没有",   pinyin:"méiyǒu",       pos:"v.",    viet:"không có",                                            lesson:5, hv:"MỘT HỮU — phủ định của 有 (có)" },
  { char:"北京",   pinyin:"Běijīng",      pos:"n.",    viet:"Bắc Kinh",                                            lesson:5, hv:"BẮC KINH — giống hệt tiếng Việt!" },

  // ── Lesson 6 ──
  { char:"一",     pinyin:"yī",           pos:"num.",  viet:"một, 1",                                              lesson:6, hv:"NHẤT — một (như 'nhất quán', 'thứ nhất')" },
  { char:"二",     pinyin:"èr",           pos:"num.",  viet:"hai, 2",                                              lesson:6, hv:"NHỊ — hai (như 'nhị thập', 'thứ nhị')" },
  { char:"三",     pinyin:"sān",          pos:"num.",  viet:"ba, 3",                                               lesson:6, hv:"TAM — ba (như 'tam giác', 'tam quốc')" },
  { char:"四",     pinyin:"sì",           pos:"num.",  viet:"bốn, 4",                                              lesson:6, hv:"TỨ — bốn (như 'tứ giác', 'tứ phương')" },
  { char:"五",     pinyin:"wǔ",           pos:"num.",  viet:"năm, 5",                                              lesson:6, hv:"NGŨ — năm (như 'ngũ vị', 'ngũ hành')" },
  { char:"六",     pinyin:"liù",          pos:"num.",  viet:"sáu, 6",                                              lesson:6, hv:"LỤC — sáu (như 'lục địa', 'lục giác')" },
  { char:"七",     pinyin:"qī",           pos:"num.",  viet:"bảy, 7",                                              lesson:6, hv:"THẤT — bảy (như 'thất bại', 'thất tịch')" },
  { char:"八",     pinyin:"bā",           pos:"num.",  viet:"tám, 8",                                              lesson:6, hv:"BÁT — tám (như 'bát giác')" },
  { char:"九",     pinyin:"jiǔ",          pos:"num.",  viet:"chín, 9",                                             lesson:6, hv:"CỬU — chín (như 'cửu vạn')" },
  { char:"十",     pinyin:"shí",          pos:"num.",  viet:"mười, 10",                                            lesson:6, hv:"THẬP — mười (như 'thập kỷ', 'thập niên')" },
  { char:"两",     pinyin:"liǎng",        pos:"num.",  viet:"hai (dùng trước lượng từ)",                           lesson:6, hv:"LƯỠNG — hai (như 'lưỡng tính', 'lưỡng cực')" },
  { char:"零",     pinyin:"líng",         pos:"num.",  viet:"số không, 0",                                         lesson:6, hv:"LINH — số 0" },
  { char:"百",     pinyin:"bǎi",          pos:"num.",  viet:"trăm, 100",                                           lesson:6, hv:"BÁCH — trăm (như 'bách khoa', 'bách phân')" },
  { char:"点",     pinyin:"diǎn",         pos:"n.",    viet:"giờ (đơn vị thời gian)",                              lesson:6, hv:"ĐIỂM — giờ (điểm trên đồng hồ)" },
  { char:"分",     pinyin:"fēn",          pos:"n.",    viet:"phút",                                                lesson:6, hv:"PHÂN — phút (chia nhỏ giờ)" },
  { char:"半",     pinyin:"bàn",          pos:"n.",    viet:"rưỡi (30 phút), một nửa",                             lesson:6, hv:"BÁN — nửa (như 'bán cầu', 'bán đảo')" },
  { char:"刻",     pinyin:"kè",           pos:"n.",    viet:"khắc (15 phút)",                                      lesson:6, hv:"KHẮC — giống hệt tiếng Việt!" },
  { char:"差",     pinyin:"chà",          pos:"v.",    viet:"thiếu, kém",                                          lesson:6, hv:"SAI — thiếu, chênh lệch (như 'sai số')" },
  { char:"早",     pinyin:"zǎo",          pos:"adj./n.", viet:"sớm; buổi sáng (như 早上)",                          lesson:6, hv:"TẢO — sớm (như 'tảo hôn')" },
  { char:"几",     pinyin:"jǐ",           pos:"pron.", viet:"mấy, bao nhiêu (như 几点)",                            lesson:6, hv:"KỶ — mấy/bao nhiêu (số lượng nhỏ)" },
  { char:"上课",   pinyin:"shàngkè",      pos:"v.",    viet:"vào lớp, đi học",                                     lesson:6, hv:"THƯỢNG KHÓA — lên lớp" },
  { char:"下课",   pinyin:"xiàkè",        pos:"v.",    viet:"tan học, hết tiết",                                   lesson:6, hv:"HẠ KHÓA — xuống lớp" },
  { char:"部分",   pinyin:"bùfèn",        pos:"n.",    viet:"phần (như 大部分 = phần lớn)",                          lesson:6, hv:"BỘ PHẬN — giống hệt tiếng Việt!" },
  { char:"讲座",   pinyin:"jiǎngzuò",     pos:"n.",    viet:"bài giảng, buổi diễn giảng",                          lesson:6, hv:"GIẢNG TỌA — bài giảng (chỗ giảng)" },
  { char:"太",     pinyin:"tài",          pos:"adv.",  viet:"quá (dùng trong 太……了)",                              lesson:6, hv:"THÁI — quá (như 'thái quá')" },
  { char:"开始",   pinyin:"kāishǐ",       pos:"v.",    viet:"bắt đầu",                                             lesson:6, hv:"KHAI THỦY — mở đầu" },
  { char:"现在",   pinyin:"xiànzài",      pos:"n./adv.", viet:"bây giờ, hiện tại",                                 lesson:6, hv:"HIỆN TẠI — giống hệt tiếng Việt!" },
  { char:"一会儿", pinyin:"yíhuìr",       pos:"q.",    viet:"một lát, một chốc",                                   lesson:6, hv:"NHẤT HỘI — một lát" },
  { char:"见",     pinyin:"jiàn",         pos:"v.",    viet:"gặp, thấy",                                           lesson:6, hv:"KIẾN — thấy/gặp (như 'kiến thức', 'tái kiến')" },
  { char:"晚",     pinyin:"wǎn",          pos:"adj./n.", viet:"muộn, tối; buổi tối (như 晚上)",                     lesson:6, hv:"VÃN — muộn (như 'vãn cảnh')" },
  { char:"午",     pinyin:"wǔ",           pos:"n.",    viet:"giữa trưa, giờ ngọ (trong 上午/中午/下午)",              lesson:6, hv:"NGỌ — giữa trưa (như 'giờ ngọ', 'chính ngọ')" },
  { char:"吃",     pinyin:"chī",          pos:"v.",    viet:"ăn",                                                  lesson:6, hv:"KHIẾT — ăn (HV ít dùng)" },
  { char:"饭",     pinyin:"fàn",          pos:"n.",    viet:"cơm, bữa ăn",                                         lesson:6, hv:"PHẠN — cơm (như 'phạn điếm')" },
  { char:"吃饭",   pinyin:"chī fàn",      pos:"v.",    viet:"ăn cơm, dùng bữa",                                    lesson:6, hv:"KHIẾT PHẠN — ăn cơm" },
  { char:"睡觉",   pinyin:"shuìjiào",     pos:"v.",    viet:"đi ngủ, ngủ (động từ tách rời: 睡 + 觉)",               lesson:6, hv:"THỤY GIÁC — ngủ (觉 = giấc; tách 早/午/晚 vào giữa)" },
  { char:"再",     pinyin:"zài",          pos:"adv.",  viet:"lại, một lần nữa, tiếp (như 再见, 再说)",                lesson:6, hv:"TÁI — lại (như 'tái phát', 'tái diễn')" },
  { char:"再见",   pinyin:"zàijiàn",      pos:"v./int.", viet:"tạm biệt (lit. 'gặp lại')",                          lesson:6, hv:"TÁI KIẾN — gặp lại (lời chia tay)" },

  // ── Add new words below ──
];

// Auto-assign `n` from array index
words.forEach((w, i) => w.n = i + 1);
