/**
 * Chinese Vocabulary Data
 *
 * To add a new word, just append to the array — `n` is assigned automatically.
 *   { char: "汉字", pinyin: "pīnyīn", pos: "n.", viet: "nghĩa tiếng Việt", lesson: <number> }
 *
 * pos options: n. (noun), v. (verb), pron. (pronoun), adv. (adverb), adj. (adjective), part. (particle), suff. (suffix), q. (quantifier), or "" (none)
 */
const words = [
  // ── Lesson 1 ──
  { char:"你好",   pinyin:"nǐ hǎo",       pos:"",      viet:"chào bạn",                                          lesson:1, hv:"NỄ HẢO — lit. 'bạn tốt' = chào", radical:"你 = 亻(NHÂN — người) + 尔(NHĨ — bạn) → một người gọi 'bạn' | 好 = 女(NỮ — phụ nữ) + 子(TỬ — con) → mẹ bồng con = tốt/lành" },
  { char:"好",     pinyin:"hǎo",           pos:"adj.",  viet:"tốt, khỏe, hay, ngon",                              lesson:1, hv:"HẢO — tốt (như 'hảo cảm', 'hảo hán')", radical:"女(NỮ — phụ nữ) + 子(TỬ — con) → mẹ bồng con = tốt/lành" },
  { char:"你",     pinyin:"nǐ",            pos:"pron.", viet:"bạn, anh, chị... (ngôi thứ 2 số ít)",               lesson:1, hv:"NỄ — bạn (đại từ ngôi 2)", radical:"亻(NHÂN — người) + 尔(NHĨ — bạn) → một người gọi 'bạn'" },
  { char:"是",     pinyin:"shì",           pos:"v.",    viet:"là, thì...",                                         lesson:1, hv:"THỊ — là (như 'thị phi', 'như thị')", radical:"日(NHẬT — mặt trời) + 正(CHÍNH — đúng/thẳng) → mặt trời đứng thẳng = đúng/là" },
  { char:"老师",   pinyin:"lǎoshī",        pos:"n.",    viet:"giáo viên, thầy/cô giáo",                           lesson:1, hv:"LÃO SƯ — thầy/cô (dùng trong võ thuật, văn học)", radical:"老 = 土(THỔ — đất) + 人(NHÂN — người) + 匕 → người già bám rễ trên đất | 师 = 帀 + 巾(CÂN — vải) → sư phụ truyền dạy" },
  { char:"吗",     pinyin:"ma",            pos:"part.", viet:"...không? ...à? (trợ từ nghi vấn)",                  lesson:1, hv:"MA — trợ từ nghi vấn (HV ít dùng)", radical:"口(KHẨU — miệng) + 马(MÃ — ngựa) → trợ từ phiên âm — coi như ký hiệu nghi vấn" },
  { char:"了",     pinyin:"le",            pos:"part.", viet:"rồi, đã (trợ từ chỉ hoàn thành/biến đổi)",            lesson:1, hv:"LIỄU — hoàn thành (như 'liễu kết', 'liễu giải')", radical:"móc 2 nét đơn — coi như ký hiệu của 'hoàn thành'" },
  { char:"不",     pinyin:"bù",            pos:"adv.",  viet:"không (trợ từ phủ định)",                            lesson:1, hv:"BẤT — không (như 'bất công', 'bất an')", radical:"tượng hình con chim bay lên không tới = không/chưa" },
  { char:"我",     pinyin:"wǒ",            pos:"pron.", viet:"tôi, tớ, mình... (ngôi thứ nhất số ít)",            lesson:1, hv:"NGÃ — tôi (như 'bản ngã', 'tự ngã')", radical:"tượng hình bàn tay (手) cầm vũ khí (戈 — giáo) → 'cầm giáo bảo vệ mình' = tôi/ta" },
  { char:"学生",   pinyin:"xuésheng",      pos:"n.",    viet:"học sinh",                                           lesson:1, hv:"HỌC SINH — giống hệt tiếng Việt!", radical:"学 = 冖(MIÊN — mái) + 子(TỬ — con) + 爻(học vấn) → đứa trẻ dưới mái học chữ | 生 = 土(THỔ — đất) + 丿 → cây con mọc lên khỏi đất = sinh/sống" },
  { char:"她",     pinyin:"tā",            pos:"pron.", viet:"cô ấy, chị ấy, nó (nữ, ngôi thứ 3 số ít)",         lesson:1, hv:"THA — cô ấy (như 'tha hương', 'tha nhân')", radical:"女(NỮ — phụ nữ) + 也(DÃ — cũng) → cô ấy (dạng nữ của 他)" },
  { char:"谢谢",   pinyin:"xièxie",        pos:"v.",    viet:"cảm ơn",                                            lesson:1, hv:"TẠ TẠ — cảm tạ (lặp 2 lần)", radical:"讠(NGÔN — lời nói) + 射(XẠ — bắn) → bắn ra lời cảm ơn (lặp 2 lần để nhấn mạnh)" },
  { char:"不客气", pinyin:"bú kèqi",        pos:"",      viet:"đừng khách sáo",                                    lesson:1, hv:"BẤT KHÁCH KHÍ — đừng khách khí", radical:"不(BẤT — không) | 客(KHÁCH) = 宀(MIÊN — mái) + 各(CÁC — chỉ thanh) → khách dưới mái | 气(KHÍ — khí/thái độ) → 'không khách khí' = đừng khách sáo" },
  { char:"您",     pinyin:"nín",           pos:"pron.", viet:"ông, bà, cô, chú, anh, chị... (trang trọng, số ít)", lesson:1, hv:"kính ngữ của 你 (NỄ) — HV ít dùng", radical:"你(NỄ — bạn) đặt trên 心(TÂM — tim) → 'gọi bạn từ trái tim' = bạn (kính ngữ)" },
  { char:"留学生", pinyin:"liúxuéshēng",    pos:"n.",    viet:"lưu học sinh",                                      lesson:1, hv:"LƯU HỌC SINH — giống hệt tiếng Việt!", radical:"留 = 田(ĐIỀN — ruộng) + 刀 + 口 → ở lại làm việc trên đồng ruộng | 学 = đứa trẻ dưới mái học chữ | 生 = cây con mọc lên = người" },
  { char:"叫",     pinyin:"jiào",          pos:"v.",    viet:"gọi, kêu",                                           lesson:1, hv:"KHIẾU — gọi (như 'khiếu nại')", radical:"口(KHẨU — miệng) + 丩(âm xoắn) → miệng kêu lên = gọi/kêu" },
  { char:"什么",   pinyin:"shénme",        pos:"pron.", viet:"gì, cái gì?",                                        lesson:1, hv:"THẬM MA — gì (HV ít dùng)" },
  { char:"名字",   pinyin:"míngzi",        pos:"n.",    viet:"tên, họ tên",                                        lesson:1, hv:"DANH TỰ — tên (danh=tên, tự=chữ)", radical:"名 = 夕(TỊCH — chiều tối) + 口(KHẨU — miệng) → gọi tên trong bóng tối | 字 = 宀(MIÊN — mái) + 子(TỬ — con) → đứa trẻ dưới mái học chữ" },
  { char:"大卫",   pinyin:"Dàwèi",         pos:"n.",    viet:"David (tên người)",                                  lesson:1, hv:"ĐẠI VỆ — phiên âm 'David'" },
  { char:"王",     pinyin:"Wáng",          pos:"n.",    viet:"Vương (họ)",                                          lesson:1, hv:"VƯƠNG — vua / họ Vương (như 'vương quốc')" },
  { char:"李军",   pinyin:"Lǐ Jūn",        pos:"n.",    viet:"Lý Quân (tên người)",                                lesson:1, hv:"LÝ QUÂN — họ Lý + tên Quân" },
  { char:"还没",   pinyin:"hái méi",       pos:"adv.",  viet:"chưa",                                                lesson:1, hv:"HOÀN MỘT — vẫn chưa (HOÀN = vẫn, MỘT = không)", radical:"还 = 辶(SƯỚC — di chuyển) + 不 → vẫn đi, chưa tới | 没 = 氵(THỦY — nước) + 殳 → bị chìm = chưa/không" },
  { char:"工作",   pinyin:"gōngzuò",       pos:"v./n.", viet:"đi làm, công việc",                                   lesson:1, hv:"CÔNG TÁC — công việc / công tác", radical:"工 = thước thợ mộc = công việc | 作 = 亻(NHÂN — người) + 乍(thoắt) → người làm gì đó = chế tạo/làm" },

  // ── Lesson 2 ──
  { char:"同学",   pinyin:"tóngxué",       pos:"n.",    viet:"bạn cùng học",                                       lesson:2, hv:"ĐỒNG HỌC — bạn cùng lớp", radical:"同 = 冂(khung) + 口(KHẨU — miệng) → các miệng trong cùng khung = cùng nhau | 学 = đứa trẻ dưới mái học chữ" },
  { char:"们",     pinyin:"men",           pos:"suff.", viet:"hậu tố chỉ người ở số nhiều",                        lesson:2, hv:"MÔN — hậu tố số nhiều (HV ít dùng)", radical:"亻(NHÂN — người) + 门(MÔN — cửa) → người người qua cửa = hậu tố số nhiều" },
  { char:"来",     pinyin:"lái",           pos:"v.",    viet:"đến, tới",                                            lesson:2, hv:"LAI — đến (như 'tương lai', 'lai lịch')", radical:"tượng hình bông lúa — hạt lúa đến = đến/tới" },
  { char:"介绍",   pinyin:"jièshào",       pos:"v.",    viet:"giới thiệu",                                         lesson:2, hv:"GIỚI THIỆU — giống hệt tiếng Việt!", radical:"介(GIỚI — đứng giữa) = 人 + 八 → người đứng giữa | 绍(THIỆU) = 纟(MỊCH — sợi) + 召(TRIỆU — chỉ thanh) → kết nối → 'người đứng giữa kết nối' = giới thiệu" },
  { char:"一下儿", pinyin:"yíxiàr",         pos:"q.",    viet:"một chút",                                           lesson:2, hv:"NHẤT HẠ — một chút (lit. 'một lần xuống')", radical:"一(NHẤT — một) | 下(HẠ) = nét dưới đường ngang → dưới/xuống → 'một lần xuống' = một chút" },
  { char:"姓",     pinyin:"xìng",          pos:"v./n.", viet:"họ (của tên)",                                        lesson:2, hv:"TÍNH — họ (như 'họ tên')", radical:"女(NỮ — phụ nữ) + 生(SINH — sinh) → họ truyền qua bên mẹ = họ" },
  { char:"的",     pinyin:"de",            pos:"part.", viet:"trợ từ",                                              lesson:2, hv:"ĐÍCH — trợ từ sở hữu (HV gốc nhưng nghĩa khác)" },
  { char:"哪",     pinyin:"nǎ",            pos:"pron.", viet:"nào",                                                lesson:2, hv:"NA — nào (đại từ nghi vấn)", radical:"口(KHẨU — miệng) + 那(kia) → miệng hỏi 'cái nào?'" },
  { char:"国",     pinyin:"guó",           pos:"n.",    viet:"nước, quốc gia",                                     lesson:2, hv:"QUỐC — nước (như 'quốc gia', 'quốc tế')", radical:"囗(viền/biên) + 玉(NGỌC — ngọc) → ngọc quý trong biên giới = nước" },
  { char:"人",     pinyin:"rén",           pos:"n.",    viet:"người",                                               lesson:2, hv:"NHÂN — người (như 'nhân loại', 'nhân văn')", radical:"tượng hình người đứng dang chân" },
  { char:"他",     pinyin:"tā",            pos:"pron.", viet:"anh ấy, ông ấy...",                                  lesson:2, hv:"THA — anh ấy (như 'tha nhân')", radical:"亻(NHÂN — người) + 也(DÃ — cũng) → anh ấy (dạng nam của 她)" },
  { char:"认识",   pinyin:"rènshi",        pos:"v.",    viet:"quen biết",                                           lesson:2, hv:"NHẬN THỨC — quen biết", radical:"认(NHẬN) = 讠(NGÔN — lời) + 人(chỉ thanh) → nhận biết | 识(THỨC) = 讠(NGÔN — lời) + 只(chỉ thanh) → biết → 'nhận + biết' = quen biết" },
  { char:"很",     pinyin:"hěn",           pos:"adv.",  viet:"rất",                                                lesson:2, hv:"NGẪN — rất (HV ít dùng)", radical:"彳(SÁCH — bước) + 艮(CẤN — vững) → bước đi vững chắc = rất" },
  { char:"高兴",   pinyin:"gāoxìng",       pos:"adj.",  viet:"vui mừng",                                           lesson:2, hv:"CAO HỨNG — vui, hứng khởi", radical:"高(CAO) = hình tòa nhà cao = cao | 兴(HƯNG) = tượng hình bốn tay cùng nâng vật lên = hưng phấn → 'lòng dâng cao' = vui mừng" },
  { char:"也",     pinyin:"yě",            pos:"adv.",  viet:"cũng",                                               lesson:2, hv:"DÃ — cũng (như 'dã thị')", radical:"nét cong đơn — trợ từ 'cũng', coi như ký hiệu" },
  { char:"呢",     pinyin:"ne",            pos:"part.", viet:"trợ từ",                                              lesson:2, hv:"NỊ — trợ từ (HV ít dùng)" },
  { char:"中国",   pinyin:"Zhōngguó",      pos:"n.",    viet:"Trung Quốc",                                         lesson:2, hv:"TRUNG QUỐC — giống hệt tiếng Việt!", radical:"中 = nét dọc xuyên giữa hình chữ nhật → trúng tâm | 国 = ngọc trong biên giới" },
  { char:"美国",   pinyin:"Měiguó",        pos:"n.",    viet:"Mỹ",                                                  lesson:2, hv:"MỸ QUỐC — giống hệt tiếng Việt!", radical:"美 = 羊(DƯƠNG — cừu) + 大(ĐẠI — to) → cừu to đẹp = đẹp | 国 = nước" },
  { char:"英国",   pinyin:"Yīngguó",       pos:"n.",    viet:"Anh",                                                 lesson:2, hv:"ANH QUỐC — giống hệt tiếng Việt!", radical:"英(ANH — bông hoa nổi bật / Anh quốc) — bộ 艹(THẢO — cỏ) gợi hoa | 国 = nước → nước Anh" },
  { char:"法国",   pinyin:"Fǎguó",         pos:"n.",    viet:"Pháp",                                                lesson:2, hv:"PHÁP QUỐC — giống hệt tiếng Việt!", radical:"法(PHÁP — pháp luật/cách thức) — bộ 氵(THỦY — nước) | 国(QUỐC — nước) → 'pháp quốc' = nước Pháp" },
  { char:"加拿大", pinyin:"Jiānádà",        pos:"n.",    viet:"Canada",                                              lesson:2, hv:"GIA NÃ ĐẠI — phiên âm 'Canada'" },
  { char:"日本",   pinyin:"Rìběn",         pos:"n.",    viet:"Nhật Bản",                                            lesson:2, hv:"NHẬT BẢN — giống hệt tiếng Việt!", radical:"日(NHẬT — mặt trời) | 本 = 木(MỘC — cây) + 一 → vạch ở gốc cây = gốc/nguồn" },
  { char:"韩国",   pinyin:"Hánguó",        pos:"n.",    viet:"Hàn Quốc",                                            lesson:2, hv:"HÀN QUỐC — giống hệt tiếng Việt!", radical:"韩 = chữ phức tạp — nhận biết hình dạng | 国 = nước" },
  { char:"越南",   pinyin:"Yuènán",        pos:"n.",    viet:"Việt Nam",                                            lesson:2, hv:"VIỆT NAM — giống hệt tiếng Việt!", radical:"越 = 走(TẨU — đi) + 戉(VIỆT — rìu) → đi vượt qua | 南 = 十 + 冂 + 里 → dấu hướng = phía nam" },

  // ── Lesson 3 ──
  { char:"那",     pinyin:"nà",            pos:"pron.", viet:"kia, đó",                                            lesson:3, hv:"NA — kia/đó (đại từ chỉ định xa)", radical:"阝(PHỤ — thành/đất) + 冉(NHIỄM — chậm) → nơi xa kia = đó/kia" },
  { char:"谁",     pinyin:"shéi/shuí",     pos:"pron.", viet:"ai, người nào",                                      lesson:3, hv:"THÙY — ai (văn cổ, như 'thùy hỉ')", radical:"讠(NGÔN — lời, bộ thủ) + 隹(CHUỲ — chim đuôi ngắn, chỉ thanh) → từ nghi vấn = ai" },
  { char:"书",     pinyin:"shū",           pos:"n.",    viet:"quyển sách",                                         lesson:3, hv:"THƯ — sách (như 'thư viện', 'thư từ')", radical:"tượng hình bút lông đang viết = sách" },
  { char:"同屋",   pinyin:"tóngwū",        pos:"n.",    viet:"bạn cùng phòng",                                     lesson:3, hv:"ĐỒNG ỐC — cùng nhà/phòng", radical:"同(ĐỒNG — cùng) | 屋(ỐC) = 尸(THI — mái nhà cách điệu) + 至(CHÍ — đến) → 'đến dưới một mái' = phòng → bạn cùng phòng" },
  { char:"汉语",   pinyin:"Hànyǔ",         pos:"n.",    viet:"tiếng Hán",                                          lesson:3, hv:"HÁN NGỮ — tiếng Hán/tiếng Trung", radical:"汉(HÁN — dân tộc Hán / sông Hán) — bộ 氵(THỦY — nước) | 语(NGỮ) = 讠(NGÔN — lời) + 吾(NGÔ — chỉ thanh) → ngôn ngữ → tiếng Hán" },
  { char:"课本",   pinyin:"kèběn",         pos:"n.",    viet:"sách giáo khoa, giáo trình",                         lesson:3, hv:"KHÓA BẢN — bản của bài học (sách giáo trình)", radical:"课(KHÓA) = 讠(NGÔN — lời) + 果(QUẢ — chỉ thanh) → bài học | 本(BẢN) = 木(MỘC — cây) + 一 → vạch ở gốc cây = sách/cuốn → sách giáo khoa" },
  { char:"词典",   pinyin:"cídiǎn",        pos:"n.",    viet:"từ điển",                                             lesson:3, hv:"TỪ ĐIỂN — giống hệt tiếng Việt!", radical:"词(TỪ) = 讠(NGÔN — lời) + 司(TƯ — chỉ thanh, gợi 'quản') → từ ngữ | 典(ĐIỂN — sách kinh điển) → 'sách quản từ' = từ điển" },
  { char:"就是",   pinyin:"jiù shì",       pos:"",      viet:"điều đó nghĩa là",                                   lesson:3, hv:"TỰU THỊ — chính là (TỰU = liền/ngay, THỊ = là)", radical:"就 = 京(KINH — kinh đô) + 尤(VƯU — đặc biệt) → đúng tại kinh đô = tức là | 是 = mặt trời thẳng = là" },
  { char:"日语",   pinyin:"Rìyǔ",          pos:"n.",    viet:"tiếng Nhật",                                         lesson:3, hv:"NHẬT NGỮ — tiếng Nhật", radical:"日(NHẬT — mặt trời/Nhật Bản) | 语(NGỮ) = 讠(NGÔN — lời) + 吾(NGÔ — chỉ thanh) → ngôn ngữ → tiếng Nhật" },
  { char:"这",     pinyin:"zhè",           pos:"pron.", viet:"này, đây",                                           lesson:3, hv:"GIÁ — này/đây (đại từ chỉ định gần)", radical:"辶(SƯỚC — di chuyển) + 文(VĂN — chữ/văn) → di chuyển về phía này = này" },
  { char:"杂志",   pinyin:"zázhì",         pos:"n.",    viet:"tạp chí",                                             lesson:3, hv:"TẠP CHÍ — giống hệt tiếng Việt!", radical:"杂(TẠP — pha trộn) | 志(CHÍ — ghi chép) = 士(SĨ — kẻ sĩ) + 心(TÂM — tim) → 'ghi chép pha tạp' = tạp chí" },
  { char:"音乐",   pinyin:"yīnyuè",        pos:"n.",    viet:"âm nhạc",                                            lesson:3, hv:"ÂM NHẠC — giống hệt tiếng Việt!", radical:"音(ÂM — âm thanh) = 立 + 日 | 乐(NHẠC) — tượng hình nhạc cụ có dây trên giá gỗ → âm + nhạc" },
  { char:"朋友",   pinyin:"péngyou",       pos:"n.",    viet:"bạn, bạn bè",                                        lesson:3, hv:"BẰNG HỮU — bạn bè (văn học)", radical:"朋 = hai 月(NGUYỆT — trăng) cạnh nhau → hai trăng kề bên = bạn | 友 = 又(HỰU — tay) + 又 → hai tay nắm = bạn" },
  { char:"语言",   pinyin:"yǔyán",        pos:"n.",    viet:"ngôn ngữ",                                           lesson:3, hv:"NGỮ NGÔN — = ngôn ngữ (đảo vị trí)", radical:"语 = 讠(NGÔN — lời) + 吾(NGÔ — tôi) → lời của tôi | 言 = 口(KHẨU — miệng) + nét ngang → lời từ miệng = lời nói" },
  { char:"说",     pinyin:"shuō",         pos:"v.",    viet:"nói",                                                 lesson:3, hv:"THUYẾT — nói (như 'thuyết minh', 'tiểu thuyết')", radical:"讠(NGÔN — lời, bộ thủ) + 兑(ĐOÀI — chỉ thanh) → nói" },
  { char:"会",     pinyin:"huì",          pos:"v.",    viet:"biết (qua rèn luyện, học hỏi)",                       lesson:3, hv:"HỘI — biết qua học (như 'lĩnh hội', 'cơ hội')", radical:"亼(tụ tập) + 曰(VIẾT — nói) → người tụ lại để nói = biết/hội" },
  { char:"本",     pinyin:"běn",          pos:"mw.",   viet:"cuốn, quyển",                                         lesson:3, hv:"BẢN — cuốn/quyển (như 'phiên bản', 'cơ bản')", radical:"木(MỘC — cây) + 一 → vạch tại gốc cây = gốc/quyển (lượng từ)" },
  { char:"喜欢",   pinyin:"xǐhuan",       pos:"v.",    viet:"thích",                                               lesson:3, hv:"HỶ HOAN — vui thích", radical:"喜 = 壴(trống) + 口(KHẨU — miệng) → miệng bên trống = vui | 欢 = 又(HỰU — tay) + 欠(KHIẾM — há miệng) → dang tay đón = vui mừng" },
  { char:"看",     pinyin:"kàn",          pos:"v.",    viet:"xem, nhìn, đọc",                                      lesson:3, hv:"KHÁN — xem (như 'khán giả', 'khán đài')", radical:"手(THỦ — tay) trên 目(MỤC — mắt) → tay che mắt nhìn xa = xem" },
  { char:"听",     pinyin:"tīng",         pos:"v.",    viet:"nghe",                                                lesson:3, hv:"THÍNH — nghe (như 'thính giả')", radical:"口(KHẨU — miệng, bộ thủ) + 斤(CÂN — chỉ thanh) → giản thể của 聽 (gốc phức tạp) = nghe" },

  // ── Lesson 4 ──
  { char:"请问",   pinyin:"qǐngwèn",      pos:"v.",    viet:"xin hỏi",                                             lesson:4, hv:"THỈNH VẤN — xin hỏi", radical:"请(THỈNH) = 讠(NGÔN — lời) + 青(THANH — chỉ thanh) → lời lịch sự = xin/mời | 问(VẤN) = 门(MÔN — cửa) + 口(KHẨU — miệng) → miệng hỏi tại cửa = hỏi" },
  { char:"图书馆", pinyin:"túshūguǎn",    pos:"n.",    viet:"thư viện",                                            lesson:4, hv:"ĐỒ THƯ QUÁN — thư viện (lit. 'quán đồ thư')", radical:"图 = 囗(biên) + 冬(họa tiết) → họa tiết khép kín = bản đồ | 书 = bút lông viết = sách | 馆 = 饣(THỰC — ăn) + 官(QUAN — quan) → quán quan tiếp khách = quán/viện" },
  { char:"在",     pinyin:"zài",          pos:"v./adv.", viet:"ở, đang",                                           lesson:4, hv:"TẠI — ở (như 'hiện tại', 'tồn tại')", radical:"才(TÀI — tài năng/tay) + 土(THỔ — đất) → tay cắm xuống đất = ở/đang" },
  { char:"哪儿",   pinyin:"nǎr",          pos:"pron.", viet:"ở đâu, chỗ nào",                                      lesson:4, hv:"NA NHI — ở đâu", radical:"口(KHẨU — miệng) + 那(kia) → giống 哪, hỏi 'nơi nào?' (儿 = hậu tố Bắc Kinh)" },
  { char:"哪里",   pinyin:"nǎli",         pos:"pron.", viet:"ở đâu, chỗ nào",                                      lesson:4, hv:"NA LÝ — ở đâu", radical:"哪 = hỏi 'nào' | 里 = 田(ĐIỀN — ruộng) + 土(THỔ — đất) → trong làng = trong/nơi" },
  { char:"对不起", pinyin:"duìbuqǐ",      pos:"v.",    viet:"xin lỗi",                                             lesson:4, hv:"ĐỐI BẤT KHỞI — xin lỗi (lit. 'không thể đối lại')", radical:"对 = 又(HỰU — tay) + 寸(THỐN — tấc) → tay chính xác = đối/đối diện | 不 = phủ định | 起 = 走(TẨU — đi) + 己(KỶ — mình) → mình đứng dậy = khởi" },
  { char:"个",     pinyin:"gè",           pos:"mw.",   viet:"lượng từ chung (cho người, đồ vật)",                 lesson:4, hv:"CÁ — lượng từ chung (như 'cá nhân')", radical:"亻(NHÂN — người) + 丨(nét dọc) → đơn vị một người — lượng từ chung" },
  { char:"学校",   pinyin:"xuéxiào",      pos:"n.",    viet:"trường học",                                          lesson:4, hv:"HỌC HIỆU — trường học", radical:"学(HỌC) = đứa trẻ dưới mái học chữ | 校(HIỆU) = 木(MỘC — gỗ, bộ thủ) + 交(GIAO — chỉ thanh) → công trình gỗ học tập = trường" },
  { char:"知道",   pinyin:"zhīdào",       pos:"v.",    viet:"biết",                                                lesson:4, hv:"TRI ĐẠO — biết (như 'tri thức')", radical:"知 = 矢(THỈ — mũi tên) + 口(KHẨU — miệng) → lời thẳng như tên = biết | 道 = 辶(SƯỚC — di chuyển) + 首(THỦ — đầu) → đầu dẫn đường = đường/đạo" },
  { char:"没关系", pinyin:"méi guānxi",   pos:"",      viet:"không sao, không có gì",                              lesson:4, hv:"MỘT QUAN HỆ — không sao (lit. 'không có quan hệ gì')", radical:"没 = không có | 关(QUAN — liên quan, đóng/mở) | 系(HỆ) = 纟(MỊCH — sợi) → mối nối → 'không có quan hệ' = không sao" },
  { char:"这儿",   pinyin:"zhèr",         pos:"pron.", viet:"chỗ này, nơi này",                                    lesson:4, hv:"GIÁ NHI — chỗ này", radical:"这 = di chuyển về này = này (儿 = hậu tố Bắc Kinh)" },
  { char:"这里",   pinyin:"zhèli",        pos:"pron.", viet:"chỗ này, nơi này",                                    lesson:4, hv:"GIÁ LÝ — chỗ này", radical:"这 = này | 里 = trong/nơi → nơi này" },
  { char:"教学",   pinyin:"jiàoxué",      pos:"n.",    viet:"dạy học",                                             lesson:4, hv:"GIÁO HỌC — giống hệt tiếng Việt!", radical:"教 = 爻(học vấn) + 子(TỬ — con) + 攴(gõ nhẹ) → gõ nhắc trẻ học = dạy | 学 = đứa trẻ dưới mái học" },
  { char:"楼",     pinyin:"lóu",          pos:"n.",    viet:"tòa nhà",                                             lesson:4, hv:"LÂU — tòa nhà (như 'lâu đài', 'cao lâu')", radical:"木(MỘC — gỗ, bộ thủ) + 娄(LÂU — chỉ thanh) → công trình gỗ nhiều tầng = lầu/tầng" },
  { char:"那儿",   pinyin:"nàr",          pos:"pron.", viet:"chỗ kia, nơi kia",                                    lesson:4, hv:"NA NHI — chỗ kia", radical:"那 = đó/kia (儿 = hậu tố Bắc Kinh)" },
  { char:"那里",   pinyin:"nàli",         pos:"pron.", viet:"chỗ kia, nơi kia",                                    lesson:4, hv:"NA LÝ — chỗ kia", radical:"那 = đó | 里 = nơi → nơi đó" },
  { char:"宿舍",   pinyin:"sùshè",        pos:"n.",    viet:"ký túc xá",                                           lesson:4, hv:"TÚC XÁ — giống hệt tiếng Việt!", radical:"宿(TÚC — trú đêm) = 宀(MIÊN — mái) + 亻(NHÂN — người) + 百(BÁCH — trăm) → 'nhiều người dưới một mái' | 舍(XÁ — nhà trọ giản đơn) → ký túc xá" },
  { char:"北边",   pinyin:"běibian",      pos:"n.",    viet:"phía bắc",                                            lesson:4, hv:"BẮC BIÊN — phía bắc", radical:"北 = hai người đứng quay lưng → quay đi = bắc | 边 = 辶(SƯỚC — di chuyển) + 力(LỰC — sức) → cạnh/phía" },
  { char:"左边",   pinyin:"zuǒbian",      pos:"n.",    viet:"bên trái",                                            lesson:4, hv:"TẢ BIÊN — bên trái", radical:"左 = 工(CÔNG — thợ) + 手(THỦ — tay) → tay làm việc (theo lịch sử là tay trái) | 边 = phía" },
  { char:"右边",   pinyin:"yòubian",      pos:"n.",    viet:"bên phải",                                            lesson:4, hv:"HỮU BIÊN — bên phải", radical:"右 = 口(KHẨU — miệng) + 手(THỦ — tay) → tay ăn/nói (theo lịch sử là tay phải) | 边 = phía" },
  { char:"上边",   pinyin:"shàngbian",    pos:"n.",    viet:"phía trên",                                           lesson:4, hv:"THƯỢNG BIÊN — phía trên", radical:"上(THƯỢNG) = vạch trên đường ngang → trên/phía trên | 边 = phía" },
  { char:"下边",   pinyin:"xiàbian",      pos:"n.",    viet:"phía dưới",                                           lesson:4, hv:"HẠ BIÊN — phía dưới", radical:"下(HẠ) = vạch dưới đường ngang → dưới/phía dưới | 边 = phía" },
  { char:"不用谢", pinyin:"búyòng xiè",   pos:"",      viet:"không cần cảm ơn, không có gì",                       lesson:4, hv:"BẤT DỤNG TẠ — không cần cảm tạ", radical:"不(BẤT — không) | 用(DỤNG — cần dùng) | 谢(TẠ — cảm ơn) = 讠(NGÔN — lời) + 射(XẠ — chỉ thanh) → 'không cần tạ' = không có gì" },
  { char:"不用",   pinyin:"búyòng",       pos:"adv.",  viet:"không cần",                                           lesson:4, hv:"BẤT DỤNG — không cần", radical:"不(BẤT — không) | 用(DỤNG — dùng/cần) → không cần" },
  { char:"对",     pinyin:"duì",          pos:"adj.",  viet:"đúng",                                                lesson:4, hv:"ĐỐI — đúng (như 'đối phó', 'đối với')", radical:"又(HỰU — tay) + 寸(THỐN — tấc) → đo lường chính xác = đúng/đối diện" },

  // ── Lesson 5 ──
  { char:"有",     pinyin:"yǒu",          pos:"v.",    viet:"có",                                                  lesson:5, hv:"HỮU — có (giống tiếng Việt!)", radical:"月(NGUYỆT — trăng) + 又(HỰU — tay) → tay nắm trăng = có" },
  { char:"有用",   pinyin:"yǒuyòng",      pos:"adj.",  viet:"có ích, hữu dụng",                                    lesson:5, hv:"HỮU DỤNG — giống hệt tiếng Việt!", radical:"有 = có | 用(DỤNG) = dụng cụ = dùng → có ích" },
  { char:"有名",   pinyin:"yǒumíng",      pos:"adj.",  viet:"nổi tiếng",                                           lesson:5, hv:"HỮU DANH — có danh tiếng", radical:"有 = có | 名 = 夕(TỊCH — chiều tối) + 口(KHẨU — miệng) → gọi tên trong tối = nổi danh" },
  { char:"空儿",   pinyin:"kòngr",        pos:"n.",    viet:"thời gian rảnh, lúc rảnh",                            lesson:5, hv:"KHÔNG — trống, rảnh (như 'không khí', 'không gian')", radical:"空(KHÔNG) = 穴(HUYỆT — hang) + 工(CÔNG — chỉ thanh) → khoảng trống = rảnh/trống" },
  { char:"时候",   pinyin:"shíhou",       pos:"n.",    viet:"lúc, khi, thời gian",                                 lesson:5, hv:"THỜI HẦU — lúc/khi", radical:"时(THỜI) = 日(NHẬT — mặt trời) + 寺(TỰ — chỉ thanh) → mặt trời / thời gian | 候(HẦU) = 亻(NHÂN — người) + chỉ thanh → 'người đợi thời gian' = lúc/khoảnh khắc" },
  { char:"欢迎",   pinyin:"huānyíng",     pos:"v.",    viet:"hoan nghênh, chào đón",                               lesson:5, hv:"HOAN NGHÊNH — giống hệt tiếng Việt!", radical:"欢 = 又(HỰU — tay) + 欠(KHIẾM — há miệng) → dang tay đón = vui | 迎 = 辶(SƯỚC — di chuyển) + 卬(người ngước nhìn) → ra đón = nghênh" },
  { char:"去",     pinyin:"qù",           pos:"v.",    viet:"đi",                                                  lesson:5, hv:"KHỨ — đi (trong 'quá khứ')", radical:"土(THỔ — đất) + 厶(TƯ — riêng/rời) → 'rời đất ra đi' = đi" },
  { char:"玩儿",   pinyin:"wánr",         pos:"v.",    viet:"chơi",                                                lesson:5, hv:"NGOẠN — chơi (như 'ngoạn mục', 'du ngoạn')", radical:"玩(NGOẠN) = 王(VƯƠNG/NGỌC — bộ ngọc, gợi 'vật quý') + 元(NGUYÊN — chỉ thanh) → chơi (xưa quý tộc chơi ngọc)" },
  { char:"卫生间", pinyin:"wèishēngjiān", pos:"n.",    viet:"nhà vệ sinh",                                         lesson:5, hv:"VỆ SINH GIAN — giống tiếng Việt!", radical:"卫 = 行(HÀNH — đi) + 口 → bảo vệ di chuyển = vệ | 生(SINH) = sinh sôi = vệ sinh | 间 = 门(MÔN — cửa) + 日(NHẬT — mặt trời) → ánh sáng qua cửa = phòng/khoảng" },
  { char:"教室",   pinyin:"jiàoshì",      pos:"n.",    viet:"phòng học, lớp học",                                  lesson:5, hv:"GIÁO THẤT — phòng học", radical:"教(GIÁO — dạy, gõ nhắc trẻ học) | 室(THẤT — phòng) = 宀(MIÊN — mái) + 至(CHÍ — đến) → 'phòng để dạy' = lớp học" },
  { char:"旁边",   pinyin:"pángbiān",     pos:"n.",    viet:"bên cạnh",                                            lesson:5, hv:"BÀNG BIÊN — bên cạnh", radical:"旁(BÀNG — bên cạnh) | 边(BIÊN — cạnh/phía) → 'bàng biên' = phía bên cạnh" },
  { char:"西边",   pinyin:"xībiān",       pos:"n.",    viet:"phía tây",                                            lesson:5, hv:"TÂY BIÊN — phía tây", radical:"西(TÂY) — tượng hình chim đậu vào tổ lúc hoàng hôn = hướng tây | 边 = cạnh/phía" },
  { char:"小",     pinyin:"xiǎo",         pos:"adj.",  viet:"nhỏ, bé",                                             lesson:5, hv:"TIỂU — nhỏ (như 'tiểu học', 'tiểu thuyết')", radical:"nét giữa với hai chấm hai bên — trông nhỏ = nhỏ" },
  { char:"中",     pinyin:"zhōng",        pos:"adj.",  viet:"vừa, trung bình",                                     lesson:5, hv:"TRUNG — giữa (như 'trung học', 'trung tâm')", radical:"nét dọc xuyên giữa hình chữ nhật = giữa/trung tâm" },
  { char:"大",     pinyin:"dà",           pos:"adj.",  viet:"to, lớn",                                             lesson:5, hv:"ĐẠI — lớn (như 'đại học', 'đại sứ')", radical:"人(NHÂN — người) dang tay rộng = to/lớn" },
  { char:"没有",   pinyin:"méiyǒu",       pos:"v.",    viet:"không có",                                            lesson:5, hv:"MỘT HỮU — phủ định của 有 (có)", radical:"没 = 氵(THỦY — nước) + 殳 → bị chìm = không/thiếu | 有 = có → không có" },
  { char:"北京",   pinyin:"Běijīng",      pos:"n.",    viet:"Bắc Kinh",                                            lesson:5, hv:"BẮC KINH — giống hệt tiếng Việt!", radical:"北 = hai người quay lưng = bắc | 京(KINH) = 亠 + 口 + 小 → tòa nhà cao trong kinh đô" },

  // ── Lesson 6 ──
  { char:"一",     pinyin:"yī",           pos:"num.",  viet:"một, 1",                                              lesson:6, hv:"NHẤT — một (như 'nhất quán', 'thứ nhất')", radical:"một nét ngang đơn = một" },
  { char:"二",     pinyin:"èr",           pos:"num.",  viet:"hai, 2",                                              lesson:6, hv:"NHỊ — hai (như 'nhị thập', 'thứ nhị')", radical:"hai nét ngang = hai" },
  { char:"三",     pinyin:"sān",          pos:"num.",  viet:"ba, 3",                                               lesson:6, hv:"TAM — ba (như 'tam giác', 'tam quốc')", radical:"ba nét ngang = ba" },
  { char:"四",     pinyin:"sì",           pos:"num.",  viet:"bốn, 4",                                              lesson:6, hv:"TỨ — bốn (như 'tứ giác', 'tứ phương')", radical:"囗(biên) + 儿(hai chân) → bốn chân trong hộp = bốn" },
  { char:"五",     pinyin:"wǔ",           pos:"num.",  viet:"năm, 5",                                              lesson:6, hv:"NGŨ — năm (như 'ngũ vị', 'ngũ hành')", radical:"tiến hóa từ vạch đếm 5 nét" },
  { char:"六",     pinyin:"liù",          pos:"num.",  viet:"sáu, 6",                                              lesson:6, hv:"LỤC — sáu (như 'lục địa', 'lục giác')", radical:"亠(chấm trên) + 八(BÁT — chia/tám) → hình của số sáu" },
  { char:"七",     pinyin:"qī",           pos:"num.",  viet:"bảy, 7",                                              lesson:6, hv:"THẤT — bảy (như 'thất bại', 'thất tịch')", radical:"nhìn như số 7 ngược — neo thị giác đơn giản" },
  { char:"八",     pinyin:"bā",           pos:"num.",  viet:"tám, 8",                                              lesson:6, hv:"BÁT — tám (như 'bát giác')", radical:"hai nét tách ra = chia/tám" },
  { char:"九",     pinyin:"jiǔ",          pos:"num.",  viet:"chín, 9",                                             lesson:6, hv:"CỬU — chín (như 'cửu vạn')", radical:"nét móc đơn = gần mười = chín" },
  { char:"十",     pinyin:"shí",          pos:"num.",  viet:"mười, 10",                                            lesson:6, hv:"THẬP — mười (như 'thập kỷ', 'thập niên')", radical:"chữ thập hoàn chỉnh = mười (đối xứng)" },
  { char:"两",     pinyin:"liǎng",        pos:"num.",  viet:"hai (dùng trước lượng từ)",                           lesson:6, hv:"LƯỠNG — hai (như 'lưỡng tính', 'lưỡng cực')", radical:"一 + 冂(khung) + 2 人 bên trong → hai người trong khung = hai (dùng trước lượng từ)" },
  { char:"零",     pinyin:"líng",         pos:"num.",  viet:"số không, 0",                                         lesson:6, hv:"LINH — số 0", radical:"雨(VŨ — mưa) + 令(LỆNH) → giọt mưa rải rác = số không/lẻ" },
  { char:"百",     pinyin:"bǎi",          pos:"num.",  viet:"trăm, 100",                                           lesson:6, hv:"BÁCH — trăm (như 'bách khoa', 'bách phân')", radical:"一(NHẤT — một) + 白(BẠCH — chỉ thanh) → ký hiệu chỉ số đếm = trăm" },
  { char:"点",     pinyin:"diǎn",         pos:"n.",    viet:"giờ (đơn vị thời gian)",                              lesson:6, hv:"ĐIỂM — giờ (điểm trên đồng hồ)", radical:"灬(HỎA — chấm lửa, bộ thủ) + 占(CHIẾM — chỉ thanh) → chấm nhỏ trên mặt đồng hồ = giờ/điểm" },
  { char:"分",     pinyin:"fēn",          pos:"n.",    viet:"phút",                                                lesson:6, hv:"PHÂN — phút (chia nhỏ giờ)", radical:"八(BÁT — chia) + 刀(ĐAO — dao) → dao chia = phút/phần" },
  { char:"半",     pinyin:"bàn",          pos:"n.",    viet:"rưỡi (30 phút), một nửa",                             lesson:6, hv:"BÁN — nửa (như 'bán cầu', 'bán đảo')", radical:"八(BÁT — chia) + 丷 + 十(THẬP — mười) → mười chia đôi = nửa/30 phút" },
  { char:"刻",     pinyin:"kè",           pos:"n.",    viet:"khắc (15 phút)",                                      lesson:6, hv:"KHẮC — giống hệt tiếng Việt!", radical:"刂/刀(ĐAO — dao, bộ thủ) + 亥(HỢI — chỉ thanh, không liên quan heo) → dao khắc dấu = khắc / 15 phút" },
  { char:"差",     pinyin:"chà",          pos:"v.",    viet:"thiếu, kém",                                          lesson:6, hv:"SAI — thiếu, chênh lệch (như 'sai số')", radical:"羊(DƯƠNG — cừu) bị lệch + 工(CÔNG — chỉ thanh) → 'cừu lạc đàn' = sai/thiếu/lệch" },
  { char:"早",     pinyin:"zǎo",          pos:"adj./n.", viet:"sớm; buổi sáng (như 早上)",                          lesson:6, hv:"TẢO — sớm (như 'tảo hôn')", radical:"日(NHẬT — mặt trời) + 十(THẬP — mười) → mặt trời vừa nhú trên đường chân trời = sớm/sáng" },
  { char:"几",     pinyin:"jǐ",           pos:"pron.", viet:"mấy, bao nhiêu (như 几点)",                            lesson:6, hv:"KỶ — mấy/bao nhiêu (số lượng nhỏ)", radical:"hình bàn nhỏ chân cong = mấy/bao nhiêu" },
  { char:"上课",   pinyin:"shàngkè",      pos:"v.",    viet:"vào lớp, đi học",                                     lesson:6, hv:"THƯỢNG KHÓA — lên lớp", radical:"上(THƯỢNG) = vạch trên = lên/bắt đầu | 课(KHÓA) = 讠(NGÔN — lời) + 果(QUẢ — quả) → bài học có kết quả → đi lên lớp" },
  { char:"下课",   pinyin:"xiàkè",        pos:"v.",    viet:"tan học, hết tiết",                                   lesson:6, hv:"HẠ KHÓA — xuống lớp", radical:"下(HẠ) = vạch dưới = xuống/kết thúc | 课(KHÓA) = bài học → lớp xuống/giải tán" },
  { char:"部分",   pinyin:"bùfèn",        pos:"n.",    viet:"phần (như 大部分 = phần lớn)",                          lesson:6, hv:"BỘ PHẬN — giống hệt tiếng Việt!", radical:"部(BỘ — bộ phận, nhóm) | 分(PHÂN) = 八(BÁT — chia) + 刀(ĐAO — dao) → 'một bộ chia ra' = phần" },
  { char:"讲座",   pinyin:"jiǎngzuò",     pos:"n.",    viet:"bài giảng, buổi diễn giảng",                          lesson:6, hv:"GIẢNG TỌA — bài giảng (chỗ giảng)", radical:"讲(GIẢNG) = 讠(NGÔN — lời) + chỉ thanh → giảng giải | 座(TỌA) = 广(NGHIỄM — mái) + 坐(TỌA — ngồi) → 'chỗ ngồi nghe giảng' = bài giảng/buổi giảng" },
  { char:"太",     pinyin:"tài",          pos:"adv.",  viet:"quá (dùng trong 太……了)",                              lesson:6, hv:"THÁI — quá (như 'thái quá')", radical:"大(ĐẠI — lớn) + 丶(chấm) → lớn cộng thêm chút nữa = quá" },
  { char:"开始",   pinyin:"kāishǐ",       pos:"v.",    viet:"bắt đầu",                                             lesson:6, hv:"KHAI THỦY — mở đầu", radical:"开(KHAI — mở) = hai tay đẩy cánh cửa mở | 始(THỦY) = 女(NỮ — bộ nữ, gốc gắn với sinh nở) + 台(ĐÀI — chỉ thanh) → khởi đầu → 'mở + khởi' = bắt đầu" },
  { char:"现在",   pinyin:"xiànzài",      pos:"n./adv.", viet:"bây giờ, hiện tại",                                 lesson:6, hv:"HIỆN TẠI — giống hệt tiếng Việt!", radical:"现(HIỆN) = 王(VƯƠNG/NGỌC — bộ ngọc) + 见(KIẾN — thấy) → 'ngọc lộ ra trước mắt' = hiện ra | 在(TẠI — đang ở) → 'hiện đang' = bây giờ" },
  { char:"一会儿", pinyin:"yíhuìr",       pos:"q.",    viet:"một lát, một chốc",                                   lesson:6, hv:"NHẤT HỘI — một lát", radical:"一(NHẤT — một) + 会(HỘI — gặp/khoảnh khắc) + 儿(hậu tố) → 'một thoáng' = một lát" },
  { char:"见",     pinyin:"jiàn",         pos:"v.",    viet:"gặp, thấy",                                           lesson:6, hv:"KIẾN — thấy/gặp (như 'kiến thức', 'tái kiến')", radical:"目(MỤC — mắt) + 儿(hai chân) → mắt có chân đi gặp = thấy/gặp" },
  { char:"晚",     pinyin:"wǎn",          pos:"adj./n.", viet:"muộn, tối; buổi tối (như 晚上)",                     lesson:6, hv:"VÃN — muộn (như 'vãn cảnh')", radical:"日(NHẬT — mặt trời) + 免(MIỄN — chỉ thanh, gợi 'lánh đi') → mặt trời đã lánh xuống = muộn/tối" },
  { char:"午",     pinyin:"wǔ",           pos:"n.",    viet:"giữa trưa, giờ ngọ (trong 上午/中午/下午)",              lesson:6, hv:"NGỌ — giữa trưa (như 'giờ ngọ', 'chính ngọ')", radical:"tượng hình chày — dùng giã gạo lúc trưa = giờ ngọ/giữa trưa" },
  { char:"吃",     pinyin:"chī",          pos:"v.",    viet:"ăn",                                                  lesson:6, hv:"KHIẾT — ăn (HV ít dùng)", radical:"口(KHẨU — miệng, bộ thủ) + 乞(KHẤT — chỉ thanh) → hành động của miệng = ăn" },
  { char:"饭",     pinyin:"fàn",          pos:"n.",    viet:"cơm, bữa ăn",                                         lesson:6, hv:"PHẠN — cơm (như 'phạn điếm')", radical:"饣(THỰC — đồ ăn, bộ thủ) + 反(PHẢN — chỉ thanh) → đồ ăn = cơm/bữa" },
  { char:"吃饭",   pinyin:"chī fàn",      pos:"v.",    viet:"ăn cơm, dùng bữa",                                    lesson:6, hv:"KHIẾT PHẠN — ăn cơm", radical:"吃 = miệng xin ăn = ăn | 饭 = cơm chín = cơm → ăn cơm" },
  { char:"睡觉",   pinyin:"shuìjiào",     pos:"v.",    viet:"đi ngủ, ngủ (động từ tách rời: 睡 + 觉)",               lesson:6, hv:"THỤY GIÁC — ngủ (觉 = giấc; tách 早/午/晚 vào giữa)", radical:"睡 = 目(MỤC — mắt) + 垂(THÙY — rũ xuống) → mắt rũ xuống = buồn ngủ | 觉 = 爫(trảo — móng tay) + 冖 + 见(KIẾN — thấy) → cảm giác/giấc → kết hợp: ngủ-cảm giác = đi ngủ" },
  { char:"再",     pinyin:"zài",          pos:"adv.",  viet:"lại, một lần nữa, tiếp (như 再见, 再说)",                lesson:6, hv:"TÁI — lại (như 'tái phát', 'tái diễn')", radical:"一 + 冂 + 土 → một lớp xếp chồng thêm = lại" },
  { char:"再见",   pinyin:"zàijiàn",      pos:"v./int.", viet:"tạm biệt (lit. 'gặp lại')",                          lesson:6, hv:"TÁI KIẾN — gặp lại (lời chia tay)", radical:"再 = lại | 见 = mắt có chân đi gặp → gặp lại = tạm biệt" },

  // ── Lesson 7 ──
  // General / misc
  { char:"课",     pinyin:"kè",           pos:"n.",    viet:"bài học, tiết học",                                   lesson:7, hv:"KHÓA — như 'khóa học'", radical:"讠(NGÔN — lời, bộ thủ) + 果(QUẢ — chỉ thanh) → bài học/lớp" },
  { char:"班",     pinyin:"bān",          pos:"n.",    viet:"ban, lớp, ca làm việc",                                lesson:7, hv:"BAN — như 'ban điều hành', 'ban giám hiệu'", radical:"王 + 刂(ĐAO — dao) + 王 → tượng hình mảnh ngọc bị tách bằng dao → chia thành nhóm = ban/lớp" },
  { char:"上班",   pinyin:"shàngbān",     pos:"v.",    viet:"đi làm, bắt đầu ca làm (động từ tách rời)",            lesson:7, hv:"THƯỢNG BAN — lên ca (cùng họ với 上课 = vào lớp)", radical:"上(THƯỢNG) = lên/vào | 班(BAN) = ban/ca → 'lên ca' = đi làm" },
  { char:"下班",   pinyin:"xiàbān",       pos:"v.",    viet:"tan làm, hết ca (động từ tách rời)",                   lesson:7, hv:"HẠ BAN — xuống ca (cùng họ với 下课 = tan học)", radical:"下(HẠ) = xuống/kết thúc | 班(BAN) = ban/ca → 'xuống ca' = tan làm" },
  { char:"件",     pinyin:"jiàn",         pos:"q.",    viet:"lượng từ (cho 事, 衣服...)",                            lesson:7, hv:"KIỆN — như 'kiện hàng', 'sự kiện'", radical:"亻(NHÂN — bộ người, chỉ vật/sự) + 牛(NGƯU — chỉ thanh, không liên quan nghĩa 'bò') → lượng từ cho việc, đồ rời" },
  { char:"事",     pinyin:"shì",          pos:"n.",    viet:"việc, chuyện",                                         lesson:7, hv:"SỰ — như 'sự việc', 'sự kiện'", radical:"tượng hình tay cầm cờ/bút lông — vốn chỉ chức vụ → việc/sự" },
  { char:"可是",   pinyin:"kěshi",        pos:"conj.", viet:"nhưng, tuy nhiên",                                     lesson:7, hv:"KHẢ THỊ — HV ít dùng", radical:"可(KHẢ — có thể) | 是(THỊ — là, đúng) → 'có thể là vậy nhưng...' = nhưng/tuy nhiên" },
  { char:"没问题", pinyin:"méi wèntí",    pos:"",      viet:"không có vấn đề",                                      lesson:7, hv:"MỘT VẤN ĐỀ — giống tiếng Việt!", radical:"没 = 氵(THỦY — nước) + 殳 → bị chìm = không có | 问(VẤN) = 门(MÔN — cửa) + 口(KHẨU — miệng) → miệng hỏi tại cửa = hỏi | 题(ĐỀ) = 是(THỊ — đúng) + 页(HIỆT — trang/đầu) → chủ đề trên trang = vấn đề" },
  { char:"钥匙",   pinyin:"yàoshi",       pos:"n.",    viet:"chìa khóa",                                            lesson:7, hv:"THƯỢC THI — HV ít dùng", radical:"钥(THƯỢC) = 钅(KIM — kim loại) → mảnh kim loại mở khóa | 匙(THI) = 匕(THUỶ — thìa) → vật giống chiếc thìa nhỏ → chìa khóa" },
  { char:"里",     pinyin:"lǐ",           pos:"n.",    viet:"trong, bên trong",                                     lesson:7, hv:"LÝ — trong (như 'nội lý')", radical:"田(ĐIỀN — ruộng) + 土(THỔ — đất) → trong làng/đồng = trong/bên trong" },
  { char:"外",     pinyin:"wài",          pos:"n.",    viet:"ngoài, bên ngoài",                                     lesson:7, hv:"NGOẠI — ngoài (như 'ngoại lai', 'ngoại quốc')", radical:"夕(TỊCH — chiều tối) + 卜(BỐC — bói toán) → 'bói lúc chiều tối, ra ngoài cửa' = ngoài/bên ngoài" },
  { char:"上",     pinyin:"shàng",        pos:"n.",    viet:"trên, phía trên",                                      lesson:7, hv:"THƯỢNG — trên (như 'thượng đẳng', 'thượng nguồn')", radical:"vạch nhỏ phía trên đường ngang → trên/phía trên" },
  { char:"下",     pinyin:"xià",          pos:"n.",    viet:"dưới, phía dưới",                                      lesson:7, hv:"HẠ — dưới (như 'hạ giới', 'hạ tầng')", radical:"vạch nhỏ phía dưới đường ngang → dưới/phía dưới" },
  { char:"前",     pinyin:"qián",         pos:"n.",    viet:"trước, phía trước",                                    lesson:7, hv:"TIỀN — trước (như 'tiền tuyến', 'tiền nhân')", radical:"chữ gốc 歬 = 止(CHỈ — chân) + 舟(CHU — thuyền) → 'chân trên thuyền tiến tới' = phía trước" },
  { char:"后",     pinyin:"hòu",          pos:"n.",    viet:"sau, phía sau",                                        lesson:7, hv:"HẬU — sau (như 'hậu phương', 'hậu trường')", radical:"chữ giản thể của 後 (HẬU) — chỉ phía sau / sau lưng" },
  { char:"后边",   pinyin:"hòubian",      pos:"n.",    viet:"phía sau",                                             lesson:7, hv:"HẬU BIÊN — phía sau (hậu=sau)", radical:"后(HẬU — phía sau, như 'hậu phương') | 边(BIÊN — cạnh/phía) → phía sau" },
  { char:"和",     pinyin:"hé",           pos:"conj./prep.", viet:"và, với (liên từ)",                              lesson:7, hv:"HÒA — như 'hòa bình', 'hòa hợp'", radical:"禾(HÒA — lúa) + 口(KHẨU — miệng) → cùng ăn lúa = hòa thuận/và/với" },
  { char:"跟",     pinyin:"gēn",          pos:"prep.", viet:"cùng với, theo (giới từ)",                             lesson:7, hv:"CĂN — HV ít dùng (gốc/theo)", radical:"足(TÚC — chân, bộ thủ) + 艮(CẤN — chỉ thanh) → chân theo sau = theo/cùng" },
  { char:"听说",   pinyin:"tīngshuō",     pos:"v.",    viet:"nghe nói",                                             lesson:7, hv:"THÍNH THUYẾT — nghe người ta nói", radical:"听 = 口(KHẨU — miệng) + 斤(CÂN — rìu) → tai nghe sắc bén = nghe | 说 = 讠(NGÔN — lời) + 兑(ĐOÀI — đổi) → trao đổi lời = nói → 'nghe-nói' = nghe nói/người ta đồn" },
  { char:"当然",   pinyin:"dāngrán",      pos:"adv.",  viet:"tất nhiên, dĩ nhiên",                                  lesson:7, hv:"ĐƯƠNG NHIÊN — giống hệt tiếng Việt!", radical:"当(ĐƯƠNG — nên/đáng) | 然(NHIÊN — như vậy) → 'nên là vậy' = đương nhiên (HV trùng tiếng Việt!)" },
  { char:"吧",     pinyin:"ba",           pos:"part.", viet:"trợ từ gợi ý, yêu cầu",                                lesson:7, hv:"BA — HV ít dùng", radical:"口(KHẨU — miệng) + 巴(BA — phiên âm) → trợ từ dịu giọng từ miệng = đề nghị/yêu cầu" },

  // Time / day (chronological)
  { char:"昨天",   pinyin:"zuótiān",      pos:"n.",    viet:"hôm qua",                                              lesson:7, hv:"TẠC THIÊN — ngày hôm qua (tạc=qua)", radical:"昨(TẠC) = 日(NHẬT — mặt trời) + 乍(SẠ — thoáng) → 'mặt trời vừa qua' = hôm qua | 天(THIÊN) = trời/ngày → 'ngày đã qua' = hôm qua" },
  { char:"今天",   pinyin:"jīntiān",      pos:"n.",    viet:"hôm nay",                                              lesson:7, hv:"KIM THIÊN — ngày nay (kim=nay)", radical:"今(KIM — nay) | 天(THIÊN — trời/ngày) → 'ngày nay' = hôm nay" },
  { char:"明天",   pinyin:"míngtiān",     pos:"n.",    viet:"ngày mai",                                            lesson:7, hv:"MINH THIÊN — ngày sáng (minh=sáng, thiên=trời/ngày)", radical:"明 = 日(NHẬT — mặt trời) + 月(NGUYỆT — trăng) → mặt trời và mặt trăng = sáng/rõ | 天 = 一(vạch trên) + 大(ĐẠI — to/người) → trên đầu người = trời/ngày" },
  { char:"上午",   pinyin:"shàngwǔ",      pos:"n.",    viet:"buổi sáng",                                            lesson:7, hv:"THƯỢNG NGỌ — trước giờ ngọ", radical:"上(THƯỢNG) = vạch trên = trước | 午(NGỌ) = chày giã gạo lúc trưa → 'trước giờ ngọ' = buổi sáng" },
  { char:"下午",   pinyin:"xiàwǔ",        pos:"n.",    viet:"buổi chiều",                                           lesson:7, hv:"HẠ NGỌ — sau giờ ngọ", radical:"下(HẠ) = vạch dưới = sau | 午(NGỌ) = giờ trưa → 'sau giờ ngọ' = buổi chiều" },
  { char:"晚上",   pinyin:"wǎnshang",     pos:"n.",    viet:"buổi tối",                                             lesson:7, hv:"VÃN THƯỢNG — trên buổi tối", radical:"晚(VÃN) = 日(NHẬT — mặt trời) + 免(MIỄN — thỏ chạy) → mặt trời đuổi thỏ (hoàng hôn) = muộn/tối | 上(THƯỢNG) = trên/lên → 'trên buổi tối' = đêm" },
  { char:"时间",   pinyin:"shíjiān",      pos:"n.",    viet:"thời gian",                                            lesson:7, hv:"THỜI GIAN — giống hệt tiếng Việt!", radical:"时(THỜI) = 日(NHẬT — mặt trời) + 寺(TỰ — chùa) → mặt trời tại chùa (đo bằng chuông) = thời gian | 间(GIAN) = 门(MÔN — cửa) + 日(NHẬT) → ánh sáng qua cửa = khoảng/giữa → 'khoảng thời gian' = thời lượng" },

  // Entertainment
  { char:"电影",   pinyin:"diànyǐng",     pos:"n.",    viet:"phim, điện ảnh",                                       lesson:7, hv:"ĐIỆN ẢNH — giống hệt tiếng Việt!", radical:"电(ĐIỆN) = tia chớp = điện | 影(ẢNH) = 景(CẢNH) + 彡(tia) → hình ảnh chuyển động = phim/bóng → 'hình điện' = phim" },
  { char:"电影院", pinyin:"diànyǐngyuàn", pos:"n.",    viet:"rạp chiếu phim",                                       lesson:7, hv:"ĐIỆN ẢNH VIỆN — viện chiếu phim điện", radical:"电(ĐIỆN) = tượng hình tia chớp = điện | 影(ẢNH) = 景(CẢNH) + 彡(tia sáng) → hình ảnh do tia tạo = phim/bóng | 院(VIỆN) = 阝(PHỤ — đất) + 完(HOÀN — đầy đủ) → nơi khép kín = viện → 'viện chiếu phim điện' = rạp chiếu phim" },

  // Vehicles (general → specific → place → quantifier → verbs)
  { char:"车",     pinyin:"chē",          pos:"n.",    viet:"xe, phương tiện",                                      lesson:7, hv:"XA — xe (như 'xa lộ', 'xe')", radical:"tượng hình chiếc xe ngựa cổ nhìn từ trên (bánh + trục) = xe" },
  { char:"自行车", pinyin:"zìxíngchē",    pos:"n.",    viet:"xe đạp",                                              lesson:7, hv:"TỰ HÀNH XA — xe tự đi", radical:"自(TỰ) = tượng hình mũi chỉ vào mình = tự | 行(HÀNH) = tượng hình ngã tư = đi/hành | 车(XA) = tượng hình xe (bánh + trục) = xe → 'xe tự đi' = xe đạp" },
  { char:"摩托车", pinyin:"mótuōchē",     pos:"n.",    viet:"xe máy",                                               lesson:7, hv:"MA THÁ XA — phiên âm 'moto' + xe", radical:"摩(MA) = 麻(MA — gai) + 手(THỦ — tay) → cọ xát (phiên âm 'mo') | 托(THÁ) = 扌(THỦ — tay) + 乇 → đỡ/giao (phiên âm 'tuo') | 车(XA) = xe → 摩托 phiên âm 'moto' + xe = xe máy" },
  { char:"汽车",   pinyin:"qìchē",        pos:"n.",    viet:"ô tô",                                                 lesson:7, hv:"KHÍ XA — xe hơi (khí=hơi nước/động cơ)", radical:"汽(KHÍ) = 氵(THỦY — nước) + 气(KHÍ — hơi/gas) → hơi nước | 车(XA) = xe → 'xe hơi nước' = ô tô (vốn chạy bằng hơi nước)" },
  { char:"车棚",   pinyin:"chēpéng",      pos:"n.",    viet:"chỗ để xe",                                            lesson:7, hv:"XA BỒNG — mái che xe", radical:"车(XA) = xe | 棚(BỒNG) = 木(MỘC — gỗ) + 朋(BẰNG — đôi) → ván gỗ kề bên nhau = mái che → 'mái che xe' = chỗ để xe" },
  { char:"辆",     pinyin:"liàng",        pos:"q.",    viet:"lượng từ cho xe cộ",                                   lesson:7, hv:"LƯỢNG — lượng từ (HV ít dùng)", radical:"车(XA — xe, bộ thủ) + 两(LƯỠNG — đôi, gợi 'hai bánh/trục') → lượng từ chuyên cho xe cộ" },
  { char:"骑",     pinyin:"qí",           pos:"v.",    viet:"cưỡi, đi (xe đạp, ngựa...)",                            lesson:7, hv:"KỴ — cưỡi (như 'kỵ binh')", radical:"马(MÃ — ngựa, bộ thủ) + 奇(KỲ — chỉ thanh) → động từ về cưỡi ngựa / đi xe 2 bánh = cưỡi" },
  { char:"开",     pinyin:"kāi",          pos:"v.",    viet:"lái (xe có động cơ); mở, khởi động",                  lesson:7, hv:"KHAI — mở, khởi động (như 'khai mạc')", radical:"一 + 廾(hai tay đẩy mở) → tay đẩy cánh cửa = mở/bắt đầu/lái" },

  // ── Lesson 8 ──
  // Communication
  { char:"电话",   pinyin:"diànhuà",      pos:"n.",    viet:"điện thoại",                                          lesson:8, hv:"ĐIỆN THOẠI — giống hệt tiếng Việt!", radical:"电(ĐIỆN) = tia chớp = điện | 话(THOẠI) = 讠(NGÔN — lời) + 舌(THIỆT — lưỡi) → lời từ lưỡi = cuộc nói/lời nói" },
  { char:"手机",   pinyin:"shǒujī",       pos:"n.",    viet:"điện thoại di động",                                  lesson:8, hv:"THỦ CƠ — máy cầm tay", radical:"手(THỦ — tay) | 机(CƠ — máy) = 木(MỘC — gỗ) + 几(KỶ — chỉ thanh) → 'máy cầm tay' = điện thoại di động" },
  { char:"护照",   pinyin:"hùzhào",       pos:"n.",    viet:"hộ chiếu",                                            lesson:8, hv:"HỘ CHIẾU — giống hệt tiếng Việt!", radical:"护(HỘ — bảo vệ) = 扌(THỦ — tay, bộ thủ) + 户(HỘ — chỉ thanh) → tay che chở | 照(CHIẾU — chiếu/giấy chứng) = 召(TRIỆU — chỉ thanh) + 灬(HỎA — lửa) → 'ánh sáng chiếu giấy' → 'giấy bảo vệ' = hộ chiếu" },
  { char:"作业",   pinyin:"zuòyè",        pos:"n.",    viet:"bài tập, bài tập về nhà",                              lesson:8, hv:"TÁC NGHIỆP — bài tập (tác = làm, nghiệp = công việc)", radical:"作(TÁC) = 亻(NHÂN — người) + 乍(SẠ — chỉ thanh) → người làm việc gì = làm/tác | 业(NGHIỆP) — tượng hình giá nhạc cụ cổ → công việc/sự nghiệp → 'công việc phải làm' = bài tập" },
  { char:"号",     pinyin:"hào",          pos:"n.",    viet:"số (thứ tự, địa chỉ, ngày)",                          lesson:8, hv:"HIỆU — số/ký hiệu (như 'tín hiệu')", radical:"口(KHẨU — miệng) + 丂 → tiếng kêu/ký hiệu = số/hiệu" },
  { char:"号码",   pinyin:"hàomǎ",        pos:"n.",    viet:"số, mã số (số điện thoại, mã hàng)",                  lesson:8, hv:"HIỆU MÃ — mã số", radical:"号(HIỆU — số) | 码(MÃ) = 石(THẠCH — đá) + 马(MÃ — chỉ thanh) → đá khắc số = mã/số" },
  { char:"多少",   pinyin:"duōshao",      pos:"pron.", viet:"bao nhiêu (hỏi số lượng — số lớn)",                   lesson:8, hv:"ĐA THIỂU — nhiều ít", radical:"多(ĐA — nhiều) + 少(THIỂU — ít) → 'nhiều-ít' = hỏi số lượng" },

  // Time
  { char:"周末",   pinyin:"zhōumò",       pos:"n.",    viet:"cuối tuần",                                            lesson:8, hv:"CHU MẠT — cuối tuần (chu = chu kỳ, mạt = ngọn/cuối)", radical:"周(CHU — tuần/chu kỳ) | 末(MẠT — ngọn) = 木(MỘC — cây) + 一 (vạch trên ngọn) → 'cuối chu kỳ' = cuối tuần" },
  { char:"分钟",   pinyin:"fēnzhōng",     pos:"n.",    viet:"phút (đơn vị thời gian đếm số phút)",                 lesson:8, hv:"PHÂN CHUNG — phút (đơn vị)", radical:"分(PHÂN — chia/phút) | 钟(CHUNG) = 钅(KIM — kim loại) + 中(TRUNG — chỉ thanh) → đồng hồ → 'phần chia trên đồng hồ' = phút" },

  // Conjunction / adverb
  { char:"不过",   pinyin:"búguò",        pos:"conj.", viet:"nhưng, tuy nhiên (nhẹ hơn 可是)",                      lesson:8, hv:"BẤT QUÁ — không quá (nhưng cũng không quá nghiêm trọng)", radical:"不(BẤT — không) | 过(QUÁ) = 辶(SƯỚC — di chuyển) + 寸(THỐN — chỉ thanh) → 'không vượt quá' = nhưng (nhẹ)" },
  { char:"就",     pinyin:"jiù",          pos:"adv.",  viet:"thì, liền, ngay (nhấn ngay sau đó/chính là)",          lesson:8, hv:"TỰU — liền/thì (như 'tựu trung')", radical:"京(KINH — kinh đô) + 尤(VƯU — chỉ thanh) → 'đến ngay kinh đô' = liền/ngay" },
  { char:"都",     pinyin:"dōu",          pos:"adv.",  viet:"đều, tất cả, cả",                                      lesson:8, hv:"ĐÔ — đều (khi đọc dū thì là thủ đô)", radical:"者(GIẢ — kẻ/ngươi) + 阝(PHỤ — đất/thành) → 'tất cả mọi người ở đó' = đều" },
  { char:"等",     pinyin:"děng",         pos:"v.",    viet:"chờ, đợi; vân vân; cấp bậc",                           lesson:8, hv:"ĐẲNG — đợi/đẳng cấp (như 'đẳng cấp', 'bình đẳng')", radical:"竹(TRÚC — tre, bộ thủ) + 寺(TỰ — chỉ thanh) → nén tre đo thời gian = chờ/đợi" },

  // Interrogative
  { char:"怎么",   pinyin:"zěnme",        pos:"pron.", viet:"làm thế nào, làm sao",                                lesson:8, hv:"HV ít dùng — đại từ nghi vấn", radical:"怎 = 乍(SẠ — thoáng) + 心(TÂM — tim) → 'đột nhiên thắc mắc trong lòng' | 么 = trợ từ phiên âm → đại từ 'thế nào'" },

  // Movement / transport
  { char:"走",     pinyin:"zǒu",          pos:"v.",    viet:"dịch chuyển, rời khỏi (đi nói chung, không nhất thiết là đi bộ)", lesson:8, hv:"TẨU — đi/chạy (như 'tẩu thoát')", radical:"土(THỔ — đất) + 龰(người dang chân) → người bước trên đất = đi/dịch chuyển" },
  { char:"走路",   pinyin:"zǒulù",        pos:"v.",    viet:"đi bộ (hình thức đi lại bằng chân — động từ tách rời)", lesson:8, hv:"TẨU LỘ — đi đường (đi bộ)", radical:"走(TẨU — đi) + 路(LỘ — đường) → 'đi trên đường' = đi bộ (cách di chuyển bằng chân)" },
  { char:"路",     pinyin:"lù",           pos:"n.",    viet:"đường, con đường, tuyến đường",                       lesson:8, hv:"LỘ — đường (như 'lộ trình', 'đại lộ')", radical:"足(TÚC — chân, bộ thủ) + 各(CÁC — chỉ thanh) → 'chân đi qua' = đường" },
  { char:"公共汽车", pinyin:"gōnggòng qìchē", pos:"n.", viet:"xe bus",                                              lesson:8, hv:"CÔNG CỘNG KHÍ XA — xe chạy hơi (ô tô) công cộng", radical:"公(CÔNG — chung) + 共(CỘNG — cùng) → công cộng | 汽车 → ô tô → 'ô tô công cộng' = xe bus" },
  { char:"到",     pinyin:"dào",          pos:"v.",    viet:"đến, tới",                                             lesson:8, hv:"ĐÁO — đến (như 'đáo hạn', 'đáo nhậm')", radical:"至(CHÍ — đến) + 刂(ĐAO — chỉ thanh) → 'đến nơi' = đến/tới" },

  // Adjective / quantifier
  { char:"快",     pinyin:"kuài",         pos:"adj.",  viet:"nhanh, mau",                                           lesson:8, hv:"KHOÁI — nhanh (như 'khoái lạc', 'khoái mã')", radical:"忄(TÂM — tim, bộ thủ) + 夬(QUYẾT — chỉ thanh) → 'lòng phấn khởi, nhanh' = nhanh" },

  // Direction
  { char:"东",     pinyin:"dōng",         pos:"n.",    viet:"đông (hướng), phía đông",                              lesson:8, hv:"ĐÔNG — phía đông (như 'phương đông', 'đông á')", radical:"giản thể của 東 — gốc: 日(NHẬT — mặt trời) qua 木(MỘC — cây) → mặt trời mọc qua cây = hướng đông" },
  { char:"东南",   pinyin:"dōngnán",      pos:"n.",    viet:"đông nam (hướng)",                                     lesson:8, hv:"ĐÔNG NAM — đông nam", radical:"东(ĐÔNG) + 南(NAM) → 'đông + nam' = hướng đông nam" },

  // Place
  { char:"房间",   pinyin:"fángjiān",     pos:"n.",    viet:"phòng, căn phòng",                                     lesson:8, hv:"PHÒNG GIAN — gian phòng", radical:"房(PHÒNG) = 户(HỘ — cửa) + 方(PHƯƠNG — chỉ thanh) → khu vực có cửa = phòng | 间(GIAN) = 门(MÔN — cửa) + 日(NHẬT) → khoảng giữa các cửa = gian" },
  { char:"室",     pinyin:"shì",          pos:"n.",    viet:"phòng (trong cụm: 教室, 卧室, 办公室)",                  lesson:8, hv:"THẤT — phòng (như 'lễ thất', 'phòng thất')", radical:"宀(MIÊN — mái nhà) + 至(CHÍ — đến) → 'nơi đến dưới mái' = phòng" },
  { char:"校园",   pinyin:"xiàoyuán",     pos:"n.",    viet:"khuôn viên trường, sân trường",                       lesson:8, hv:"HIỆU VIÊN — sân trường", radical:"校(HIỆU — trường) | 园(VIÊN) = 囗(viền — rào quanh) + 元(NGUYÊN — chỉ thanh) → vườn có rào → 'vườn của trường' = khuôn viên trường" },

  // ── Add new words below ──
];

// Auto-assign `n` from array index
words.forEach((w, i) => w.n = i + 1);
